--DROP   VIEW QBM1_MEMOV;
CREATE VIEW QBM1_MEMOV ( 
QBM1_UKETSUKENO
,QBM1_MAKEDATE
,QBM1_MEMOCD
,QBM1_TSUUCHIKBN
,QBM1_MEMOBNR
,QBM1_RIREKIKBN
,QBM1_USERNAME
,QBM1_STRDATE
,QBM1_UPDDATE
,QBM1_DELDATE
,QBM1_OPID
,QBM1_WSID
,QBM1_LINKUKENO
 ) AS 	-- メモ管理テーブル --
select
	QBM1_UKETSUKENO,
	QBM1_MAKEDATE,
	QBM1_MEMOCD,
	QBM1_TSUUCHIKBN,
	QBM1_MEMOBNR,
	QBM1_RIREKIKBN,
	QBM1_USERNAME,
	QBM1_STRDATE,
	QBM1_UPDDATE,
	QBM1_DELDATE,
	QBM1_OPID,
	QBM1_WSID,
	Null QBM1_LINKUKENO
from QBM1_MEMOT
union all	-- 対応履歴テーブル --
	Select
		QBM8_UKETSUKENO		QBM1_UKETSUKENO,
		QBM8_MAKEDATE		QBM1_MAKEDATE,
		QBM8_MEMOCD			QBM1_MEMOCD,
		'0'					QBM1_TSUUCHIKBN,
		Null				QBM1_MEMOBNR,
		'0'					QBM1_RIREKIKBN,
		QBM8_OPID			QBM1_USERNAME,
		QBM8_STRDATE		QBM1_STRDATE,
		QBM8_UPDDATE		QBM1_UPDDATE,
		QBM8_DELDATE		QBM1_DELDATE,
		QBM8_OPID			QBM1_OPID,
		QBM8_WSID			QBM1_WSID,
		Null				QBM1_LINKUKENO
	From QBM8_WORKMEMOV
	where  SUBSTR(QBM8_MEMOCD,1,3) = '019'
	  and  QBM8_DELDATE Is Null
union all	-- 既存入会メモテーブル --
	Select
		QBMA_UKETSUKENO		QBM1_UKETSUKENO,
		QBM1_MAKEDATE,
		'05800' || SUBSTR(QBM1_MEMOCD,1,3) QBM1_MEMOCD,
		QBM1_TSUUCHIKBN,
		QBM1_MEMOBNR,
		QBM1_RIREKIKBN,
		QBM1_USERNAME,
		QBM1_STRDATE,
		QBM1_UPDDATE,
		QBM1_DELDATE,
		QBM1_OPID,
		QBM1_WSID,
		QBMA_LINKUKETSUKE	QBM1_LINKUKENO
	from QBMA_LINKMEMOT,QBM1_MEMOT
	where  QBMA_LINKUKETSUKE  =      QBM1_UKETSUKENO
	  and  QBMA_MEMOCD        =      '15900002' --既存入会紐付けメモ
	  and  QBMA_DELDATE Is Null;
