CREATE VIEW QBV2_MENUGRPV ( 
QBV2_MENUID
,QBV2_MENUMEI
,QBV2_MODULEATR
,QBV2_JOBKBN
 ) AS 
SELECT
 substr(QUA1_MenuId,3) QBV2_MenuId, QuA1_MenuMei QBv2_MenuMei,QUA1_MODULEATR  QBv2_MODULEATR,QUA1_JOBKBN QBv2_JOBKBN
From QUA1_MENUGRPM@link_secu.tcc.card
;
