CREATE VIEW QBV3_COURIERLOGV ( 
TRANSACTION_NO
,ACT_NAME
,COURIER_ID
,COURIER_INST_ID
,NODE_ID
,MAP_NAME_ID
,ACT_NAME_ID
,RETURN_STATE
,USER_ID
,MACH_ID
,IN_ACT_DATE
,REQUEST_DATE
,RETURN_DATE
,ROOT_LOGIN
,USER_TAG
,LOGIN_NAME
,USER_NAME
 ) AS 
select
	a.TRANSACTION_NO 	,
	b.ACT_NAME	,
	a.COURIER_ID 	,
	a.COURIER_INST_ID ,
	a.NODE_ID 	,
	a.MAP_NAME_ID 	,
	a.ACT_NAME_ID 	,
	a.RETURN_STATE 	,
	a.USER_ID 	,
	a.MACH_ID 	,
	a.IN_ACT_DATE 	,
	a.REQUEST_DATE 	,
	a.RETURN_DATE 	,
	a.ROOT_LOGIN 	,
	a.USER_TAG 	,
	c.LOGIN_NAME ,
	c.LOGIN_NAME as User_Name
from ifam.Courier_LOG a,ifam.ACTIVITY_NAMES b,ifam.USERS c
where a.ACT_NAME_ID = b.ACT_NAME_ID
  and a.USER_ID = c.USER_ID(+)
;
