CREATE VIEW QBV6_MOSHIKOMIV ( 
QBA1_UKETSUKENO
,QBA1_COURIERID
,QBA1_KAKUTOKUTEN
,QBA1_EIGYOTEN
,QBA1_KAKUTOKUROUT
,QBA1_INPUTROUTE
,QBA1_CARDKBN
,QBA1_CARDSYURUI
,QBA1_CARDHAKKOKEITAI
,QBA1_IMAGESTRDATE
,QBA1_IMAGEFILE
,QBA1_HONFACEKBN
,QBA1_HONTEIKEIKBN
,QBA1_HONKNNAME
,QBA1_HONKJNAME
,QBA1_HONRMNAME
,QBA1_HONJUSHOCD
,QBA1_HONCHIBAN
,QBA1_HONYUBINNO
,QBA1_HONKNTODOFUKEN
,QBA1_HONKNSHIKCHOSN
,QBA1_HONKNBANCHI
,QBA1_HONKNKATAGAKI
,QBA1_HONKJJUSHO
,QBA1_HONKJBANCHI
,QBA1_HONKJKATAGAKI
,QBA1_HONTEL1
,QBA1_HONTEL2
,QBA1_HONTEL3
,QBA1_HONKEITAITEL1
,QBA1_HONKEITAITEL2
,QBA1_HONKEITAITEL3
,QBA1_HONSEX
,QBA1_HONBIRTHDAY
,QBA1_HONSUMAIKBN
,QBA1_HONSUMAINENSU
,QBA1_HONHAIGUUM
,QBA1_HONCHILDSU
,QBA1_HONDOKYOKBN
,QBA1_HONCASHKIBOKG
,QBA1_HONZANDAKACNT
,QBA1_HONZANDAKAKG
,QBA1_HONPASSWORD
,QBA1_HONCALLKBN
,QBA1_HONCALLNAME
,QBA1_KINSHOKUSHU
,QBA1_KINKINMUKBN
,QBA1_KINKNHAIGUNAME
,QBA1_KINKJHAIGUNAME
,QBA1_KINHAIGUZOKGR
,QBA1_KINHAIGUBIRTH
,QBA1_KINKNNAME
,QBA1_KINKJNAME
,QBA1_KINJUSHOCD
,QBA1_KINCHIBAN
,QBA1_KINYUBINNO
,QBA1_KINKNTODOFUKEN
,QBA1_KINKNSHIKCHOSN
,QBA1_KINKNBANCHI
,QBA1_KINKNKATAGAKI
,QBA1_KINKJJUSHO
,QBA1_KINKJBANCHI
,QBA1_KINKJKATAGAKI
,QBA1_KINTEL1
,QBA1_KINTEL2
,QBA1_KINTEL3
,QBA1_KINNAISEN
,QBA1_KINHONTEL1
,QBA1_KINHONTEL2
,QBA1_KINHONTEL3
,QBA1_KINNENSHUKBN
,QBA1_KINSHUNYUKBN
,QBA1_KINKJMAENAME
,QBA1_KINMAENENSUKBN
,QBA1_KINMAERIYU
,QBA1_KINSHOZOKUBUKA
,QBA1_KINYAKUSHOKU
,QBA1_KINNYUSHADATE
,QBA1_KINSETSURITSU
,QBA1_KINSHIHONKG
,QBA1_KINJUGYOCNT
,QBA1_KINNENSUKBN
,QBA1_KINJIEINAIYO
,QBA1_KINELSENENSHU
,QBA1_KINELSESHUNYU
,QBA1_SKISHOKAISHA
,QBA1_SKIKACD
,QBA1_SKIKOJINCD
,QBA1_SKINAISEN
,QBA1_SKIMISECD
,QBA1_SKIBUHANCD
,QBA1_SKICORNERDATE
,QBA1_ELSTOZAIKBN
,QBA1_ELSCLABUCD
,QBA1_ELSFUNYUSKB
,QBA1_ELSHENSAIHOHO
,QBA1_ELSCARDSOUFU
,QBA1_ELSSEIKYUSOFU
,QBA1_ELSCARDHAKKOKBN
,QBA1_ELSCARDYUSOKBN
,QBA1_ELSBUBIKIKBN
,QBA1_ELSYOSINRANK
,QBA1_ELSCARDUMUFLG
,QBA1_ELSCARDSINPAN
,QBA1_ELSCARDSONOTA
,QBA1_CTLCANS
,QBA1_CTLCANRIYU
,QBA1_CTLCANTUIKI
,QBA1_CTLHENKYAKUS
,QBA1_CTLCANSOKUJIKBN
,QBA1_CTLSEISADATE
,QBA1_CTLFSTSGDATE
,QBA1_CTLSCDSNSDATE
,QBA1_CTLMSTSTRDATE
,QBA1_CTLHAKKENDATE
,QBA1_CTLRONEDATE
,QBA1_CTLHONKNNAME
,QBA1_CTLKINKNNAME
,QBA1_CTLKANRITEN
,QBA1_CTLKAISHATEN
,QBA1_CTLJIGYOTEN
,QBA1_CTLDMTEN
,QBA1_CTLFLOKBN
,QBA1_NOCIFNO
,QBA1_NOKAIINNO
,QBA1_NOBLACKNO
,QBA1_NOCICINQNO
,QBA1_RONSYURUI
,QBA1_RONKNG
,QBA1_RONSHIHARAICNT
,QBA1_RONATAMAKNG
,QBA1_RONKAIINNO
,QBA1_RONSKTKBN
,QBA1_RONSKTKESSAICD
-- 2001.08.01 カードローン二次対応 SQT.YAMADA -->
,QBA1_HENSAIKNG
,QBA1_BOUNASKNG
,QBA1_LINKKAIIN
-- 2001.08.01 SQT.YAMADA -->
,QBA1_STRDATE
,QBA1_UPDDATE
,QBA1_DELDATE
,QBA1_OPID
,QBA1_WSID
 ) AS 
select
	QBA1_UketsukeNO		,
	QBA1_CourierID		,
	QBAP_ENTRYPKG.QBAP_GetETenMei(QBA1_KakutokuTen)	QBA1_KakutokuTen,
	QBAP_ENTRYPKG.QBAP_GetETenMei(QBA1_EigyoTen)  QBA1_EigyoTen,
	QBA1_KakutokuRout	,
	QBAP_ENTRYPKG.QBAP_GetCodeMei('DGI',QBA1_InputRoute) QBA1_InputRoute,
	QBA1_CardKBN		,
	QBA1_CardSyurui		,
	QBA1_CardHakkoKeitai,
	QBA1_ImageStrDate	,
	QBA1_ImageFile		,
	QBAP_ENTRYPKG.QBAP_GetCodeMei('C82',QBA1_HonFaceKBN) QBA1_HonFaceKBN,
	QBAP_ENTRYPKG.QBAP_GetCodeMei('C81',QBA1_HonTeikeiKBN) QBA1_HonTeikeiKBN,
	QBA1_HonKNName,
	QBA1_HonKJName,
	QBA1_HonRMName,
	QBA1_HonJushoCD,
	QBA1_HonChiban,
	QBA1_HonYubinNo,
	QBA1_HonKNTodofuken,
	QBA1_HonKNShikchosn,
	QBA1_HonKNBanchi,
	QBA1_HonKNKatagaki,
	QBA1_HonKJJusho,
	QBA1_HonKJBanchi,
	QBA1_HonKJKatagaki,
	QBA1_HonTel1,
	QBA1_HonTel2,
	QBA1_HonTel3,
	QBA1_HonKeitaiTel1,
	QBA1_HonKeitaiTel2,
	QBA1_HonKeitaiTel3,
	QBA1_HonSex,
	QBA1_HonBirthday,
	QBAP_ENTRYPKG.QBAP_GetCodeMei('DG1',QBA1_HonSumaiKBN) QBA1_HonSumaiKBN,
	QBAP_ENTRYPKG.QBAP_GetCodeMei('C25',QBA1_HonSumaiNensu) QBA1_HonSumaiNensu,
	QBAP_ENTRYPKG.QBAP_GetCodeMei('DGL',QBA1_HonHaiguUM) QBA1_HonHaiguUM,
	QBA1_HonChildSU,
	QBAP_ENTRYPKG.QBAP_GetCodeMei('DGM',QBA1_HonDokyoKBN) QBA1_HonDokyoKBN,
	QBAP_ENTRYPKG.QBAP_GetCashingKG(QBA1_HonCashKiboKG) QBA1_HonCashKiboKG,
	QBA1_HonZandakaCNT,
	QBA1_HonZandakaKG,
	QBA1_HonPassWord,
	QBA1_HonCallKBN,
	QBA1_HonCallName,
/*******  勤務先情報  *******/
	QBAP_ENTRYPKG.QBAP_GetCodeMei('DG3',QBA1_KinShokushu) QBA1_KinShokushu,
	QBAP_ENTRYPKG.QBAP_GetCodeMei('DG2',QBA1_KinKinmuKBN) QBA1_KinKinmuKBN,
	QBA1_KinKNHaiguName,
	QBA1_KinKJHaiguName,
	QBAP_ENTRYPKG.QBAP_GetCodeMei('C18',QBA1_KinHaiguZokgr) QBA1_KinHaiguZokgr,
	QBA1_KinHaiguBirth,
	QBA1_KinKNName,
	QBA1_KinKJName,
	QBA1_KinJushoCD,
	QBA1_KinChiban,
	QBA1_KinYubinNO,
	QBA1_KinKNTodofuken,
	QBA1_KinKNShikchosn,
	QBA1_KinKNBanchi,
	QBA1_KinKNKatagaki,
	QBA1_KinKJJusho,
	QBA1_KinKJBanchi,
	QBA1_KinKJKatagaki,
	QBA1_KinTel1,
	QBA1_KinTel2,
	QBA1_KinTel3,
	QBA1_KinNaisen,
	QBA1_KinHonTel1,
	QBA1_KinHonTel2,
	QBA1_KinHonTel3,
	QBAP_ENTRYPKG.QBAP_GetCodeMei('DGN',QBA1_KinNenshuKBN) QBA1_KinNenshuKBN,
	QBAP_ENTRYPKG.QBAP_GetCodeMei('DG4',QBA1_KinShunyuKBN) QBA1_KinShunyuKBN,
	QBA1_KinKJMaeName,
	QBAP_ENTRYPKG.QBAP_GetCodeMei('C29',QBA1_KinMaeNensuKBN) QBA1_KinMaeNensuKBN,
	QBAP_ENTRYPKG.QBAP_GetCodeMei('DG5',QBA1_KinMaeRiyu) QBA1_KinMaeRiyu,
	QBA1_KinShozokuBuka,
	QBA1_KinYakushoku,
	QBA1_KinNyushaDate,
	QBA1_KinSetsuritsu,
	QBAP_ENTRYPKG.QBAP_GetCodeMei('C26',QBA1_KinShihonKG) QBA1_KinShihonKG,
	QBAP_ENTRYPKG.QBAP_GetCodeMei('C27',QBA1_KinJugyoCNT) QBA1_KinJugyoCNT,
	QBAP_ENTRYPKG.QBAP_GetCodeMei('C29',QBA1_KinNensuKBN) QBA1_KinNensuKBN,
	QBA1_KinJieiNaiyo,
	QBAP_ENTRYPKG.QBAP_GetCodeMei('DGN',QBA1_KinElseNenshu) QBA1_KinElseNenshu,
	QBA1_KinElseShunyu,
/*******  紹介情報  *******/
	QBA1_SkiShokaisha,
	QBA1_SkiKaCD,
	QBA1_SkiKojinCD,
	QBA1_SkiNaisen,
	QBA1_SkiMiseCD,
	QBA1_SkiBuhanCD,
	QBA1_SkiCornerDate,
/*******  その他情報  *******/
	QBA1_ELSTozaiKBN,
	QBA1_ELSClabuCD,
	QBA1_ELSFunyuSKB,
	QBA1_ELSHensaiHoHo,
	QBA1_ELSCardSoufu,
	QBA1_ELSSeikyuSofu,
	QBA1_ELSCardHakkoKBN,
	QBA1_ELSCardYusoKBN,
	QBA1_ELSBubikiKBN,
	QBA1_ELSYosinRank,
	QBA1_ELSCardUmuFlg,
	QBA1_ELSCardSinpan,
	QBA1_ELSCardSonota,
/*******  制御情報  *******/
	QBA1_CTLCanS,
	QBAP_ENTRYPKG.QBAP_GetCodeMei('C21',QBA1_CTLCanRiyu) QBA1_CTLCanRiyu,
	QBA1_CTLCanTuiki,
	QBA1_CTLHenkyakuS,
	QBA1_CTLCansokujiKBN,
	QBA1_CTLSeisaDate,
	QBA1_CTLFstSGDate,
	QBA1_CTLScdSNSDate,
	QBA1_CTLMstSTRDate,
	QBA1_CTLHakkenDate,
	QBA1_CTLRoneDate,
	QBA1_CTLHonKNName,
	QBA1_CTLKinKNName,
	QBA1_CTLKanriTEN,
	QBA1_CTLKaishaTEN,
	QBA1_CTLJigyoTEN,
--	2001/06/01 SQT.YAMADA ＤＭ店対応
--	QBA1_CTLDMTEN,
	QBAP_ENTRYPKG.QBAP_GetETenMei(QBA1_CTLDMTEN)	QBA1_CTLDMTEN,
	QBA1_CTLFloKBN,
/*******  番号情報  *******/
	QBA1_NoCIFNO,
	QBA1_NoKaiinNO,
	QBA1_NoBlackNO,
	QBA1_NoCICInqNO,
/*******  ローン情報  *******/
	QBAP_ENTRYPKG.QBAP_GetCodeMei('C60',QBA1_RONSyurui) QBA1_RONSyurui,
	QBA1_RONKNG,
	QBA1_RONShiharaiCNT,
	QBA1_RONAtamaKNG,
	QBA1_RONKaiinNO,
	QBA1_RONSktKbn,
	QBA1_RONSktKessaiCD,
-- 2001.08.01 カードローン二次対応 SQT.YAMADA -->
/*******  ＷＩＳＨ情報  *******/
	Nvl(QBA1_HENSAIKNG,0) QBA1_HENSAIKNG,
	Nvl(QBA1_BOUNASKNG,0) QBA1_BOUNASKNG,
	QBAP_MEMO_MEIPKG.QBAP_MEMOGET_LINKKAIIN(QBA1_UketsukeNO) QBA1_LINKKAIIN,
-- 2001.08.01 SQT.YAMADA <--
/*******  レコード情報  *******/
	QBA1_STRDate,
	QBA1_UPDDate,
	QBA1_DELDate,
	QBA1_OPID,
	QBA1_WSID
from QBA1_MoshikomiT
;
