CREATE VIEW QBV7_KESSAIMEMOV ( 
QBV7_UKETSUKENO
,QBV7_KAIINNO
,QBV7_HONKNNAME
,QBV7_HONKJNAME
,QBV7_MEMO
,QBV7_KAISTRDATE
,QBV7_MEMOSTRDATE
,QBV7_MEMOCD
,QBV7_CARDMEI
,QBV7_CARDKBN
 ) AS 
select 
	QBM1_UKETSUKENO    QBV7_UKETSUKENO ,
	QBAP_CENT200PKG.QBAP_GetGaibuKaiinNo(QBA1_CARDKBN,substr(QBA1_NOKAIINNO,1,12),substr(QBA1_NOKAIINNO,13,1)) QBV7_KaiinNo ,
	QBA1_HONKNNAME     QBV7_HONKNNAME ,
	QBA1_HONKJNAME     QBV7_HONKJNAME ,
	QBM8_MEMO          QBV7_MEMO      ,
        to_char(QBA1_CTLMSTSTRDATE,'yyyy/mm/dd') QBV7_KaiStrDate,
        to_char(QBM1_StrDate,'yyyy/mm/dd')       QBV7_MemoStrDate,
        QBM1_MEMOCD        QBV7_MEMOCD,
	QTA6_CARDMEI       QBV7_CARDMEI,
	QTA6_PRMCARDKBN    QBV7_CARDKBN
from QBM1_MEMOT a,QBM8_WORKMEMOT b,QBA1_MOSHIKOMIT c,QTA6_CARDCTRLT d
where QBM1_UKETSUKENO = QBM8_UKETSUKENO
  and QBM1_MAKEDATE   = QBM8_MAKEDATE
  and QBM1_MEMOCD     = QBM8_MEMOCD
  and QBM1_UKETSUKENO = QBA1_UKETSUKENO
  and QTA6_PRMCARDKBN = QBA1_CARDKBN
  
/* 2000/11/08 Åiè·äQëŒâûÅjèåèí«â¡ */
  and QBM1_DELDATE   is Null
;
