CREATE VIEW QBVK_QB00011P ( 
NO
,STR_KBN
,STR_YEAR
,NUM_MON
,STR_TANTOCD
 ) AS 
select
      QBE3_UKETSUKENO NO,
      '0' STR_KBN,
      to_char(add_months(QBE3_MASTERSTRIRAIDATE,-2),'YYYY') STR_YEAR,
      to_number(to_char(add_months(QBE3_MASTERSTRIRAIDATE,-2),'MM')) NUM_MON,
      rpad(QBE3_KESSAITANTOU,8) STR_TANTOCD
 from QBE3_TOKEIT
where QBE3_KESSAITANTOU != 'JIDO0000'
  and QBE3_KESSAIKEKKA = '01'
union
select
      QBE3_UKETSUKENO NO,
      '0' STR_KBN,
      to_char(add_months(QBE3_MASTERSTRIRAIDATE,-2),'YYYY') STR_YEAR,
      to_number(to_char(add_months(QBE3_MASTERSTRIRAIDATE,-2),'MM')) NUM_MON,
      NULL STR_TANTOCD
 from QBE3_TOKEIT
where QBE3_KESSAITANTOU = 'JIDO0000'
  and QBE3_KESSAIKEKKA = '01'
union
select
      QBE3_UKETSUKENO NO,
      '1' STR_KBN,
      to_char(add_months(QBE3_MASTERSTRIRAIDATE,-2),'YYYY') STR_YEAR,
      to_number(to_char(add_months(QBE3_MASTERSTRIRAIDATE,-2),'MM')) NUM_MON,
      rpad(QBE3_KESSAITANTOU,8) STR_TANTOCD
 from QBE3_TOKEIT,QSA2_SCODET
where QBE3_KESSAITANTOU != 'JIDO0000'
  and QBE3_KESSAIKEKKA = '13'
  and QSA2_PRMCODEKBN = 'DI8'
  and QSA2_PRMCODENO = '1'
  and QSA2_MEI = QBE3_AESRESULTCD
union
select
      QBE3_UKETSUKENO NO,
      '2' STR_KBN,
      to_char(add_months(QBE3_MASTERSTRIRAIDATE,-2),'YYYY') STR_YEAR,
      to_number(to_char(add_months(QBE3_MASTERSTRIRAIDATE,-2),'MM')) NUM_MON,
      rpad(QBE3_KESSAITANTOU,8) STR_TANTOCD
 from QBE3_TOKEIT,QSA2_SCODET
where QBE3_KESSAITANTOU != 'JIDO0000'
  and QBE3_KESSAIKEKKA = '13'
  and QSA2_PRMCODEKBN = 'DI8'
  and QSA2_PRMCODENO = '2'
  and QSA2_MEI = QBE3_AESRESULTCD
union
select
      QBE3_UKETSUKENO NO,
      '3' STR_KBN,
      to_char(add_months(QBE3_MASTERSTRIRAIDATE,-2),'YYYY') STR_YEAR,
      to_number(to_char(add_months(QBE3_MASTERSTRIRAIDATE,-2),'MM')) NUM_MON,
      rpad(QBE3_KESSAITANTOU,8) STR_TANTOCD
 from QBE3_TOKEIT,QSA2_SCODET
where QBE3_KESSAITANTOU != 'JIDO0000'
  and QBE3_KESSAIKEKKA = '13'
  and QSA2_PRMCODEKBN = 'DI8'
  and QSA2_PRMCODENO = '3'
  and QSA2_MEI = QBE3_AESRESULTCD
union
select
      QBE3_UKETSUKENO NO,
      '4' STR_KBN,
      to_char(add_months(QBE3_MASTERSTRIRAIDATE,-2),'YYYY') STR_YEAR,
      to_number(to_char(add_months(QBE3_MASTERSTRIRAIDATE,-2),'MM')) NUM_MON,
      rpad(QBE3_KESSAITANTOU,8) STR_TANTOCD
 from QBE3_TOKEIT,QSA2_SCODET
where QBE3_KESSAITANTOU != 'JIDO0000'
  and QBE3_KESSAIKEKKA = '13'
  and QSA2_PRMCODEKBN = 'DI8'
  and QSA2_PRMCODENO = '4'
  and QSA2_MEI = QBE3_AESRESULTCD
union
select
      QBE3_UKETSUKENO NO,
      '5' STR_KBN,
      to_char(add_months(QBE3_MASTERSTRIRAIDATE,-2),'YYYY') STR_YEAR,
      to_number(to_char(add_months(QBE3_MASTERSTRIRAIDATE,-2),'MM')) NUM_MON,
      rpad(QBE3_KESSAITANTOU,8) STR_TANTOCD
 from QBE3_TOKEIT,QSA2_SCODET ATBL,QSA2_SCODET BTBL,QSA2_SCODET CTBL,QSA2_SCODET DTBL
where QBE3_KESSAITANTOU != 'JIDO0000'
  and QBE3_KESSAIKEKKA = '13'
  and ATBL.QSA2_PRMCODEKBN = 'DI8'
  and ATBL.QSA2_PRMCODENO = '1'
  and ATBL.QSA2_MEI != QBE3_AESRESULTCD
  and BTBL.QSA2_PRMCODEKBN = 'DI8'
  and BTBL.QSA2_PRMCODENO = '2'
  and BTBL.QSA2_MEI != QBE3_AESRESULTCD
  and CTBL.QSA2_PRMCODEKBN = 'DI8'
  and CTBL.QSA2_PRMCODENO = '3'
  and CTBL.QSA2_MEI != QBE3_AESRESULTCD
  and DTBL.QSA2_PRMCODEKBN = 'DI8'
  and DTBL.QSA2_PRMCODENO = '4'
  and DTBL.QSA2_MEI != QBE3_AESRESULTCD
union
select
      QBE3_UKETSUKENO NO,
      '6' STR_KBN,
      to_char(add_months(QBE3_MASTERSTRIRAIDATE,-2),'YYYY') STR_YEAR,
      to_number(to_char(add_months(QBE3_MASTERSTRIRAIDATE,-2),'MM')) NUM_MON,
      NULL STR_TANTOCD
 from QBE3_TOKEIT
where QBE3_KESSAITANTOU = 'JIDO0000'
  and QBE3_KESSAIKEKKA = '12'
union
select
      QBE3_UKETSUKENO NO,
      '7' STR_KBN,
      to_char(add_months(QBE3_MASTERSTRIRAIDATE,-2),'YYYY') STR_YEAR,
      to_number(to_char(add_months(QBE3_MASTERSTRIRAIDATE,-2),'MM')) NUM_MON,
      rpad(QBE3_KESSAITANTOU,8) STR_TANTOCD
 from QBE3_TOKEIT
where QBE3_KESSAITANTOU != 'JIDO0000'
  and QBE3_KESSAIKEKKA = '18'
union
select
      QBE3_UKETSUKENO NO,
      '7' STR_KBN,
      to_char(add_months(QBE3_MASTERSTRIRAIDATE,-2),'YYYY') STR_YEAR,
      to_number(to_char(add_months(QBE3_MASTERSTRIRAIDATE,-2),'MM')) NUM_MON,
      NULL STR_TANTOCD
 from QBE3_TOKEIT
where QBE3_KESSAITANTOU = 'JIDO0000'
  and QBE3_KESSAIKEKKA = '13'
;
