CREATE VIEW QBKC_LABELV ( 
QBKC_PRMTOUZAIKBN
,QBKC_PRMSOUFUSAKIKBN
,QBKC_PRMGINKOUCD
,QBKC_SOHATENA
,QBKC_SOHATENA1
,QBKC_SOHATENA2
,QBKC_SOHYUBINNO
,QBKC_SOHJUSYO1
,QBKC_SOHJUSYO2
,QBKC_SOHJUSYO3
,QBKC_SOHJUSYO4
 ) AS 
SELECT QBK2_PRMTouzaiKbn,
       QBK2_PRMSoufusakiKbn,
       QBK2_PRMGinkouCd,
       QBK2_SOHAtena,
       QBK2_SOHAtena1,
       QBK2_SOHAtena2,
       QSAP_EDYubinNoPKG.QSAP_EDYubinNoFNC(QBK2_SOHYuubinNo),
       QSAP_EDJusyoPKG.QSAP_EDJusyoFUNC(1, QBK2_SOHJushoKan, QBK2_SOHBanchiKan, QBK2_SOHKataKan, '', ''),
       QSAP_EDJusyoPKG.QSAP_EDJusyoFUNC(2, QBK2_SOHJushoKan, QBK2_SOHBanchiKan, QBK2_SOHKataKan, '', ''),
       QSAP_EDJusyoPKG.QSAP_EDJusyoFUNC(3, QBK2_SOHJushoKan, QBK2_SOHBanchiKan, QBK2_SOHKataKan, '', ''),
       QSAP_EDJusyoPKG.QSAP_EDJusyoFUNC(4, QBK2_SOHJushoKan, QBK2_SOHBanchiKan, QBK2_SOHKataKan, '', '')
FROM   QBK2_TGinkoM
;
