CREATE VIEW QBKI_TGINKOUV ( 
QBKI_PRMTOUZAIKBN
,QBKI_PRMSOUFUSAKIKBN
,QBKI_PRMGINKOUCD
,QBKI_SOHATENA
,QBKI_SOHATENA1
,QBKI_SOHATENA2
,QBKI_SOHYUBINNO
,QBKI_SOHTELSHIGAI
,QBKI_SOHTELKYOKU
,QBKI_SOHTELNO
,QBKI_SOHJUSHOCD
,QBKI_SOHJUSHOKAN
,QBKI_SOHBANCHIKAN
,QBKI_SOHKATAKAN
,QBKI_SOHTANTOMEI
,QBKI_RIYOGINKOUCD
,QBKI_RIYOGINKOUMEI
,QBKI_SOHSOUFUMEI
 ) AS 
SELECT QBK2_PRMTouzaiKbn QBKI_PRMTouzaiKbn,
       QBK2_PRMSoufusakiKbn QBKI_PRMSoufusakiKbn,
       QBK2_PRMGinkouCd QBKI_PRMGinkouCd,
       QBK2_SOHAtena QBKI_SOHAtena,
       QBK2_SOHAtena1 QBKI_SOHAtena1,
       QBK2_SOHAtena2 QBKI_SOHAtena2,
       QBK2_SOHYuubinNo QBKI_SOHYubinNo,
       QBK2_SOHTelShigai QBKI_SOHTelShigai,
       QBK2_SOHTelKyoku QBKI_SOHTelKyoku,
       QBK2_SOHTelNo QBKI_SOHTelNo,
       QBK2_SOHJushoCd QBKI_SOHJushoCd,
       QBK2_SOHJushoKan QBKI_SOHJushoKan,
       QBK2_SOHBanchiKan QBKI_SOHBanchiKan,
       QBK2_SOHKataKan QBKI_SOHKataKan,
       QBK2_SOHTantoMei QBKI_SOHTantoMei,
       QBKH_RiyoGinkouCd QBKI_RiyoGinkouCd,
       QBKH_RiyoGinkouMei QBKI_RiyoGinkouMei,
       QSA2_Mei QBKI_SOHSoufuMei
FROM   QBK2_TGinkoM,
       QBKH_TGRiyoV,
       QSA2_SCodeT
WHERE  QBK2_PRMTouzaiKbn = QBKH_RiyoTouzaiKbn (+)
AND    QBK2_PRMSoufusakiKbn = QBKH_SOHSoufusakiKbn (+)
AND    QBK2_PRMGinkouCd = QBKH_SOHGinkouCd (+)
AND    QSA2_PRMCodeKbn = 'DI2'
AND    QBK2_PRMSoufusakiKbn = QSA2_PRMCodeNo (+)
;
