--DROP   VIEW QBKJ_MIRATIV;
CREATE VIEW QBKJ_MIRATIV ( 
STRNAME
,STRSOHATENA
,STRSOHSHITENMEI
,STRSOHTEL
,STRSOHTANTOMEI
,STRDATHASOUYMD
,STRPRMUKETUKENO
,STRGAIBUKAIINNO
,STRBLACKNO
,STRSOHTOUZAIKBN
,STRSOHSOUFUSAKIKBN
,STRSOHGINKOUCD
,STRSOHSHITENCD
,STRKOZGINKOUCD
,STRKOZSHITENCD
,STRKOZGINKOUNM
,STRKOZSHITENNM
,STRKOZSHUMOKU
,STRKOZYUCHOSAIHATU
,STRKOZNO
,STRKOZMEIGI
,STRJFHHURIKAEKEKACD
,NUMJFHSEIKYUYM
 ) AS 
select
QBA1_HONKJNAME		strNAME,
QBK2_SOHATENA		strSOHATENA,
''			strSOHSHITENMEI,
rtrim(QBK2_SOHTELSHIGAI) || '-' || rtrim(QBK2_SOHTELKYOKU) || '-' || rtrim(QBK2_SOHTELNO) strSOHTEL,
QBK2_SOHTANTOMEI	strSOHTANTOMEI,
to_char(QBK1_DATHASOUYMD,'YYYY/MM/DD')	strDATHASOUYMD,
QBK1_PRMUKETUKENO	strPRMUKETUKENO,
QBK1_GAIBUKAIINNO	strGAIBUKAIINNO,
QBK1_BLACKNO		strBLACKNO,
QBK1_SOHTOUZAIKBN	strSOHTOUZAIKBN,
QBK1_SOHSOUFUSAKIKBN	strSOHSOUFUSAKIKBN,
QBK1_SOHGINKOUCD	strSOHGINKOUCD,
QBK1_SOHSHITENCD	strSOHSHITENCD,
QBK1_KOZGINKOUCD	strKOZGINKOUCD,
QBK1_KOZSHITENCD	strKOZSHITENCD,
QTA7_KINYUKIKANNMKJ	strKOZGINKOUNM,
QTA7_SITENNMKJ		strKOZSHITENNM,
QBK1_KOZSHUMOKU		strKOZSHUMOKU,
QBK1_KOZYUCHOSAIHATU	strKOZYUCHOSAIHATU,
QBK1_KOZNO		strKOZNO,
QBK1_KOZMEIGI		strKOZMEIGI,
QBK1_JFHHURIKAEKEKACD	strJFHHURIKAEKEKACD,
QBK1_JFHSEIKYUYM	numJFHSEIKYUYM
FROM QBK1_KFURIT,QBK2_TGINKOM,QTA7_GINKOUM,QBA1_MOSHIKOMIT
WHERE QBK1_PRMUKETUKENO = QBA1_UKETSUKENO (+)
AND QBK1_PRMNAIBUKAIINNO = '00000000'
AND QBK1_SOHTOUZAIKBN = QBK2_PRMTOUZAIKBN (+)
AND QBK1_SOHSOUFUSAKIKBN = QBK2_PRMSOUFUSAKIKBN (+)
AND QBK1_SOHGINKOUCD = QBK2_PRMGINKOUCD (+)
AND QBK1_SOHSHITENCD = '00000'
AND QBK1_KOZGINKOUCD = QTA7_PRMKIKANCD
AND substr(QBK1_KOZSHITENCD,3,3) = QTA7_PRMSHITENCD
AND QTA7_PRMHUKACD = '1'
AND QBK1_KOZGINKOUCD != '0000'
AND QBK1_KOZGINKOUCD != '9900'
AND QBK1_SOHKAKUNINKBN = '0'
AND QBK1_HEKHENKYAKUKBN = '0'
AND QBK1_DATHASOUYMD is not NULL
AND QBK1_DATHENKYAKUYMD is NULL
-- 2004/04/19ＪＣＢ委託した口振依頼は、未埒空きリストの対象外 IMZ.YAMADA -->
AND QBK1_KOUHASOTANTOCD <> 'JCBITAKU'
-- 2004/04/19ＪＣＢ委託した口振依頼は、未埒空きリストの対象外 IMZ.YAMADA <--
union
select
QBA1_HONKJNAME		strNAME,
QBK2_SOHATENA		strSOHATENA,
''			strSOHSHITENMEI,
rtrim(QBK2_SOHTELSHIGAI) || '-' || rtrim(QBK2_SOHTELKYOKU) || '-' || rtrim(QBK2_SOHTELNO) strSOHTEL,
QBK2_SOHTANTOMEI	strSOHTANTOMEI,
to_char(QBK1_DATHASOUYMD,'YYYY/MM/DD')	strDATHASOUYMD,
QBK1_PRMUKETUKENO	strPRMUKETUKENO,
QBK1_GAIBUKAIINNO	strGAIBUKAIINNO,
QBK1_BLACKNO		strBLACKNO,
QBK1_SOHTOUZAIKBN	strSOHTOUZAIKBN,
QBK1_SOHSOUFUSAKIKBN	strSOHSOUFUSAKIKBN,
QBK1_SOHGINKOUCD	strSOHGINKOUCD,
QBK1_SOHSHITENCD	strSOHSHITENCD,
QBK1_KOZGINKOUCD	strKOZGINKOUCD,
QBK1_KOZSHITENCD	strKOZSHITENCD,
''			strKOZGINKOUNM,
''			strKOZSHITENNM,
QBK1_KOZSHUMOKU		strKOZSHUMOKU,
QBK1_KOZYUCHOSAIHATU	strKOZYUCHOSAIHATU,
QBK1_KOZNO		strKOZNO,
QBK1_KOZMEIGI		strKOZMEIGI,
QBK1_JFHHURIKAEKEKACD	strJFHHURIKAEKEKACD,
QBK1_JFHSEIKYUYM	numJFHSEIKYUYM
FROM QBK1_KFURIT,QBK2_TGINKOM,QBA1_MOSHIKOMIT
WHERE QBK1_PRMUKETUKENO = QBA1_UKETSUKENO (+)
AND QBK1_PRMNAIBUKAIINNO = '00000000'
AND QBK1_SOHTOUZAIKBN = QBK2_PRMTOUZAIKBN (+)
AND QBK1_SOHSOUFUSAKIKBN = QBK2_PRMSOUFUSAKIKBN (+)
AND QBK1_SOHGINKOUCD = QBK2_PRMGINKOUCD (+)
AND QBK1_SOHSHITENCD = '00000'
AND (QBK1_KOZGINKOUCD = '0000' OR QBK1_KOZGINKOUCD = '9900')
AND QBK1_SOHKAKUNINKBN = '0'
AND QBK1_HEKHENKYAKUKBN = '0'
AND QBK1_DATHASOUYMD is not NULL
AND QBK1_DATHENKYAKUYMD is NULL
-- 2004/04/19ＪＣＢ委託した口振依頼は、未埒空きリストの対象外 IMZ.YAMADA -->
AND QBK1_KOUHASOTANTOCD <> 'JCBITAKU'
-- 2004/04/19ＪＣＢ委託した口振依頼は、未埒空きリストの対象外 IMZ.YAMADA <--
union
select
QBA1_HONKJNAME		strNAME,
S.QTA7_KINYUKIKANNMKJ	strSOHATENA,
S.QTA7_SITENNMKJ	strSOHSHITENMEI,
S.QTA7_TEL		strSOHTEL,
''			strSOHTANTOMEI,
to_char(QBK1_DATHASOUYMD,'YYYY/MM/DD')	strDATHASOUYMD,
QBK1_PRMUKETUKENO	strPRMUKETUKENO,
QBK1_GAIBUKAIINNO	strGAIBUKAIINNO,
QBK1_BLACKNO		strBLACKNO,
QBK1_SOHTOUZAIKBN	strSOHTOUZAIKBN,
QBK1_SOHSOUFUSAKIKBN	strSOHSOUFUSAKIKBN,
QBK1_SOHGINKOUCD	strSOHGINKOUCD,
QBK1_SOHSHITENCD	strSOHSHITENCD,
QBK1_KOZGINKOUCD	strKOZGINKOUCD,
QBK1_KOZSHITENCD	strKOZSHITENCD,
K.QTA7_KINYUKIKANNMKJ	strKOZGINKOUNM,
K.QTA7_SITENNMKJ	strKOZSHITENNM,
QBK1_KOZSHUMOKU		strKOZSHUMOKU,
QBK1_KOZYUCHOSAIHATU	strKOZYUCHOSAIHATU,
QBK1_KOZNO		strKOZNO,
QBK1_KOZMEIGI		strKOZMEIGI,
QBK1_JFHHURIKAEKEKACD	strJFHHURIKAEKEKACD,
QBK1_JFHSEIKYUYM	numJFHSEIKYUYM
FROM QBK1_KFURIT,QTA7_GINKOUM S,QTA7_GINKOUM K,QBA1_MOSHIKOMIT
WHERE QBK1_PRMUKETUKENO = QBA1_UKETSUKENO (+)
AND QBK1_PRMNAIBUKAIINNO = '00000000'
AND QBK1_SOHGINKOUCD = S.QTA7_PRMKIKANCD
AND substr(QBK1_SOHSHITENCD,3,3) = S.QTA7_PRMSHITENCD
AND S.QTA7_PRMHUKACD = '1'
AND QBK1_SOHSHITENCD != '00000'
AND QBK1_KOZGINKOUCD = K.QTA7_PRMKIKANCD
AND substr(QBK1_KOZSHITENCD,3,3) = K.QTA7_PRMSHITENCD
AND K.QTA7_PRMHUKACD = '1'
AND QBK1_KOZGINKOUCD != '0000'
AND QBK1_KOZGINKOUCD != '9900'
AND QBK1_SOHKAKUNINKBN = '0'
AND QBK1_HEKHENKYAKUKBN = '0'
AND QBK1_DATHASOUYMD is not NULL
AND QBK1_DATHENKYAKUYMD is NULL
-- 2004/04/19ＪＣＢ委託した口振依頼は、未埒空きリストの対象外 IMZ.YAMADA -->
AND QBK1_KOUHASOTANTOCD <> 'JCBITAKU'
-- 2004/04/19ＪＣＢ委託した口振依頼は、未埒空きリストの対象外 IMZ.YAMADA <--
union
select
QBA1_HONKJNAME		strNAME,
S.QTA7_KINYUKIKANNMKJ	strSOHATENA,
S.QTA7_SITENNMKJ	strSOHSHITENMEI,
S.QTA7_TEL		strSOHTEL,
''			strSOHTANTOMEI,
to_char(QBK1_DATHASOUYMD,'YYYY/MM/DD')	strDATHASOUYMD,
QBK1_PRMUKETUKENO	strPRMUKETUKENO,
QBK1_GAIBUKAIINNO	strGAIBUKAIINNO,
QBK1_BLACKNO		strBLACKNO,
QBK1_SOHTOUZAIKBN	strSOHTOUZAIKBN,
QBK1_SOHSOUFUSAKIKBN	strSOHSOUFUSAKIKBN,
QBK1_SOHGINKOUCD	strSOHGINKOUCD,
QBK1_SOHSHITENCD	strSOHSHITENCD,
QBK1_KOZGINKOUCD	strKOZGINKOUCD,
QBK1_KOZSHITENCD	strKOZSHITENCD,
''			strKOZGINKOUNM,
''			strKOZSHITENNM,
QBK1_KOZSHUMOKU		strKOZSHUMOKU,
QBK1_KOZYUCHOSAIHATU	strKOZYUCHOSAIHATU,
QBK1_KOZNO		strKOZNO,
QBK1_KOZMEIGI		strKOZMEIGI,
QBK1_JFHHURIKAEKEKACD	strJFHHURIKAEKEKACD,
QBK1_JFHSEIKYUYM	numJFHSEIKYUYM
FROM QBK1_KFURIT,QTA7_GINKOUM S,QBA1_MOSHIKOMIT
WHERE QBK1_PRMUKETUKENO = QBA1_UKETSUKENO (+)
AND QBK1_PRMNAIBUKAIINNO = '00000000'
AND QBK1_SOHGINKOUCD = S.QTA7_PRMKIKANCD
AND substr(QBK1_SOHSHITENCD,3,3) = S.QTA7_PRMSHITENCD
AND S.QTA7_PRMHUKACD = '1'
AND QBK1_SOHSHITENCD != '00000'
AND (QBK1_KOZGINKOUCD = '0000' OR QBK1_KOZGINKOUCD = '9900')
AND QBK1_SOHKAKUNINKBN = '0'
AND QBK1_HEKHENKYAKUKBN = '0'
AND QBK1_DATHASOUYMD is not NULL
AND QBK1_DATHENKYAKUYMD is NULL
-- 2004/04/19ＪＣＢ委託した口振依頼は、未埒空きリストの対象外 IMZ.YAMADA -->
AND QBK1_KOUHASOTANTOCD <> 'JCBITAKU'
-- 2004/04/19ＪＣＢ委託した口振依頼は、未埒空きリストの対象外 IMZ.YAMADA <--
union
select
QTA1_HONSHIMEIKAN	strNAME,
QBK2_SOHATENA		strSOHATENA,
''			strSOHSHITENMEI,
rtrim(QBK2_SOHTELSHIGAI) || '-' || rtrim(QBK2_SOHTELKYOKU) || '-' || rtrim(QBK2_SOHTELNO) strSOHTEL,
QBK2_SOHTANTOMEI	strSOHTANTOMEI,
to_char(QBK1_DATHASOUYMD,'YYYY/MM/DD')	strDATHASOUYMD,
QBK1_PRMUKETUKENO	strPRMUKETUKENO,
QBK1_GAIBUKAIINNO	strGAIBUKAIINNO,
QBK1_BLACKNO		strBLACKNO,
QBK1_SOHTOUZAIKBN	strSOHTOUZAIKBN,
QBK1_SOHSOUFUSAKIKBN	strSOHSOUFUSAKIKBN,
QBK1_SOHGINKOUCD	strSOHGINKOUCD,
QBK1_SOHSHITENCD	strSOHSHITENCD,
QBK1_KOZGINKOUCD	strKOZGINKOUCD,
QBK1_KOZSHITENCD	strKOZSHITENCD,
QTA7_KINYUKIKANNMKJ	strKOZGINKOUNM,
QTA7_SITENNMKJ		strKOZSHITENNM,
QBK1_KOZSHUMOKU		strKOZSHUMOKU,
QBK1_KOZYUCHOSAIHATU	strKOZYUCHOSAIHATU,
QBK1_KOZNO		strKOZNO,
QBK1_KOZMEIGI		strKOZMEIGI,
QBK1_JFHHURIKAEKEKACD	strJFHHURIKAEKEKACD,
QBK1_JFHSEIKYUYM	numJFHSEIKYUYM
FROM QBK1_KFURIT,QBK2_TGINKOM,QTA7_GINKOUM,QTA1_KAIINM
WHERE QBK1_KIGYOUCD = QTA1_PRMKIGYOUCD
AND QBK1_SUBRANGEKEY = QTA1_PRMSUBRANGEKEY
AND QBK1_PRMNAIBUKAIINNO = QTA1_PRMNAIBUKAIINNO
AND QBK1_PRMNAIBUKAIINNO != '00000000'
AND QBK1_SOHTOUZAIKBN = QBK2_PRMTOUZAIKBN (+)
AND QBK1_SOHSOUFUSAKIKBN = QBK2_PRMSOUFUSAKIKBN (+)
AND QBK1_SOHGINKOUCD = QBK2_PRMGINKOUCD (+)
AND QBK1_SOHSHITENCD = '00000'
AND QBK1_KOZGINKOUCD = QTA7_PRMKIKANCD
AND substr(QBK1_KOZSHITENCD,3,3) = QTA7_PRMSHITENCD
AND QTA7_PRMHUKACD = '1'
AND QBK1_KOZGINKOUCD != '0000'
AND QBK1_KOZGINKOUCD != '9900'
AND QBK1_SOHKAKUNINKBN = '0'
AND QBK1_HEKHENKYAKUKBN = '0'
AND QBK1_DATHASOUYMD is not NULL
AND QBK1_DATHENKYAKUYMD is NULL
-- 2004/04/19ＪＣＢ委託した口振依頼は、未埒空きリストの対象外 IMZ.YAMADA -->
AND QBK1_KOUHASOTANTOCD <> 'JCBITAKU'
-- 2004/04/19ＪＣＢ委託した口振依頼は、未埒空きリストの対象外 IMZ.YAMADA <--
union
select
QTA1_HONSHIMEIKAN	strNAME,
QBK2_SOHATENA		strSOHATENA,
''			strSOHSHITENMEI,
rtrim(QBK2_SOHTELSHIGAI) || '-' || rtrim(QBK2_SOHTELKYOKU) || '-' || rtrim(QBK2_SOHTELNO) strSOHTEL,
QBK2_SOHTANTOMEI	strSOHTANTOMEI,
to_char(QBK1_DATHASOUYMD,'YYYY/MM/DD')	strDATHASOUYMD,
QBK1_PRMUKETUKENO	strPRMUKETUKENO,
QBK1_GAIBUKAIINNO	strGAIBUKAIINNO,
QBK1_BLACKNO		strBLACKNO,
QBK1_SOHTOUZAIKBN	strSOHTOUZAIKBN,
QBK1_SOHSOUFUSAKIKBN	strSOHSOUFUSAKIKBN,
QBK1_SOHGINKOUCD	strSOHGINKOUCD,
QBK1_SOHSHITENCD	strSOHSHITENCD,
QBK1_KOZGINKOUCD	strKOZGINKOUCD,
QBK1_KOZSHITENCD	strKOZSHITENCD,
''			strKOZGINKOUNM,
''			strKOZSHITENNM,
QBK1_KOZSHUMOKU		strKOZSHUMOKU,
QBK1_KOZYUCHOSAIHATU	strKOZYUCHOSAIHATU,
QBK1_KOZNO		strKOZNO,
QBK1_KOZMEIGI		strKOZMEIGI,
QBK1_JFHHURIKAEKEKACD	strJFHHURIKAEKEKACD,
QBK1_JFHSEIKYUYM	numJFHSEIKYUYM
FROM QBK1_KFURIT,QBK2_TGINKOM,QTA1_KAIINM
WHERE QBK1_KIGYOUCD = QTA1_PRMKIGYOUCD
AND QBK1_SUBRANGEKEY = QTA1_PRMSUBRANGEKEY
AND QBK1_PRMNAIBUKAIINNO = QTA1_PRMNAIBUKAIINNO
AND QBK1_PRMNAIBUKAIINNO != '00000000'
AND QBK1_SOHTOUZAIKBN = QBK2_PRMTOUZAIKBN (+)
AND QBK1_SOHSOUFUSAKIKBN = QBK2_PRMSOUFUSAKIKBN (+)
AND QBK1_SOHGINKOUCD = QBK2_PRMGINKOUCD (+)
AND QBK1_SOHSHITENCD = '00000'
AND (QBK1_KOZGINKOUCD = '0000' OR QBK1_KOZGINKOUCD = '9900')
AND QBK1_SOHKAKUNINKBN = '0'
AND QBK1_HEKHENKYAKUKBN = '0'
AND QBK1_DATHASOUYMD is not NULL
AND QBK1_DATHENKYAKUYMD is NULL
-- 2004/04/19ＪＣＢ委託した口振依頼は、未埒空きリストの対象外 IMZ.YAMADA -->
AND QBK1_KOUHASOTANTOCD <> 'JCBITAKU'
-- 2004/04/19ＪＣＢ委託した口振依頼は、未埒空きリストの対象外 IMZ.YAMADA <--
union
select
QTA1_HONSHIMEIKAN	strNAME,
S.QTA7_KINYUKIKANNMKJ	strSOHATENA,
S.QTA7_SITENNMKJ	strSOHSHITENMEI,
S.QTA7_TEL		strSOHTEL,
''			strSOHTANTOMEI,
to_char(QBK1_DATHASOUYMD,'YYYY/MM/DD')	strDATHASOUYMD,
QBK1_PRMUKETUKENO	strPRMUKETUKENO,
QBK1_GAIBUKAIINNO	strGAIBUKAIINNO,
QBK1_BLACKNO		strBLACKNO,
QBK1_SOHTOUZAIKBN	strSOHTOUZAIKBN,
QBK1_SOHSOUFUSAKIKBN	strSOHSOUFUSAKIKBN,
QBK1_SOHGINKOUCD	strSOHGINKOUCD,
QBK1_SOHSHITENCD	strSOHSHITENCD,
QBK1_KOZGINKOUCD	strKOZGINKOUCD,
QBK1_KOZSHITENCD	strKOZSHITENCD,
K.QTA7_KINYUKIKANNMKJ	strKOZGINKOUNM,
K.QTA7_SITENNMKJ	strKOZSHITENNM,
QBK1_KOZSHUMOKU		strKOZSHUMOKU,
QBK1_KOZYUCHOSAIHATU	strKOZYUCHOSAIHATU,
QBK1_KOZNO		strKOZNO,
QBK1_KOZMEIGI		strKOZMEIGI,
QBK1_JFHHURIKAEKEKACD	strJFHHURIKAEKEKACD,
QBK1_JFHSEIKYUYM	numJFHSEIKYUYM
FROM QBK1_KFURIT,QTA7_GINKOUM S,QTA7_GINKOUM K,QTA1_KAIINM
WHERE QBK1_KIGYOUCD = QTA1_PRMKIGYOUCD
AND QBK1_SUBRANGEKEY = QTA1_PRMSUBRANGEKEY
AND QBK1_PRMNAIBUKAIINNO = QTA1_PRMNAIBUKAIINNO
AND QBK1_PRMNAIBUKAIINNO != '00000000'
AND QBK1_SOHGINKOUCD = S.QTA7_PRMKIKANCD
AND substr(QBK1_SOHSHITENCD,3,3) = S.QTA7_PRMSHITENCD
AND S.QTA7_PRMHUKACD = '1'
AND QBK1_SOHSHITENCD != '00000'
AND QBK1_KOZGINKOUCD = K.QTA7_PRMKIKANCD
AND substr(QBK1_KOZSHITENCD,3,3) = K.QTA7_PRMSHITENCD
AND K.QTA7_PRMHUKACD = '1'
AND QBK1_KOZGINKOUCD != '0000'
AND QBK1_KOZGINKOUCD != '9900'
AND QBK1_SOHKAKUNINKBN = '0'
AND QBK1_HEKHENKYAKUKBN = '0'
AND QBK1_DATHASOUYMD is not NULL
AND QBK1_DATHENKYAKUYMD is NULL
-- 2004/04/19ＪＣＢ委託した口振依頼は、未埒空きリストの対象外 IMZ.YAMADA -->
AND QBK1_KOUHASOTANTOCD <> 'JCBITAKU'
-- 2004/04/19ＪＣＢ委託した口振依頼は、未埒空きリストの対象外 IMZ.YAMADA <--
union
select
QTA1_HONSHIMEIKAN	strNAME,
S.QTA7_KINYUKIKANNMKJ	strSOHATENA,
S.QTA7_SITENNMKJ	strSOHSHITENMEI,
S.QTA7_TEL		strSOHTEL,
''			strSOHTANTOMEI,
to_char(QBK1_DATHASOUYMD,'YYYY/MM/DD')	strDATHASOUYMD,
QBK1_PRMUKETUKENO	strPRMUKETUKENO,
QBK1_GAIBUKAIINNO	strGAIBUKAIINNO,
QBK1_BLACKNO		strBLACKNO,
QBK1_SOHTOUZAIKBN	strSOHTOUZAIKBN,
QBK1_SOHSOUFUSAKIKBN	strSOHSOUFUSAKIKBN,
QBK1_SOHGINKOUCD	strSOHGINKOUCD,
QBK1_SOHSHITENCD	strSOHSHITENCD,
QBK1_KOZGINKOUCD	strKOZGINKOUCD,
QBK1_KOZSHITENCD	strKOZSHITENCD,
''			strKOZGINKOUNM,
''			strKOZSHITENNM,
QBK1_KOZSHUMOKU		strKOZSHUMOKU,
QBK1_KOZYUCHOSAIHATU	strKOZYUCHOSAIHATU,
QBK1_KOZNO		strKOZNO,
QBK1_KOZMEIGI		strKOZMEIGI,
QBK1_JFHHURIKAEKEKACD	strJFHHURIKAEKEKACD,
QBK1_JFHSEIKYUYM	numJFHSEIKYUYM
FROM QBK1_KFURIT,QTA7_GINKOUM S,QTA1_KAIINM
WHERE QBK1_KIGYOUCD = QTA1_PRMKIGYOUCD
AND QBK1_SUBRANGEKEY = QTA1_PRMSUBRANGEKEY
AND QBK1_PRMNAIBUKAIINNO = QTA1_PRMNAIBUKAIINNO
AND QBK1_PRMNAIBUKAIINNO != '00000000'
AND QBK1_SOHGINKOUCD = S.QTA7_PRMKIKANCD
AND substr(QBK1_SOHSHITENCD,3,3) = S.QTA7_PRMSHITENCD
AND S.QTA7_PRMHUKACD = '1'
AND QBK1_SOHSHITENCD != '00000'
AND (QBK1_KOZGINKOUCD = '0000' OR QBK1_KOZGINKOUCD = '9900')
AND QBK1_SOHKAKUNINKBN = '0'
AND QBK1_HEKHENKYAKUKBN = '0'
AND QBK1_DATHASOUYMD is not NULL
AND QBK1_DATHENKYAKUYMD is NULL
-- 2004/04/19ＪＣＢ委託した口振依頼は、未埒空きリストの対象外 IMZ.YAMADA -->
AND QBK1_KOUHASOTANTOCD <> 'JCBITAKU'
-- 2004/04/19ＪＣＢ委託した口振依頼は、未埒空きリストの対象外 IMZ.YAMADA <--
;
