CREATE VIEW QBKK_JFHKEKKAV ( 
TOUZAIKBN
,GAIBUKAIINNO
,UKETUKENO
,NAIBUKAIINNO
,KNJ_NAME
,GINKOUCD
,KNJ_GINKO_NAME
,SHITENCD
,KNJ_SHITEN_NAME
,SHUMOKU
,YUCHOSAIHATU
,KOZNO
,KOZMEIGI
,HEKHENKYAKUKBN
,HURIKAEKEKACD
,SEIKYUYM
,HASOUYMD
,HENKYAKUYMD
,KAKUNINKBN
,BLACKNO
 ) AS 
select QBK1_SOHTOUZAIKBN      TOUZAIKBN,
       QBK1_GAIBUKAIINNO      GAIBUKAIINNO,
       QBK1_PRMUKETUKENO      UKETUKENO,
       QBK1_PRMNAIBUKAIINNO   NAIBUKAIINNO,
       QTA1_HONSHIMEIKAN      KNJ_NAME,
       QBK1_KOZGINKOUCD       GINKOUCD,
       QTA7_KINYUKIKANNMKJ    KNJ_GINKO_NAME,
       QBK1_KOZSHITENCD       SHITENCD,
       QTA7_SITENNMKJ         KNJ_SHITEN_NAME,
       QBK1_KOZSHUMOKU        SHUMOKU,
       QBK1_KOZYUCHOSAIHATU   YUCHOSAIHATU,
       QBK1_KOZNO             KOZNO,
       QBK1_KOZMEIGI          KOZMEIGI,
       QBK1_HEKHENKYAKUKBN    HEKHENKYAKUKBN,
       QBK1_JFHHURIKAEKEKACD  HURIKAEKEKACD,
       QBK1_JFHSEIKYUYM       SEIKYUYM,
       QBK1_DATHASOUYMD       HASOUYMD,
       QBK1_DATHENKYAKUYMD    HENKYAKUYMD,
       QBK1_SOHKAKUNINKBN     KAKUNINKBN,
       QBK1_BLACKNO           BLACKNO
  from QBK1_KFURIT, QTA1_KAIINM, QTA7_GINKOUM
 where QBK1_KIGYOUCD          = QTA1_PRMKIGYOUCD
   and QBK1_SUBRANGEKEY       = QTA1_PRMSUBRANGEKEY
   and QBK1_PRMNAIBUKAIINNO   = QTA1_PRMNAIBUKAIINNO
   and QBK1_KOZGINKOUCD       = QTA7_PRMKIKANCD
   and QBK1_KOZSHITENCD       = '00' || QTA7_PRMSHITENCD
   and QBK1_KOZGINKOUCD      != '9900'
   and QBK1_GAIBUKAIINNO     != '0000000000000000'
   and QBK1_JFHHURIKAEKEKACD != '0'
   and QBK1_JFHHURIKAEKEKACD != '1'
   and QBK1_DATJFHENREIYMD is not NULL
union
select QBK1_SOHTOUZAIKBN      TOUZAIKBN,
       QBK1_GAIBUKAIINNO      GAIBUKAIINNO,
       QBK1_PRMUKETUKENO      UKETUKENO,
       QBK1_PRMNAIBUKAIINNO   NAIBUKAIINNO,
       QTA1_HONSHIMEIKAN      KNJ_NAME,
       QBK1_KOZGINKOUCD       GINKOUCD,
       '—X•Ö‹Ç'               KNJ_GINKO_NAME,
       QBK1_KOZSHITENCD       SHITENCD,
       NULL                   KNJ_SHITEN_NAME,
       QBK1_KOZSHUMOKU        SHUMOKU,
       QBK1_KOZYUCHOSAIHATU   YUCHOSAIHATU,
       QBK1_KOZNO             KOZNO,
       QBK1_KOZMEIGI          KOZMEIGI,
       QBK1_HEKHENKYAKUKBN    HEKHENKYAKUKBN,
       QBK1_JFHHURIKAEKEKACD  HURIKAEKEKACD,
       QBK1_JFHSEIKYUYM       SEIKYUYM,
       QBK1_DATHASOUYMD       HASOUYMD,
       QBK1_DATHENKYAKUYMD    HENKYAKUYMD,
       QBK1_SOHKAKUNINKBN     KAKUNINKBN,
       QBK1_BLACKNO           BLACKNO
  from QBK1_KFURIT, QTA1_KAIINM
 where QBK1_KIGYOUCD          = QTA1_PRMKIGYOUCD
   and QBK1_SUBRANGEKEY       = QTA1_PRMSUBRANGEKEY
   and QBK1_PRMNAIBUKAIINNO   = QTA1_PRMNAIBUKAIINNO
   and QBK1_KOZGINKOUCD       = '9900'
   and QBK1_GAIBUKAIINNO     != '0000000000000000'
   and QBK1_JFHHURIKAEKEKACD != '0'
   and QBK1_JFHHURIKAEKEKACD != '1'
   and QBK1_DATJFHENREIYMD is not NULL
;
