CREATE VIEW QSA6_KAIINITIRANV ( 
QTA1_GKNSHIKIBETSUNO
,QTA1_GKNEDABAN
,QTA1_TENEIGYOU
,QTA1_TENKAKUTOKU
,QTA1_CARDKBN
,QTA1_HONSHIMEIKANA
,QTA1_HONSHIMEIKAN
,QTA1_HONSEINENGAPPI
,QTA1_HONSEX
,QTA1_JTKTELSHIGAI
,QTA1_JTKTELKYOKU
,QTA1_JTKTELNO
,QTA1_JTKJUSHOKANA
,QTA1_JTKJUSHOKAN
,QTA1_JTKBANCHIKANA
,QTA1_JTKBANCHIKAN
,QTA1_JTKKATAKANA
,QTA1_JTKKATAKAN
,QTA1_CIFNO
,QTA1_KOZGINKOUCD
,QTA1_KOZGINKOUMEI
,QTA1_KOZSHITENCD
,QTA1_KOZSHITENMEI
,QTA1_KOZSHUMOKU
,QTA1_KOZNO
,QTA1_KOZMEIGI
,QTA1_ATUKAKARI
,QTA2_KZKSHIMEIKANA
,QTA2_KZKSHIMEIKAN
,QTA2_KZKSEX
,QTA2_CIFNO
,QTA2_EDABAN
,QTA2_KZKSEINENGAPPI
,QTAC_PRMBLACKNO
,QTAC_TENEIGYOUCD
,QTAC_TENKAKUTOKU
,QTAC_BLACKRIYU
,QTAC_BLACKRIYUTUIKI
,QTAC_CIFNO
,QTAC_HONSHIMEIKANA
,QTAC_HONSHIMEIKAN
,QTAC_HONSEINENGAPPI
,QTAC_HONSEX
,QTAC_JTKTELSHIGAI
,QTAC_JTKTELKYOKU
,QTAC_JTKTELNO
,QTAC_JTKJUSHOCD
,QTAC_JTKBANCHIKANA
,QTAC_JTKBANCHIKAN
,QTAC_JTKKATAKANA
,QTAC_JTKKATAKAN
,QTAC_CARDKBN
,QTAC_KAIINNO
,QTAS_SHIMEI
,QTAS_TELNO
,QTAS_HONMAESHIMEI
,QTAS_HONMAETELNO
,QTAS_PRMCIFNO
,QTAS_KIGYOUCD
,QTAS_SUBRANGEKEY
,QTAS_NOJNAIBUKAIINNO
,QTAS_HONSEINENGAPPI
 ) AS 
SELECT QTA1_GKNShikibetsuNo,QTA1_GKNEdaban,
	QTA1_TENEigyou,QTA1_TENKakutoku,
	QTA1_CardKbn,QTA1_HONShimeiKana,
	QTA1_HONShimeiKan,QTA1_HONSeinengappi,
	QTA1_HONSex,QTA1_JTKTelShigai,
	QTA1_JTKTelKyoku,QTA1_JTKTelNo,
	QTA1_JTKJushokana,QTA1_JTKJushoKan,
	QTA1_JTKBanchiKana,QTA1_JTKBanchiKan,
	QTA1_JTKKataKana,QTA1_JTKKataKan,
	QTA1_CIFNo,QTA1_KOZGinkouCD,
	QTA1_KOZGinkouMei,QTA1_KOZShitenCd,
	QTA1_KOZShitenMei,QTA1_KOZShumoku,
	QTA1_KOZNo,QTA1_KOZMeigi,QTA1_ATUKakari,
	QTA2_KZKShimeiKana,QTA2_KZKShimeiKan,
	QTA2_KZKSex,QTA2_CIFNo,QTA2_Edaban,
	QTA2_KZKSeinengappi,
	QTAC_PRMBlackNo,QTAC_TENEigyouCd,
	QTAC_TENKakutoku,QTAC_BlackRiyu,
	QTAC_BlackRiyuTuiki,QTAC_CIFNo,
	QTAC_HONShimeiKana,QTAC_HONShimeiKan,
	QTAC_HONSeinengappi,QTAC_HONSex,
	QTAC_JTKTelShigai,QTAC_JTKTelKyoku,
	QTAC_JTKTelNo,QTAC_JTKJushoCd,
	QTAC_JTKBanchiKana,QTAC_JTKBanchiKan,
	QTAC_JTKKataKana,QTAC_JTKKataKan,
	QTAC_CardKbn,QTAC_KaiinNo,
	QTAS_Shimei,QTAS_TelNo,QTAS_HONMaeShimei,
	QTAS_HONMaeTelNo,QTAS_PRMCIFNo,
	QTAS_KigyouCd,QTAS_SubRangeKey,QTAS_NOJNaibuKaiinNo,
	QTAS_HONSeinengappi
 FROM  	QTA1_KaiinM KainM, QTA2_KaiinKazokM KazokuM,
	QTAC_BlackT BlackT,QTAS_NameSearchMS NameS
 WHERE 	(NameS.QTAS_KigyouCd = KainM.QTA1_PRMKigyouCd(+)
 AND	NameS.QTAS_SubRangeKey = KainM.QTA1_PRMSubRangeKey(+)
 AND	NameS.QTAS_NOJNaibuKaiinNo = KainM.QTA1_PRMNaibuKaiinNo(+))
 AND 	(NameS.QTAS_PRMCIFNo = KazokuM.QTA2_CIFNo(+)
 AND	NameS.QTAS_KigyouCd = KazokuM.QTA2_PRMKigyouCd(+)
 AND	NameS.QTAS_SubRangeKey = KazokuM.QTA2_PRMSubRangeKey(+)
 AND	NameS.QTAS_NOJNaibuKaiinNo = KazokuM.QTA2_PRMNaibuKaiinNo(+))
 AND	(NameS.QTAS_NOJBlackNo = BlackT.QTAC_PRMBlackNo(+))

;
