DROP   VIEW QTAF_RIYOUDTV;

CREATE VIEW QTAF_RIYOUDTV (
         QTAF_PRMKIGYOUCD
        ,QTAF_PRMSUBRANGEKEY
        ,QTAF_PRMNAIBUKAIINNO
        ,QTAF_PRMTORIHIKINO
        ,QTAF_RECKBN
        ,QTAF_AKAKUROKBN
        ,QTAF_SEIKYUHORYUKBN
        ,QTAF_RIYOUBI
        ,QTAF_KEIJYOUBI
        ,QTAF_HASSEITEN
        ,QTAF_GYOUSU
        ,QTAF_GKGSHIHARAIHOHO
        ,QTAF_GKGATOSHOUHIZEI
        ,QTAF_GKGATAMAKIN
        ,QTAF_GKGRIYOUSHACD
        ,QTAF_GENTIKAKAKU_MIDASI
        ,QTAF_ISOTUUKA
        ,QTAF_GKGGENTIKAKAKU
        ,QTAF_GKGKOKUNAIKAIGAI
        ,QTAG_PRMGYOUNO
        ,QTAG_GMSSEIKYUKANJI
        ,QTAG_GMSSURYOU
        ,QTAG_GMSKNG
        ,QTAG_GMSBUBIKIGAKU
        ,QTAG_GMSZEIKBN
 ) AS
SELECT
         A.QTAF_PRMKIGYOUCD
        ,A.QTAF_PRMSUBRANGEKEY
        ,A.QTAF_PRMNAIBUKAIINNO
        ,A.QTAF_PRMTORIHIKINO
        ,A.QTAF_RECKBN
        ,A.QTAF_AKAKUROKBN
        ,A.QTAF_SEIKYUHORYUKBN
        ,A.QTAF_RIYOUBI
        ,A.QTAF_KEIJYOUBI
        ,A.QTAF_HASSEITEN
        ,A.QTAF_GYOUSU
        ,A.QTAF_GKGSHIHARAIHOHO
        ,A.QTAF_GKGATOSHOUHIZEI
        ,A.QTAF_GKGATAMAKIN
        ,A.QTAF_GKGRIYOUSHACD
        ,'ÅiåªínâøäiÅ@'
        ,A.QTAF_ISOTUUKA
        ,A.QTAF_GKGGENTIKAKAKU
        ,A.QTAF_GKGKOKUNAIKAIGAI
        ,B.QTAG_PRMGYOUNO
        ,B.QTAG_GMSSEIKYUKANJI
        ,B.QTAG_GMSSURYOU
        ,B.QTAG_GMSKNG
        ,B.QTAG_GMSBUBIKIGAKU
        ,B.QTAG_GMSZEIKBN
FROM     QTAF_RIYOUDTLT A
        ,QTAG_RIYOUDTLGT B
WHERE    A.QTAF_PRMKIGYOUCD     = B.QTAG_PRMKIGYOUCD (+)
AND      A.QTAF_PRMSUBRANGEKEY  = B.QTAG_PRMSUBRANGEKEY (+)
AND      A.QTAF_PRMNAIBUKAIINNO = B.QTAG_PRMNAIBUKAIINNO (+)
AND      A.QTAF_PRMTORIHIKINO   = B.QTAG_PRMTORIHIKINO (+)
AND      A.QTAF_AKAKUROKBN     != '1'
AND      A.QTAF_AKAKUROKBN     != '2'
AND      A.QTAF_SEIKYUHORYUKBN != '1'
;