CREATE VIEW QTAT_NYUKINLISTV ( 
QTAT_PRMKIGYOUCD
,QTAT_PRMSUBRANJEKEY
,QTAT_PRMNAIBUKAIINNO
,QTAT_PRMMEISAINO
,QTAT_PRMSHORITOORIBAN
,QTAT_TOUZAIKBN
,QTAT_NYUKINHASSEITEN
,QTAT_KEIJYOUBI
,QTAT_NYUKINBI
,QTAT_NYUKINHASSEIRIYU
,QTAT_NYUKINKEIRO
,QTAT_KEIROHONYAKUCHI
,QTAT_DENPYOUSHUBETSU
,QTAT_DENPYOUNO
,QTAT_KNG
,QTAT_BUNKAIKBN
,QTAT_BUNKAIKBNHONYAKU
,QTAT_SEIKYUNENGETSU
,QTAT_SHIHARAIHOHO
,QTAT_HOUHOUHONYAKUCHI
,QTAT_JTJGENPON
,QTAT_JTJTESURYOU
,QTAT_JTJSONGAIKIN
,QTAT_JTJMODOSIRISOKU
 ) AS 
select
QTAL_PRMKigyouCd,QTAL_PRMSubRanjeKey,
QTAL_PRMNaibuKaiinNo, QTAL_PRMMeisaiNo, QTAL_PRMKeijyouTuuBan,
QTAL_TouzaiKbn, QTAL_NyukinHasseiTen,
QTAL_KeijyouBi, QTAL_NyukinBi, QTAL_NyukinHasseiRiyu,
QTAL_NyukinKeiro, QTAL_KeiroHonyakuchi, QTAL_DenpyouShubetsu, QTAL_DenpyouNo,
QTAL_Kng,
' ', ' ', 0,' ',
' ',0,
0,0,0
from QTAL_NyukinKJT
union
select
QTAM_PRMKigyouCd,QTAM_PRMSubRanjiKey,
QTAM_PRMNaibuKaiinNo, QTAM_PRMNyukinMeisai, QTAM_PRMShoriTuuBan,
QTAM_TouzaiKbn, QTAM_NyukinHasseiTen,
QTAM_BunkaiBi, QTAM_NyukinBi, ' ',
' ', ' ', QTAM_DenpyouSyubetsu, ' ',
0,
QTAM_BunkaiKbn, QTAM_BunkaiKbnHonyaku, QTAM_SeikyuNengetsu, QTAM_ShiharaiHoho,
QTAM_HouhouHonyakuChi, QTAM_JTJGenpon,
QTAM_JTJTesuryou76 + QTAM_JTJTesuryou16  + QTAM_JTJJimTesuryou,
QTAM_JTJSongaikin, QTAM_JTJModosiRisoku
from QTAM_NyukinSPT
;
