
--DROP   VIEW QTB1_MOSHIKOMITV ;

CREATE VIEW QTB1_MOSHIKOMITV ( 
QBA1_UKETSUKENO,          -- 申込書Ｔ.受付番号
QBA1_COURIERID,           -- 申込書Ｔ.クーリアＩＤ
QBA1_KAKUTOKUTEN,         -- 申込書Ｔ.獲得店
QBA1_EIGYOTEN,            -- 申込書Ｔ.営業店
QBA1_KAKUTOKUROUT,        -- 申込書Ｔ.獲得ルート
QBA1_INPUTROUTE,          -- 申込書Ｔ.入力ルート
QBA1_CARDKBN,             -- 申込書Ｔ.カード区分
QBA1_CARDSYURUI,          -- 申込書Ｔ.カード種類
QBA1_CARDHAKKOKEITAI,     -- 申込書Ｔ.カード発行形態
QBA1_IMAGESTRDATE,        -- 申込書Ｔ.イメージ登録日
QBA1_IMAGEFILE,           -- 申込書Ｔ.イメージファイル名
QBA1_HONFACEKBN,          -- 申込書Ｔ.本人属性・ﾌｪｰｽ区分
QBA1_HONTEIKEIKBN,        -- 申込書Ｔ.本人属性・提携区分
QBA1_HONKNNAME,           -- 申込書Ｔ.本人属性・カナ氏名
QBA1_HONKJNAME,           -- 申込書Ｔ.本人属性・漢字氏名
QBA1_HONRMNAME,           -- 申込書Ｔ.本人属性・ローマ字氏名
QBA1_HONJUSHOCD,          -- 申込書Ｔ.本人属性・住所コード
QBA1_HONCHIBAN,           -- 申込書Ｔ.本人属性・地番
QBA1_HONYUBINNO,          -- 申込書Ｔ.本人属性・郵便番号
QBA1_HONKNTODOFUKEN,      -- 申込書Ｔ.本人属性・カナ都道府県
QBA1_HONKNSHIKCHOSN,      -- 申込書Ｔ.本人属性・カナ市区町村
QBA1_HONKNBANCHI,         -- 申込書Ｔ.本人属性・カナ番地
QBA1_HONKNKATAGAKI,       -- 申込書Ｔ.本人属性・カナ方書
QBA1_HONKJJUSHO,          -- 申込書Ｔ.本人属性・漢字住所
QBA1_HONKJBANCHI,         -- 申込書Ｔ.本人属性・漢字番地
QBA1_HONKJKATAGAKI,       -- 申込書Ｔ.本人属性・漢字方書
QBA1_HONTEL1,             -- 申込書Ｔ.本人属性・電話番号(市街局番）
QBA1_HONTEL2,             -- 申込書Ｔ.本人属性・電話番号(局番）
QBA1_HONTEL3,             -- 申込書Ｔ.本人属性・電話番号（番号）
QBA1_HONKEITAITEL1,       -- 申込書Ｔ.本人属性・携帯電話番号(1）
QBA1_HONKEITAITEL2,       -- 申込書Ｔ.本人属性・携帯電話番号(2）
QBA1_HONKEITAITEL3,       -- 申込書Ｔ.本人属性・携帯電話番号(3）
QBA1_HONSEX,              -- 申込書Ｔ.本人属性・性別
QBA1_HONBIRTHDAY,         -- 申込書Ｔ.本人属性・生年月日
QBA1_HONSUMAIKBN,         -- 申込書Ｔ.本人属性・住まい区分
QBA1_HONSUMAINENSU,       -- 申込書Ｔ.本人属性・居住年数
QBA1_HONHAIGUUM,          -- 申込書Ｔ.本人属性・配偶者有無
QBA1_HONCHILDSU,          -- 申込書Ｔ.本人属性・子供人数
QBA1_HONDOKYOKBN,         -- 申込書Ｔ.本人属性・両親同居区分
QBA1_HONCASHKIBOKG,       -- 申込書Ｔ.本人属性・借入希望限度額
QBA1_HONZANDAKACNT,       -- 申込書Ｔ.本人属性・既借入残高合計件数
QBA1_HONZANDAKAKG,        -- 申込書Ｔ.本人属性・既借入残高合計金額
QBA1_HONPASSWORD,         -- 申込書Ｔ.本人属性・暗証番号
QBA1_HONCALLKBN,          -- 申込書Ｔ.本人属性・呼出区分
QBA1_HONCALLNAME,         -- 申込書Ｔ.本人属性・呼出名
QBA1_KINSHOKUSHU,         -- 申込書Ｔ.勤務先情報・職種
QBA1_KINKINMUKBN,         -- 申込書Ｔ.勤務先情報・勤務先区分
QBA1_KINKNHAIGUNAME,      -- 申込書Ｔ.勤務先情報・カナ配偶者氏名
QBA1_KINKJHAIGUNAME,      -- 申込書Ｔ.勤務先情報・漢字配偶者氏名
QBA1_KINHAIGUZOKGR,       -- 申込書Ｔ.勤務先情報・配偶者続柄
QBA1_KINHAIGUBIRTH,       -- 申込書Ｔ.勤務先情報・配偶者生年月日
QBA1_KINKNNAME,           -- 申込書Ｔ.勤務先情報・カナ勤務先名
QBA1_KINKJNAME,           -- 申込書Ｔ.勤務先情報・漢字勤務先名
QBA1_KINJUSHOCD,          -- 申込書Ｔ.勤務先情報・勤務先住所コード
QBA1_KINCHIBAN,           -- 申込書Ｔ.勤務先情報・勤務先地番
QBA1_KINYUBINNO,          -- 申込書Ｔ.勤務先情報・勤務先郵便番号
QBA1_KINKNTODOFUKEN,      -- 申込書Ｔ.勤務先情報・勤務先カナ都道府県
QBA1_KINKNSHIKCHOSN,      -- 申込書Ｔ.勤務先情報・勤務先カナ市区町村
QBA1_KINKNBANCHI,         -- 申込書Ｔ.勤務先情報・勤務先カナ番地
QBA1_KINKNKATAGAKI,       -- 申込書Ｔ.勤務先情報・勤務先カナ方書
QBA1_KINKJJUSHO,          -- 申込書Ｔ.勤務先情報・勤務先漢字住所
QBA1_KINKJBANCHI,         -- 申込書Ｔ.勤務先情報・勤務先漢字番地
QBA1_KINKJKATAGAKI,       -- 申込書Ｔ.勤務先情報・勤務先漢字方書
QBA1_KINTEL1,             -- 申込書Ｔ.勤務先情報・勤務先電話番号(市街局番）
QBA1_KINTEL2,             -- 申込書Ｔ.勤務先情報・勤務先電話番号(局番）
QBA1_KINTEL3,             -- 申込書Ｔ.勤務先情報・勤務先電話番号(番号）
QBA1_KINNAISEN,           -- 申込書Ｔ.勤務先情報・勤務先内線
QBA1_KINHONTEL1,          -- 申込書Ｔ.勤務先情報・勤務先本社電話番号(市街局番
QBA1_KINHONTEL2,          -- 申込書Ｔ.勤務先情報・勤務先本社電話番号（局番）
QBA1_KINHONTEL3,          -- 申込書Ｔ.勤務先情報・勤務先本社電話番号（番号）
QBA1_KINNENSHUKBN,        -- 申込書Ｔ.勤務先情報・年収区分
QBA1_KINSHUNYUKBN,        -- 申込書Ｔ.勤務先情報・収入源区分
QBA1_KINKJMAENAME,        -- 申込書Ｔ.勤務先情報・転職前漢字勤務先名
QBA1_KINMAENENSUKBN,      -- 申込書Ｔ.勤務先情報・転職前勤続年数
QBA1_KINMAERIYU,          -- 申込書Ｔ.勤務先情報・転職理由
QBA1_KINSHOZOKUBUKA,      -- 申込書Ｔ.勤務先情報・勤務先所属部課名
QBA1_KINYAKUSHOKU,        -- 申込書Ｔ.勤務先情報・勤務先役職
QBA1_KINNYUSHADATE,       -- 申込書Ｔ.勤務先情報・勤務先入社年月
QBA1_KINSETSURITSU,       -- 申込書Ｔ.勤務先情報・勤務先設立年月
QBA1_KINSHIHONKG,         -- 申込書Ｔ.勤務先情報・資本金
QBA1_KINJUGYOCNT,         -- 申込書Ｔ.勤務先情報・従業員数
QBA1_KINNENSUKBN,         -- 申込書Ｔ.勤務先情報・勤続／営業年数区分
QBA1_KINJIEINAIYO,        -- 申込書Ｔ.勤務先情報・自営営業内容
QBA1_KINELSENENSHU,       -- 申込書Ｔ.勤務先情報・その他年収
QBA1_KINELSESHUNYU,       -- 申込書Ｔ.勤務先情報・その他収入内容
QBA1_SKISHOKAISHA,        -- 申込書Ｔ.紹介情報・紹介者
QBA1_SKIKACD,             -- 申込書Ｔ.紹介情報・課ｺｰﾄﾞ
QBA1_SKIKOJINCD,          -- 申込書Ｔ.紹介情報・個人ｺｰﾄﾞ
QBA1_SKINAISEN,           -- 申込書Ｔ.紹介情報・内線
QBA1_SKIMISECD,           -- 申込書Ｔ.紹介情報・店ｺｰﾄﾞ
QBA1_SKIBUHANCD,          -- 申込書Ｔ.紹介情報・部班ｺｰﾄﾞ
QBA1_SKICORNERDATE,       -- 申込書Ｔ.紹介情報・ｺｰﾅｰ受付日
QBA1_ELSTOZAIKBN,         -- 申込書Ｔ.東西区分
QBA1_ELSCLABUCD,          -- 申込書Ｔ.クラブコード
QBA1_ELSFUNYUSKB,         -- 申込書Ｔ.封入識別ｺｰﾄﾞ
QBA1_ELSHENSAIHOHO,       -- 申込書Ｔ.返済方法
QBA1_ELSCARDSOUFU,        -- 申込書Ｔ.ｶｰﾄﾞ送付先区分
QBA1_ELSSEIKYUSOFU,       -- 申込書Ｔ.請求書送付先区分
QBA1_ELSCARDHAKKOKBN,     -- 申込書Ｔ.ｶｰﾄﾞ発行区分
QBA1_ELSCARDYUSOKBN,      -- 申込書Ｔ.ｶｰﾄﾞ郵送区分
QBA1_ELSBUBIKIKBN,        -- 申込書Ｔ.歩引／ﾎﾟｲﾝﾄ区分
QBA1_ELSYOSINRANK,        -- 申込書Ｔ.与信ﾗﾝｸ
QBA1_ELSCARDUMUFLG,       -- 申込書Ｔ.その他情報・所有カード・所有カードフラグ
QBA1_ELSCARDSINPAN,       -- 申込書Ｔ.その他情報・所有カード・信販系カード名称
QBA1_ELSCARDSONOTA,       -- 申込書Ｔ.その他情報・所有カード・その他名称
QBA1_CTLCANS,             -- 申込書Ｔ.制御情報・ｷｬﾝｾﾙｻｲﾝ
QBA1_CTLCANRIYU,          -- 申込書Ｔ.制御情報・ｷｬﾝｾﾙ理由
QBA1_CTLCANTUIKI,         -- 申込書Ｔ.制御情報・ｷｬﾝｾﾙ理由追記
QBA1_CTLHENKYAKUS,        -- 申込書Ｔ.制御情報・申込書返却ｻｲﾝ
QBA1_CTLCANSOKUJIKBN,     -- 申込書Ｔ.制御情報・ｷｬﾝｾﾙ即時区分
QBA1_CTLSEISADATE,        -- 申込書Ｔ.制御情報・精査完了日
QBA1_CTLFSTSGDATE,        -- 申込書Ｔ.制御情報・自動審査日
QBA1_CTLSCDSNSDATE,       -- 申込書Ｔ.制御情報・2次審査依頼日
QBA1_CTLMSTSTRDATE,       -- 申込書Ｔ.制御情報・ﾏｽﾀ登録依頼日
QBA1_CTLHAKKENDATE,       -- 申込書Ｔ.制御情報・発券日付
QBA1_CTLRONEDATE,         -- 申込書Ｔ.制御情報・ローン応諾日付
QBA1_CTLHONKNNAME,        -- 申込書Ｔ.制御情報・名寄用カナ氏名
QBA1_CTLKINKNNAME,        -- 申込書Ｔ.制御情報・名寄用カナ勤務先名
QBA1_CTLKANRITEN,         -- 申込書Ｔ.制御情報・管理店
QBA1_CTLKAISHATEN,        -- 申込書Ｔ.制御情報・会社店
QBA1_CTLJIGYOTEN,         -- 申込書Ｔ.制御情報・事業本部
QBA1_CTLDMTEN,            -- 申込書Ｔ.制御情報・ＤＭ店
QBA1_CTLFLOKBN,           -- 申込書Ｔ.制御情報・フロー区分
QBA1_NOCIFNO,             -- 申込書Ｔ.番号情報・ＣＩＦ番号
QBA1_NOKAIINNO,           -- 申込書Ｔ.番号情報・会員番号
QBA1_NOBLACKNO,           -- 申込書Ｔ.番号情報・ﾌﾞﾗｯｸ番号
QBA1_NOCICINQNO,          -- 申込書Ｔ.番号情報・ＣＩＣ・照会№
QBA1_RONSYURUI,           -- 申込書Ｔ.ローン・ローン種類
QBA1_RONKNG,              -- 申込書Ｔ.ローン・ローン金額
QBA1_RONSHIHARAICNT,      -- 申込書Ｔ.ローン・支払回数
QBA1_RONATAMAKNG,         -- 申込書Ｔ.ローン・頭金
QBA1_RONKAIINNO,          -- 申込書Ｔ.ローン・ローン会員番号
QBA1_RONSKTKBN,           -- 申込書Ｔ.ローン・即決区分
QBA1_RONSKTKESSAICD,      -- 申込書Ｔ.ローン・即決決済者ｺｰﾄﾞ
QBA1_STRDATE,             -- 申込書Ｔ.登録年月日
QBA1_UPDDATE,             -- 申込書Ｔ.更新年月日
QBA1_DELDATE,             -- 申込書Ｔ.削除年月日
QBA1_OPID,                -- 申込書Ｔ.ｵﾍﾟﾚｰﾀID
QBA1_WSID,                -- 申込書Ｔ.端末ID
QBA1_ELSYUUCHOSAIKBN,     -- 申込書Ｔ.郵貯再発行区分
QBA1_HENSAIKNG,           -- 申込書Ｔ.ＷＩＳＨ・毎月返済額
QBA1_BOUNASKNG,           -- 申込書Ｔ.ＷＩＳＨ・ﾎﾞｰﾅｽ月増額
QBAB_UKETSUKENO,          -- メールアドレステーブル.受付番号
QBAB_KAZOKURBN,           -- メールアドレステーブル.家族区分
QBAB_INQKBN,              -- メールアドレステーブル.メール区分
QBAB_GAIBUKAIINNO,        -- メールアドレステーブル.外部会員番号
QBAB_ADDRESS,             -- メールアドレステーブル.メールアドレス
QBAB_STRDATE,             -- メールアドレステーブル.登録日
QBAB_UPDDATE,             -- メールアドレステーブル.更新日
QBAB_DELDATE,             -- メールアドレステーブル.削除日
QBAB_EXPDATE,             -- メールアドレステーブル.出力日
QBAB_OPID,                -- メールアドレステーブル.ｵﾍﾟﾚｰﾀID
QBAB_WSID                 -- メールアドレステーブル.端末ID
 ) AS 
Select
QBA1_UKETSUKENO,          -- 申込書Ｔ.受付番号
QBA1_COURIERID,           -- 申込書Ｔ.クーリアＩＤ
QBA1_KAKUTOKUTEN,         -- 申込書Ｔ.獲得店
QBA1_EIGYOTEN,            -- 申込書Ｔ.営業店
QBA1_KAKUTOKUROUT,        -- 申込書Ｔ.獲得ルート
QBA1_INPUTROUTE,          -- 申込書Ｔ.入力ルート
QBA1_CARDKBN,             -- 申込書Ｔ.カード区分
QBA1_CARDSYURUI,          -- 申込書Ｔ.カード種類
QBA1_CARDHAKKOKEITAI,     -- 申込書Ｔ.カード発行形態
QBA1_IMAGESTRDATE,        -- 申込書Ｔ.イメージ登録日
QBA1_IMAGEFILE,           -- 申込書Ｔ.イメージファイル名
QBA1_HONFACEKBN,          -- 申込書Ｔ.本人属性・ﾌｪｰｽ区分
QBA1_HONTEIKEIKBN,        -- 申込書Ｔ.本人属性・提携区分
QBA1_HONKNNAME,           -- 申込書Ｔ.本人属性・カナ氏名
QBA1_HONKJNAME,           -- 申込書Ｔ.本人属性・漢字氏名
QBA1_HONRMNAME,           -- 申込書Ｔ.本人属性・ローマ字氏名
QBA1_HONJUSHOCD,          -- 申込書Ｔ.本人属性・住所コード
QBA1_HONCHIBAN,           -- 申込書Ｔ.本人属性・地番
QBA1_HONYUBINNO,          -- 申込書Ｔ.本人属性・郵便番号
QBA1_HONKNTODOFUKEN,      -- 申込書Ｔ.本人属性・カナ都道府県
QBA1_HONKNSHIKCHOSN,      -- 申込書Ｔ.本人属性・カナ市区町村
QBA1_HONKNBANCHI,         -- 申込書Ｔ.本人属性・カナ番地
QBA1_HONKNKATAGAKI,       -- 申込書Ｔ.本人属性・カナ方書
QBA1_HONKJJUSHO,          -- 申込書Ｔ.本人属性・漢字住所
QBA1_HONKJBANCHI,         -- 申込書Ｔ.本人属性・漢字番地
QBA1_HONKJKATAGAKI,       -- 申込書Ｔ.本人属性・漢字方書
QBA1_HONTEL1,             -- 申込書Ｔ.本人属性・電話番号(市街局番）
QBA1_HONTEL2,             -- 申込書Ｔ.本人属性・電話番号(局番）
QBA1_HONTEL3,             -- 申込書Ｔ.本人属性・電話番号（番号）
QBA1_HONKEITAITEL1,       -- 申込書Ｔ.本人属性・携帯電話番号(1）
QBA1_HONKEITAITEL2,       -- 申込書Ｔ.本人属性・携帯電話番号(2）
QBA1_HONKEITAITEL3,       -- 申込書Ｔ.本人属性・携帯電話番号(3）
QBA1_HONSEX,              -- 申込書Ｔ.本人属性・性別
QBA1_HONBIRTHDAY,         -- 申込書Ｔ.本人属性・生年月日
QBA1_HONSUMAIKBN,         -- 申込書Ｔ.本人属性・住まい区分
QBA1_HONSUMAINENSU,       -- 申込書Ｔ.本人属性・居住年数
QBA1_HONHAIGUUM,          -- 申込書Ｔ.本人属性・配偶者有無
QBA1_HONCHILDSU,          -- 申込書Ｔ.本人属性・子供人数
QBA1_HONDOKYOKBN,         -- 申込書Ｔ.本人属性・両親同居区分
QBA1_HONCASHKIBOKG,       -- 申込書Ｔ.本人属性・借入希望限度額
QBA1_HONZANDAKACNT,       -- 申込書Ｔ.本人属性・既借入残高合計件数
QBA1_HONZANDAKAKG,        -- 申込書Ｔ.本人属性・既借入残高合計金額
QBA1_HONPASSWORD,         -- 申込書Ｔ.本人属性・暗証番号
QBA1_HONCALLKBN,          -- 申込書Ｔ.本人属性・呼出区分
QBA1_HONCALLNAME,         -- 申込書Ｔ.本人属性・呼出名
QBA1_KINSHOKUSHU,         -- 申込書Ｔ.勤務先情報・職種
QBA1_KINKINMUKBN,         -- 申込書Ｔ.勤務先情報・勤務先区分
QBA1_KINKNHAIGUNAME,      -- 申込書Ｔ.勤務先情報・カナ配偶者氏名
QBA1_KINKJHAIGUNAME,      -- 申込書Ｔ.勤務先情報・漢字配偶者氏名
QBA1_KINHAIGUZOKGR,       -- 申込書Ｔ.勤務先情報・配偶者続柄
QBA1_KINHAIGUBIRTH,       -- 申込書Ｔ.勤務先情報・配偶者生年月日
QBA1_KINKNNAME,           -- 申込書Ｔ.勤務先情報・カナ勤務先名
QBA1_KINKJNAME,           -- 申込書Ｔ.勤務先情報・漢字勤務先名
QBA1_KINJUSHOCD,          -- 申込書Ｔ.勤務先情報・勤務先住所コード
QBA1_KINCHIBAN,           -- 申込書Ｔ.勤務先情報・勤務先地番
QBA1_KINYUBINNO,          -- 申込書Ｔ.勤務先情報・勤務先郵便番号
QBA1_KINKNTODOFUKEN,      -- 申込書Ｔ.勤務先情報・勤務先カナ都道府県
QBA1_KINKNSHIKCHOSN,      -- 申込書Ｔ.勤務先情報・勤務先カナ市区町村
QBA1_KINKNBANCHI,         -- 申込書Ｔ.勤務先情報・勤務先カナ番地
QBA1_KINKNKATAGAKI,       -- 申込書Ｔ.勤務先情報・勤務先カナ方書
QBA1_KINKJJUSHO,          -- 申込書Ｔ.勤務先情報・勤務先漢字住所
QBA1_KINKJBANCHI,         -- 申込書Ｔ.勤務先情報・勤務先漢字番地
QBA1_KINKJKATAGAKI,       -- 申込書Ｔ.勤務先情報・勤務先漢字方書
QBA1_KINTEL1,             -- 申込書Ｔ.勤務先情報・勤務先電話番号(市街局番）
QBA1_KINTEL2,             -- 申込書Ｔ.勤務先情報・勤務先電話番号(局番）
QBA1_KINTEL3,             -- 申込書Ｔ.勤務先情報・勤務先電話番号(番号）
QBA1_KINNAISEN,           -- 申込書Ｔ.勤務先情報・勤務先内線
QBA1_KINHONTEL1,          -- 申込書Ｔ.勤務先情報・勤務先本社電話番号(市街局番
QBA1_KINHONTEL2,          -- 申込書Ｔ.勤務先情報・勤務先本社電話番号（局番）
QBA1_KINHONTEL3,          -- 申込書Ｔ.勤務先情報・勤務先本社電話番号（番号）
QBA1_KINNENSHUKBN,        -- 申込書Ｔ.勤務先情報・年収区分
QBA1_KINSHUNYUKBN,        -- 申込書Ｔ.勤務先情報・収入源区分
QBA1_KINKJMAENAME,        -- 申込書Ｔ.勤務先情報・転職前漢字勤務先名
QBA1_KINMAENENSUKBN,      -- 申込書Ｔ.勤務先情報・転職前勤続年数
QBA1_KINMAERIYU,          -- 申込書Ｔ.勤務先情報・転職理由
QBA1_KINSHOZOKUBUKA,      -- 申込書Ｔ.勤務先情報・勤務先所属部課名
QBA1_KINYAKUSHOKU,        -- 申込書Ｔ.勤務先情報・勤務先役職
QBA1_KINNYUSHADATE,       -- 申込書Ｔ.勤務先情報・勤務先入社年月
QBA1_KINSETSURITSU,       -- 申込書Ｔ.勤務先情報・勤務先設立年月
QBA1_KINSHIHONKG,         -- 申込書Ｔ.勤務先情報・資本金
QBA1_KINJUGYOCNT,         -- 申込書Ｔ.勤務先情報・従業員数
QBA1_KINNENSUKBN,         -- 申込書Ｔ.勤務先情報・勤続／営業年数区分
QBA1_KINJIEINAIYO,        -- 申込書Ｔ.勤務先情報・自営営業内容
QBA1_KINELSENENSHU,       -- 申込書Ｔ.勤務先情報・その他年収
QBA1_KINELSESHUNYU,       -- 申込書Ｔ.勤務先情報・その他収入内容
QBA1_SKISHOKAISHA,        -- 申込書Ｔ.紹介情報・紹介者
QBA1_SKIKACD,             -- 申込書Ｔ.紹介情報・課ｺｰﾄﾞ
QBA1_SKIKOJINCD,          -- 申込書Ｔ.紹介情報・個人ｺｰﾄﾞ
QBA1_SKINAISEN,           -- 申込書Ｔ.紹介情報・内線
QBA1_SKIMISECD,           -- 申込書Ｔ.紹介情報・店ｺｰﾄﾞ
QBA1_SKIBUHANCD,          -- 申込書Ｔ.紹介情報・部班ｺｰﾄﾞ
QBA1_SKICORNERDATE,       -- 申込書Ｔ.紹介情報・ｺｰﾅｰ受付日
QBA1_ELSTOZAIKBN,         -- 申込書Ｔ.東西区分
QBA1_ELSCLABUCD,          -- 申込書Ｔ.クラブコード
QBA1_ELSFUNYUSKB,         -- 申込書Ｔ.封入識別ｺｰﾄﾞ
QBA1_ELSHENSAIHOHO,       -- 申込書Ｔ.返済方法
QBA1_ELSCARDSOUFU,        -- 申込書Ｔ.ｶｰﾄﾞ送付先区分
QBA1_ELSSEIKYUSOFU,       -- 申込書Ｔ.請求書送付先区分
QBA1_ELSCARDHAKKOKBN,     -- 申込書Ｔ.ｶｰﾄﾞ発行区分
QBA1_ELSCARDYUSOKBN,      -- 申込書Ｔ.ｶｰﾄﾞ郵送区分
QBA1_ELSBUBIKIKBN,        -- 申込書Ｔ.歩引／ﾎﾟｲﾝﾄ区分
QBA1_ELSYOSINRANK,        -- 申込書Ｔ.与信ﾗﾝｸ
QBA1_ELSCARDUMUFLG,       -- 申込書Ｔ.その他情報・所有カード・所有カードフラグ
QBA1_ELSCARDSINPAN,       -- 申込書Ｔ.その他情報・所有カード・信販系カード名称
QBA1_ELSCARDSONOTA,       -- 申込書Ｔ.その他情報・所有カード・その他名称
QBA1_CTLCANS,             -- 申込書Ｔ.制御情報・ｷｬﾝｾﾙｻｲﾝ
QBA1_CTLCANRIYU,          -- 申込書Ｔ.制御情報・ｷｬﾝｾﾙ理由
QBA1_CTLCANTUIKI,         -- 申込書Ｔ.制御情報・ｷｬﾝｾﾙ理由追記
QBA1_CTLHENKYAKUS,        -- 申込書Ｔ.制御情報・申込書返却ｻｲﾝ
QBA1_CTLCANSOKUJIKBN,     -- 申込書Ｔ.制御情報・ｷｬﾝｾﾙ即時区分
QBA1_CTLSEISADATE,        -- 申込書Ｔ.制御情報・精査完了日
QBA1_CTLFSTSGDATE,        -- 申込書Ｔ.制御情報・自動審査日
QBA1_CTLSCDSNSDATE,       -- 申込書Ｔ.制御情報・2次審査依頼日
QBA1_CTLMSTSTRDATE,       -- 申込書Ｔ.制御情報・ﾏｽﾀ登録依頼日
QBA1_CTLHAKKENDATE,       -- 申込書Ｔ.制御情報・発券日付
QBA1_CTLRONEDATE,         -- 申込書Ｔ.制御情報・ローン応諾日付
QBA1_CTLHONKNNAME,        -- 申込書Ｔ.制御情報・名寄用カナ氏名
QBA1_CTLKINKNNAME,        -- 申込書Ｔ.制御情報・名寄用カナ勤務先名
QBA1_CTLKANRITEN,         -- 申込書Ｔ.制御情報・管理店
QBA1_CTLKAISHATEN,        -- 申込書Ｔ.制御情報・会社店
QBA1_CTLJIGYOTEN,         -- 申込書Ｔ.制御情報・事業本部
QBA1_CTLDMTEN,            -- 申込書Ｔ.制御情報・ＤＭ店
QBA1_CTLFLOKBN,           -- 申込書Ｔ.制御情報・フロー区分
QBA1_NOCIFNO,             -- 申込書Ｔ.番号情報・ＣＩＦ番号
QBA1_NOKAIINNO,           -- 申込書Ｔ.番号情報・会員番号
QBA1_NOBLACKNO,           -- 申込書Ｔ.番号情報・ﾌﾞﾗｯｸ番号
QBA1_NOCICINQNO,          -- 申込書Ｔ.番号情報・ＣＩＣ・照会№
QBA1_RONSYURUI,           -- 申込書Ｔ.ローン・ローン種類
QBA1_RONKNG,              -- 申込書Ｔ.ローン・ローン金額
QBA1_RONSHIHARAICNT,      -- 申込書Ｔ.ローン・支払回数
QBA1_RONATAMAKNG,         -- 申込書Ｔ.ローン・頭金
QBA1_RONKAIINNO,          -- 申込書Ｔ.ローン・ローン会員番号
QBA1_RONSKTKBN,           -- 申込書Ｔ.ローン・即決区分
QBA1_RONSKTKESSAICD,      -- 申込書Ｔ.ローン・即決決済者ｺｰﾄﾞ
QBA1_STRDATE,             -- 申込書Ｔ.登録年月日
QBA1_UPDDATE,             -- 申込書Ｔ.更新年月日
QBA1_DELDATE,             -- 申込書Ｔ.削除年月日
QBA1_OPID,                -- 申込書Ｔ.ｵﾍﾟﾚｰﾀID
QBA1_WSID,                -- 申込書Ｔ.端末ID
QBA1_ELSYUUCHOSAIKBN,     -- 申込書Ｔ.郵貯再発行区分
QBA1_HENSAIKNG,           -- 申込書Ｔ.ＷＩＳＨ・毎月返済額
QBA1_BOUNASKNG,           -- 申込書Ｔ.ＷＩＳＨ・ﾎﾞｰﾅｽ月増額
QBAB_UKETSUKENO,          -- メールアドレステーブル.受付番号
QBAB_KAZOKURBN,           -- メールアドレステーブル.家族区分
QBAB_INQKBN,              -- メールアドレステーブル.メール区分
QBAB_GAIBUKAIINNO,        -- メールアドレステーブル.外部会員番号
QBAB_ADDRESS,             -- メールアドレステーブル.メールアドレス
QBAB_STRDATE,             -- メールアドレステーブル.登録日
QBAB_UPDDATE,             -- メールアドレステーブル.更新日
QBAB_DELDATE,             -- メールアドレステーブル.削除日
QBAB_EXPDATE,             -- メールアドレステーブル.出力日
QBAB_OPID,                -- メールアドレステーブル.ｵﾍﾟﾚｰﾀID
QBAB_WSID                 -- メールアドレステーブル.端末ID
From QBA1_MOSHIKOMIT,QBAB_MAILADDRESST
Where
QBA1_UKETSUKENO          = QBAB_UKETSUKENO(+) and
QBAB_KAZOKURBN(+)        = 1;
