
--DROP   VIEW QTB1_KAIINMV ;

CREATE VIEW QTB1_KAIINMV ( 
QTA1_PRMKIGYOUCD,         -- 会員マスタ.主キー・企業コード
QTA1_PRMSUBRANGEKEY,      -- 会員マスタ.主キー・サブレンジキー
QTA1_PRMNAIBUKAIINNO,     -- 会員マスタ.主キー・内部会員番号
QTA1_RECKBN,              -- 会員マスタ.レコード区分
QTA1_ZANDAKAKANRIKBN,     -- 会員マスタ.残高管理区分
QTA1_KAIJOKBN,            -- 会員マスタ.解除区分
QTA1_10TO16KBN,           -- 会員マスタ.10桁16桁区分
QTA1_GKNSHIKIBETSUNO,     -- 会員マスタ.外部会員番号・識別番号
QTA1_GKNEDABAN,           -- 会員マスタ.外部会員番号・本人枝番
QTA1_TENKAISHA,           -- 会員マスタ.店情報・会社店
QTA1_TENSAIKENKANRI,      -- 会員マスタ.店情報・債権管理店
QTA1_TENEIGYOU,           -- 会員マスタ.店情報・営業店
QTA1_TENDM,               -- 会員マスタ.店情報・ＤＭ店
QTA1_TENJIGYOHONBU,       -- 会員マスタ.店情報・事業本部コード
QTA1_TENKAKUTOKU,         -- 会員マスタ.店情報・獲得店
QTA1_CARDKBN,             -- 会員マスタ.カード区分
QTA1_TRSSYOKU1,           -- 会員マスタ.取扱商品・Ｓ翌一回払
QTA1_TRSSYOKU2,           -- 会員マスタ.取扱商品・Ｓ翌二回払
QTA1_TRSSBONUS1,          -- 会員マスタ.取扱商品・Ｓボーナス一回払
QTA1_TRSSBONUS2,          -- 会員マスタ.取扱商品・Ｓボーナス二回払
QTA1_TRSSKAPPU,           -- 会員マスタ.取扱商品・Ｓ割賦
QTA1_TRSSREVOLVING,       -- 会員マスタ.取扱商品・Ｓリボルビング
QTA1_TRSSHANBAI,          -- 会員マスタ.取扱商品・Ｓ職員販売
QTA1_TRSSKAKEURI,         -- 会員マスタ.取扱商品・Ｓ職員掛売
QTA1_TRSCREVOLVING,       -- 会員マスタ.取扱商品・Ｃリボルビング
QTA1_TRSCYOKU1,           -- 会員マスタ.取扱商品・Ｃ翌一回払
QTA1_CARDLOANUSEKBN,      -- 会員マスタ.カードローン使用区分
QTA1_HENSAIHOUHOU,        -- 会員マスタ.返済方法
QTA1_SIHARAIYOTEIBI,      -- 会員マスタ.支払予定日
QTA1_REVSMAITSUKI,        -- 会員マスタ.リボルビング・Ｓ毎月分
QTA1_REVSBONUS,           -- 会員マスタ.リボルビング・Ｓボーナス分
QTA1_REVCMAITSUKI,        -- 会員マスタ.リボルビング・Ｃ毎月分
QTA1_REVCBONUS,           -- 会員マスタ.リボルビング・Ｃボーナス分
QTA1_BBKSHUBETSU,         -- 会員マスタ.歩引情報・種別
QTA1_BBKRITSU,            -- 会員マスタ.歩引情報・率
QTA1_ASNGEN,              -- 会員マスタ.暗証番号・現
QTA1_ANSKYUU,             -- 会員マスタ.暗証番号・旧
QTA1_ANSHENKOUYMD,        -- 会員マスタ.暗証番号・変更日
QTA1_NYKUKETSUKENO,       -- 会員マスタ.入会情報・受付番号
QTA1_NYKUKETSUKEYMD,      -- 会員マスタ.入会情報・受付日
QTA1_NYKKESSAIYMD,        -- 会員マスタ.入会情報・決裁日
QTA1_YUKOKIGEN,           -- 会員マスタ.有効期限
QTA1_KTKROUTE,            -- 会員マスタ.獲得情報・ルート
QTA1_KTKSHOUKAISHACD,     -- 会員マスタ.獲得情報・紹介者コード
QTA1_YSNRANK,             -- 会員マスタ.与信情報・与信ランク
QTA1_YSNSOUGENDO,         -- 会員マスタ.与信情報・総限度額
QTA1_YSNNOBEGENDO,        -- 会員マスタ.与信情報・延払限度額
QTA1_YSNKYUBONUSGENDO,    -- 会員マスタ.与信情報・旧ボーナス限度額
QTA1_YSNCASHGENDO,        -- 会員マスタ.与信情報・キャッシング限度額
QTA1_YSNIKKATSUGENDO,     -- 会員マスタ.与信情報・一時一括限度額
QTA1_YSNKAPPUGENDO,       -- 会員マスタ.与信情報・一時割賦限度額
QTA1_YSNBONUSGENDO,       -- 会員マスタ.与信情報・一時ボーナス限度額
QTA1_YSNYUKOKAISHI,       -- 会員マスタ.与信情報・一時限度額有効期限開始
QTA1_YSNYUKOOWARI,        -- 会員マスタ.与信情報・一時限度額有効期限終了
QTA1_CIFDOUITSUNINNO,     -- 会員マスタ.CIF情報・同一人番号
QTA1_CIFNO,               -- 会員マスタ.CIF情報・ＣＩＦ番号
QTA1_CIFSHOUKAINO,        -- 会員マスタ.CIF情報・ＣＩＣ照会番号
QTA1_HONSHIMEIKANA,       -- 会員マスタ.本人情報・氏名カナ
QTA1_HONSHIMEIROMA,       -- 会員マスタ.本人情報・氏名ローマ字
QTA1_HONSHIMEIKAN,        -- 会員マスタ.本人情報・氏名漢字
QTA1_HONSEINENGAPPI,      -- 会員マスタ.本人情報・生年月日
QTA1_HONSEX,              -- 会員マスタ.本人情報・性別
QTA1_JTKTELSHIGAI,        -- 会員マスタ.自宅情報・市外局番
QTA1_JTKTELKYOKU,         -- 会員マスタ.自宅情報・電話局番
QTA1_JTKTELNO,            -- 会員マスタ.自宅情報・電話番号
QTA1_JTKJUSHOCD,          -- 会員マスタ.自宅情報・住所コード
QTA1_JTKYUUBINNO,         -- 会員マスタ.自宅情報・郵便番号
QTA1_JTKKENKANA,          -- 会員マスタ.自宅情報・県名カナ
QTA1_JTKJUSHOKANA,        -- 会員マスタ.自宅情報・住所名カナ
QTA1_JTKBANCHIKANA,       -- 会員マスタ.自宅情報・番地カナ
QTA1_JTKKATAKANA,         -- 会員マスタ.自宅情報・方書カナ
QTA1_JTKJUSHOKAN,         -- 会員マスタ.自宅情報・住所名漢字
QTA1_JTKBANCHIKAN,        -- 会員マスタ.自宅情報・番地漢字
QTA1_JTKKATAKAN,          -- 会員マスタ.自宅情報・方書漢字
QTA1_KOZHENKOUYMD,        -- 会員マスタ.口座情報・登録変更日
QTA1_KOZGINKOUCD,         -- 会員マスタ.口座情報・銀行コード
QTA1_KOZGINKOUMEI,        -- 会員マスタ.口座情報・銀行名
QTA1_KOZSHITENCD,         -- 会員マスタ.口座情報・支店コード
QTA1_KOZSHITENMEI,        -- 会員マスタ.口座情報・支店名
QTA1_KOZSHUMOKU,          -- 会員マスタ.口座情報・預金種目
QTA1_KOZNO,               -- 会員マスタ.口座情報・口座番号
QTA1_KOZMEIGI,            -- 会員マスタ.口座情報・口座名義
QTA1_CLUBCD,              -- 会員マスタ.クラブコード
QTA1_STSKOZATOROKUYMD,    -- 会員マスタ.ステータス情報・口座ステータス登録日
QTA1_STSKOZA,             -- 会員マスタ.ステータス情報・口座ステータス
QTA1_STSCARDTOROKUYMD,    -- 会員マスタ.ステータス情報・カードステータス登録日
QTA1_STSCARD,             -- 会員マスタ.ステータス情報・カードステータス
QTA1_EDJRIYOUSHACD1,      -- 会員マスタ.枝番情報・利用者コード１
QTA1_EDJJIKOYMD1,         -- 会員マスタ.枝番情報・事故発生日１
QTA1_EDJCARDJYOKYO1,      -- 会員マスタ.枝番情報・カード状況１
QTA1_EDJRIYOUSHACD2,      -- 会員マスタ.枝番情報・利用者コード２
QTA1_EDJJIKOYMD2,         -- 会員マスタ.枝番情報・事故発生日２
QTA1_EDJCARDJYOKYO2,      -- 会員マスタ.枝番情報・カード状況２
QTA1_EDJRIYOUSHACD3,      -- 会員マスタ.枝番情報・利用者コード３
QTA1_EDJJIKOYMD3,         -- 会員マスタ.枝番情報・事故発生日３
QTA1_EDJCARDJYOKYO3,      -- 会員マスタ.枝番情報・カード状況３
QTA1_EDJRIYOUSHACD4,      -- 会員マスタ.枝番情報・利用者コード４
QTA1_EDJJIKOYMD4,         -- 会員マスタ.枝番情報・事故発生日４
QTA1_EDJCARDJYOKYO4,      -- 会員マスタ.枝番情報・カード状況４
QTA1_EDJRIYOUSHACD5,      -- 会員マスタ.枝番情報・利用者コード５
QTA1_EDJJIKOYMD5,         -- 会員マスタ.枝番情報・事故発生日５
QTA1_EDJCARDJYOKYO5,      -- 会員マスタ.枝番情報・カード状況５
QTA1_EDJRIYOUSHACD6,      -- 会員マスタ.枝番情報・利用者コード６
QTA1_EDJJIKOYMD6,         -- 会員マスタ.枝番情報・事故発生日６
QTA1_EDJCARDJYOKYO6,      -- 会員マスタ.枝番情報・カード状況６
QTA1_EDJRIYOUSHACD7,      -- 会員マスタ.枝番情報・利用者コード７
QTA1_EDJJIKOYMD7,         -- 会員マスタ.枝番情報・事故発生日７
QTA1_EDJCARDJYOKYO7,      -- 会員マスタ.枝番情報・カード状況７
QTA1_EDJRIYOUSHACD8,      -- 会員マスタ.枝番情報・利用者コード８
QTA1_EDJJIKOYMD8,         -- 会員マスタ.枝番情報・事故発生日８
QTA1_EDJCARDJYOKYO8,      -- 会員マスタ.枝番情報・カード状況８
QTA1_EDJRIYOUSHACD9,      -- 会員マスタ.枝番情報・利用者コード９
QTA1_EDJJIKOYMD9,         -- 会員マスタ.枝番情報・事故発生日９
QTA1_EDJCARDJYOKYO9,      -- 会員マスタ.枝番情報・カード状況９
QTA1_SOHCARD,             -- 会員マスタ.送付先情報・カード
QTA1_SOHSEIKYU,           -- 会員マスタ.送付先情報・請求書
QTA1_CDHHAKKOUKBN,        -- 会員マスタ.カード発券情報・発行区分
QTA1_CDHYUSOKBN,          -- 会員マスタ.カード発券情報・郵送区分
QTA1_CDHYMD,              -- 会員マスタ.カード発券情報・日
QTA1_CDHYUCHOSAIHATU,     -- 会員マスタ.カード発券情報・郵貯再発行回数
QTA1_KIKYMD,              -- 会員マスタ.口座移管情報・移管日
QTA1_KIKKYUUNO,           -- 会員マスタ.口座移管情報・旧会員番号
QTA1_KIK10KETANO,         -- 会員マスタ.口座移管情報・10桁会員番号
QTA1_TKSHENREIYMD,        -- 会員マスタ.提携先情報・返戻日
QTA1_TKSCARDNO,           -- 会員マスタ.提携先情報・カード番号
QTA1_TKSKEKKACD,          -- 会員マスタ.提携先情報・結果コード
QTA1_TKSRIYUCD,           -- 会員マスタ.提携先情報・理由コード
QTA1_EDBSAISHURIYOU,      -- 会員マスタ.枝番情報・最終利用者コード
QTA1_EDBYUKOMUKO1,        -- 会員マスタ.枝番情報・有効無効表示1
QTA1_EDBYUKOMUKO2,        -- 会員マスタ.枝番情報・有効無効表示2
QTA1_EDBYUKOMUKO3,        -- 会員マスタ.枝番情報・有効無効表示3
QTA1_EDBYUKOMUKO4,        -- 会員マスタ.枝番情報・有効無効表示4
QTA1_EDBYUKOMUKO5,        -- 会員マスタ.枝番情報・有効無効表示5
QTA1_EDBYUKOMUKO6,        -- 会員マスタ.枝番情報・有効無効表示6
QTA1_EDBYUKOMUKO7,        -- 会員マスタ.枝番情報・有効無効表示7
QTA1_EDBYUKOMUKO8,        -- 会員マスタ.枝番情報・有効無効表示8
QTA1_EDBYUKOMUKO9,        -- 会員マスタ.枝番情報・有効無効表示9
QTA1_ATUKAKARI,           -- 会員マスタ.扱部係情報・扱部課係
QTA1_ATUKOUSHINMAE,       -- 会員マスタ.扱部係情報・更新前扱部課係
QTA1_ATUHENKOUYMD,        -- 会員マスタ.扱部係情報・変更日
QTA1_PNTSHINNO,           -- 会員マスタ.交換番号情報・新交換番号
QTA1_PNTKYUUNO,           -- 会員マスタ.交換番号情報・旧交換番号
QTA1_PNTHENKOUYMD,        -- 会員マスタ.交換番号情報・交換番号変更日
QTA1_PNTKBN,              -- 会員マスタ.ポイント情報・区分
QTA1_PNTCARDFACE,         -- 会員マスタ.ポイント情報・カードフェース
QTA1_PNTTEIKEIKBN,        -- 会員マスタ.ポイント情報・提携区分
QTA1_IKANMAECARDKBN,      -- 会員マスタ.移管前カード区分
QTA1_KMSKBN,              -- 会員マスタ.勤務先情報・区分
QTA1_KMSMEIKANA,          -- 会員マスタ.勤務先情報・名称カナ
QTA1_KMSMEIKAN,           -- 会員マスタ.勤務先情報・名称漢字
QTA1_KMSBUKA,             -- 会員マスタ.勤務先情報・所属部課
QTA1_KMSTELSHIGAI,        -- 会員マスタ.勤務先情報・市外局番
QTA1_KMSTELKYOKU,         -- 会員マスタ.勤務先情報・電話局番
QTA1_KMSTELNO,            -- 会員マスタ.勤務先情報・電話番号
QTA1_KMSJUSHOCD,          -- 会員マスタ.勤務先情報・住所コード
QTA1_KMSYUUBINNO,         -- 会員マスタ.勤務先情報・郵便番号
QTA1_KMSKENKANA,          -- 会員マスタ.勤務先情報・県名カナ
QTA1_KMSJUSHOKANA,        -- 会員マスタ.勤務先情報・住所名カナ
QTA1_KMSBANCHIKANA,       -- 会員マスタ.勤務先情報・番地カナ
QTA1_KMSKATAKANA,         -- 会員マスタ.勤務先情報・方書カナ
QTA1_KMSJUSHOKAN,         -- 会員マスタ.勤務先情報・住所名漢字
QTA1_KMSBANCHIKAN,        -- 会員マスタ.勤務先情報・番地漢字
QTA1_KMSKATAKAN,          -- 会員マスタ.勤務先情報・方書漢字
QTA1_HOSTSHORIYMD,        -- 会員マスタ.ホスト処理日
QTA1_HOSTSHORITIME,       -- 会員マスタ.ホスト処理時刻
QTA1_SVRKOUSHINYMD,       -- 会員マスタ.サーバ更新日
QTAR_PRMKIGYOUCD,         -- Ｗｅｂ会員マスタ.主キー・企業コード
QTAR_PRMSUBRANGEKEY,      -- Ｗｅｂ会員マスタ.主キー・サブレンジキー
QTAR_PRMNAIBUKAIINNO,     -- Ｗｅｂ会員マスタ.主キー・内部会員番号
QTAR_PRMRIYOUSHACD,       -- Ｗｅｂ会員マスタ.主キー・利用者コード
QTAR_SEQNO,               -- Ｗｅｂ会員マスタ.ＳＥＱ
QTAR_WEBKAIINID,          -- Ｗｅｂ会員マスタ.Web会員ＩＤ
QTAR_GAIBUKAIINNO,        -- Ｗｅｂ会員マスタ.外部会員番号
QTAR_KAIINKEY,            -- Ｗｅｂ会員マスタ.ＴＣＣ会員マスタキー
QTAR_NMOSHIKOMIDATE,      -- Ｗｅｂ会員マスタ.申込登録日時
QTAR_SMOSHIKOMIDATE,      -- Ｗｅｂ会員マスタ.請求登録日時
QTAR_SMOSHIKOMIKAISU,     -- Ｗｅｂ会員マスタ.請求確認回数
QTAR_STRDATE,             -- Ｗｅｂ会員マスタ.作成日時
QTAR_UPDDATE,             -- Ｗｅｂ会員マスタ.更新日時
QTAR_DELDATE,             -- Ｗｅｂ会員マスタ.削除日時
QBE9_UKETSUKENO           -- 申込書テーブル.受付番号
 ) AS 
Select
QTA1_PRMKIGYOUCD,         -- 会員マスタ.主キー・企業コード
QTA1_PRMSUBRANGEKEY,      -- 会員マスタ.主キー・サブレンジキー
QTA1_PRMNAIBUKAIINNO,     -- 会員マスタ.主キー・内部会員番号
QTA1_RECKBN,              -- 会員マスタ.レコード区分
QTA1_ZANDAKAKANRIKBN,     -- 会員マスタ.残高管理区分
QTA1_KAIJOKBN,            -- 会員マスタ.解除区分
QTA1_10TO16KBN,           -- 会員マスタ.10桁16桁区分
QTA1_GKNSHIKIBETSUNO,     -- 会員マスタ.外部会員番号・識別番号
QTA1_GKNEDABAN,           -- 会員マスタ.外部会員番号・本人枝番
QTA1_TENKAISHA,           -- 会員マスタ.店情報・会社店
QTA1_TENSAIKENKANRI,      -- 会員マスタ.店情報・債権管理店
QTA1_TENEIGYOU,           -- 会員マスタ.店情報・営業店
QTA1_TENDM,               -- 会員マスタ.店情報・ＤＭ店
QTA1_TENJIGYOHONBU,       -- 会員マスタ.店情報・事業本部コード
QTA1_TENKAKUTOKU,         -- 会員マスタ.店情報・獲得店
QTA1_CARDKBN,             -- 会員マスタ.カード区分
QTA1_TRSSYOKU1,           -- 会員マスタ.取扱商品・Ｓ翌一回払
QTA1_TRSSYOKU2,           -- 会員マスタ.取扱商品・Ｓ翌二回払
QTA1_TRSSBONUS1,          -- 会員マスタ.取扱商品・Ｓボーナス一回払
QTA1_TRSSBONUS2,          -- 会員マスタ.取扱商品・Ｓボーナス二回払
QTA1_TRSSKAPPU,           -- 会員マスタ.取扱商品・Ｓ割賦
QTA1_TRSSREVOLVING,       -- 会員マスタ.取扱商品・Ｓリボルビング
QTA1_TRSSHANBAI,          -- 会員マスタ.取扱商品・Ｓ職員販売
QTA1_TRSSKAKEURI,         -- 会員マスタ.取扱商品・Ｓ職員掛売
QTA1_TRSCREVOLVING,       -- 会員マスタ.取扱商品・Ｃリボルビング
QTA1_TRSCYOKU1,           -- 会員マスタ.取扱商品・Ｃ翌一回払
QTA1_CARDLOANUSEKBN,      -- 会員マスタ.カードローン使用区分
QTA1_HENSAIHOUHOU,        -- 会員マスタ.返済方法
QTA1_SIHARAIYOTEIBI,      -- 会員マスタ.支払予定日
QTA1_REVSMAITSUKI,        -- 会員マスタ.リボルビング・Ｓ毎月分
QTA1_REVSBONUS,           -- 会員マスタ.リボルビング・Ｓボーナス分
QTA1_REVCMAITSUKI,        -- 会員マスタ.リボルビング・Ｃ毎月分
QTA1_REVCBONUS,           -- 会員マスタ.リボルビング・Ｃボーナス分
QTA1_BBKSHUBETSU,         -- 会員マスタ.歩引情報・種別
QTA1_BBKRITSU,            -- 会員マスタ.歩引情報・率
QTA1_ASNGEN,              -- 会員マスタ.暗証番号・現
QTA1_ANSKYUU,             -- 会員マスタ.暗証番号・旧
QTA1_ANSHENKOUYMD,        -- 会員マスタ.暗証番号・変更日
QTA1_NYKUKETSUKENO,       -- 会員マスタ.入会情報・受付番号
QTA1_NYKUKETSUKEYMD,      -- 会員マスタ.入会情報・受付日
QTA1_NYKKESSAIYMD,        -- 会員マスタ.入会情報・決裁日
QTA1_YUKOKIGEN,           -- 会員マスタ.有効期限
QTA1_KTKROUTE,            -- 会員マスタ.獲得情報・ルート
QTA1_KTKSHOUKAISHACD,     -- 会員マスタ.獲得情報・紹介者コード
QTA1_YSNRANK,             -- 会員マスタ.与信情報・与信ランク
QTA1_YSNSOUGENDO,         -- 会員マスタ.与信情報・総限度額
QTA1_YSNNOBEGENDO,        -- 会員マスタ.与信情報・延払限度額
QTA1_YSNKYUBONUSGENDO,    -- 会員マスタ.与信情報・旧ボーナス限度額
QTA1_YSNCASHGENDO,        -- 会員マスタ.与信情報・キャッシング限度額
QTA1_YSNIKKATSUGENDO,     -- 会員マスタ.与信情報・一時一括限度額
QTA1_YSNKAPPUGENDO,       -- 会員マスタ.与信情報・一時割賦限度額
QTA1_YSNBONUSGENDO,       -- 会員マスタ.与信情報・一時ボーナス限度額
QTA1_YSNYUKOKAISHI,       -- 会員マスタ.与信情報・一時限度額有効期限開始
QTA1_YSNYUKOOWARI,        -- 会員マスタ.与信情報・一時限度額有効期限終了
QTA1_CIFDOUITSUNINNO,     -- 会員マスタ.CIF情報・同一人番号
QTA1_CIFNO,               -- 会員マスタ.CIF情報・ＣＩＦ番号
QTA1_CIFSHOUKAINO,        -- 会員マスタ.CIF情報・ＣＩＣ照会番号
QTA1_HONSHIMEIKANA,       -- 会員マスタ.本人情報・氏名カナ
QTA1_HONSHIMEIROMA,       -- 会員マスタ.本人情報・氏名ローマ字
QTA1_HONSHIMEIKAN,        -- 会員マスタ.本人情報・氏名漢字
QTA1_HONSEINENGAPPI,      -- 会員マスタ.本人情報・生年月日
QTA1_HONSEX,              -- 会員マスタ.本人情報・性別
QTA1_JTKTELSHIGAI,        -- 会員マスタ.自宅情報・市外局番
QTA1_JTKTELKYOKU,         -- 会員マスタ.自宅情報・電話局番
QTA1_JTKTELNO,            -- 会員マスタ.自宅情報・電話番号
QTA1_JTKJUSHOCD,          -- 会員マスタ.自宅情報・住所コード
QTA1_JTKYUUBINNO,         -- 会員マスタ.自宅情報・郵便番号
QTA1_JTKKENKANA,          -- 会員マスタ.自宅情報・県名カナ
QTA1_JTKJUSHOKANA,        -- 会員マスタ.自宅情報・住所名カナ
QTA1_JTKBANCHIKANA,       -- 会員マスタ.自宅情報・番地カナ
QTA1_JTKKATAKANA,         -- 会員マスタ.自宅情報・方書カナ
QTA1_JTKJUSHOKAN,         -- 会員マスタ.自宅情報・住所名漢字
QTA1_JTKBANCHIKAN,        -- 会員マスタ.自宅情報・番地漢字
QTA1_JTKKATAKAN,          -- 会員マスタ.自宅情報・方書漢字
QTA1_KOZHENKOUYMD,        -- 会員マスタ.口座情報・登録変更日
QTA1_KOZGINKOUCD,         -- 会員マスタ.口座情報・銀行コード
QTA1_KOZGINKOUMEI,        -- 会員マスタ.口座情報・銀行名
QTA1_KOZSHITENCD,         -- 会員マスタ.口座情報・支店コード
QTA1_KOZSHITENMEI,        -- 会員マスタ.口座情報・支店名
QTA1_KOZSHUMOKU,          -- 会員マスタ.口座情報・預金種目
QTA1_KOZNO,               -- 会員マスタ.口座情報・口座番号
QTA1_KOZMEIGI,            -- 会員マスタ.口座情報・口座名義
QTA1_CLUBCD,              -- 会員マスタ.クラブコード
QTA1_STSKOZATOROKUYMD,    -- 会員マスタ.ステータス情報・口座ステータス登録日
QTA1_STSKOZA,             -- 会員マスタ.ステータス情報・口座ステータス
QTA1_STSCARDTOROKUYMD,    -- 会員マスタ.ステータス情報・カードステータス登録日
QTA1_STSCARD,             -- 会員マスタ.ステータス情報・カードステータス
QTA1_EDJRIYOUSHACD1,      -- 会員マスタ.枝番情報・利用者コード１
QTA1_EDJJIKOYMD1,         -- 会員マスタ.枝番情報・事故発生日１
QTA1_EDJCARDJYOKYO1,      -- 会員マスタ.枝番情報・カード状況１
QTA1_EDJRIYOUSHACD2,      -- 会員マスタ.枝番情報・利用者コード２
QTA1_EDJJIKOYMD2,         -- 会員マスタ.枝番情報・事故発生日２
QTA1_EDJCARDJYOKYO2,      -- 会員マスタ.枝番情報・カード状況２
QTA1_EDJRIYOUSHACD3,      -- 会員マスタ.枝番情報・利用者コード３
QTA1_EDJJIKOYMD3,         -- 会員マスタ.枝番情報・事故発生日３
QTA1_EDJCARDJYOKYO3,      -- 会員マスタ.枝番情報・カード状況３
QTA1_EDJRIYOUSHACD4,      -- 会員マスタ.枝番情報・利用者コード４
QTA1_EDJJIKOYMD4,         -- 会員マスタ.枝番情報・事故発生日４
QTA1_EDJCARDJYOKYO4,      -- 会員マスタ.枝番情報・カード状況４
QTA1_EDJRIYOUSHACD5,      -- 会員マスタ.枝番情報・利用者コード５
QTA1_EDJJIKOYMD5,         -- 会員マスタ.枝番情報・事故発生日５
QTA1_EDJCARDJYOKYO5,      -- 会員マスタ.枝番情報・カード状況５
QTA1_EDJRIYOUSHACD6,      -- 会員マスタ.枝番情報・利用者コード６
QTA1_EDJJIKOYMD6,         -- 会員マスタ.枝番情報・事故発生日６
QTA1_EDJCARDJYOKYO6,      -- 会員マスタ.枝番情報・カード状況６
QTA1_EDJRIYOUSHACD7,      -- 会員マスタ.枝番情報・利用者コード７
QTA1_EDJJIKOYMD7,         -- 会員マスタ.枝番情報・事故発生日７
QTA1_EDJCARDJYOKYO7,      -- 会員マスタ.枝番情報・カード状況７
QTA1_EDJRIYOUSHACD8,      -- 会員マスタ.枝番情報・利用者コード８
QTA1_EDJJIKOYMD8,         -- 会員マスタ.枝番情報・事故発生日８
QTA1_EDJCARDJYOKYO8,      -- 会員マスタ.枝番情報・カード状況８
QTA1_EDJRIYOUSHACD9,      -- 会員マスタ.枝番情報・利用者コード９
QTA1_EDJJIKOYMD9,         -- 会員マスタ.枝番情報・事故発生日９
QTA1_EDJCARDJYOKYO9,      -- 会員マスタ.枝番情報・カード状況９
QTA1_SOHCARD,             -- 会員マスタ.送付先情報・カード
QTA1_SOHSEIKYU,           -- 会員マスタ.送付先情報・請求書
QTA1_CDHHAKKOUKBN,        -- 会員マスタ.カード発券情報・発行区分
QTA1_CDHYUSOKBN,          -- 会員マスタ.カード発券情報・郵送区分
QTA1_CDHYMD,              -- 会員マスタ.カード発券情報・日
QTA1_CDHYUCHOSAIHATU,     -- 会員マスタ.カード発券情報・郵貯再発行回数
QTA1_KIKYMD,              -- 会員マスタ.口座移管情報・移管日
QTA1_KIKKYUUNO,           -- 会員マスタ.口座移管情報・旧会員番号
QTA1_KIK10KETANO,         -- 会員マスタ.口座移管情報・10桁会員番号
QTA1_TKSHENREIYMD,        -- 会員マスタ.提携先情報・返戻日
QTA1_TKSCARDNO,           -- 会員マスタ.提携先情報・カード番号
QTA1_TKSKEKKACD,          -- 会員マスタ.提携先情報・結果コード
QTA1_TKSRIYUCD,           -- 会員マスタ.提携先情報・理由コード
QTA1_EDBSAISHURIYOU,      -- 会員マスタ.枝番情報・最終利用者コード
QTA1_EDBYUKOMUKO1,        -- 会員マスタ.枝番情報・有効無効表示1
QTA1_EDBYUKOMUKO2,        -- 会員マスタ.枝番情報・有効無効表示2
QTA1_EDBYUKOMUKO3,        -- 会員マスタ.枝番情報・有効無効表示3
QTA1_EDBYUKOMUKO4,        -- 会員マスタ.枝番情報・有効無効表示4
QTA1_EDBYUKOMUKO5,        -- 会員マスタ.枝番情報・有効無効表示5
QTA1_EDBYUKOMUKO6,        -- 会員マスタ.枝番情報・有効無効表示6
QTA1_EDBYUKOMUKO7,        -- 会員マスタ.枝番情報・有効無効表示7
QTA1_EDBYUKOMUKO8,        -- 会員マスタ.枝番情報・有効無効表示8
QTA1_EDBYUKOMUKO9,        -- 会員マスタ.枝番情報・有効無効表示9
QTA1_ATUKAKARI,           -- 会員マスタ.扱部係情報・扱部課係
QTA1_ATUKOUSHINMAE,       -- 会員マスタ.扱部係情報・更新前扱部課係
QTA1_ATUHENKOUYMD,        -- 会員マスタ.扱部係情報・変更日
QTA1_PNTSHINNO,           -- 会員マスタ.交換番号情報・新交換番号
QTA1_PNTKYUUNO,           -- 会員マスタ.交換番号情報・旧交換番号
QTA1_PNTHENKOUYMD,        -- 会員マスタ.交換番号情報・交換番号変更日
QTA1_PNTKBN,              -- 会員マスタ.ポイント情報・区分
QTA1_PNTCARDFACE,         -- 会員マスタ.ポイント情報・カードフェース
QTA1_PNTTEIKEIKBN,        -- 会員マスタ.ポイント情報・提携区分
QTA1_IKANMAECARDKBN,      -- 会員マスタ.移管前カード区分
QTA1_KMSKBN,              -- 会員マスタ.勤務先情報・区分
QTA1_KMSMEIKANA,          -- 会員マスタ.勤務先情報・名称カナ
QTA1_KMSMEIKAN,           -- 会員マスタ.勤務先情報・名称漢字
QTA1_KMSBUKA,             -- 会員マスタ.勤務先情報・所属部課
QTA1_KMSTELSHIGAI,        -- 会員マスタ.勤務先情報・市外局番
QTA1_KMSTELKYOKU,         -- 会員マスタ.勤務先情報・電話局番
QTA1_KMSTELNO,            -- 会員マスタ.勤務先情報・電話番号
QTA1_KMSJUSHOCD,          -- 会員マスタ.勤務先情報・住所コード
QTA1_KMSYUUBINNO,         -- 会員マスタ.勤務先情報・郵便番号
QTA1_KMSKENKANA,          -- 会員マスタ.勤務先情報・県名カナ
QTA1_KMSJUSHOKANA,        -- 会員マスタ.勤務先情報・住所名カナ
QTA1_KMSBANCHIKANA,       -- 会員マスタ.勤務先情報・番地カナ
QTA1_KMSKATAKANA,         -- 会員マスタ.勤務先情報・方書カナ
QTA1_KMSJUSHOKAN,         -- 会員マスタ.勤務先情報・住所名漢字
QTA1_KMSBANCHIKAN,        -- 会員マスタ.勤務先情報・番地漢字
QTA1_KMSKATAKAN,          -- 会員マスタ.勤務先情報・方書漢字
QTA1_HOSTSHORIYMD,        -- 会員マスタ.ホスト処理日
QTA1_HOSTSHORITIME,       -- 会員マスタ.ホスト処理時刻
QTA1_SVRKOUSHINYMD,       -- 会員マスタ.サーバ更新日
QTAR_PRMKIGYOUCD,         -- Ｗｅｂ会員マスタ.主キー・企業コード
QTAR_PRMSUBRANGEKEY,      -- Ｗｅｂ会員マスタ.主キー・サブレンジキー
QTAR_PRMNAIBUKAIINNO,     -- Ｗｅｂ会員マスタ.主キー・内部会員番号
QTAR_PRMRIYOUSHACD,       -- Ｗｅｂ会員マスタ.主キー・利用者コード
QTAR_SEQNO,               -- Ｗｅｂ会員マスタ.ＳＥＱ
QTAR_WEBKAIINID,          -- Ｗｅｂ会員マスタ.Web会員ＩＤ
QTAR_GAIBUKAIINNO,        -- Ｗｅｂ会員マスタ.外部会員番号
QTAR_KAIINKEY,            -- Ｗｅｂ会員マスタ.ＴＣＣ会員マスタキー
QTAR_NMOSHIKOMIDATE,      -- Ｗｅｂ会員マスタ.申込登録日時
QTAR_SMOSHIKOMIDATE,      -- Ｗｅｂ会員マスタ.請求登録日時
QTAR_SMOSHIKOMIKAISU,     -- Ｗｅｂ会員マスタ.請求確認回数
QTAR_STRDATE,             -- Ｗｅｂ会員マスタ.作成日時
QTAR_UPDDATE,             -- Ｗｅｂ会員マスタ.更新日時
QTAR_DELDATE,             -- Ｗｅｂ会員マスタ.削除日時
QBE9_UKETSUKENO           -- 申込書テーブル.受付番号
From QTA1_KAIINM,QTAR_WEBSEIKYUKAIINM,QBE9_UKETSUKENOT
Where
QTA1_PRMKIGYOUCD         = QTAR_PRMKIGYOUCD(+)     AND
QTA1_PRMSUBRANGEKEY      = QTAR_PRMSUBRANGEKEY(+)  AND
QTA1_PRMNAIBUKAIINNO     = QTAR_PRMNAIBUKAIINNO(+) AND
QTAR_PRMRIYOUSHACD(+)    = '1'                     AND
QTA1_NYKUKETSUKENO       = QBE9_UKETSUKENO(+) ;
