
--DROP   VIEW QTBF_RIYOUDTLTV ;

CREATE VIEW QTBF_RIYOUDTLTV ( 
QTAF_PRMKIGYOUCD,         -- 利用明細テーブル.主キー・企業コード
QTAF_PRMSUBRANGEKEY,      -- 利用明細テーブル.主キー・サブレンジキー
QTAF_PRMNAIBUKAIINNO,     -- 利用明細テーブル.主キー・内部会員番号
QTAF_PRMTORIHIKINO,       -- 利用明細テーブル.主キー・取引通番
QTAF_DENPYOUNO,           -- 利用明細テーブル.伝票ＮＯ
QTAF_RECKBN,              -- 利用明細テーブル.レコード区分
QTAF_KAIJYOKBN,           -- 利用明細テーブル.解除区分
QTAF_AKAKUROKBN,          -- 利用明細テーブル.赤黒非表示区分
QTAF_SEIKYUHORYUKBN,      -- 利用明細テーブル.請求保留区分
QTAF_DENPYOUSHUBETSU,     -- 利用明細テーブル.伝票種別
QTAF_BATCHNO,             -- 利用明細テーブル.バッチＮＯ
QTAF_GNOBATCHNO,          -- 利用明細テーブル.Ｇ－ＮＯ・ＧバッチＮＯ
QTAF_GNOSEQUENCE,         -- 利用明細テーブル.Ｇ－ＮＯ・Ｇ伝票シーケンス
QTAF_CARDNO,              -- 利用明細テーブル.カード番号
QTAF_RIYOUBI,             -- 利用明細テーブル.利用日
QTAF_UKETSUKEBI,          -- 利用明細テーブル.受付日
QTAF_KEIJYOUBI,           -- 利用明細テーブル.計上日
QTAF_HASSEITEN,           -- 利用明細テーブル.発生店
QTAF_KAMEITENNO,          -- 利用明細テーブル.加盟店ＮＯ
QTAF_POSREGNO,            -- 利用明細テーブル.ＰＯＳ端末情報・ＰＯＳレジＮＯ
QTAF_POSTORIHIKINO,       -- 利用明細テーブル.ＰＯＳ端末情報・ＰＯＳ取引ＮＯ
QTAF_TANMATSU,            -- 利用明細テーブル.ＣＤ端末番号
QTAF_KAKAKAATSUKAI,       -- 利用明細テーブル.課係・Ａ課係扱課扱
QTAF_KAKAKAKA,            -- 利用明細テーブル.課係・Ａ課係扱課課
QTAF_KAKKKAKARIKAKARI,    -- 利用明細テーブル.課係・Ｋ課係係
QTAF_SAICD,               -- 利用明細テーブル.催コード
QTAF_TKURIAGETUUBAN,      -- 利用明細テーブル.提携売上通番
QTAF_GYOUSU,              -- 利用明細テーブル.行数
QTAF_GYOUNO,              -- 利用明細テーブル.行№
QTAF_GKGSHIHARAIHOHO,     -- 利用明細テーブル.合計行・支払方法
QTAF_GKGLOANSHUBETSU,     -- 利用明細テーブル.合計行・ローン種別
QTAF_GKGRIYOUKNG,         -- 利用明細テーブル.合計行・利用金額
QTAF_GKGSHOUHINDAIKIN,    -- 利用明細テーブル.合計行・商品代金
QTAF_GKGBUBIKIRITSU,      -- 利用明細テーブル.合計行・歩引率
QTAF_GKGBUBIKIGAKU,       -- 利用明細テーブル.合計行・歩引額
QTAF_GKGBUBIKITAISHOU,    -- 利用明細テーブル.合計行・歩引対象額合計
QTAF_GKGBUBIKIJYOGAI,     -- 利用明細テーブル.合計行・歩引除外
QTAF_GKGSHOUNINNO,        -- 利用明細テーブル.合計行・承認番号
QTAF_GKGBUNKATSUKAISU,    -- 利用明細テーブル.合計行・分割回数
QTAF_GKGBONUSKAISU,       -- 利用明細テーブル.合計行・ボーナス回数
QTAF_GKGBONUSKASAN,       -- 利用明細テーブル.合計行・ボーナス加算額
QTAF_GKGMAESHOUHIZEI,     -- 利用明細テーブル.合計行・歩引前消費税
QTAF_GKGATOSHOUHIZEI,     -- 利用明細テーブル.合計行・歩引後消費税
QTAF_GKGATAMAKIN,         -- 利用明細テーブル.合計行・頭金
QTAF_GKGTESURYOURITSU,    -- 利用明細テーブル.合計行・手数料率
QTAF_GKGTESURYOUGAKU,     -- 利用明細テーブル.合計行・手数料額
QTAF_GKGCHUSYUTSUSUMI,    -- 利用明細テーブル.合計行・請求抽出済サイン
QTAF_GKGPO1KEIJYOUKBN,    -- 利用明細テーブル.合計行・ポ1計上区分
QTAF_GKGRIYOUSHACD,       -- 利用明細テーブル.合計行・利用者コード
QTAF_GKGGENTIKAKAKU,      -- 利用明細テーブル.合計行・現地価格
QTAF_GKGKANSANRATE,       -- 利用明細テーブル.合計行・換算レート
QTAF_GKGKANSANBI,         -- 利用明細テーブル.合計行・換算日
QTAF_GKGKOKUNAIKAIGAI,    -- 利用明細テーブル.合計行・国内海外識別
QTAF_GKGKEISANSUMISIGN,   -- 利用明細テーブル.合計行・入金手数料計算済サイン
QTAF_GKGHURIKAEKAIINNO,   -- 利用明細テーブル.合計行・振替会員番号
QTAF_GKGHASSEIROUTO,      -- 利用明細テーブル.合計行・発生ルート
QTAF_KAMEITENTESURYO,     -- 利用明細テーブル.加盟店手数料
QTAF_DANKEITESURYOU,      -- 利用明細テーブル.団契手数料
QTAF_DENPYOUUMUFLG,       -- 利用明細テーブル.伝票無フラグ
QTAF_IDOKEIJYOUKBN,       -- 利用明細テーブル.移動計上区分
QTAF_CASHINGBUNKAI,       -- 利用明細テーブル.ｷｬｯｼﾝｸﾞ分解処理通番
QTAF_HURIKAEKBN,          -- 利用明細テーブル.振替区分
QTAF_SHAINNOUMUKBN,       -- 利用明細テーブル.社員ＮＯ有無区分
QTAF_DENNYURYOKUTEN,      -- 利用明細テーブル.伝票入力店
QTAF_DAIHIKIDENPYOKBN,    -- 利用明細テーブル.代引伝票区分
QTAF_POINTSHIKIBETSU,     -- 利用明細テーブル.歩引ポイント識別区分
QTAF_GKPTSUJYOUGOUKEI,    -- 利用明細テーブル.合計ポイント・通常合計ポイント
QTAF_GKPBONUSGOUKEI,      -- 利用明細テーブル.合計ポイント・ボーナス合計ポイント
QTAF_YOUTAICD,            -- 利用明細テーブル.様態コード
QTAF_KEIJYOUURICHOUKBN,   -- 利用明細テーブル.係計上売帳区分
QTAF_ZEIRITUKBN,          -- 利用明細テーブル.税率区分
QTAF_HOSTSHORIYMD,        -- 利用明細テーブル.ホスト処理日
QTAF_HOSTSHORITIME,       -- 利用明細テーブル.ホスト処理時刻
QTAF_SVRKOUSHINYMD,       -- 利用明細テーブル.サーバ更新日
QTAF_ISOTUUKA,            -- 利用明細テーブル.ＩＳＯ通貨単位
QTAF_ITIBUHENPINKBN,      -- 利用明細テーブル.一部返品区分
QTAF_JIDOFURIKAE,         -- 利用明細テーブル.自動振替種別
QTAK_PRMURITUUBAN,        -- 加盟店原伝テーブル.主キー・売上通番
QTAK_URITORIHIKIA,        -- 加盟店原伝テーブル.売上情報・取引Ａ
QTAK_URITORIHIKIB,        -- 加盟店原伝テーブル.売上情報・取引Ｂ
QTAK_URITORIHIKIC,        -- 加盟店原伝テーブル.売上情報・取引Ｃ
QTAK_URICARDNO,           -- 加盟店原伝テーブル.売上情報・カード番号
QTAK_URIRIYOUBI,          -- 加盟店原伝テーブル.売上情報・利用日
QTAK_URIUKETSUKEBI,       -- 加盟店原伝テーブル.売上情報・受付日
QTAK_URIKEIJYOUBI,        -- 加盟店原伝テーブル.売上情報・計上日
QTAK_URISHIHARAIHOHO,     -- 加盟店原伝テーブル.売上情報・支払方法
QTAK_URIBUNKATSUKAISU,    -- 加盟店原伝テーブル.売上情報・分割回数
QTAK_URIRIYOUKNG,         -- 加盟店原伝テーブル.売上情報・利用金額
QTAK_URIURIAGEKNG,        -- 加盟店原伝テーブル.売上情報・売上金額
QTAK_URIZEISOURYOU,       -- 加盟店原伝テーブル.売上情報・税送料
QTAK_URIURIAGEGOUKEI,     -- 加盟店原伝テーブル.売上情報・売上合計
QTAK_URIWARIBIKIGAKU,     -- 加盟店原伝テーブル.売上情報・割引額
QTAK_URIGAITESURYOU,      -- 加盟店原伝テーブル.売上情報・時間外手数料
QTAK_URISHOUNINNO,        -- 加盟店原伝テーブル.売上情報・承認番号
QTAK_URIKOKUNAIKAIGAI,    -- 加盟店原伝テーブル.売上情報・国内海外識別区分
QTAK_KAITUUKAGAKU,        -- 加盟店原伝テーブル.海外利用情報・現地通貨額
QTAK_KAIKANSANRATE,       -- 加盟店原伝テーブル.海外利用情報・換算レート
QTAK_KAIKANSANBI,         -- 加盟店原伝テーブル.海外利用情報・換算日
QTAK_KAITOSHIMEI,         -- 加盟店原伝テーブル.海外利用情報・加盟店都市名
QTAK_KAITUUKAKOSHOU,      -- 加盟店原伝テーブル.海外利用情報・通貨呼称
QTAK_KAITUUKACD,          -- 加盟店原伝テーブル.海外利用情報・通貨コード
QTAK_KAISHUUCD,           -- 加盟店原伝テーブル.海外利用情報・州コード
QTAK_KAIKUNICD,           -- 加盟店原伝テーブル.海外利用情報・国コード
QTAK_TKSSHOUKAINO1,       -- 加盟店原伝テーブル.提携先情報・提携先照会番号１
QTAK_TKSSHOUKAINO2,       -- 加盟店原伝テーブル.提携先情報・提携先照会番号２
QTAK_TKSKAMEITENNO,       -- 加盟店原伝テーブル.提携先情報・加盟店番号
QTAK_TKSKAMEITENMEI1,     -- 加盟店原伝テーブル.提携先情報・加盟店名称１
QTAK_TKSKAMEITENMEI2,     -- 加盟店原伝テーブル.提携先情報・加盟店名称２
QTAK_TKSGYOUSHUCD,        -- 加盟店原伝テーブル.提携先情報・業種コード
QTAK_TKSPOSENTRYCD,       -- 加盟店原伝テーブル.提携先情報・ＰＯＳエントリーコード
QTAK_TKSBONUSHYOUJI,      -- 加盟店原伝テーブル.提携先情報・ボーナス表示
QTAK_KJKKIGYOUCD,         -- 加盟店原伝テーブル.計上時会員情報・企業コード
QTAK_KJKSUBRANGEKEY,      -- 加盟店原伝テーブル.計上時会員情報・サブレンジキー
QTAK_KJKNAIBUKAIINNO,     -- 加盟店原伝テーブル.計上時会員情報・内部会員番号
QTAK_KJKKANRITEN,         -- 加盟店原伝テーブル.計上時会員情報・債権管理店
QTAK_KJKCARDKBN,          -- 加盟店原伝テーブル.計上時会員情報・カード区分
QTAK_KJKCARDKAIINMEI,     -- 加盟店原伝テーブル.計上時会員情報・カード会員氏名
QTAK_HOSTSHORIYMD,        -- 加盟店原伝テーブル.ホスト処理日
QTAK_HOSTSHORITIME,       -- 加盟店原伝テーブル.ホスト処理時刻
QTAK_SVRKOUSHINYMD,       -- 加盟店原伝テーブル.サーバ更新日
QTAK_KMTCHARGEBACK,       -- 加盟店原伝テーブル.加盟店情報・チャージバック区分
QTAK_KMTKJYAGOU,          -- 加盟店原伝テーブル.加盟店情報・加盟店漢字屋号
QTAK_KMTDENPYOUKI,        -- 加盟店原伝テーブル.加盟店情報・伝票検索キー
QTAK_KMTSEISANKBN,        -- 加盟店原伝テーブル.加盟店情報・精算区分
QTAK_MOTOECINDICATOR,     -- 加盟店原伝テーブル.サーバ更新日
QTAK_CHACTTERMINDICATOR,  -- 加盟店原伝テーブル.
QTAK_AUTHSOURCECODE,      -- 加盟店原伝テーブル.
QTAK_TCQ                  -- 加盟店原伝テーブル.
 ) AS 
Select
QTAF_PRMKIGYOUCD,         -- 利用明細テーブル.主キー・企業コード
QTAF_PRMSUBRANGEKEY,      -- 利用明細テーブル.主キー・サブレンジキー
QTAF_PRMNAIBUKAIINNO,     -- 利用明細テーブル.主キー・内部会員番号
QTAF_PRMTORIHIKINO,       -- 利用明細テーブル.主キー・取引通番
QTAF_DENPYOUNO,           -- 利用明細テーブル.伝票ＮＯ
QTAF_RECKBN,              -- 利用明細テーブル.レコード区分
QTAF_KAIJYOKBN,           -- 利用明細テーブル.解除区分
QTAF_AKAKUROKBN,          -- 利用明細テーブル.赤黒非表示区分
QTAF_SEIKYUHORYUKBN,      -- 利用明細テーブル.請求保留区分
QTAF_DENPYOUSHUBETSU,     -- 利用明細テーブル.伝票種別
QTAF_BATCHNO,             -- 利用明細テーブル.バッチＮＯ
QTAF_GNOBATCHNO,          -- 利用明細テーブル.Ｇ－ＮＯ・ＧバッチＮＯ
QTAF_GNOSEQUENCE,         -- 利用明細テーブル.Ｇ－ＮＯ・Ｇ伝票シーケンス
QTAF_CARDNO,              -- 利用明細テーブル.カード番号
QTAF_RIYOUBI,             -- 利用明細テーブル.利用日
QTAF_UKETSUKEBI,          -- 利用明細テーブル.受付日
QTAF_KEIJYOUBI,           -- 利用明細テーブル.計上日
QTAF_HASSEITEN,           -- 利用明細テーブル.発生店
QTAF_KAMEITENNO,          -- 利用明細テーブル.加盟店ＮＯ
QTAF_POSREGNO,            -- 利用明細テーブル.ＰＯＳ端末情報・ＰＯＳレジＮＯ
QTAF_POSTORIHIKINO,       -- 利用明細テーブル.ＰＯＳ端末情報・ＰＯＳ取引ＮＯ
QTAF_TANMATSU,            -- 利用明細テーブル.ＣＤ端末番号
QTAF_KAKAKAATSUKAI,       -- 利用明細テーブル.課係・Ａ課係扱課扱
QTAF_KAKAKAKA,            -- 利用明細テーブル.課係・Ａ課係扱課課
QTAF_KAKKKAKARIKAKARI,    -- 利用明細テーブル.課係・Ｋ課係係
QTAF_SAICD,               -- 利用明細テーブル.催コード
QTAF_TKURIAGETUUBAN,      -- 利用明細テーブル.提携売上通番
QTAF_GYOUSU,              -- 利用明細テーブル.行数
QTAF_GYOUNO,              -- 利用明細テーブル.行№
QTAF_GKGSHIHARAIHOHO,     -- 利用明細テーブル.合計行・支払方法
QTAF_GKGLOANSHUBETSU,     -- 利用明細テーブル.合計行・ローン種別
QTAF_GKGRIYOUKNG,         -- 利用明細テーブル.合計行・利用金額
QTAF_GKGSHOUHINDAIKIN,    -- 利用明細テーブル.合計行・商品代金
QTAF_GKGBUBIKIRITSU,      -- 利用明細テーブル.合計行・歩引率
QTAF_GKGBUBIKIGAKU,       -- 利用明細テーブル.合計行・歩引額
QTAF_GKGBUBIKITAISHOU,    -- 利用明細テーブル.合計行・歩引対象額合計
QTAF_GKGBUBIKIJYOGAI,     -- 利用明細テーブル.合計行・歩引除外
QTAF_GKGSHOUNINNO,        -- 利用明細テーブル.合計行・承認番号
QTAF_GKGBUNKATSUKAISU,    -- 利用明細テーブル.合計行・分割回数
QTAF_GKGBONUSKAISU,       -- 利用明細テーブル.合計行・ボーナス回数
QTAF_GKGBONUSKASAN,       -- 利用明細テーブル.合計行・ボーナス加算額
QTAF_GKGMAESHOUHIZEI,     -- 利用明細テーブル.合計行・歩引前消費税
QTAF_GKGATOSHOUHIZEI,     -- 利用明細テーブル.合計行・歩引後消費税
QTAF_GKGATAMAKIN,         -- 利用明細テーブル.合計行・頭金
QTAF_GKGTESURYOURITSU,    -- 利用明細テーブル.合計行・手数料率
QTAF_GKGTESURYOUGAKU,     -- 利用明細テーブル.合計行・手数料額
QTAF_GKGCHUSYUTSUSUMI,    -- 利用明細テーブル.合計行・請求抽出済サイン
QTAF_GKGPO1KEIJYOUKBN,    -- 利用明細テーブル.合計行・ポ1計上区分
QTAF_GKGRIYOUSHACD,       -- 利用明細テーブル.合計行・利用者コード
QTAF_GKGGENTIKAKAKU,      -- 利用明細テーブル.合計行・現地価格
QTAF_GKGKANSANRATE,       -- 利用明細テーブル.合計行・換算レート
QTAF_GKGKANSANBI,         -- 利用明細テーブル.合計行・換算日
QTAF_GKGKOKUNAIKAIGAI,    -- 利用明細テーブル.合計行・国内海外識別
QTAF_GKGKEISANSUMISIGN,   -- 利用明細テーブル.合計行・入金手数料計算済サイン
QTAF_GKGHURIKAEKAIINNO,   -- 利用明細テーブル.合計行・振替会員番号
QTAF_GKGHASSEIROUTO,      -- 利用明細テーブル.合計行・発生ルート
QTAF_KAMEITENTESURYO,     -- 利用明細テーブル.加盟店手数料
QTAF_DANKEITESURYOU,      -- 利用明細テーブル.団契手数料
QTAF_DENPYOUUMUFLG,       -- 利用明細テーブル.伝票無フラグ
QTAF_IDOKEIJYOUKBN,       -- 利用明細テーブル.移動計上区分
QTAF_CASHINGBUNKAI,       -- 利用明細テーブル.ｷｬｯｼﾝｸﾞ分解処理通番
QTAF_HURIKAEKBN,          -- 利用明細テーブル.振替区分
QTAF_SHAINNOUMUKBN,       -- 利用明細テーブル.社員ＮＯ有無区分
QTAF_DENNYURYOKUTEN,      -- 利用明細テーブル.伝票入力店
QTAF_DAIHIKIDENPYOKBN,    -- 利用明細テーブル.代引伝票区分
QTAF_POINTSHIKIBETSU,     -- 利用明細テーブル.歩引ポイント識別区分
QTAF_GKPTSUJYOUGOUKEI,    -- 利用明細テーブル.合計ポイント・通常合計ポイント
QTAF_GKPBONUSGOUKEI,      -- 利用明細テーブル.合計ポイント・ボーナス合計ポイント
QTAF_YOUTAICD,            -- 利用明細テーブル.様態コード
QTAF_KEIJYOUURICHOUKBN,   -- 利用明細テーブル.係計上売帳区分
QTAF_ZEIRITUKBN,          -- 利用明細テーブル.税率区分
QTAF_HOSTSHORIYMD,        -- 利用明細テーブル.ホスト処理日
QTAF_HOSTSHORITIME,       -- 利用明細テーブル.ホスト処理時刻
QTAF_SVRKOUSHINYMD,       -- 利用明細テーブル.サーバ更新日
QTAF_ISOTUUKA,            -- 利用明細テーブル.ＩＳＯ通貨単位
QTAF_ITIBUHENPINKBN,      -- 利用明細テーブル.一部返品区分
--QTAF_JIDOFURIKAE,         -- 利用明細テーブル.自動振替種別
QTAF_JIDOUFURIKAEKBN,       -- 利用明細テーブル.自動振替種別 2003/03/19 項目の変更
QTAK_PRMURITUUBAN,        -- 加盟店原伝テーブル.主キー・売上通番
QTAK_URITORIHIKIA,        -- 加盟店原伝テーブル.売上情報・取引Ａ
QTAK_URITORIHIKIB,        -- 加盟店原伝テーブル.売上情報・取引Ｂ
QTAK_URITORIHIKIC,        -- 加盟店原伝テーブル.売上情報・取引Ｃ
QTAK_URICARDNO,           -- 加盟店原伝テーブル.売上情報・カード番号
QTAK_URIRIYOUBI,          -- 加盟店原伝テーブル.売上情報・利用日
QTAK_URIUKETSUKEBI,       -- 加盟店原伝テーブル.売上情報・受付日
QTAK_URIKEIJYOUBI,        -- 加盟店原伝テーブル.売上情報・計上日
QTAK_URISHIHARAIHOHO,     -- 加盟店原伝テーブル.売上情報・支払方法
QTAK_URIBUNKATSUKAISU,    -- 加盟店原伝テーブル.売上情報・分割回数
QTAK_URIRIYOUKNG,         -- 加盟店原伝テーブル.売上情報・利用金額
QTAK_URIURIAGEKNG,        -- 加盟店原伝テーブル.売上情報・売上金額
QTAK_URIZEISOURYOU,       -- 加盟店原伝テーブル.売上情報・税送料
QTAK_URIURIAGEGOUKEI,     -- 加盟店原伝テーブル.売上情報・売上合計
QTAK_URIWARIBIKIGAKU,     -- 加盟店原伝テーブル.売上情報・割引額
QTAK_URIGAITESURYOU,      -- 加盟店原伝テーブル.売上情報・時間外手数料
QTAK_URISHOUNINNO,        -- 加盟店原伝テーブル.売上情報・承認番号
QTAK_URIKOKUNAIKAIGAI,    -- 加盟店原伝テーブル.売上情報・国内海外識別区分
QTAK_KAITUUKAGAKU,        -- 加盟店原伝テーブル.海外利用情報・現地通貨額
QTAK_KAIKANSANRATE,       -- 加盟店原伝テーブル.海外利用情報・換算レート
QTAK_KAIKANSANBI,         -- 加盟店原伝テーブル.海外利用情報・換算日
QTAK_KAITOSHIMEI,         -- 加盟店原伝テーブル.海外利用情報・加盟店都市名
QTAK_KAITUUKAKOSHOU,      -- 加盟店原伝テーブル.海外利用情報・通貨呼称
QTAK_KAITUUKACD,          -- 加盟店原伝テーブル.海外利用情報・通貨コード
QTAK_KAISHUUCD,           -- 加盟店原伝テーブル.海外利用情報・州コード
QTAK_KAIKUNICD,           -- 加盟店原伝テーブル.海外利用情報・国コード
QTAK_TKSSHOUKAINO1,       -- 加盟店原伝テーブル.提携先情報・提携先照会番号１
QTAK_TKSSHOUKAINO2,       -- 加盟店原伝テーブル.提携先情報・提携先照会番号２
QTAK_TKSKAMEITENNO,       -- 加盟店原伝テーブル.提携先情報・加盟店番号
QTAK_TKSKAMEITENMEI1,     -- 加盟店原伝テーブル.提携先情報・加盟店名称１
QTAK_TKSKAMEITENMEI2,     -- 加盟店原伝テーブル.提携先情報・加盟店名称２
QTAK_TKSGYOUSHUCD,        -- 加盟店原伝テーブル.提携先情報・業種コード
QTAK_TKSPOSENTRYCD,       -- 加盟店原伝テーブル.提携先情報・ＰＯＳエントリーコード
QTAK_TKSBONUSHYOUJI,      -- 加盟店原伝テーブル.提携先情報・ボーナス表示
QTAK_KJKKIGYOUCD,         -- 加盟店原伝テーブル.計上時会員情報・企業コード
QTAK_KJKSUBRANGEKEY,      -- 加盟店原伝テーブル.計上時会員情報・サブレンジキー
QTAK_KJKNAIBUKAIINNO,     -- 加盟店原伝テーブル.計上時会員情報・内部会員番号
QTAK_KJKKANRITEN,         -- 加盟店原伝テーブル.計上時会員情報・債権管理店
QTAK_KJKCARDKBN,          -- 加盟店原伝テーブル.計上時会員情報・カード区分
QTAK_KJKCARDKAIINMEI,     -- 加盟店原伝テーブル.計上時会員情報・カード会員氏名
QTAK_HOSTSHORIYMD,        -- 加盟店原伝テーブル.ホスト処理日
QTAK_HOSTSHORITIME,       -- 加盟店原伝テーブル.ホスト処理時刻
QTAK_SVRKOUSHINYMD,       -- 加盟店原伝テーブル.サーバ更新日
QTAK_KMTCHARGEBACK,       -- 加盟店原伝テーブル.加盟店情報・チャージバック区分
QTAK_KMTKJYAGOU,          -- 加盟店原伝テーブル.加盟店情報・加盟店漢字屋号
QTAK_KMTDENPYOUKI,        -- 加盟店原伝テーブル.加盟店情報・伝票検索キー
QTAK_KMTSEISANKBN,        -- 加盟店原伝テーブル.加盟店情報・精算区分
QTAK_MOTOECINDICATOR,     -- 加盟店原伝テーブル.サーバ更新日
QTAK_CHACTTERMINDICATOR,  -- 加盟店原伝テーブル.
QTAK_AUTHSOURCECODE,      -- 加盟店原伝テーブル.
QTAK_TCQ                  -- 加盟店原伝テーブル.
From QTAF_RIYOUDTLT,QTAK_KAMEITENT
Where
QTAF_TKURIAGETUUBAN       = QTAK_PRMURITUUBAN(+) ;
