CREATE OR REPLACE VIEW QXA3_Monitoring1V AS 
SELECT TO_CHAR(QXA3_SHORIDATE,'yyyy') || 'îN ' ||
	TO_CHAR(QXA3_SHORIDATE,'mm') || 'åé ' ||
	TO_CHAR(QXA3_SHORIDATE,'dd') || 'ì˙' 			AS SHORIDATE,
	QXA3_SHORITANTO									AS SHORITANTO,
	QXA3_SHORITANTOMEI 								AS SHORITANTOMEI,
	NVL(QXA3_ERRCODE, QXA3_FDSSCORE)				AS ERRCODE,
	QXA3_DATAREGDATE								AS DATAREGDATE,
	TO_CHAR(QXA3_SHORIDATE,'hh24:mi:ss') 			AS JYUSHINTIME,
	SUBSTR(QXA3_GAIBUKAIINNO, 1, 4) || '-' ||
	SUBSTR(QXA3_GAIBUKAIINNO, 5, 4) || '-' ||
	SUBSTR(QXA3_GAIBUKAIINNO, 9, 4) || '-' ||
	SUBSTR(QXA3_GAIBUKAIINNO, 13, 4)				AS GAIBUKAIINNO,
	QTA1_HONSHIMEIKAN								AS HONSHIMEIKAN,
	DECODE(LENGTH(QXA3_KAMEITENNO), 
		13, 
		SUBSTR(QXA3_KAMEITENNO, 1, 5) || '-'
		|| SUBSTR(QXA3_KAMEITENNO, 6, 2) || '-'
		|| SUBSTR(QXA3_KAMEITENNO, 8, 1) || '-'
		|| SUBSTR(QXA3_KAMEITENNO, 9, 5), 
		QXA3_KAMEITENNO) 							AS KAMEITEN_BANGO, -- ÇPÇRåÖà»è„ÇÃÇ∆Ç´xxxxx-xx-x-xxxxxå`éÆ
	QXA8_KAMEITENMEIKANJI							AS KAMEITENMEIKANJI,
	QXA3_SHORIDATE,
        a.QSA2_MEI AS TAISHO
FROM 	QXA3_MonitoringT, 
	QTA1_KAIINM, 
	QXA8_KameitenInfM,
        (SELECT  QSA2_PRMCODENO,QSA2_MEI FROM QSA2_SCODET WHERE QSA2_PRMCODEKBN='DX2') a
WHERE QXA3_KIGYOUCD		=	QTA1_PRMKIGYOUCD(+)
AND	QXA3_SUBRANGEKEY	=	QTA1_PRMSUBRANGEKEY(+)
AND	QXA3_NAIBUKAIINNO	=	QTA1_PRMNAIBUKAIINNO(+)
AND	QXA3_KAMEITENNO		=	QXA8_KAMEITENNO(+)
AND     QXA3_TAISHO             =       a.QSA2_PRMCODENO(+)
;
