CREATE OR REPLACE VIEW QXA3_MonitoringV AS SELECT 
	QXA3_TAISHO,
	QXA3_GAIBUKAIINNO,
	QXA3_DATAREGDATE,
	QXA3_KAMEITENNO,
	QXA3_SHORIDATE,

	QXA3_SHORIYMD,
	QXA3_JYUSHINTIME,
	SUBSTR(QXA3_GAIBUKAIINNO, 1, 4) || '-' ||
	SUBSTR(QXA3_GAIBUKAIINNO, 5, 4) || '-' ||
	SUBSTR(QXA3_GAIBUKAIINNO, 9, 4) || '-' ||
	SUBSTR(QXA3_GAIBUKAIINNO, 13, 4) AS GAIBUKAIINNO,
	DECODE(LENGTH(QXA3_KAMEITENNO), 
		13, 
		SUBSTR(QXA3_KAMEITENNO, 1, 5) || '-'
		|| SUBSTR(QXA3_KAMEITENNO, 6, 2) || '-'
		|| SUBSTR(QXA3_KAMEITENNO, 8, 1) || '-'
		|| SUBSTR(QXA3_KAMEITENNO, 9, 5), 
		QXA3_KAMEITENNO) AS KAMEITEN_BANGO,		-- ÇPÇRåÖà»è„ÇÃÇ∆Ç´xxxxx-xx-x-xxxxxå`éÆ
	SCODE1.QSA2_MEI AS TORIHIKI,
	QXA3_ERRCODE,
	QXA3_FDSSCORE,
	SCODE2.QSA2_MEI AS TAISHO,
	QXA3_SHORITANTO,
	TO_CHAR(QXA3_SHORIDATE, 'yyyy/mm/dd') AS SYORIBI,
	QXA3_SHORITANTOMEI
FROM QXA3_MONITORINGT, 
(SELECT QSA2_PRMCODENO, QSA2_MEI FROM QSA2_SCODET WHERE QSA2_PRMCODEKBN = 'DS9') SCODE1,
(SELECT QSA2_PRMCODENO, QSA2_MEI FROM QSA2_SCODET WHERE QSA2_PRMCODEKBN = 'DX2') SCODE2
WHERE SCODE1.QSA2_PRMCODENO(+) = QXA3_TORIHIKIKBN
AND	SCODE2.QSA2_PRMCODENO(+) = QXA3_TAISHO
;