CREATE OR REPLACE VIEW QXAX_ERRCODEV AS
Select QTA8_PRMCODEKBN As KBN,QTA8_PRMCODENO As NO,QTA8_MEI As MEI,'P' As STS
From QTA8_CODET
Where QTA8_PRMCODEKBN='C92' And QTA8_PRMCODENO<>'    '
Union All
Select QSA2_PRMCODEKBN As KBN,QSA2_PRMCODENO As NO,QSA2_MEI As MEI,'C' As STS
From QSA2_SCODET
Where QSA2_PRMCODEKBN='DSD' And QSA2_PRMCODENO<>'    '
;
