CREATE OR REPLACE VIEW QMBV_OUTPUTDATAV
/*
******************************************************************************************
システム名		：TCC支援システム
サブシステム名	：臨時カードポイント還元
ビュー名		：QMB1_OUTPUTDATAV
作成日			：2012/08/03
作成者			：IMZ.Shibutani
------------------------------------------------------------------------------------------
更新日付	案件/障害番号	氏名				理由
YYYYMMDD	XXXXXXXXXX		XXX.NNNNNNNNNN		XXXXXXXXXX
******************************************************************************************
*/
	( 
	--	キー情報
	 KEY_KOKAN
	,KEY_CARD
	,KEY_DAY
	--	データ部
	,RINJICARDNO
	,JUSHOFUBIFLG
	,KARISTRDATE
	,KYAKADATE
	,RINJICARDTEISHIDATE
	,KAKUTEIPOINT
	,MIKAKUTEIPOINT
	,KOUKANKANOU
	,TEGAMIFLG
	,TEGAMISAKUSEIDATE
	,KNNAME
	,BIRTHDAY
	,JITAKUTEL
	,HONKJNAME
	,QSA2_MEI
	)
AS
	SELECT
		 Q_MAIN.KEY_KOKAN
		,Q_MAIN.KEY_CARD
		,Q_MAIN.BASE_DAY
		,QMB1.QMB1_RINJICARDNO
		,QMB1.QMB1_JUSHOFUBIFLG
		,QMB1.QMB1_KARISTRDATE
		,QMB1.QMB1_KYAKADATE
		,QMB1.QMB1_RINJICARDTEISHIDATE
		,QMB1.QMB1_KAKUTEIPOINT
		,QMB1.QMB1_MIKAKUTEIPOINT
		,QMB1.QMB1_KOUKANKANOU
		,QMB1.QMB1_TEGAMIFLG
		,QMB1.QMB1_TEGAMISAKUSEIDATE
		,RTRIM(QMB1.QMB1_KNNAME, ' ' || TO_MULTI_BYTE(' '))		AS QMB1_KNNAME
		,QMB1.QMB1_BIRTHDAY
		,QMB1.QMB1_JITAKUTEL
		,RTRIM(QBA1.QBA1_HONKJNAME, ' ' || TO_MULTI_BYTE(' '))	AS QBA1_HONKJNAME
		,QSA2.QSA2_MEI
	FROM
		--	メイン（キー情報の組み合わせ）
		(
		SELECT
			 Q_KOKAN.KEY_KOKAN
			,Q_CARD.KEY_CARD
			,Q_DAYS.BASE_DAY
		FROM
			(
			--	交換有無のキー情報（"1"：あり、"2"：なし）
			SELECT
				TO_CHAR(TO_NUMBER(SUBSTR(QSA2_PRMCODENO, 3, 2)))	AS KEY_KOKAN
			FROM
				QSA2_SCODET
			WHERE
				QSA2_PRMCODEKBN	= 'QMB'
			AND	QSA2_PRMCODENO	LIKE '03%'
			)	Q_KOKAN
			,(
			--	カード区分のキー情報
			SELECT
				QSA2_PRMCODENO	AS KEY_CARD
			FROM
				QSA2_SCODET
			WHERE
				QSA2_PRMCODEKBN	= 'QMB'
			AND	QSA2_PRMCODENO	LIKE '01%'
			)	Q_CARD
			,(
			--	日付情報（2012/01/01からシステム日付 - 1まで）
			SELECT
				TO_CHAR(TO_DATE('20120101','YYYYMMDD') + LEVEL-1,'YYYYMMDD') AS BASE_DAY
			FROM
				DUAL
			CONNECT BY
				TO_DATE('20120101','YYYYMMDD') + LEVEL-1 <= SYSDATE - 1
			)	Q_DAYS
		)	Q_MAIN
		LEFT OUTER JOIN
			(
			SELECT
				 QMB1_RINJICARDNO
				,QMB1_JUSHOFUBIFLG
				,QMB1_KARISTRDATE
				,QMB1_KYAKADATE
				,QMB1_RINJICARDTEISHIDATE
				,QMB1_KAKUTEIPOINT
				,QMB1_KOUKANKANOU
				,QMB1_MIKAKUTEIPOINT
				,QMB1_TEGAMIFLG
				,QMB1_TEGAMISAKUSEIDATE
				,QMB1_KNNAME
				,QMB1_BIRTHDAY
				,QMB1_JITAKUTEL
				,(
				CASE QMB1_KOUKANKANOU
					WHEN 0 THEN	'2'
					ELSE		'1'
				END
				)	AS KEY_KOKAN
				,QMB1_DATASAKUSEIDATE
				,QMB1_BUNSHOSHUBETSU
				,QMB1_UKETSUKENO
			FROM
				QMB1_POINTKANGENT
			)	QMB1 ON
			Q_MAIN.KEY_KOKAN			= QMB1.KEY_KOKAN
		AND	Q_MAIN.KEY_CARD				= QMB1.QMB1_BUNSHOSHUBETSU
		AND	Q_MAIN.BASE_DAY				= QMB1.QMB1_DATASAKUSEIDATE
		LEFT OUTER JOIN QBA1_MOSHIKOMIT QBA1 ON
			QMB1.QMB1_UKETSUKENO		= QBA1.QBA1_UKETSUKENO
		LEFT OUTER JOIN QSA2_SCODET QSA2 ON
			Q_MAIN.KEY_CARD				= QSA2.QSA2_PRMCODENO
		AND	QSA2.QSA2_PRMCODEKBN		= 'QMB'
;
