CREATE VIEW QXNF_HONAKULISTV ( 
QXNF_TOUZAIKBN
,QXNF_SAKUSEIBI
,QXNF_KAIINNO
,QXNF_KAIINNAME
,QXNF_DENPYOSYUBETU
,QXNF_RIYOUSHA
,QXNF_MISE
,QXNF_DENPYONO
,QXNF_TORIHIKITUUBAN
,QXNF_SIHARAIHOHO
,QXNF_KEIJYOBI
,QXNF_RIYOUBI
,QXNF_SHOUHINMEI
,QXNF_KINGAKU
,QXNF_KOZASTATUS
 ) AS 
SELECT
        QXN6_TouzaiKbn,
        DECODE(QXN6_BATSyoriBi,NULL,' ',TO_CHAR(QXN6_BATSyoriBi,'YYYYMMDD')),
        QXN6_RYMCardNo,
        NVL(QXN6_Meigi,' '),
        QXN6_RYMDenSyubetsu,
        QXN6_RYMRiyousyaCD,
        QXN6_RYMHASSEITEN,
        QXN6_RYMDenpyoNo,
        QXN6_RYMToriTsuban,
        QXN6_RYMShiharai,
        DECODE(QXN6_RYMKeijouBi,NULL,' ',TO_CHAR(QXN6_RYMKeijouBi,'YYYYMMDD')),
        DECODE(QXN6_RYMRiyouBi,NULL,' ',TO_CHAR(QXN6_RYMRiyouBi,'YYYYMMDD')),
        NVL(QXN6_KGDKameitenMei1,' '),
        QXN6_RYMRiyouKng,
        NVL(QSA3_MEI,' ')
     FROM
        QXN6_HonAkuDataT,  --本人悪用データテーブル
  (SELECT QSA3_PRMCODENO,
    QSA3_MEI
   FROM QSA3_CodeV
   WHERE QSA3_PRMCODEKBN = 'S01'
  ) QSA3_CodeV  --コードＶＩＥＷ
     WHERE QXN6_RYMStatus =  QSA3_PRMCodeNo(+)

;
