#!/bin/csh
#　 スクリプト名 ： QLHJ09UX
#　 業  務       : クレジット帳票
#　 機  能       ： 経理月次決算月９日処理
#　 作成者       ： FIP
#   修  正       ： 2004/03/02 ワークデータ削除処理対応

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                                 # シェル名 file 名=job名
setenv JOB_ID       $SHELL_NAME:t                      # ジョブ名
setenv JOBNET_ID   'QLH071UX'                          # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
set    USERKEY    = $JOBNET_ID                         # ユーザキー
set    PRM_JOBNET =  "'"$JOBNET_ID"'"
set    PRM_JOB = "'"$JOB_ID"'"


###################################################################
# STEP-1     ＳＱＬローダーの実行                                 #
###################################################################

###################################################################
##set   LDR_CTRL_DIR  = '/home/ipc/qv/ldr'                #LOADER CONTROL DIR
##set   DATAV_DIR     = '/home/ipc/qv/host_data'          #DATA DIR
##set   USER_LOG_DIR  = '/home/ipc/qv/ldrlog'             #LOADER LOG DIR
##set   LDR_LOG_DIR   = '/home/ipc/qv/ldrlog'
set   DATAV_DIR     = $QV_DATA_DIR'/qv/data/host/merge'   #DATA DIR
set   DATAV_S     = '.hft'  			          #DATA 拡張子

# 2004/03/02 ワークデータ削除処理対応 ==>                                        #
set    KINOU      = 'クレジット帳票：カード取扱高月計データを削除する'
set    MODULE     = 'SQL*PLUS'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"  # 開始メッセージの出力
########################################################################
# STEP-1.0   カード取扱高月計データクリア                              #
########################################################################

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF > $LOGFILE
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF > $LOGFILE

TRUNCATE TABLE QVG2_CardGekkeiDT;
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
        set MSG = "失敗:カード取扱高月計データクリア RC=[$rc]"
        $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
        exit  1
endif
$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"  # 終了メッセージの出力
# 2004/03/02 ワークデータ削除処理対応 <==

###################################################################
# STEP-1.1     ＳＱＬローダーの実行           カード取扱高月報９  #
###################################################################
set    KINOU      = 'クレジット帳票：経理月次決算月９日処理 LOADER(カード取扱高月報９)'
set    CTLID      = 'QVBD_SLD5000'              #LOADER CONTROL F名
set    DATAID     = 'QVCF_S005000'$DATAV_S      #DATA
set    MODULE     = $CTLID 
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"  # 開始メッセージの出力
setenv NLS_LANG Japanese_Japan.JA16SJIS

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlldr $DB_USERID/$DB_PASSWORD           \
sqlldr $DB_USERID/$DB_PASSWORD@$ORACLE_SID\
       control=$LDR_CTRL_DIR/$CTLID.ctl  \
       data=$DATAV_DIR/$DATAID           \
       log=$LDR_LOG_DIR/ldr.log          \
       >& $USER_LOG_DIR/ldr1.log
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

#echo 'normal end'
set rc = $status
setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
        $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
        exit  1                                  # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"  # 終了メッセージの出力

###################################################################
# STEP-1.2     ＳＱＬローダーの実行     売掛金残高表９（期計）    #
###################################################################
set    KINOU      = 'クレジット帳票：経理月次決算月９日処理 LOADER(売掛金残高表９（期計）)'
set    CTLID      = 'QVBD_SLD5400'              #LOADER CONTROL F名
set    DATAID     = 'QVCF_S005400'$DATAV_S      #DATA
set    MODULE     = $CTLID 
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"  # 開始メッセージの出力
setenv NLS_LANG Japanese_Japan.JA16SJIS

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlldr $DB_USERID/$DB_PASSWORD           \
sqlldr $DB_USERID/$DB_PASSWORD@$ORACLE_SID\
       control=$LDR_CTRL_DIR/$CTLID.ctl  \
       data=$DATAV_DIR/$DATAID           \
       log=$LDR_LOG_DIR/ldr.log          \
       >& $USER_LOG_DIR/ldr1.log 
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

#echo 'normal end'
set rc = $status
setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
        $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
        exit  1                                  # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"  # 終了メッセージの出力

#######################################################################
# STEP-1.3     ＳＱＬローダーの実行   売掛金残高表９（決算半月計）    #
#######################################################################
set    KINOU      = 'クレジット帳票：経理月次決算月９日処理 LOADER（売掛金残高表９（決算半月計））'
set    CTLID      = 'QVBD_SLD5600'              #LOADER CONTROL F名
set    DATAID     = 'QVCF_S005600'$DATAV_S      #DATA
set    MODULE     = $CTLID 
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"  # 開始メッセージの出力
setenv NLS_LANG Japanese_Japan.JA16SJIS

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlldr $DB_USERID/$DB_PASSWORD           \
sqlldr $DB_USERID/$DB_PASSWORD@$ORACLE_SID\
       control=$LDR_CTRL_DIR/$CTLID.ctl  \
       data=$DATAV_DIR/$DATAID           \
       log=$LDR_LOG_DIR/ldr.log          \
       >& $USER_LOG_DIR/ldr1.log 
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

#echo 'normal end'
set rc = $status
setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
        $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
        exit  1                                  # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"  # 終了メッセージの出力



###################################################################
# STEP-2     ストアド・プロシジャの実行                           #
###################################################################
set   MODULE = 'qusc_sspexec.exe'

###################################################################
# STEP-2.1   ストアド・プロシジャの実行    売掛金（管理店別）印刷 #
###################################################################
set    KINOU      = 'クレジット帳票：経理月次決算月９日処理(売掛金（管理店別）印刷）'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"  # 開始メッセージの出力
setenv NLS_LANG Japanese_Japan.JA16SJIS
set    PRM_Data = "'3'"                          #付与ﾊﾟﾗﾒｰﾀ

$EXE_DIR/qusc_sspexec.exe  $JOBNET_ID  $JOB_ID  "QVBP_S002100Pkg.QVBP_S002100( $PRM_JOBNET, $PRM_JOB,$PRM_Data)"

set rc = $status
setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
        $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
        exit  1                                  # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"  # 終了メッセージの出力


####################################################################
# STEP-2.2   ストアド・プロシジャの実行     売掛金（全社）印刷     #
####################################################################
set    KINOU      = 'クレジット帳票：経理月次決算月９日処理（売掛金（全社）印刷）'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"  # 開始メッセージの出力
setenv NLS_LANG Japanese_Japan.JA16SJIS
set    PRM_Data = "'3'"                          #付与ﾊﾟﾗﾒｰﾀ

$EXE_DIR/qusc_sspexec.exe  $JOBNET_ID  $JOB_ID  "QVBP_S002200Pkg.QVBP_S002200( $PRM_JOBNET, $PRM_JOB,$PRM_Data)"

set rc = $status
setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
        $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
        exit  1                                  # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"  # 終了メッセージの出力


###################################################################
# STEP-2.3   ストアド・プロシジャの実行    売掛金（管理店別）印刷 #
###################################################################
set    KINOU      = 'クレジット帳票：経理月次決算月９日処理(売掛金（管理店別）印刷）'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"  # 開始メッセージの出力
setenv NLS_LANG Japanese_Japan.JA16SJIS
set    PRM_Data = "'5'"                          #付与ﾊﾟﾗﾒｰﾀ

$EXE_DIR/qusc_sspexec.exe  $JOBNET_ID  $JOB_ID  "QVBP_S002100Pkg.QVBP_S002100( $PRM_JOBNET, $PRM_JOB,$PRM_Data)"

set rc = $status
setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
        $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
        exit  1                                  # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"  # 終了メッセージの出力


####################################################################
# STEP-2.4   ストアド・プロシジャの実行     売掛金（全社）印刷     #
####################################################################
set    KINOU      = 'クレジット帳票：経理月次決算月９日処理（売掛金（全社）印刷）'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"  # 開始メッセージの出力
setenv NLS_LANG Japanese_Japan.JA16SJIS
set    PRM_Data = "'5'"                          #付与ﾊﾟﾗﾒｰﾀ

$EXE_DIR/qusc_sspexec.exe  $JOBNET_ID  $JOB_ID  "QVBP_S002200Pkg.QVBP_S002200( $PRM_JOBNET, $PRM_JOB,$PRM_Data)"

set rc = $status
setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
        $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
        exit  1                                  # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"  # 終了メッセージの出力



########################################################################
# STEP-2.5   ストアド・プロシジャの実行     カード取扱高月計累積       #
########################################################################
set    KINOU      = 'クレジット帳票：経理月次決算月９日処理（カード取扱高月計累積）'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"   # 開始メッセージの出力
setenv NLS_LANG Japanese_Japan.JA16SJIS
set    PRM_Data = "'6'"                          #付与ﾊﾟﾗﾒｰﾀ

$EXE_DIR/qusc_sspexec.exe  $JOBNET_ID  $JOB_ID  "QVBP_S001500Pkg.QVBP_S001500( $PRM_JOBNET, $PRM_JOB,$PRM_Data)"

set rc = $status
setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
        $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
        exit  1                                   # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   # 終了メッセージの出力


########################################################################
# STEP-2.6 ストアド・プロシジャの実行   カード取扱高月計期間管理Ｔ作成 #
########################################################################
set    KINOU      = 'クレジット帳票：経理月次決算月９日処理（カード取扱高月計期間管理Ｔ作成）'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"   # 開始メッセージの出力
setenv NLS_LANG Japanese_Japan.JA16SJIS
set    PRM_Data = "'6'"                          #付与ﾊﾟﾗﾒｰﾀ

$EXE_DIR/qusc_sspexec.exe  $JOBNET_ID  $JOB_ID  "QVBP_S002700Pkg.QVBP_S002700( $PRM_JOBNET, $PRM_JOB,$PRM_Data)"

set rc = $status
setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
        $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
        exit  1                                   # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   # 終了メッセージの出力


########################################################################
# STEP-2.7 ストアド・プロシジャの実行   カード取扱高月計印刷作成       #
########################################################################
set    KINOU      = 'クレジット帳票：経理月次決算月９日処理（カード取扱高月計印刷作成）'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"   # 開始メッセージの出力
setenv NLS_LANG Japanese_Japan.JA16SJIS

$EXE_DIR/qusc_sspexec.exe  $JOBNET_ID  $JOB_ID  "QVBP_S001600Pkg.QVBP_S001600( $PRM_JOBNET, $PRM_JOB)"

set rc = $status
setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
        $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
        exit  1                                   # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   # 終了メッセージの出力


########################################################################
# STEP-2.8 ストアド・プロシジャの実行   カード種類別印刷作成           #
########################################################################
set    KINOU      = 'クレジット帳票：経理月次決算月９日処理（カード種類別印刷作成）'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"   # 開始メッセージの出力
setenv NLS_LANG Japanese_Japan.JA16SJIS

$EXE_DIR/qusc_sspexec.exe  $JOBNET_ID  $JOB_ID  "QVBP_S001700Pkg.QVBP_S001700( $PRM_JOBNET, $PRM_JOB)"

set rc = $status
setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
        $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
        exit  1                                   # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   # 終了メッセージの出力


########################################################################
# STEP-2.8 ストアド・プロシジャの実行   手数料収益内訳表印刷作成       #
########################################################################
set    KINOU      = 'クレジット帳票：経理月次決算月９日処理（手数料収益内訳表印刷作成）'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"   # 開始メッセージの出力
setenv NLS_LANG Japanese_Japan.JA16SJIS

$EXE_DIR/qusc_sspexec.exe  $JOBNET_ID  $JOB_ID  "QVBP_S001800Pkg.QVBP_S001800( $PRM_JOBNET, $PRM_JOB)"

set rc = $status
setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
        $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
        exit  1                                   # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   # 終了メッセージの出力

###################################################################
#                           終 了                                 #
###################################################################
exit 0                                           # 正常終了

~
