LOAD DATA
CHARACTERSET JA16SJIS
TRUNCATE
PRESERVE BLANKS
INTO TABLE QAAI_POINTCTRLM
fields terminated by "q"
(
    QAAI_PRMKIGYOUCD         CHAR, -- CHAR(4) NOT NULL,
    QAAI_PRMSUBRANGEKEY      CHAR, -- CHAR(4) NOT NULL,
    QAAI_PRMNAIBUKAIINNO     CHAR, -- CHAR(8) NOT NULL,
    QAAI_PRMRECKBN           CHAR, -- CHAR(1) NOT NULL,
    QAAI_ZOKTUMITATEYUKO     DATE NULLIF (QAAI_ZOKTUMITATEYUKO="00000000"),  --  DATE NULL,
    QAAI_ZOKHIKIKAEYUKO      DATE NULLIF (QAAI_ZOKHIKIKAEYUKO="00000000"),  --  DATE NULL,
    QAAI_ZOKTORIKESITUUBAN   CHAR, -- NUMBER(7) NOT NULL,
    QAAI_TOKTKURIKOSIPOINT   CHAR, -- NUMBER(11) NOT NULL,
    QAAI_TOKTHASSEIPOINT     CHAR, -- NUMBER(11) NOT NULL,
    QAAI_TOKTHIKIKAEPOINT    CHAR, -- NUMBER(11) NOT NULL,
    QAAI_TOKTTORIKESIPOINT   CHAR, -- NUMBER(11) NOT NULL,
    QAAI_TOKTZANPOINT        CHAR, -- NUMBER(11) NOT NULL,
    QAAI_TOKSHASSEIPOINT     CHAR, -- NUMBER(11) NOT NULL,
    QAAI_TOKSHIKIKAEPOINT    CHAR, -- NUMBER(11) NOT NULL,
    QAAI_TOKSTORIKESIPOINT   CHAR, -- NUMBER(11) NOT NULL,
    QAAI_TOKRHASSEIPOINT     CHAR, -- NUMBER(11) NOT NULL,
    QAAI_TOKRHIKIKAEPOINT    CHAR, -- NUMBER(11) NOT NULL,
    QAAI_KIGMKIGENGIREFLG    CHAR, -- CHAR(1) NOT NULL,
    QAAI_KIGMTUMITATEYUKO    DATE NULLIF (QAAI_KIGMTUMITATEYUKO="00000000"),  --  DATE NULL,
    QAAI_KIGMHIKIKAEYUKO     DATE NULLIF (QAAI_KIGMHIKIKAEYUKO="00000000"),  --  DATE NULL,
    QAAI_KIGMKIGENGIREPOINT  CHAR, -- NUMBER(11) NOT NULL,
    QAAI_KIGMHIKIKAEPOINT    CHAR, -- NUMBER(11) NOT NULL,
    QAAI_KIGMTORIKESIPOINT   CHAR, -- NUMBER(11) NOT NULL,
    QAAI_HIKIKAEANSYOUNO     CHAR, -- CHAR(4) NOT NULL,
    QAAI_SEIKYUNENGETU       CHAR, -- NUMBER(6) NOT NULL,
    QAAI_HOSTSHORIYMD        CHAR, -- CHAR(8) NOT NULL,
    QAAI_HOSTSHORITIME       CHAR, -- CHAR(6) NOT NULL,
    QAAI_SVRKOUSHINYMD       DATE NULLIF (QAAI_SVRKOUSHINYMD="00000000") --  DATE NULL,
)
