LOAD DATA
CHARACTERSET JA16SJIS
APPEND
PRESERVE BLANKS
INTO TABLE QCS2_GAIGAICNVT
FIELDS TERMINATED BY "q"
(
    QCS2_PRMCSTCARDNO        CHAR,  --CHAR(16) NOT NULL,
    QCS2_KIGYOUCD            CHAR,  --CHAR(04) ,
    QCS2_SUBRANGEKEY         CHAR,  --CHAR(04) ,
    QCS2_NAIBUKAIINNO        CHAR,  --CHAR(08) ,
    QCS2_KIKKYUUNO           CHAR,  --CHAR(16) ,
    QCS2_NYKUKETSUKENO       CHAR,  --CHAR(08) ,
    QCS2_IKNKBN              CHAR,  --CHAR(01) ,
    QCS2_IKNKOUZAYMD         DATE "YYYYMMDD" NULLIF(QCS2_IKNKOUZAYMD="00000000"),
    QCS2_IKNSAKIKAIINNO      CHAR,  --CHAR(16) ,
    QCS2_CARDKBN             CHAR,  --CHAR(06) ,
    QCS2_HONSHIMEIKANA       CHAR,  --VARCHAR2(30) ,
    QCS2_RIYOUSHACD          CHAR,  --CHAR(01) ,
    QCS2_YUKOKIGEN           CHAR,  --NUMBER(06) ,
    QCS2_TENKANRI            CHAR,  --CHAR(02) ,
    QCS2_TENKAKUTOKU         CHAR,  --CHAR(02) ,
    QCS2_STSKBN              CHAR,  --CHAR(01) ,
    QCS2_STSKBNTOROKUYMD     DATE "YYYYMMDD" NULLIF(QCS2_STSKBNTOROKUYMD="00000000"),
    QCS2_PNTSHINNO           CHAR,  --NUMBER(04) ,
    QCS2_PNTKYUUNO           CHAR,  --NUMBER(04) ,
    QCS2_PNTHENKOUYMD        DATE "YYYYMMDD" NULLIF(QCS2_PNTHENKOUYMD="00000000"),
    QCS2_TOUYmd              DATE "YYYYMMDD" NULLIF(QCS2_TOUYmd="00000000"),
    QCS2_KOUYmd              DATE "YYYYMMDD" NULLIF(QCS2_KOUYmd="00000000"),
    QCS2_HOSTSHORIYMD        CHAR,  --CHAR(08) ,
    QCS2_HOSTSHORITIME       CHAR,  --CHAR(06) ,
    QCS2_SVRKOUSHINYMD       DATE "YYYYMMDD" NULLIF(QCS2_SVRKOUSHINYMD="00000000")
)
