LOAD DATA
APPEND
PRESERVE BLANKS
INTO TABLE QCS3_RIYOUDTLT
FIELDS TERMINATED BY "q"
(
       QCS3_PRMKigyouCd            CHAR, --  CHAR(4) NOT NULL,
       QCS3_PRMSubRangeKey         CHAR, --  CHAR(4) NOT NULL,
       QCS3_PRMNaibuKaiinNo        CHAR, --  CHAR(8) NOT NULL,
       QCS3_PRMTorihikiNo          CHAR, --  NUMBER(7) NOT NULL,
       QCS3_DenpyouNo              CHAR, --  CHAR(12) NOT NULL,
       QCS3_RecKbn                 CHAR, --  CHAR(1) NOT NULL,
       QCS3_KaijyoKbn              CHAR, --  CHAR(1) NOT NULL,
       QCS3_AkakuroKbn             CHAR, --  CHAR(1) NOT NULL,
       QCS3_SeikyuHoryuKbn         CHAR, --  CHAR(1) NOT NULL,
       QCS3_DenpyouShubetsu        CHAR, --  CHAR(4) NOT NULL,
       QCS3_BatchNo                CHAR, --  NUMBER(4) NOT NULL,
       QCS3_GNOBatchNo             CHAR, --  NUMBER(4) NOT NULL,
       QCS3_GNOSequence            CHAR, --  NUMBER(3) NOT NULL,
       QCS3_CardNo                 CHAR, --  CHAR(16) NOT NULL,
       QCS3_RiyouBi                DATE NULLIF(QCS3_RiyouBi="00000000"),
       QCS3_UketsukeBi             DATE NULLIF(QCS3_UketsukeBi="00000000"),
       QCS3_KeijyouBi              DATE NULLIF(QCS3_KeijyouBi="00000000"),
       QCS3_HasseiTen              CHAR, --  CHAR(2) NOT NULL,
       QCS3_KameiTenNo             CHAR, --  CHAR(10) NOT NULL,
       QCS3_POSRegNo               CHAR, --  CHAR(4) NOT NULL,
       QCS3_POSTorihikiNo          CHAR, --  CHAR(5) NOT NULL,
       QCS3_Tanmatsu               CHAR, --  CHAR(9) NOT NULL,
       QCS3_KAKAKaatsukai          CHAR, --  CHAR(2) NOT NULL,
       QCS3_KAKAKaka               CHAR, --  CHAR(2) NOT NULL,
       QCS3_KAKKKakarikakari       CHAR, --  CHAR(2) NOT NULL,
       QCS3_SaiCd                  CHAR, --  CHAR(3) NOT NULL,
       QCS3_TKUriageTuuBan         CHAR, --  NUMBER(13) NOT NULL,
       QCS3_GyouSu                 CHAR, --  NUMBER(2) NOT NULL,
       QCS3_GyouNo                 CHAR, --  NUMBER(2) NOT NULL,
       QCS3_GKGShiharaiHoho        CHAR, --  CHAR(2) NOT NULL,
       QCS3_GKGLoanShubetsu        CHAR, --  CHAR(5) NOT NULL,
       QCS3_GKGRiyouKng            CHAR, --  NUMBER(11) NOT NULL,
       QCS3_GKGShouhinDaikin       CHAR, --  NUMBER(11) NOT NULL,
       QCS3_GKGBubikiRitsu         CHAR, --  NUMBER(2) NOT NULL,
       QCS3_GKGBubikiGaku          CHAR, --  NUMBER(11) NOT NULL,
       QCS3_GKGBubikiTaishou       CHAR, --  NUMBER(11) NOT NULL,
       QCS3_GKGBubikiJyogai        CHAR, --  NUMBER(11) NOT NULL,
       QCS3_GKGShouninNo           CHAR, --  CHAR(7) NOT NULL,
       QCS3_GKGBunkatsuKaiSu       CHAR, --  NUMBER(3) NOT NULL,
       QCS3_GKGBonusKaisu          CHAR, --  NUMBER(2) NOT NULL,
       QCS3_GKGBonusKasan          CHAR, --  NUMBER(11) NOT NULL,
       QCS3_GKGMaeShouhiZei        CHAR, --  NUMBER(9) NOT NULL,
       QCS3_GKGAtoShouhiZei        CHAR, --  NUMBER(9) NOT NULL,
       QCS3_GKGAtamakin            CHAR, --  NUMBER(11) NOT NULL,
       QCS3_GKGTesuryouRitsu       CHAR, --  NUMBER(4,2) NOT NULL,
       QCS3_GKGTesuryouGaku        CHAR, --  NUMBER(9) NOT NULL,
       QCS3_GKGChusyutsuSumi       CHAR, --  CHAR(1) NOT NULL,
       QCS3_GKGPo1KeijyouKbn       CHAR, --  CHAR(1) NOT NULL,
       QCS3_GKGRiyoushaCd          CHAR, --  CHAR(1) NOT NULL,
       QCS3_GKGGentiKakaku         CHAR, --  NUMBER(13,3) NOT NULL,
       QCS3_GKGKansanRate          CHAR, --  NUMBER(13,7) NULL,
       QCS3_GKGKansanBi            DATE NULLIF(QCS3_GKGKansanBi="00000000"),
       QCS3_GKGKokuNaiKaiGai       CHAR, --  CHAR(1) NOT NULL,
       QCS3_GKGKeisanSumiSign      CHAR, --  CHAR(1) NOT NULL,
       QCS3_GKGHurikaeKaiinNo      CHAR, --  CHAR(16) NOT NULL,
       QCS3_GKGHasseiRouto         CHAR, --  CHAR(1) NOT NULL,
       QCS3_KameitenTesuryo        CHAR, --  NUMBER(9) NOT NULL,
       QCS3_DankeiTesuryou         CHAR, --  NUMBER(9) NOT NULL,
       QCS3_DenpyouUmuFlg          CHAR, --  CHAR(1) NOT NULL,
       QCS3_IdoKeijyouKbn          CHAR, --  CHAR(1) NOT NULL,
       QCS3_CashingBunkai          CHAR, --  CHAR(5) NOT NULL,
       QCS3_HurikaeKbn             CHAR, --  CHAR(1) NOT NULL,
       QCS3_ShainNoUmuKbn          CHAR, --  CHAR(1) NOT NULL,
       QCS3_DenNyuryokuTen         CHAR, --  CHAR(2) NOT NULL,
       QCS3_DaihikiDenpyoKbn       CHAR, --  CHAR(1) NOT NULL,
       QCS3_PointShikibetsu        CHAR, --  CHAR(1) NOT NULL,
       QCS3_GKPTsujyouGoukei       CHAR, --  NUMBER(11) NOT NULL,
       QCS3_GKPBonusGoukei         CHAR, --  NUMBER(11) NOT NULL,
       QCS3_YoutaiCd               CHAR, --  CHAR(2) NOT NULL,
       QCS3_KeijyouUrichouKbn      CHAR, --  CHAR(1) NOT NULL,
       QCS3_ZeirituKbn             CHAR, --  CHAR(1) NOT NULL,
       QCS3_HostShoriYmd           CHAR, --  CHAR(8) NOT NULL,
       QCS3_HostShoriTime          CHAR, --  CHAR(6) NOT NULL,
       QCS3_SvrKoushinYmd          DATE NULLIF(QCS3_SvrKoushinYmd="00000000"),
       QCS3_ISOTUUKA               CHAR, --  CHAR(3) NULL,
       QCS3_ITIBUHENPINKBN         CHAR, --  CHAR(1) NULL,
       QCS3_JIDOUFURIKAEKBN        CHAR, --  CHAR(1) NULL
       QCS3_JyoGaiUtiKin           CHAR  --  NUMBER(13) NOT NULL
)
