LOAD DATA
CHARACTERSET JA16SJIS
APPEND
PRESERVE BLANKS
INTO TABLE QCS4_RIYOUDTLGT
FIELDS TERMINATED BY "q"
(
       QCS4_PRMKigyouCd            CHAR, --  CHAR(4) NOT NULL,
       QCS4_PRMSubRangeKey         CHAR, --  CHAR(4) NOT NULL,
       QCS4_PRMNaibuKaiinNo        CHAR, --  CHAR(8) NOT NULL,
       QCS4_PRMTorihikiNo          CHAR, --  NUMBER(7) NOT NULL,
       QCS4_PRMGyouNo              CHAR, --  NUMBER(2) NOT NULL,
       QCS4_DenpyouNo              CHAR, --  CHAR(12) NOT NULL,
       QCS4_RecKbn                 CHAR, --  CHAR(1) NOT NULL,
       QCS4_KaijyoKbn              CHAR, --  CHAR(1) NOT NULL,
       QCS4_AkaKuroKbn             CHAR, --  CHAR(1) NOT NULL,
       QCS4_SeikyuHoryuKbn         CHAR, --  CHAR(1) NOT NULL,
       QCS4_DenpyouShubetsu        CHAR, --  CHAR(4) NOT NULL,
       QCS4_BatchNo                CHAR, --  NUMBER(4) NULL,
       QCS4_GNOBatchNo             CHAR, --  NUMBER(4) NULL,
       QCS4_GNOSequence            CHAR, --  NUMBER(3) NOT NULL,
       QCS4_CardNo                 CHAR, --  CHAR(16) NOT NULL,
       QCS4_RiyouBi                DATE NULLIF(QCS4_RiyouBi="00000000"),
       QCS4_UketsukeBi             DATE NULLIF(QCS4_UketsukeBi="00000000"),
       QCS4_KeijyouBi              DATE NULLIF(QCS4_KeijyouBi="00000000"),
       QCS4_HasseiTen              CHAR, --  CHAR(2) NOT NULL,
       QCS4_KameiTenNo             CHAR, --  CHAR(10) NOT NULL,
       QCS4_POSRegNo               CHAR, --  CHAR(4) NOT NULL,
       QCS4_POSTorihikiNo          CHAR, --  CHAR(5) NOT NULL,
       QCS4_Tanmatsu               CHAR, --  CHAR(9) NOT NULL,
       QCS4_KAKAKaAtsukai          CHAR, --  CHAR(2) NOT NULL,
       QCS4_KAKAKaKa               CHAR, --  CHAR(2) NOT NULL,
       QCS4_KAKKKakariKakari       CHAR, --  CHAR(2) NOT NULL,
       QCS4_SaiCd                  CHAR, --  CHAR(3) NOT NULL,
       QCS4_TKUriageTuuBan         CHAR, --  NUMBER(13) NOT NULL,
       QCS4_GyouSu                 CHAR, --  NUMBER(2) NOT NULL,
       QCS4_GMSBuMon               CHAR, --  CHAR(2) NOT NULL,
       QCS4_GMSHinGunCd            CHAR, --  CHAR(3) NOT NULL,
       QCS4_GMSHGCheckDigit        CHAR, --  CHAR(1) NOT NULL,
       QCS4_GMSFloor               CHAR, --  CHAR(1) NOT NULL,
       QCS4_GMSHinMeiCd            CHAR, --  CHAR(3) NOT NULL,
       QCS4_GMSHMCheckDigit        CHAR, --  CHAR(1) NOT NULL,
       QCS4_GMSSeikyuKanji         CHAR, --  VARCHAR2(40) NULL,
       QCS4_GMSHinMeiSaisai        CHAR, --  CHAR(4) NOT NULL,
       QCS4_GMSSeikyuSakuin        CHAR, --  CHAR(1) NOT NULL,
       QCS4_GMSSuryou              CHAR, --  NUMBER(9,2) NOT NULL,
       QCS4_GMSTanka               CHAR, --  NUMBER(7) NOT NULL,
       QCS4_GMSKng                 CHAR, --  NUMBER(11) NOT NULL,
       QCS4_GMSJyogaiKbn           CHAR, --  CHAR(1) NOT NULL,
       QCS4_GMSBubikiGaku          CHAR, --  NUMBER(9) NOT NULL,
       QCS4_GMSZeiKbn              CHAR, --  CHAR(1) NOT NULL,
       QCS4_GMSKankinKbn           CHAR, --  CHAR(1) NOT NULL,
       QCS4_GMSGetsureiCd          CHAR, --  CHAR(1) NOT NULL,
       QCS4_GMSMaeShouhiZei        CHAR, --  NUMBER(9) NOT NULL,
       QCS4_GMSPointRitsu          CHAR, --  NUMBER(4,2) NOT NULL,
       QCS4_GMSGakuPointSu         CHAR, --  NUMBER(11) NOT NULL,
       QCS4_GMSBoPointRitsu        CHAR, --  NUMBER(4,2) NOT NULL,
       QCS4_GMSBoGakuPointSu       CHAR, --  NUMBER(11) NOT NULL,
       QCS4_HostShoriYmd           CHAR, --  CHAR(8) NOT NULL,
       QCS4_HostShoriTime          CHAR, --  CHAR(6) NOT NULL,
       QCS4_SvrKoushinYmd          DATE NULLIF(QCS4_SvrKoushinYmd="00000000"),
       QCS4_JgiAnbunGaku           CHAR, --  NUMBER(11) NOT NULL,
       QCS4_ShjAnbunJuni           CHAR --  NUMBER(2) NOT NULL
)
