LOAD DATA
CHARACTERSET JA16SJIS
TRUNCATE
PRESERVE BLANKS
INTO TABLE QCS7_POINTCTRLM
FIELDS TERMINATED BY "q"
(
    QCS7_PRMKIGYOUCD         CHAR, -- CHAR(4) NOT NULL,
    QCS7_PRMSUBRANGEKEY      CHAR, -- CHAR(4) NOT NULL,
    QCS7_PRMNAIBUKAIINNO     CHAR, -- CHAR(8) NOT NULL,
    QCS7_PRMRECKBN           CHAR, -- CHAR(1) NOT NULL,
    QCS7_ZOKTUMITATEYUKO     DATE NULLIF (QCS7_ZOKTUMITATEYUKO="00000000"),  --  DATE NULL,
    QCS7_ZOKHIKIKAEYUKO      DATE NULLIF (QCS7_ZOKHIKIKAEYUKO="00000000"),  --  DATE NULL,
    QCS7_ZOKTORIKESITUUBAN   CHAR, -- NUMBER(7) NOT NULL,
    QCS7_TOKTKURIKOSIPOINT   CHAR, -- NUMBER(11) NOT NULL,
    QCS7_TOKTHASSEIPOINT     CHAR, -- NUMBER(11) NOT NULL,
    QCS7_TOKTHIKIKAEPOINT    CHAR, -- NUMBER(11) NOT NULL,
    QCS7_TOKTTORIKESIPOINT   CHAR, -- NUMBER(11) NOT NULL,
    QCS7_TOKTZANPOINT        CHAR, -- NUMBER(11) NOT NULL,
    QCS7_TOKSHASSEIPOINT     CHAR, -- NUMBER(11) NOT NULL,
    QCS7_TOKSHIKIKAEPOINT    CHAR, -- NUMBER(11) NOT NULL,
    QCS7_TOKSTORIKESIPOINT   CHAR, -- NUMBER(11) NOT NULL,
    QCS7_TOKRHASSEIPOINT     CHAR, -- NUMBER(11) NOT NULL,
    QCS7_TOKRHIKIKAEPOINT    CHAR, -- NUMBER(11) NOT NULL,
    QCS7_KIGMKIGENGIREFLG    CHAR, -- CHAR(1) NOT NULL,
    QCS7_KIGMTUMITATEYUKO    DATE NULLIF (QCS7_KIGMTUMITATEYUKO="00000000"),  --  DATE NULL,
    QCS7_KIGMHIKIKAEYUKO     DATE NULLIF (QCS7_KIGMHIKIKAEYUKO="00000000"),  --  DATE NULL,
    QCS7_KIGMKIGENGIREPOINT  CHAR, -- NUMBER(11) NOT NULL, 
    QCS7_KIGMHIKIKAEPOINT    CHAR, -- NUMBER(11) NOT NULL,
    QCS7_KIGMTORIKESIPOINT   CHAR, -- NUMBER(11) NOT NULL,
    QCS7_HIKIKAEANSYOUNO     CHAR, -- CHAR(4) NOT NULL,
    QCS7_SEIKYUNENGETU       CHAR, -- NUMBER(6) NOT NULL,
    QCS7_HOSTSHORIYMD        CHAR, -- CHAR(8) NOT NULL,
    QCS7_HOSTSHORITIME       CHAR, -- CHAR(6) NOT NULL,
    QCS7_SVRKOUSHINYMD       DATE NULLIF (QCS7_SVRKOUSHINYMD="00000000") --  DATE NULL,
) 
