UNRECOVERABLE
LOAD DATA
CHARACTERSET JA16SJIS
APPEND
PRESERVE BLANKS
INTO TABLE QHA5_SEIRIREKIT
( QHA5_KEYSEIKYUYM       POSITION(  1:  6) CHAR,
  QHA5_KEYSEQNO          POSITION(  7: 13) CHAR,
  QHA5_KEYBUNKATSUNO     POSITION( 14: 15) INTEGER EXTERNAL,
  QHA5_KEYVERSIONNO      POSITION( 16: 17) INTEGER EXTERNAL,
  QHA5_KAIINNO           POSITION( 18: 33) CHAR,
  QHA5_TENCD             POSITION( 34: 35) CHAR,
  QHA5_TOUZAIKBN         POSITION( 36: 36) CHAR,
  QHA5_KIGYOCD           POSITION( 37: 40) CHAR,
  QHA5_SUBRNG            POSITION( 41: 44) CHAR,
  QHA5_NAIBUKAIIN        POSITION( 45: 52) CHAR,
  QHA5_SAGYOKBN          POSITION( 53: 53) CHAR,
  QHA5_SEIKYUKNG         POSITION( 54: 63) INTEGER EXTERNAL,
--  QHA5_MEMO              POSITION( 64:363) CHAR,
  QHA5_MEMO              POSITION(64)      CHAR TERMINATED BY '|',
  QHA5_MOTOBUNKATSUNO    POSITION(365:366) INTEGER EXTERNAL,
  QHA5_MOTOVERSIONNO     POSITION(367:368) INTEGER EXTERNAL,
  QHA5_MOTOSEIKYUKNG     POSITION(369:378) INTEGER EXTERNAL,
  QHA5_YUUKOUFLG         POSITION(379:379) CHAR,
  QHA5_PRINTNO           POSITION(380:387) INTEGER EXTERNAL,
  QHA5_PAGE              POSITION(388:391) INTEGER EXTERNAL,
  QHA5_PRINTYMD          POSITION(392:399) DATE "YYYYMMDD",
  QHA5_KOUSHINTANTOCD    POSITION(400:407) CHAR,
  QHA5_KOUSHINTANTOMEI   POSITION(408:419) CHAR NULLIF QHA5_KOUSHINTANTOMEI=BLANKS,
  QHA5_KOUSHINDATETIME   POSITION(420:433) DATE "YYYYMMDDHH24MISS" NULLIF QHA5_KOUSHINDATETIME=BLANKS,
  QHA5_SAKUJOTANTOCD     POSITION(434:441) CHAR,
  QHA5_SAKUJOTANTOMEI    POSITION(442:453) CHAR NULLIF QHA5_SAKUJOTANTOMEI=BLANKS,
  QHA5_SAKUJODATETIME    POSITION(454:467) DATE "YYYYMMDDHH24MISS" NULLIF QHA5_SAKUJODATETIME=BLANKS,
  QHA5_TOUROKUTANTOCD    POSITION(468:475) CHAR,
  QHA5_TOUROKUTANTOMEI   POSITION(476:487) CHAR NULLIF QHA5_TOUROKUTANTOMEI=BLANKS,
  QHA5_TOUROKUBUSYOCD    POSITION(488:491) CHAR,
  QHA5_TOUROKUDATETIME   POSITION(492:505) DATE "YYYYMMDDHH24MISS" NULLIF QHA5_TOUROKUDATETIME=BLANKS)
