UNRECOVERABLE
LOAD DATA
CHARACTERSET JA16SJIS
APPEND
PRESERVE BLANKS
INTO TABLE QHA4_SEIKYUDTLT
( QHA4_KeyRecShikibetsu  POSITION(01: 01) INTEGER EXTERNAL,
  QHA4_KeySeikyuYm       POSITION(02: 07) CHAR,
  QHA4_KeySeqNo          POSITION(08: 14) CHAR,
  QHA4_KeyBunkatsuNo     POSITION(15: 16) INTEGER EXTERNAL,
  QHA4_KeyVersionNo      POSITION(17: 18) INTEGER EXTERNAL,
  QHA4_KeyRecNo          POSITION(19: 21) INTEGER EXTERNAL,
  QHA4_RecKbn            POSITION(22: 22) CHAR,
  QHA4_Kaigyo            POSITION(43: 44) INTEGER EXTERNAL,
  QHA4_Detail            POSITION(47:186) CHAR NULLIF QHA4_Detail=BLANKS,
  QHA4_TourokuDateTime   SYSDATE)
