UNRECOVERABLE
LOAD DATA
CHARACTERSET JA16SJIS
APPEND
PRESERVE BLANKS
INTO TABLE QHA8_SEIITIRANDT
( QHA8_KEYSEIKYUYM      POSITION( 01: 06) CHAR,
  QHA8_KEYSEQNO         POSITION( 07: 13) CHAR,
  QHA8_KEYBUNKATSUNO    POSITION( 14: 15) INTEGER EXTERNAL,
  QHA8_KEYVERSIONNO     POSITION( 16: 17) INTEGER EXTERNAL,
  QHA8_KIGYOCD          POSITION( 18: 21) CHAR,
  QHA8_SUBRNG           POSITION( 22: 25) CHAR,
  QHA8_NAIBUKAIIN       POSITION( 26: 33) CHAR,
  QHA8_SEIKYUKNG        POSITION( 34: 43) INTEGER EXTERNAL,
  QHA8_MOTOSEIKYUKNG    POSITION( 44: 53) INTEGER EXTERNAL,
  QHA8_MEMO             POSITION( 54 )    CHAR TERMINATED BY '|', --101 byte
  QHA8_TOUROKUDATETIME  POSITION(155:167) DATE "YYYYMMDDHH24MISS")
