UNRECOVERABLE
LOAD DATA
CHARACTERSET JA16SJIS
APPEND
PRESERVE BLANKS
INTO TABLE QHAG_SEIITIRANIKOUDT
( QHAG_KEYKIGYOCD       POSITION( 1: 4) CHAR,
  QHAG_KEYSUBRNG        POSITION( 5: 8) CHAR,
  QHAG_KEYNAIBUKAIIN    POSITION( 9:16) CHAR,
  QHAG_SEIKYUYM         POSITION(17:22) CHAR
)
