UNRECOVERABLE
LOAD DATA
CHARACTERSET JA16SJIS
APPEND
PRESERVE BLANKS
INTO TABLE QHA4_SEIKYUDTLT
( QHA4_KeyRecShikibetsu  POSITION(01: 01) INTEGER EXTERNAL,
  QHA4_KeySeikyuYm       POSITION(02: 07) CHAR,
  QHA4_KeySeqNo          POSITION(08: 14) CHAR,
  QHA4_KeyBunkatsuNo     POSITION(15: 16) INTEGER EXTERNAL,
  QHA4_KeyVersionNo      POSITION(17: 18) INTEGER EXTERNAL,
  QHA4_KeyRecNo          POSITION(19: 23) INTEGER EXTERNAL,
  QHA4_RecKbn            POSITION(24: 24) CHAR,
  QHA4_Kaigyo            POSITION(45: 46) INTEGER EXTERNAL,
  QHA4_Detail            POSITION(49:188) CHAR NULLIF QHA4_Detail=BLANKS,
  QHA4_TourokuDateTime   SYSDATE)
