UNRECOVERABLE
LOAD DATA
CHARACTERSET JA16SJIS
APPEND
PRESERVE BLANKS
INTO TABLE QHA7_SEIRIDTLT
( QHA7_KeyRecShikibetsu  POSITION( 01: 01) CHAR,
  QHA7_KeySeikyuYm       POSITION( 02: 07) CHAR,
  QHA7_KeySeqNo          POSITION( 08: 14) CHAR,
  QHA7_KeyBunkatsuNo     POSITION( 15: 16) INTEGER EXTERNAL,
  QHA7_KeyVersionNo      POSITION( 17: 18) INTEGER EXTERNAL,
  QHA7_KeyRecNo          POSITION( 19: 23) INTEGER EXTERNAL,
  QHA7_RecKbn            POSITION( 24: 24) CHAR,
  QHA7_Kaigyo            POSITION( 25: 26) INTEGER EXTERNAL,
  QHA7_Detail            POSITION( 27 )    CHAR TERMINATED BY '|',
  QHA7_TourokuTantoCd    POSITION(168:175) CHAR,
  QHA7_TourokuTantoMei   POSITION(176:187) CHAR,
  QHA7_TourokuBusyoCd    POSITION(188:191) CHAR,
  QHA7_TourokuDateTime   POSITION(192:205) DATE "YYYYMMDDHH24MISS")
