UNRECOVERABLE
LOAD DATA
CHARACTERSET JA16SJIS
APPEND
PRESERVE BLANKS
INTO TABLE QHE5_SEIRIREKIT
( QHE5_KEYSEIKYUYM       POSITION(  1:  6) CHAR,
  QHE5_KEYSEQNO          POSITION(  7: 13) CHAR,
  QHE5_KEYBUNKATSUNO     POSITION( 14: 15) INTEGER EXTERNAL,
  QHE5_KEYVERSIONNO      POSITION( 16: 17) INTEGER EXTERNAL,
  QHE5_KAIINNO           POSITION( 18: 33) CHAR,
  QHE5_TENCD             POSITION( 34: 35) CHAR,
  QHE5_TOUZAIKBN         POSITION( 36: 36) CHAR,
  QHE5_KIGYOCD           POSITION( 37: 40) CHAR,
  QHE5_SUBRNG            POSITION( 41: 44) CHAR,
  QHE5_NAIBUKAIIN        POSITION( 45: 52) CHAR,
  QHE5_SAGYOKBN          POSITION( 53: 53) CHAR,
  QHE5_SEIKYUKNG         POSITION( 54: 63) INTEGER EXTERNAL,
  QHE5_MEMO              POSITION(64)      CHAR TERMINATED BY '|',
  QHE5_MOTOBUNKATSUNO    POSITION(365:366) INTEGER EXTERNAL,
  QHE5_MOTOVERSIONNO     POSITION(367:368) INTEGER EXTERNAL,
  QHE5_MOTOSEIKYUKNG     POSITION(369:378) INTEGER EXTERNAL,
  QHE5_YUUKOUFLG         POSITION(379:379) CHAR,
  QHE5_PRINTNO           POSITION(380:387) INTEGER EXTERNAL,
  QHE5_PAGE              POSITION(388:391) INTEGER EXTERNAL,
  QHE5_PRINTYMD          POSITION(392:399) DATE "YYYYMMDD",
  QHE5_KOUSHINTANTOCD    POSITION(400:407) CHAR,
  QHE5_KOUSHINTANTOMEI   POSITION(408:419) CHAR NULLIF QHE5_KOUSHINTANTOMEI=BLANKS,
  QHE5_KOUSHINDATETIME   POSITION(420:433) DATE "YYYYMMDDHH24MISS" NULLIF QHE5_KOUSHINDATETIME=BLANKS,
  QHE5_SAKUJOTANTOCD     POSITION(434:441) CHAR,
  QHE5_SAKUJOTANTOMEI    POSITION(442:453) CHAR NULLIF QHE5_SAKUJOTANTOMEI=BLANKS,
  QHE5_SAKUJODATETIME    POSITION(454:467) DATE "YYYYMMDDHH24MISS" NULLIF QHE5_SAKUJODATETIME=BLANKS,
  QHE5_TOUROKUTANTOCD    POSITION(468:475) CHAR,
  QHE5_TOUROKUTANTOMEI   POSITION(476:487) CHAR NULLIF QHE5_TOUROKUTANTOMEI=BLANKS,
  QHE5_TOUROKUBUSYOCD    POSITION(488:491) CHAR,
  QHE5_TOUROKUDATETIME   POSITION(492:505) DATE "YYYYMMDDHH24MISS" NULLIF QHE5_TOUROKUDATETIME=BLANKS)
