UNRECOVERABLE
LOAD DATA
CHARACTERSET JA16SJIS
APPEND
PRESERVE BLANKS
INTO TABLE QHE8_SEIITIRANDT
( QHE8_KEYSEIKYUYM      POSITION( 01: 06) CHAR,
  QHE8_KEYSEQNO         POSITION( 07: 13) CHAR,
  QHE8_KEYBUNKATSUNO    POSITION( 14: 15) INTEGER EXTERNAL,
  QHE8_KEYVERSIONNO     POSITION( 16: 17) INTEGER EXTERNAL,
  QHE8_KIGYOCD          POSITION( 18: 21) CHAR,
  QHE8_SUBRNG           POSITION( 22: 25) CHAR,
  QHE8_NAIBUKAIIN       POSITION( 26: 33) CHAR,
  QHE8_SEIKYUKNG        POSITION( 34: 43) INTEGER EXTERNAL,
  QHE8_MOTOSEIKYUKNG    POSITION( 44: 53) INTEGER EXTERNAL,
  QHE8_MEMO             POSITION( 54 )    CHAR TERMINATED BY '|',
  QHE8_TOUROKUDATETIME  POSITION(155:167) DATE "YYYYMMDDHH24MISS")
