LOAD DATA
CHARACTERSET JA16SJIS
APPEND
PRESERVE BLANKS
INTO TABLE QHEG_SEIKYUUNITT
( QHEG_Keykigyocd        POSITION(001:004) CHAR,
  QHEG_Keysubrng         POSITION(005:008) CHAR,
  QHEG_Keynaibukaiin     POSITION(009:016) CHAR,
  QHEG_KeySeikyuym       POSITION(017:022) CHAR,
  QHEG_Koushinnaiyo      POSITION(023:023) CHAR,
  QHEG_Tourokuid         CONSTANT "SYSTEM  ",
  QHEG_Tourokudate       "TO_CHAR(SYSDATE,'YYYYMMDD')",
  QHEG_Tourokutime       "TO_CHAR(SYSDATE,'HH24MISS')"
)
