UNRECOVERABLE
LOAD DATA
CHARACTERSET JA16SJIS
APPEND
PRESERVE BLANKS
INTO TABLE QPA7_KGCRIRITUT
 (QPA7_PRMHENKOYMD         POSITION(0001:0010) DATE "YYYY/MM/DD",
  QPA7_RIRITU              POSITION(0011:0017) INTEGER EXTERNAL)
