LOAD DATA
CHARACTERSET JA16SJIS
APPEND
PRESERVE BLANKS
INTO TABLE QPB3_ZNDKRRK
 (  QPB3_SYORIYMD             POSITION(0001:0008) DATE 'YYYYMMDD',
    QPB3_SYAINCD2             POSITION(0015:0021) CHAR,
    QPB3_SYUBETU              "1",
    QPB3_SYORIKBN             "1",
    QPB3_KASHITSUKE           POSITION(0027:0035) INTEGER EXTERNAL,
    QPB3_KUSNFLG              "0",
    QPB3_TURKYMD              SYSDATE,
    QPB3_KUSNYMD              SYSDATE
 )
