LOAD DATA
CHARACTERSET JA16SJIS
APPEND
PRESERVE BLANKS
INTO TABLE QPAC_SyainM (
  QPAC_PRMSYAINCD1              POSITION(0001:0001) CHAR,
  QPAC_PRMSYAINCD2              POSITION(0002:0008) CHAR,
  QPAC_SIMEIKANA                POSITION(0009:0023) CHAR NULLIF QPAC_SIMEIKANA=BLANKS,
  QPAC_SIMEIKANJI               POSITION(0024:0043) CHAR NULLIF QPAC_SIMEIKANJI=BLANKS,
  QPAC_MISECD                   POSITION(0044:0046) CHAR NULLIF QPAC_MISECD=BLANKS,
  QPAC_TOZAIKBN                 POSITION(0047:0047) CHAR NULLIF QPAC_TOZAIKBN=BLANKS,
  QPAC_BUMONCD                  POSITION(0048:0053) CHAR NULLIF QPAC_BUMONCD=BLANKS,
  QPAC_SIKAKUCD                 POSITION(0054:0055) CHAR NULLIF QPAC_SIKAKUCD=BLANKS,
  QPAC_TOKYUCD                  POSITION(0056:0057) CHAR NULLIF QPAC_TOKYUCD=BLANKS,
  QPAC_BORNYMD                  POSITION(0058:0065) DATE 'YYYYMMDD' NULLIF QPAC_BORNYMD=BLANKS,
  QPAC_TAISYOKUYMD              POSITION(0066:0073) DATE 'YYYYMMDD' NULLIF QPAC_TAISYOKUYMD=BLANKS,
  QPAC_KYUSYOSTYMD              POSITION(0074:0081) DATE 'YYYYMMDD' NULLIF QPAC_KYUSYOSTYMD=BLANKS,
  QPAC_KYUSYOEDYMD              POSITION(0082:0089) DATE 'YYYYMMDD' NULLIF QPAC_KYUSYOEDYMD=BLANKS
 )
