LOAD DATA
APPEND
PRESERVE BLANKS
INTO TABLE QTA4_GAINAICNVT
fields terminated by "q"
(
 QTA4_PRMGAIBUKAIINNO        CHAR, --  NOT NULL CHAR(16)
 QTA4_IKNKBN                 CHAR, --  NOT NULL CHAR(1)
 QTA4_IKNSAKIKAIINNO         CHAR, --  NOT NULL CHAR(16)
 QTA4_IKNKOUZAYMD            DATE NULLIF (QTA4_IKNKOUZAYMD="00000000"), --  NOT NULL DATE
 QTA4_IKNYUKOUKIGEN          CHAR, --  NOT NULL NUMBER(6)
 QTA4_IKNMOTOUSERCD1         CHAR, --  NOT NULL CHAR(1)
 QTA4_IKNMOTOUSERCD2         CHAR, --  NOT NULL CHAR(1)
 QTA4_IKNMOTOUSERCD3         CHAR, --  NOT NULL CHAR(1)
 QTA4_IKNMOTOUSERCD4         CHAR, --  NOT NULL CHAR(1)
 QTA4_IKNMOTOUSERCD5         CHAR, --  NOT NULL CHAR(1)
 QTA4_IKNMOTOUSERCD6         CHAR, --  NOT NULL CHAR(1)
 QTA4_IKNMOTOUSERCD7         CHAR, --  NOT NULL CHAR(1)
 QTA4_IKNMOTOUSERCD8         CHAR, --  NOT NULL CHAR(1)
 QTA4_IKNMOTOUSERCD9         CHAR, --  NOT NULL CHAR(1)
 QTA4_NKNKIGYOUCD            CHAR, --  NOT NULL CHAR(4)
 QTA4_NKNSUBRANGEKEY         CHAR, --  NOT NULL CHAR(4)
 QTA4_NKNNO                  CHAR, --  NOT NULL CHAR(8)
 QTA4_HOSTSHORIYMD           CHAR, --  NOT NULL CHAR(8)
 QTA4_HOSTSHORITIME          CHAR, --  NOT NULL CHAR(6)
 QTA4_SVRKOUSHINYMD          DATE NULLIF (QTA4_SvrKoushinYmd="00000000") --  DATE
)
