UNRECOVERABLE
LOAD DATA
CHARACTERSET JA16SJIS
APPEND
PRESERVE BLANKS
INTO TABLE QTA1_KAIINM
fields terminated by "q"
(
       QTA1_PRMKigyouCd      CHAR, --  CHAR(4) NOT NULL,
       QTA1_PRMSubRangeKey   CHAR, --  CHAR(4) NOT NULL,
       QTA1_PRMNaibuKaiinNo  CHAR, --  CHAR(8) NOT NULL,
       QTA1_RecKbn           CHAR, --  CHAR(1) NOT NULL,
       QTA1_ZandakaKanriKbn  CHAR, --  CHAR(1) NOT NULL,
       QTA1_KaijoKbn         CHAR, --  CHAR(1) NOT NULL,
       QTA1_10to16Kbn        CHAR, --  CHAR(1) NOT NULL,
       QTA1_GKNShikibetsuNo  CHAR, --  CHAR(12) NOT NULL,
       QTA1_GKNEdaban        CHAR, --  CHAR(1) NOT NULL,
       QTA1_TENKaisha        CHAR, --  CHAR(2) NOT NULL,
       QTA1_TENSaikenKanri   CHAR, --  CHAR(2) NOT NULL,
       QTA1_TENEigyou        CHAR, --  CHAR(2) NULL,
       QTA1_TENDM            CHAR, --  CHAR(2) NOT NULL,
       QTA1_TENJigyoHonbu    CHAR, --  CHAR(2) NOT NULL,
       QTA1_TENKakutoku      CHAR, --  CHAR(2) NOT NULL,
       QTA1_CardKbn          CHAR, --  CHAR(6) NOT NULL,
       QTA1_TRSSYoku1        CHAR, --  CHAR(1) NOT NULL,
       QTA1_TRSSYoku2        CHAR, --  CHAR(1) NOT NULL,
       QTA1_TRSSBonus1       CHAR, --  CHAR(1) NOT NULL,
       QTA1_TRSSBonus2       CHAR, --  CHAR(1) NOT NULL,
       QTA1_TRSSKappu        CHAR, --  CHAR(1) NOT NULL,
       QTA1_TRSSRevolving    CHAR, --  CHAR(1) NOT NULL,
       QTA1_TRSSHanbai       CHAR, --  CHAR(1) NOT NULL,
       QTA1_TRSSKakeuri      CHAR, --  CHAR(1) NOT NULL,
       QTA1_TRSCRevolving    CHAR, --  CHAR(1) NOT NULL,
       QTA1_TRSCYoku1        CHAR, --  CHAR(1) NOT NULL,
       QTA1_CardLoanUseKbn   CHAR, --  CHAR(1) NOT NULL,
       QTA1_HensaiHouhou     CHAR, --  CHAR(1) NOT NULL,
       QTA1_SiharaiYoteiBi   CHAR, --  NUMBER(2) NOT NULL,
       QTA1_REVSMaitsuki     CHAR, --  CHAR(1) NOT NULL,
       QTA1_REVSBonus        CHAR, --  NUMBER(2) NOT NULL,
       QTA1_REVCMaitsuki     CHAR, --  CHAR(1) NOT NULL,
       QTA1_REVCBonus        CHAR, --  NUMBER(2) NOT NULL,
       QTA1_BBKShubetsu      CHAR, --  CHAR(1) NOT NULL,
       QTA1_BBKRitsu         CHAR, --  NUMBER(2) NOT NULL,
       QTA1_ASNGen           CHAR, --  CHAR(4) NOT NULL,
       QTA1_ANSKyuu          CHAR, --  CHAR(4) NOT NULL,
       QTA1_ANSHenkouYmd     DATE NULLIF (QTA1_ANSHenkouYmd="00000000"), --  DATE NULL,
       QTA1_NYKUketsukeNo    CHAR, --  CHAR(8) NOT NULL,
       QTA1_NYKUketsukeYmd   DATE NULLIF (QTA1_NYKUketsukeYmd="00000000"), --  DATE NOT NULL,
       QTA1_NYKKessaiYmd     DATE NULLIF (QTA1_NYKKessaiYmd="00000000"), --  DATE NOT NULL,
       QTA1_YukoKigen        CHAR, --  NUMBER(6) NOT NULL,
       QTA1_KTKRoute         CHAR, --  CHAR(9) NOT NULL,
       QTA1_KTKShoukaishaCd  CHAR, --  CHAR(8) NOT NULL,
       QTA1_YSNRank          CHAR, --  CHAR(1) NOT NULL,
       QTA1_YSNSouGendo      CHAR, --  NUMBER(5) NOT NULL,
       QTA1_YSNNobeGendo     CHAR, --  NUMBER(5) NOT NULL,
       QTA1_YSNKyuBonusGendo CHAR, --  NUMBER(5) NOT NULL,
       QTA1_YSNCashGendo     CHAR, --  NUMBER(5) NOT NULL,
       QTA1_YSNIkkatsuGendo  CHAR, --  NUMBER(5) NOT NULL,
       QTA1_YSNKappuGendo    CHAR, --  NUMBER(5) NOT NULL,
       QTA1_YSNBonusGendo    CHAR, --  NUMBER(5) NOT NULL,
       QTA1_YSNYukoKaishi    DATE NULLIF (QTA1_YSNYukoKaishi="00000000"), --  DATE NULL,
       QTA1_YSNYukoOwari     DATE NULLIF (QTA1_YSNYukoOwari="00000000"), --  DATE NULL,
       QTA1_CIFDouitsuNinNo  CHAR, --  CHAR(7) NOT NULL,
       QTA1_CIFNo            CHAR, --  CHAR(8) NOT NULL,
       QTA1_CIFShoukaiNo     CHAR, --  NUMBER(18) NOT NULL,
       QTA1_HONShimeiKana    CHAR, --  VARCHAR2(30) NULL,
       QTA1_HONShimeiRoma    CHAR, --  VARCHAR2(30) NULL,
       QTA1_HONShimeiKan     CHAR, --  VARCHAR2(30) NULL,
       QTA1_HONSeinengappi   DATE NULLIF (QTA1_HONSeinengappi="00000000"), --  DATE NULL,
       QTA1_HONSex           CHAR, --  CHAR(1) NOT NULL,
       QTA1_JTKTelShigai     CHAR, --  CHAR(7) NOT NULL,
       QTA1_JTKTelKyoku      CHAR, --  CHAR(4) NOT NULL,
       QTA1_JTKTelNo         CHAR, --  CHAR(4) NOT NULL,
       QTA1_JTKJushoCd       CHAR, --  CHAR(11) NOT NULL,
       QTA1_JTKYuubinNo      CHAR, --  CHAR(7) NOT NULL,
       QTA1_JTKKenKana       CHAR, --  VARCHAR2(8) NULL,
       QTA1_JTKJushoKana     CHAR, --  VARCHAR2(42) NULL,
       QTA1_JTKBanchiKana    CHAR, --  VARCHAR2(15) NULL,
       QTA1_JTKKataKana      CHAR, --  VARCHAR2(32) NULL,
       QTA1_JTKJushoKan      CHAR, --  VARCHAR2(50) NULL,
       QTA1_JTKBanchiKan     CHAR, --  VARCHAR2(30) NULL,
       QTA1_JTKKataKan       CHAR, --  VARCHAR2(64) NULL,
       QTA1_KOZHenkouYmd     DATE NULLIF (QTA1_KOZHenkouYmd="00000000"), --  DATE NULL,
       QTA1_KOZGinkouCd      CHAR, --  CHAR(4) NOT NULL,
       QTA1_KOZGinkouMei     CHAR, --  VARCHAR2(20) NULL,
       QTA1_KOZShitenCd      CHAR, --  CHAR(5) NOT NULL,
       QTA1_KOZShitenMei     CHAR, --  VARCHAR2(20) NULL,
       QTA1_KOZShumoku       CHAR, --  CHAR(1) NOT NULL,
       QTA1_KOZNo            CHAR, --  CHAR(8) NOT NULL,
       QTA1_KOZMeigi         CHAR, --  VARCHAR2(30) NULL,
       QTA1_ClubCd           CHAR, --  CHAR(2) NOT NULL,
       QTA1_STSKozaTorokuYmd DATE NULLIF (QTA1_STSKozaTorokuYmd="00000000"), --  DATE NULL,
       QTA1_STSKoza          CHAR, --  CHAR(4) NOT NULL,
       QTA1_STSCardTorokuYmd DATE NULLIF (QTA1_STSCardTorokuYmd="00000000"), --  DATE NULL,
       QTA1_STSCard          CHAR, --  CHAR(4) NOT NULL,
       QTA1_EDJRiyoushaCd1   CHAR, --  CHAR(1) NOT NULL,
       QTA1_EDJJikoYmd1      DATE NULLIF (QTA1_EDJJikoYmd1="00000000"), --  DATE NULL,
       QTA1_EDJCardJyokyo1   CHAR, --  CHAR(4) NOT NULL,
       QTA1_EDJRiyoushaCd2   CHAR, --  CHAR(1) NOT NULL,
       QTA1_EDJJikoYmd2      DATE NULLIF (QTA1_EDJJikoYmd2="00000000"), --  DATE NULL,
       QTA1_EDJCardJyokyo2   CHAR, --  CHAR(4) NOT NULL,
       QTA1_EDJRiyoushaCd3   CHAR, --  CHAR(1) NOT NULL,
       QTA1_EDJJikoYmd3      DATE NULLIF (QTA1_EDJJikoYmd3="00000000"), --  DATE NULL,
       QTA1_EDJCardJyokyo3   CHAR, --  CHAR(4) NOT NULL,
       QTA1_EDJRiyoushaCd4   CHAR, --  CHAR(1) NOT NULL,
       QTA1_EDJJikoYmd4      DATE NULLIF (QTA1_EDJJikoYmd4="00000000"), --  DATE NULL,
       QTA1_EDJCardJyokyo4   CHAR, --  CHAR(4) NOT NULL,
       QTA1_EDJRiyoushaCd5   CHAR, --  CHAR(1) NOT NULL,
       QTA1_EDJJikoYmd5      DATE NULLIF (QTA1_EDJJikoYmd5="00000000"), --  DATE NULL,
       QTA1_EDJCardJyokyo5   CHAR, --  CHAR(4) NOT NULL,
       QTA1_EDJRiyoushaCd6   CHAR, --  CHAR(1) NOT NULL,
       QTA1_EDJJikoYmd6      DATE NULLIF (QTA1_EDJJikoYmd6="00000000"), --  DATE NULL,
       QTA1_EDJCardJyokyo6   CHAR, --  CHAR(4) NOT NULL,
       QTA1_EDJRiyoushaCd7   CHAR, --  CHAR(1) NOT NULL,
       QTA1_EDJJikoYmd7      DATE NULLIF (QTA1_EDJJikoYmd7="00000000"), --  DATE NULL,
       QTA1_EDJCardJyokyo7   CHAR, --  CHAR(4) NOT NULL,
       QTA1_EDJRiyoushaCd8   CHAR, --  CHAR(1) NOT NULL,
       QTA1_EDJJikoYmd8      DATE NULLIF (QTA1_EDJJikoYmd8="00000000"), --  DATE NULL,
       QTA1_EDJCardJyokyo8   CHAR, --  CHAR(4) NOT NULL,
       QTA1_EDJRiyoushaCd9   CHAR, --  CHAR(1) NOT NULL,
       QTA1_EDJJikoYmd9      DATE NULLIF (QTA1_EDJJikoYmd9="00000000"), --  DATE NULL,
       QTA1_EDJCardJyokyo9   CHAR, --  CHAR(4) NOT NULL,
       QTA1_SOHCard          CHAR, --  CHAR(1) NOT NULL,
       QTA1_SOHSeikyu        CHAR, --  CHAR(1) NOT NULL,
       QTA1_CDHHakkouKbn     CHAR, --  CHAR(1) NOT NULL,
       QTA1_CDHYusoKbn       CHAR, --  CHAR(1) NOT NULL,
       QTA1_CDHYmd           DATE NULLIF (QTA1_CDHYmd="00000000"), --  DATE NULL,
       QTA1_CDHYuchoSaiHatu  CHAR, --  CHAR(1) NOT NULL,
       QTA1_KIKYmd           DATE NULLIF (QTA1_KIKYmd="00000000"), --  DATE NULL,
       QTA1_KIKKyuuNo        CHAR, --  CHAR(12) NOT NULL,
       QTA1_KIK10KetaNo      CHAR, --  CHAR(10) NOT NULL,
       QTA1_TKSHenreiYmd     DATE NULLIF (QTA1_TKSHenreiYmd="00000000"), --  DATE NULL,
       QTA1_TKSCardNo        CHAR, --  CHAR(16) NOT NULL,
       QTA1_TKSKekkaCd       CHAR, --  CHAR(1) NOT NULL,
       QTA1_TKSRiyuCd        CHAR, --  CHAR(3) NOT NULL,
       QTA1_EDBSaishuRiyou   CHAR, --  CHAR(1) NOT NULL,
       QTA1_EDBYukoMuko1     CHAR, --  CHAR(1) NOT NULL,
       QTA1_EDBYukoMuko2     CHAR, --  CHAR(1) NOT NULL,
       QTA1_EDBYukoMuko3     CHAR, --  CHAR(1) NOT NULL,
       QTA1_EDBYukoMuko4     CHAR, --  CHAR(1) NOT NULL,
       QTA1_EDBYukoMuko5     CHAR, --  CHAR(1) NOT NULL,
       QTA1_EDBYukoMuko6     CHAR, --  CHAR(1) NOT NULL,
       QTA1_EDBYukoMuko7     CHAR, --  CHAR(1) NOT NULL,
       QTA1_EDBYukoMuko8     CHAR, --  CHAR(1) NOT NULL,
       QTA1_EDBYukoMuko9     CHAR, --  CHAR(1) NOT NULL,
       QTA1_ATUKakari        CHAR, --  CHAR(6) NOT NULL,
       QTA1_ATUKoushinMae    CHAR, --  CHAR(6) NOT NULL,
       QTA1_ATUHenkouYmd     DATE NULLIF (QTA1_ATUHenkouYmd="00000000"), --  DATE NULL,
       QTA1_PNTShinNo        CHAR, --  NUMBER(4) NOT NULL,
       QTA1_PNTKyuuNo        CHAR, --  NUMBER(4) NOT NULL,
       QTA1_PNTHenkouYmd     DATE NULLIF (QTA1_PNTHenkouYmd="00000000"), --  DATE NULL,
       QTA1_PNTKbn           CHAR, --  CHAR(1) NOT NULL,
       QTA1_PNTCardFace      CHAR, --  CHAR(1) NOT NULL,
       QTA1_PNTTeikeiKbn     CHAR, --  CHAR(1) NOT NULL,
       QTA1_IkanmaeCardKbn   CHAR, --  CHAR(6) NOT NULL,
       QTA1_KMSKbn           CHAR, --  CHAR(1) NOT NULL,
       QTA1_KMSMeiKana       CHAR, --  VARCHAR2(30) NULL,
       QTA1_KMSMeiKan        CHAR, --  VARCHAR2(60) NULL,
       QTA1_KMSBuka          CHAR, --  VARCHAR2(30) NULL,
       QTA1_KMSTelShigai     CHAR, --  CHAR(7) NOT NULL,
       QTA1_KMSTelKyoku      CHAR, --  CHAR(4) NOT NULL,
       QTA1_KMSTelNo         CHAR, --  CHAR(4) NOT NULL,
       QTA1_KMSJushoCd       CHAR, --  CHAR(11) NOT NULL,
       QTA1_KMSYuubinNo      CHAR, --  CHAR(7) NOT NULL,
       QTA1_KMSKenKana       CHAR, --  VARCHAR2(8) NULL,
       QTA1_KMSJushoKana     CHAR, --  VARCHAR2(42) NULL,
       QTA1_KMSBanchiKana    CHAR, --  VARCHAR2(15) NULL,
       QTA1_KMSKataKana      CHAR, --  VARCHAR2(32) NULL,
       QTA1_KMSJushoKan      CHAR, --  VARCHAR2(50) NULL,
       QTA1_KMSBanchiKan     CHAR, --  VARCHAR2(30) NULL,
       QTA1_KMSKataKan       CHAR, --  VARCHAR2(64) NULL,
       QTA1_HostShoriYmd     CHAR, --  CHAR(8) NOT NULL,
       QTA1_HostShoriTime    CHAR, --  CHAR(6) NOT NULL,
       QTA1_SvrKoushinYmd    DATE NULLIF (QTA1_SvrKoushinYmd="00000000") --  DATE NULL,
)

