LOAD DATA
CHARACTERSET JA16SJIS
TRUNCATE
PRESERVE BLANKS
INTO TABLE QTAJ_POINTCTRLM
fields terminated by "q"
(
    QTAJ_PRMKIGYOUCD         CHAR, -- CHAR(4) NOT NULL,
    QTAJ_PRMSUBRANGEKEY      CHAR, -- CHAR(4) NOT NULL,
    QTAJ_PRMNAIBUKAIINNO     CHAR, -- CHAR(8) NOT NULL,
    QTAJ_PRMRECKBN           CHAR, -- CHAR(1) NOT NULL,
    QTAJ_ZOKTUMITATEYUKO     DATE NULLIF (QTAJ_ZOKTUMITATEYUKO="00000000"),  --  DATE NULL,
    QTAJ_ZOKHIKIKAEYUKO      DATE NULLIF (QTAJ_ZOKHIKIKAEYUKO="00000000"),  --  DATE NULL,
    QTAJ_ZOKTORIKESITUUBAN   CHAR, -- NUMBER(7) NOT NULL,
    QTAJ_TOKTKURIKOSIPOINT   CHAR, -- NUMBER(11) NOT NULL,
    QTAJ_TOKTHASSEIPOINT     CHAR, -- NUMBER(11) NOT NULL,
    QTAJ_TOKTHIKIKAEPOINT    CHAR, -- NUMBER(11) NOT NULL,
    QTAJ_TOKTTORIKESIPOINT   CHAR, -- NUMBER(11) NOT NULL,
    QTAJ_TOKTZANPOINT        CHAR, -- NUMBER(11) NOT NULL,
    QTAJ_TOKSHASSEIPOINT     CHAR, -- NUMBER(11) NOT NULL,
    QTAJ_TOKSHIKIKAEPOINT    CHAR, -- NUMBER(11) NOT NULL,
    QTAJ_TOKSTORIKESIPOINT   CHAR, -- NUMBER(11) NOT NULL,
    QTAJ_TOKRHASSEIPOINT     CHAR, -- NUMBER(11) NOT NULL,
    QTAJ_TOKRHIKIKAEPOINT    CHAR, -- NUMBER(11) NOT NULL,
    QTAJ_KIGMKIGENGIREFLG    CHAR, -- CHAR(1) NOT NULL,
    QTAJ_KIGMTUMITATEYUKO    DATE NULLIF (QTAJ_KIGMTUMITATEYUKO="00000000"),  --  DATE NULL,
    QTAJ_KIGMHIKIKAEYUKO     DATE NULLIF (QTAJ_KIGMHIKIKAEYUKO="00000000"),  --  DATE NULL,
    QTAJ_KIGMKIGENGIREPOINT  CHAR, -- NUMBER(11) NOT NULL, 
    QTAJ_KIGMHIKIKAEPOINT    CHAR, -- NUMBER(11) NOT NULL,
    QTAJ_KIGMTORIKESIPOINT   CHAR, -- NUMBER(11) NOT NULL,
    QTAJ_HIKIKAEANSYOUNO     CHAR, -- CHAR(4) NOT NULL,
    QTAJ_SEIKYUNENGETU       CHAR, -- NUMBER(6) NOT NULL,
    QTAJ_HOSTSHORIYMD        CHAR, -- CHAR(8) NOT NULL,
    QTAJ_HOSTSHORITIME       CHAR, -- CHAR(6) NOT NULL,
    QTAJ_SVRKOUSHINYMD       DATE NULLIF (QTAJ_SVRKOUSHINYMD="00000000") --  DATE NULL,
) 
