LOAD DATA
CHARACTERSET JA16SJIS
APPEND
PRESERVE BLANKS
INTO TABLE QTAC_BLACKT
fields terminated by "q"
(
 QTAC_PRMBlackNo               CHAR, -- CHAR(8) NOT NULL,
 QTAC_TENEigyouCd              CHAR, -- CHAR(2) NOT NULL,
 QTAC_TENKakutoku              CHAR, -- CHAR(2) NOT NULL,
 QTAC_TourokuYmd               DATE NULLIF(QTAC_TourokuYmd="00000000"), -- DATE NULL,
 QTAC_TourokuKbn               CHAR, -- CHAR(1) NOT NULL,
 QTAC_BlackRiyu                CHAR, -- CHAR(2) NOT NULL,
 QTAC_BlackRiyuTuiki           CHAR, -- VARCHAR2(20) NULL,
 QTAC_UketsukeNo               CHAR, -- CHAR(8) NOT NULL,
 QTAC_KaiinNo                  CHAR, -- CHAR(12) NOT NULL,
 QTAC_HONShimeiKana            CHAR, -- VARCHAR2(30) NULL,
 QTAC_HONShimeiKan             CHAR, -- VARCHAR2(30) NULL,
 QTAC_HONSeinengappi           DATE NULLIF(QTAC_HONSeinengappi="00000000"), -- DATE NULL,
 QTAC_HONSex                   CHAR, -- CHAR(1) NOT NULL,
 QTAC_YubinNo                  CHAR, -- VARCHAR2(7) NULL,
 QTAC_Chiban                   CHAR, -- CHAR(3) NOT NULL,
 QTAC_JTKTelShigai             CHAR, -- VARCHAR2(7) NULL,
 QTAC_JTKTelKyoku              CHAR, -- VARCHAR2(4) NULL,
 QTAC_JTKTelNo                 CHAR, -- CHAR(4) NOT NULL,
 QTAC_JTKJushoCd               CHAR, -- CHAR(11) NOT NULL,
 QTAC_JTKBanchiKana            CHAR, -- VARCHAR2(15) NULL,
 QTAC_JTKKataKana              CHAR, -- VARCHAR2(32) NULL,
 QTAC_JTKBanchiKan             CHAR, -- VARCHAR2(30) NULL,
 QTAC_JTKKataKan               CHAR, -- VARCHAR2(64) NULL,
 QTAC_KMSKbn                   CHAR, -- CHAR(1) NOT NULL,
 QTAC_KMSTelShigai             CHAR, -- VARCHAR2(7) NULL,
 QTAC_KMSTelKyoku              CHAR, -- VARCHAR2(4) NULL,
 QTAC_KMSTelNo                 CHAR, -- VARCHAR2(4) NULL,
 QTAC_KMSMeiKana               CHAR, -- VARCHAR2(30) NULL,
 QTAC_KMSMeiKan                CHAR, -- VARCHAR2(30) NULL,
 QTAC_KMSJushoCd               CHAR, -- CHAR(11) NOT NULL,
 QTAC_KMSBanchiKana            CHAR, -- VARCHAR2(15) NULL,
 QTAC_KMSKataKana              CHAR, -- VARCHAR2(32) NULL,
 QTAC_KMSBanchiKan             CHAR, -- VARCHAR2(30) NULL,
 QTAC_KMSKataKan               CHAR, -- VARCHAR2(64) NULL,
 QTAC_CifNo                    CHAR, -- CHAR(8) NOT NULL,
 QTAC_CardKbn                  CHAR, -- CHAR(6) NOT NULL,
 QTAC_CDSKNName                CHAR, -- VARCHAR2(30) NULL,
 QTAC_CDSKNKinName             CHAR, -- VARCHAR2(30) NULL,
 QTAC_CDSJitakuTel             CHAR, -- VARCHAR2(14) NULL,
 QTAC_CDSKinTel                CHAR, -- VARCHAR2(14) NULL,
 QTAC_HostShoriYmd             CHAR, -- CHAR(8) NOT NULL,
 QTAC_HostShoriTime            CHAR, -- CHAR(6) NOT NULL,
 QTAC_SvrKoushinYmd            DATE NULLIF(QTAC_SvrKoushinYmd="00000000") -- DATE NULL,
) 
