LOAD DATA
CHARACTERSET JA16SJIS
APPEND
PRESERVE BLANKS
INTO TABLE WKQSA1_JIHURIHENT
fields terminated by ":"
(
 QSA1_PRMKIGYOUCD            CHAR, --  NOT NULL CHAR(4)
 QSA1_PRMSUBRENGEKEY         CHAR, --  NOT NULL CHAR(4)
 QSA1_PRMNAIBUKAIINNO        CHAR, --  NOT NULL CHAR(8)
 QSA1_SEIKYUNENGETSU         CHAR, --  NOT NULL NUMBER(6)
 QSA1_GINKOUCD               CHAR, --  NOT NULL CHAR(4)
 QSA1_SHITENCD               CHAR, --  NOT NULL CHAR(5)
 QSA1_YOKINSHUBETSU          CHAR, --  NOT NULL CHAR(1)
 QSA1_KOUZANO                CHAR, --  NOT NULL CHAR(8)
 QSA1_KOUZAMEIGININ          CHAR, --  NOT NULL CHAR(30)
 QSA1_HURIKAEKEKKACD         CHAR, --  NOT NULL CHAR(1)
 QSA1_YUCHOSAIHATU           CHAR, --  NOT NULL CHAR(1)
 QSA1_HOSTSHORIYMD           CHAR, --  NOT NULL CHAR(8)
 QSA1_HOSTSHORITIME          CHAR, --  NOT NULL CHAR(6)
 QSA1_SVRKOUSHINYMD          DATE NULLIF (QSA1_SVRKOUSHINYMD="00000000") --  DATE
)
