LOAD DATA
CHARACTERSET JA16SJIS
APPEND
PRESERVE BLANKS
INTO TABLE QTA3_KAIINRIREKIT
(
 QTA3_PRMKIGYOUCD            POSITION(   1:   4)  CHAR, --  NOT NULL CHAR(4)
 QTA3_PRMSUBRANGEKEY         POSITION(   5:   8)  CHAR, --  NOT NULL CHAR(4)
 QTA3_PRMNAIBUKAIINNO        POSITION(   9:  16)  CHAR, --  NOT NULL CHAR(8)
 QTA3_PRMSYORIYMD            POSITION(  17:  24)  DATE, --  NULLIF (QTA3_PRMSYORIYMD="00000000"), --  DATE NOT NULL,
 QTA3_PRMSYORITIME           POSITION(  25:  32)  CHAR, --  NOT NULL NUMBER(8)
 QTA3_PRMSEQ                 POSITION(  33:  35)  CHAR, --  NOT NULL NUMBER(3)
 QTA3_KOUMOKUNO              POSITION(  36:  38)  CHAR, --  NOT NULL CHAR(3)
 QTA3_TANTCD                 POSITION(  39:  45)  CHAR, --  NOT NULL CHAR(7)
 QTA3_HENKOURIREKI           POSITION(  46: 172)  CHAR, --  TERMINATED BY "," "SUBSTR(:QTA3_HENKOURIREKI,1,128)"  --                             VARCHAR(115)(127)
 QTA3_SVRKOUSHINYMD          POSITION( 173: 180)  DATE NULLIF (QTA3_SVRKOUSHINYMD="00000000")  --  DATE NOT NULL
)
