LOAD DATA
CHARACTERSET JA16SJIS
APPEND
PRESERVE BLANKS
INTO TABLE QTA2_KAIINKAZOKM
fields terminated by "q"
(
 QTA2_PRMKIGYOUCD            CHAR, --  NOT NULL CHAR(4)
 QTA2_PRMSUBRANGEKEY         CHAR, --  NOT NULL CHAR(4)
 QTA2_PRMNAIBUKAIINNO        CHAR, --  NOT NULL CHAR(8)
 QTA2_PRMRIYOUSHACD          CHAR, --  NOT NULL CHAR(1)
 QTA2_NYUKAIYMD              DATE NULLIF (QTA2_NYUKAIYMD="00000000"), --  NOT NULL DATE
 QTA2_KZKSHIMEIKANA          CHAR, --  VARCHAR2(15)
 QTA2_KZKSHIMEIROMA          CHAR, --  VARCHAR2(30)
 QTA2_KZKSHIMEIKAN           CHAR, --  VARCHAR2(30)
 QTA2_KZKSEINENGAPPI         DATE NULLIF (QTA2_KZKSEINENGAPPI="00000000"), --  DATE
 QTA2_KZKSEX                 CHAR, --  NOT NULL CHAR(1)
 QTA2_KZKZOKUGARA            CHAR, --  NOT NULL CHAR(1)
 QTA2_CDHHAKKOUKBN           CHAR, --  NOT NULL CHAR(1)
 QTA2_CDHYMD                 DATE NULLIF (QTA2_CDHYMD="00000000"), --  NOT NULL DATE
 QTA2_CIFNO                  CHAR, --  NOT NULL CHAR(8)
 QTA2_EDABAN                 CHAR, --  NOT NULL CHAR(1)
 QTA2_TKSHENREIYMD           DATE NULLIF (QTA2_TKSHENREIYMD="00000000"), --  DATE
 QTA2_TKSRIYUCD              CHAR, --  NOT NULL CHAR(3)
 QTA2_TKSCARDNO              CHAR, --  NOT NULL CHAR(16)
 QTA2_ANSGEN                 CHAR, --  NOT NULL CHAR(4)
 QTA2_ANSKYUU                CHAR, --  NOT NULL CHAR(4)
 QTA2_ANSHENKOUYMD           DATE NULLIF (QTA2_ANSHENKOUYMD="00000000"), --  DATE
 QTA2_CLUBCD                 CHAR, --  NOT NULL CHAR(2)
 QTA2_STSTOUROKUYMD          DATE NULLIF (QTA2_STSTOUROKUYMD="00000000"), --  DATE
 QTA2_STS                    CHAR, --  NOT NULL CHAR(4)
 QTA2_HOSTSHORIYMD           CHAR, --  NOT NULL CHAR(8)
 QTA2_HOSTSHORITIME          CHAR, --  NOT NULL CHAR(6)
 QTA2_SVRKOUSHINYMD          DATE NULLIF (QTA2_SVRKOUSHINYMD="00000000") --  DATE
)

