LOAD DATA
CHARACTERSET JA16SJIS
APPEND
PRESERVE BLANKS
INTO TABLE QTAV_KAZOKURIREKIT
(
 QTAV_PRMKIGYOUCD            POSITION(   1:   4)  CHAR, --  NOT NULL CHAR(4)
 QTAV_PRMSUBRANGEKEY         POSITION(   5:   8)  CHAR, --  NOT NULL CHAR(4)
 QTAV_PRMNAIBUKAIINNO        POSITION(   9:  16)  CHAR, --  NOT NULL CHAR(8)
 QTAV_PRMRIYOUSHACD          POSITION(  17:  17)  CHAR, --  NOT NULL CHAR(1)
 QTAV_PRMSYORIYMD            POSITION(  18:  25)  DATE, --  NULLIF (QTAV_PRMSYORIYMD="00000000"), --  DATE NOT NULL,
 QTAV_PRMSYORITIME           POSITION(  26:  33)  CHAR, --  NOT NULL NUMBER(8)
 QTAV_PRMSEQ                 POSITION(  34:  36)  CHAR, --  NOT NULL NUMBER(3)
 QTAV_KOUMOKUNO              POSITION(  37:  39)  CHAR, --  NOT NULL CHAR(3)
 QTAV_TANTCD                 POSITION(  40:  46)  CHAR, --  NOT NULL CHAR(7)
 QTAV_HENKOURIREKI           POSITION(  47: 146)  CHAR, --  TERMINATED BY "," "SUBSTR(:QTA3_HENKOURIREKI,1,128)"  --                             VARCHAR(115)(100)
 QTAV_SVRKOUSHINYMD          POSITION( 147: 154)  DATE NULLIF (QTAV_SVRKOUSHINYMD="00000000")  --  DATE NOT NULL
)
