LOAD DATA
CHARACTERSET JA16SJIS
TRUNCATE
PRESERVE BLANKS
INTO TABLE QTA5_ATUKAISYAM
fields terminated by "q"
(
 QTA5_PRMSHOZOKUTEN          CHAR, --  NOT NULL CHAR(2)
 QTA5_PRMATUKAIKAKARI        CHAR, --  NOT NULL CHAR(6)
 QTA5_CC                     CHAR, --  NOT NULL CHAR(4)
 QTA5_MSTNEN                 CHAR, --  NOT NULL CHAR(4)
 QTA5_MSTKI                  CHAR, --  NOT NULL CHAR(1)
 QTA5_TOUROKUYMD             DATE NULLIF (QTA5_TOUROKUYMD="00000000"), --  DATE
 QTA5_KOUSHINYMD             DATE NULLIF (QTA5_KOUSHINYMD="00000000"), --  DATE
 QTA5_KMTMISE                CHAR, --  NOT NULL CHAR(2)
 QTA5_ATUBUMON               CHAR, --  NOT NULL CHAR(2)
 QTA5_BLOCK                  CHAR, --  NOT NULL CHAR(2)
 QTA5_TOUZAIKBN              CHAR, --  NOT NULL CHAR(1)
 QTA5_TANTOUKAN              CHAR, --  VARCHAR2(12)
 QTA5_TANTOUKANA             CHAR, --  VARCHAR2(12)
 QTA5_SAKUJOYMD              DATE NULLIF (QTA5_SAKUJOYMD="00000000"), --  DATE
 QTA5_ATUBUMEI               CHAR, --  VARCHAR2(24)
 QTA5_ATUBUKAMEI             CHAR, --  VARCHAR2(24)
 QTA5_HOSTSHORIYMD           CHAR, --  NOT NULL CHAR(8)
 QTA5_HOSTSHORITIME          CHAR, --  NOT NULL CHAR(6)
 QTA5_SVRKOUSHINYMD          DATE NULLIF (QTA5_SVRKOUSHINYMD="00000000")  --  DATE
)
