LOAD DATA
CHARACTERSET JA16SJIS
TRUNCATE
PRESERVE BLANKS
INTO TABLE QTAP_KAMEITENZT
FIELDS TERMINATED BY "q"
(
       QTAP_PRMNaibuNo      CHAR, -- CHAR(7) NOT NULL,
       QTAP_KanaMeisho      CHAR, -- CHAR(10) NOT NULL,
       QTAP_KaishaCd        CHAR, -- CHAR(5) NOT NULL,
       QTAP_HanbaiTenCd     CHAR, -- CHAR(4) NOT NULL,
       QTAP_CheckDigit      CHAR, -- CHAR(1) NOT NULL,
       QTAP_SiharaiSakiNo   CHAR, -- CHAR(7) NOT NULL,
       QTAP_KameiYmd        DATE NULLIF(QTAP_KameiYmd="00000000"), -- DATE NULL,
       QTAP_TorikesiBi      DATE NULLIF(QTAP_TorikesiBi="00000000"), -- DATE NULL,
       QTAP_KameiTenKbn     CHAR, -- CHAR(1) NOT NULL,
       QTAP_KameiTenKaku    CHAR, -- CHAR(1) NOT NULL,
       QTAP_KakutokuTen     CHAR, -- CHAR(2) NOT NULL,
       QTAP_GyoshuCd        CHAR, -- CHAR(2) NOT NULL,
       QTAP_GyoshuRenban    CHAR, -- NUMBER(3) NOT NULL,
       QTAP_MeishoAtama     CHAR, -- CHAR(2) NOT NULL,
       QTAP_MeishoShita     CHAR, -- CHAR(2) NOT NULL,
       QTAP_ShameiKana      CHAR, -- CHAR(30) NOT NULL,
       QTAP_ShameiKan       CHAR, -- VARCHAR2(40) NULL,
       QTAP_DaihyoshaKana   CHAR, -- CHAR(30) NOT NULL,
       QTAP_DaihyoshaKan    CHAR, -- VARCHAR2(40) NULL,
       QTAP_JushoCd         CHAR, -- CHAR(10) NOT NULL,
       QTAP_Yubin1          CHAR, -- CHAR(3) NOT NULL,
       QTAP_Yubin2          CHAR, -- CHAR(2) NOT NULL,
       QTAP_JushoKan1       CHAR, -- VARCHAR2(40) NULL,
       QTAP_JushoKan2       CHAR, -- VARCHAR2(40) NULL,
       QTAP_BanchiKan       CHAR, -- VARCHAR2(20) NULL,
       QTAP_KataKan         CHAR, -- VARCHAR2(40) NULL,
       QTAP_DaihyoTelNo     CHAR, -- CHAR(15) NOT NULL,
       QTAP_RENTantoBuka    CHAR, -- VARCHAR2(20) NULL,
       QTAP_RENTantoSha     CHAR, -- VARCHAR2(20) NULL,
       QTAP_RENTelNo        CHAR, -- CHAR(15) NOT NULL,
       QTAP_RENNaisen       CHAR, -- CHAR(4) NOT NULL,
       QTAP_MukoHyoBusuu    CHAR, -- NUMBER(3) NOT NULL,
       QTAP_Kyuujitu        CHAR, -- CHAR(1) NOT NULL,
       QTAP_MemoJoho        CHAR, -- VARCHAR2(60) NULL,
       QTAP_KigyouCd        CHAR, -- CHAR(4) NOT NULL,
       QTAP_HANSeikyuKana   CHAR, -- CHAR(15) NOT NULL,
       QTAP_HANHinban       CHAR, -- CHAR(6) NOT NULL,
       QTAP_HANAtena        CHAR, -- VARCHAR2(40) NULL,
       QTAP_HANCATTermUmu   CHAR, -- CHAR(1) NOT NULL,
       QTAP_HANEigyoTime    CHAR, -- CHAR(8) NOT NULL,
       QTAP_HANRank         CHAR, -- CHAR(1) NOT NULL,
       QTAP_HANKakutokuTen  CHAR, -- CHAR(2) NOT NULL,
       QTAP_HANKakutokuSha  CHAR, -- CHAR(7) NOT NULL,
       QTAP_HANHibaihinUmu  CHAR, -- CHAR(1) NOT NULL,
       QTAP_HANMitorokuFlg  CHAR, -- CHAR(1) NOT NULL,
       QTAP_HostShoriYmd    CHAR, -- CHAR(8) NOT NULL,
       QTAP_HostShoriTime   CHAR, -- CHAR(6) NOT NULL,
       QTAP_SvrKoushinYmd   DATE NULLIF(QTAP_SvrKoushinYmd="00000000"), -- DATE NULL,
--20010803óXï÷î‘çÜÇVåÖâªëŒâû
       QTAP_NEWYubin1       CHAR, -- CHAR(3) NOT NULL,
       QTAP_NEWYubin2       CHAR  -- CHAR(4) NOT NULL,
--20010803óXï÷î‘çÜÇVåÖâªëŒâû
)
