LOAD DATA
CHARACTERSET JA16SJIS
TRUNCATE
PRESERVE BLANKS
INTO TABLE QTAY_RIYOUKAIINM
FIELDS TERMINATED BY "q"
(
	QTAY_PRMKIGYOUCD		CHAR,	-- CHAR(04)	NOT NULL 主キー・企業コード
	QTAY_PRMSUBRANGEKEY		CHAR,	-- CHAR(04)	NOT NULL 主キー・サブレンジキー
	QTAY_PRMNAIBUKAIINNO		CHAR,	-- CHAR(08)	NOT NULL 主キー・内部会員番号
	QTAY_PRMSYUKEINENGETU		CHAR,	-- CHAR(06)	NOT NULL 主キー・集計年
	QTAY_KANRITEN			CHAR,	-- CHAR(02)	NOT NULL 管理店
	QTAY_CORDKBN			CHAR,	-- CHAR(06)	NOT NULL カード区分
	QTAY_SYUKEICYUNENDO		CHAR,	-- CHAR(04)	NOT NULL 集計中年度
	QTAY_RUISEKIGAKU		CHAR,	-- NUMBER(13,0)	NOT NULL 累積額
	QTAY_RAITENNISSU		CHAR,	-- NUMBER(3,0)	NOT NULL 来店日数
	QTAY_RIYOUKENSUU		CHAR,	-- NUMBER(5,0)	NOT NULL 利用件数
	QTAY_PUREMIAMUKBN1		CHAR,	-- CHAR(01)	NOT NULL プレミアム区分１
	QTAY_RUISEKIGAKU1		CHAR,	-- NUMBER(13,0)	NOT NULL 累積額１
	QTAY_RAITENNISSU1		CHAR,	-- NUMBER(3,0)	NOT NULL 来店日数１
	QTAY_RIYOUKENSUU1		CHAR,	-- NUMBER(5,0)	NOT NULL 利用件数１
	QTAY_HANTEISTATUS1		CHAR,	-- CHAR(01)	NOT NULL 判定時ステータス１
	QTAY_HANTEIBI1			CHAR,	-- CHAR(08)	NOT NULL 判定日１
	QTAY_PUREMIAMUKBN2		CHAR,	-- CHAR(01)	NOT NULL プレミアム区分２
	QTAY_RUISEKIGAKU2		CHAR,	-- NUMBER(13,0)	NOT NULL 累積額２
	QTAY_RAITENNISSU2		CHAR,	-- NUMBER(3,0)	NOT NULL 来店日数２
	QTAY_RIYOUKENSUU2		CHAR,	-- NUMBER(5,0)	NOT NULL 利用件数２
	QTAY_HANTEISTATUS2		CHAR,	-- CHAR(01)	NOT NULL 判定時ステータス２
	QTAY_HANTEIBI2			CHAR,	-- CHAR(08)	NOT NULL 判定日２
	QTAY_PUREMIAMUKBN3		CHAR,	-- CHAR(01)	NOT NULL プレミアム区分３
	QTAY_RUISEKIGAKU3		CHAR,	-- NUMBER(13)	NOT NULL 累積額３
	QTAY_RAITENNISSU3		CHAR,	-- NUMBER(3,0)	NOT NULL 来店日数３
	QTAY_RIYOUKENSUU3		CHAR,	-- NUMBER(5,0)	NOT NULL 利用件数３
	QTAY_HANTEISTATUS3		CHAR,	-- CHAR(01)	NOT NULL 判定時ステータス３
	QTAY_HANTEIBI3			CHAR,	-- CHAR(08)	NOT NULL 判定日３
	QTAY_PUREMIAMUKBN4		CHAR,	-- CHAR(01)	NOT NULL プレミアム区分４
	QTAY_RUISEKIGAKU4		CHAR,	-- NUMBER(13,0)	NOT NULL 累積額４
	QTAY_RAITENNISSU4		CHAR,	-- NUMBER(3,0)	NOT NULL 来店日数４
	QTAY_RIYOUKENSUU4		CHAR,	-- NUMBER(5,0)	NOT NULL 利用件数４
	QTAY_HANTEISTATUS4		CHAR,	-- CHAR(01)	NOT NULL 判定時ステータス４
	QTAY_HANTEIBI4			CHAR,	-- CHAR(08)	NOT NULL 判定日４
	QTAY_PUREMIAMUKBN5		CHAR,	-- CHAR(01)	NOT NULL プレミアム区分５
	QTAY_RUISEKIGAKU5		CHAR,	-- NUMBER(13,0)	NOT NULL 累積額５
	QTAY_RAITENNISSU5		CHAR,	-- NUMBER(3,0)	NOT NULL 来店日数５
	QTAY_RIYOUKENSUU5		CHAR,	-- NUMBER(5,0)	NOT NULL 利用件数５
	QTAY_HANTEISTATUS5		CHAR,	-- CHAR(01)	NOT NULL 判定時ステータス５
	QTAY_HANTEIBI5			CHAR,	-- CHAR(08)	NOT NULL 判定日５
	QTAY_HOSTSAKUSEIDATE		DATE,	-- ＨＯＳＴ作成日
	QTAY_HOSTKOUSINDATE		DATE,	-- ＨＯＳＴ更新日
	QTAY_SERVERKOUSINDATE		DATE	-- サーバ更新日
)

