LOAD DATA
CHARACTERSET JA16SJIS
TRUNCATE
PRESERVE BLANKS
INTO TABLE QTAZ_RIYOUSYUKEIT
FIELDS TERMINATED BY "q"
(
	QTAZ_PRMKIGYOUCD		CHAR,		-- CHAR(04) NOT NULL 主キー・企業コード
	QTAZ_PRMSUBRANGEKEY		CHAR,		-- CHAR(04) NOT NULL 主キー・サブレンジキー
	QTAZ_PRMNAIBUKAIINNO		CHAR,		-- CHAR(08) NOT NULL 主キー・内部会員番号
	QTAZ_PRMSYUKEINENGETU		CHAR,		-- CHAR(06) NOT NULL 集計年月
	QTAZ_JYOUTAIFLAG		CHAR,		-- CHAR(01) NOT NULL 状態フラグ
	QTAZ_SOUGAKU			CHAR,		-- NUMBER(13,0) NOT NULL 総額
	QTAZ_TAISYOUSYOUHIN		CHAR,		-- NUMBER(13,0) NOT NULL 対象商品
	QTAZ_TAISYOUGAISYOUHIN		CHAR,		-- NUMBER(13,0) NOT NULL 対象外商品
	QTAZ_SYOUHIZEI			CHAR,		-- NUMBER(13,0) NOT NULL 消費税
	QTAZ_ATAMAKIN			CHAR,		-- NUMBER(13,0) NOT NULL 頭金
	QTAZ_RIYOUKENSUU		CHAR,		-- NUMBER(5,0)  NOT NULL 利用件数
	QTAZ_RAITENNISSU		CHAR,		-- NUMBER(3,0)  NOT NULL 来店日数
	QTAZ_HASSEITEN			CHAR,		-- CHAR(02)     NOT NULL      発生店
	QTAZ_KEIJYOUDATE		DATE,		-- 計上日
	QTAZ_SHIHARAIHOUHOU		CHAR,		-- CHAR(02)	NOT NULL 支払方法
	QTAZ_HOSTSAKUSEIDATE		DATE,		-- 作成日
	QTAZ_SERVERTOUROIKUDATE		DATE		-- 
)

