LOAD DATA
CHARACTERSET JA16SJIS
APPEND
PRESERVE BLANKS
INTO TABLE QXB2_KEIJYOJISTT
FIELDS TERMINATED BY "q"
(
       QXB2_PRMKIGYOUCD	   CHAR, --  CHAR(04) NOT NUL,		
       QXB2_PRMSUBRANGEKEY	   CHAR, --  CHAR(04) NOT NULL,		
       QXB2_PRMNAIBUKAIINNO	   CHAR, --  CHAR(08) NOT NULL,		
       QXB2_PRMTORIHIKINO	   CHAR, --  NUMBER(07) NOT NULL,	
       QXB2_POSSTATUS		   CHAR, --  CHAR(02) NULL,		
       QXB2_DAIHYOUSTATUS	   CHAR, --  CHAR(04) NULL,		
       QXB2_KEIJYOTOUROKUBI01	   DATE  NULLIF(QXB2_KEIJYOTOUROKUBI01="19000000"),			
       QXB2_KEIJYOSTATUS01	   CHAR, --  CHAR(04) NOT NULL,			
       QXB2_KEIJYOTOUROKUBI02	   DATE  NULLIF(QXB2_KEIJYOTOUROKUBI02="19000000"),			
       QXB2_KEIJYOSTATUS02	   CHAR, --  CHAR(04) NULL,			
       QXB2_KEIJYOTOUROKUBI03	   DATE  NULLIF(QXB2_KEIJYOTOUROKUBI03="19000000"),			
       QXB2_KEIJYOSTATUS03	   CHAR, --  CHAR(04) NOT NULL,			
       QXB2_KEIJYOTOUROKUBI04	   DATE  NULLIF(QXB2_KEIJYOTOUROKUBI04="19000000"),			
       QXB2_KEIJYOSTATUS04	   CHAR, --  CHAR(04) NOT NULL,			
       QXB2_KEIJYOTOUROKUBI05	   DATE  NULLIF(QXB2_KEIJYOTOUROKUBI05="19000000"),			
       QXB2_KEIJYOSTATUS05	   CHAR, --  CHAR(04) NOT NULL,			
       QXB2_NEGACODE		   CHAR, --  CHAR(04) NOT NULL,			
       QXB2_NEGAJIKOBI		   DATE  NULLIF(QXB2_NEGAJIKOBI="19000000"),			
       QXB2_SEIGYOSIKIBETUKUBUN    CHAR, --  CHAR(01) NULL,			
       QXB2_TEIKEITORIHIKITUUBAN   CHAR, --  NUMBER(13) NULL,			
       QXB2_HOSTSHORIYMD	   CHAR, --  CHAR(08) NULL,			
       QXB2_HOSTSHORITIME	   CHAR, --  CHAR(06) NULL,			
       QXB2_FILLER		   CHAR, --  CHAR(06) NULL,			
       QXB2_SVRKOUSHINYMD	   CHAR  NULLIF(QXB2_SVRKOUSHINYMD="00000000")
)
