--★必ずtccuser　で実行のこと！！

CREATE TABLE TCCUSER.QVZ7_CICFILEKANRIT
	(
		QVZ7_SAKUSEIDATE		CHAR(8)			NOT NULL ,
		QVZ7_SAKUSEITIME		CHAR(6)			NOT NULL ,
		QVZ7_FILENAME_ID		CHAR(15)		NOT NULL ,
		QVZ7_FILENAME			VARCHAR2(30)	NOT NULL ,
		QVZ7_DATASIZE			NUMBER(7)		NOT NULL ,
		QVZ7_TORIKOMIDATE		CHAR(8)			,
		QVZ7_TORIKOMITIME		CHAR(6)			,
		QVZ7_TORIKOMITANTOCD	CHAR(8)			,
		QVZ7_TORIKOMITANTOMEI	VARCHAR2(40)	,
		QVZ7_KEKKAFILENAME		VARCHAR2(30)	,
		QVZ7_KEKKAFILENAME_ID   CHAR(15)		,
		QVZ7_KEKKASOSINDATE		CHAR(8)			,
		QVZ7_KEKKASOSINTIME		CHAR(6)			,
		QVZ7_KEKKASOSINTANTOCD	CHAR(8)			,
		QVZ7_KEKKASOSINTANTOMEI	VARCHAR2(40)	,
		QVZ7_HAISINKIDOUNETMEI	CHAR(8)			,
		QVZ7_UPDATEYMD			DATE			NOT NULL ,
		CONSTRAINT XIE1QVZ7_CICFILEKANRIT PRIMARY KEY (
				QVZ7_SAKUSEIDATE,
				QVZ7_SAKUSEITIME,
				QVZ7_FILENAME_ID
			) USING INDEX
			PCTFREE  5
			INITRANS 2
			MAXTRANS 255
			TABLESPACE 	CICIDX
			STORAGE(
				INITIAL 64K
				NEXT    64K
				MINEXTENTS 1
				MAXEXTENTS 100
				BUFFER_POOL DEFAULT)
			LOGGING
--		,CONSTRAINT XIE2QVZ7_CICFILEKANRITT UNIQUE (
		,CONSTRAINT XIE2QVZ7_CICFILEKANRIT UNIQUE (
				QVZ7_FILENAME_ID
			) USING INDEX
			PCTFREE 10
			INITRANS 2
			MAXTRANS 255
--			TABLESPACE 	STARSIDX
			TABLESPACE 	CICIDX
			STORAGE(
				INITIAL 8K
				NEXT    8K
				MINEXTENTS 1
				MAXEXTENTS 100
				BUFFER_POOL DEFAULT)
			LOGGING
	)
	PCTFREE 	5
	MAXTRANS 255
	TABLESPACE 	CICTBS
	STORAGE(
		INITIAL 	64K
		NEXT    	64K
		MINEXTENTS 	1
		MAXEXTENTS 	100
		BUFFER_POOL DEFAULT)
	NOCACHE
	LOGGING
	/
