--★必ずtccuser　で実行のこと！！

CREATE TABLE TCCUSER.QVZ8_CICSAIBANT
	(
		QVZ8_HULFTMEI			CHAR(6)			NOT NULL ,
		QVZ8_NUMBER				NUMBER(4)		NOT NULL ,
		QVZ8_UPDATEYMD			DATE			NOT NULL ,
		CONSTRAINT QVZ8KEY PRIMARY KEY (
			QVZ8_HULFTMEI
		) USING INDEX
		PCTFREE  5
		INITRANS 2
		MAXTRANS 255
		TABLESPACE 	CICIDX
		STORAGE(
			INITIAL 64K
			NEXT    64K
			MINEXTENTS 1
			MAXEXTENTS 100
			BUFFER_POOL DEFAULT)
		LOGGING
		)
	PCTFREE 	5
	MAXTRANS 255
	TABLESPACE 	CICTBS
	STORAGE(
	INITIAL 	64K
	NEXT    	64K
	MINEXTENTS 	1
	MAXEXTENTS 	100
	BUFFER_POOL DEFAULT)
	NOCACHE
	LOGGING
/
