--★必ずtccuser　で実行のこと！！

CREATE TABLE TCCUSER.QVZ9_CICCODET
	(
		QVZ9_HULFTMEI			CHAR(6)			NOT NULL ,
		QVZ9_FILENAMEKOTEI		VARCHAR2(30)	NOT NULL ,
		QVZ9_KEKKAFILENAMEKOTEI	VARCHAR2(30)	,
		QVZ9_HAISINKIDOUNETMEI	CHAR(8)			,
		QVZ9_FILEKAKUCHOUSI		VARCHAR2(4)		,
		CONSTRAINT QVZ9KEY PRIMARY KEY (
			QVZ9_HULFTMEI
		) USING INDEX
		PCTFREE 10
		INITRANS 2
		MAXTRANS 255
		TABLESPACE 	CICIDX
		STORAGE(
			INITIAL 64K
			NEXT    64K
			MINEXTENTS 1
			MAXEXTENTS 100
			BUFFER_POOL DEFAULT)
		LOGGING
		)
	PCTFREE 	5
	MAXTRANS 255
	TABLESPACE 	CICTBS
	STORAGE(
		INITIAL 	64K
		NEXT    	64K
		MINEXTENTS 	1
		MAXEXTENTS 	100
		BUFFER_POOL DEFAULT)
	NOCACHE
	LOGGING
/
