#!/bin/csh
#set   SHELL_NAME = $0
setenv JOBNET_ID    QBDN00UX
setenv JOB_ID       QBDJN0UX
setenv USERKEY      QBDJN0UX
set    MODULE     = QBDJN0UX
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT
set    datdir     = $QB_DATA_DIR

$LOGWRITE "$MODULE" I "START : 約定情報更新" "$USERKEY"
#---------------------------------------------------------#
#   SDBT130   約定情報更新
#---------------------------------------------------------#
setenv DDYAKUJO $datdir/Yakujo.rcv

setenv NLS_LANG Japanese_Japan.JA16SJIS
$EXE_DIR/qbab_sdbt130.exe

set rc = $status
if ($rc != 0) then
   $LOGWRITE "$MODULE" E "ERROR : 約定情報更新 RC=[$rc]" "$USERKEY"
   echo "SDBT130 ABNORMAL ENDED : RC=[$rc]"
   exit(1)
endif
setenv NLS_LANG Japanese_Japan.JA16EUC

$LOGWRITE "$MODULE" I "END" "$USERKEY"
exit(0)

