#!/bin/csh
#　スクリプト名  ： QBTJK4UX
#　 機  能       ： FAX送信BOX配信処理
#　 作成者       ： FIP
#
#   修正履歴
#   項番   管理番号    修正内容                                                                修正者         修正日
#                      友の会引越し友の会事務所設置のFAX送信BOXのIPアドレス変更                FIP            2019/3/7
#   

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                               			  	#シェル名
setenv JOB_ID       $SHELL_NAME:t                     			 	#ジョブ名
setenv JOBNET_ID   'QBTK40UX'										#ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/user.log	        				#ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT          			 	#ログ出力モジュール
set    USERKEY    = 'QBTJK4UX'                   					#ユーザキー
set    KINOU      = 'FAX送信BOX配信処理'							#機能

set    WORK_DIR   = $QB_DATA_DIR/qb/FAXWORK							#WORKディレクトリ
set    MODULE     = 'SHELL'

set    TCC        = '128.1.2.101'									#港北センター設置のFAX送信BOXのIPアドレス
#--FIP MOD START 20190307
#set    TMK        = '128.1.139.151'									#友の会事務所設置のFAX送信BOXのIPアドレス
set    TMK        = '172.25.26.128'									#友の会事務所設置のFAX送信BOXのIPアドレス
#--FIP MOD END 20190307
set    S_HAISHIN  = $EXE_DIR/qbkb_s000200.csh						#SFTP配信共通処理SHELL

$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"   					#開始メッセージの出力

#################################################
# STEP-1  SFTP配信共通処理SHELL起動処理         #
#################################################
$LOGWRITE "$MODULE" I "開始:SFTP配信共通処理SHELL起動" "$USERKEY"   #開始メッセージの出力

set WORK_FILENAME = `ls -1 $WORK_DIR | head -1` 
set FURI_KEY = `echo $WORK_FILENAME | awk -F_ '{print $3}' `

switch ( $FURI_KEY )
case TCC??:
	set IP_ADDRESS = $TCC
	breaksw

case TMK??:
	set IP_ADDRESS = $TMK
	breaksw

default:
	$LOGWRITE "$MODULE" E "失敗:振分キーが異なります" "$USERKEY"	
	exit 1

endsw

#SFTP配信共通処理SHELLを引数をFAX送付先IPアドレス、WORKディレクトリ名で起動
$S_HAISHIN $IP_ADDRESS $WORK_DIR/
#--DEBUG START
$LOGWRITE "$MODULE" I $IP_ADDRESS "$USERKEY"   #IPアドレス確認
#--DEBUG END

#直前に実行したコマンドが成功したら0、失敗したら1をRCにセット
set RC = $status
if ( $RC != 0 ) then
    $LOGWRITE  "$MODULE"  E  "失敗:SFTP配信共通処理SHELL起動 RC=[$RC]" "$USERKEY"
	exit 1		# 異常終了
endif


$LOGWRITE "$MODULE" I "終了:SFTP配信共通処理SHELL起動" "$USERKEY"   #終了メッセージの出力

#################################################
# STEP-2  WORKディレクトリ内ファイル削除処理    #
#################################################
rm -f $WORK_DIR/*											#WORKディレクトリ内のファイルを全て削除する

#################################################
# STEP-99  終了処理                             #
#################################################
$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   			#終了メッセージの出力
exit 0                                           			#正常終了
