#!/bin/csh
# 　スクリプト名 ： QHTJO2UX
#　 機  能       ： 請求明細のＬＯＡＤを行う
#　 作成者       ： FIP
#　 改造         ： ①2000/04/21 compress処理を作業メモのジョブ(QHTJOCUX)に移動
#                ： ②2000/04/21 SKIP処理を削除
#                ： ③2000/04/21 ＩＮＤＥＸ表領域の変更
#                ： ④2000/06/08 プライマリーキーをＩＮＤＥＸに変更
#                ： ⑤2002/09/21 新請求書用に修正
#                ： ⑥2006/02/20 作業ディレクトリ変更 NBC.YOSHIKAWA
#
#　 修正履歴
# 項番   管理番号    修正内容                修正者         修正日
# 000001             ｲﾝﾃﾞｯｸｽﾁｪｯｸの追加       NBC.HAYASHI    2006/11/15
# 000002 0807073     非互換対応              NBC.SHIBUICHI  2009/03/29
# 000002 0808052     非互換対応              NBC.SHIBUICHI  2009/03/29

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                              # シェル名
setenv JOB_ID       $SHELL_NAME:t                   # ジョブ名
setenv JOBNET_ID   'QHT721UX'                       # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log     # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT        # ログ出力モジュール
setenv USERKEY      'QHTJO2UX'                      # ユーザキー
set    KINOU      = '請求明細テーブル登録'

set TABLE_NAME    = QHE4_SEIKYUDTLT                 # 対象テーブル名

#000001 ADD NBC.HAYASHI 2006/11/15 START
set    INDEX_NAME   = XAK1QHE4_SEIKYUDTLT                 # 対象インデックス名
#000001 ADD NBC.HAYASHI 2006/11/15 END

#set STEP_F        = $QH_DATA_DIR/${JOB_ID}_STEP_.tmp

#⑥2006/02/20 作業ディレクトリ変更 mod==>
set    SEIKYU_DATA_DIR     = '/d380/UFS/data/qh/monthly'
#⑥2006/02/20 作業ディレクトリ変更 mod==<
set MODULE = 'SHELL'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"      # 開始メッセージの出力


#if ( ! -e $STEP_F ) then
#    touch $STEP_F
#endif

##################################
# STEP-1 主キー制約削除          #
##################################
#STEP_1:
#
##set cnt = `grep -c "STEP_1" $STEP_F`
##if ( $cnt > 0 ) then
##	goto STEP_2
##endif
#
#set MODULE = 'SQL*PLUS-1'
#$LOGWRITE "$MODULE" I "開始:QHA4 主キー制約削除" $USERKEY
#
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF > $LOGFILE
#alter table $TABLE_NAME drop primary key;
#quit SQL.SQLCODE
#EOF
#
#set rc = $status
#if ( $rc != 0 ) then
#	set MSG = "失敗:QHA4 主キー制約削除 RC=[$rc]"
#	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
#	exit  1
#endif
#
##echo "STEP_1" > $STEP_F
#
#$LOGWRITE "$MODULE" I "終了:QHA4 主キー制約削除" $USERKEY
#
##################################
# STEP-2 データロード１          #
##################################
STEP_2:

#set cnt = `grep -c "STEP_2" $STEP_F`
#if ( $cnt > 0 ) then
#	goto STEP_3
#endif

set MODULE = 'SQL*LOADER'
$LOGWRITE "$MODULE" I "開始:QHE4 データロード１" $USERKEY

#⑤2002/09/21 新請求書用に修正
#sqlldr $DB_USERID/$DB_PASSWORD                   \
#   control=$LDR_CTRL_DIR/qhad_seikyudtl.sql      \
#   data=$QH_DATA_DIR/monthly/qhaf_meisai01.hulft \
#   log=$LDR_LOG_DIR/qhad_seikyudtl01.log         \
#   direct=true                                   \
#               > $LOGFILE
#⑥2006/02/20 作業ディレクトリ変更 mod==>
#sqlldr $DB_USERID/$DB_PASSWORD                   \
#   control=$LDR_CTRL_DIR/qhed_seikyudtl.sql      \
#   data=$QH_DATA_DIR/monthly/qhef_meisai01.hulft \
#   log=$LDR_LOG_DIR/qhed_seikyudtl01.log         \
#   direct=true                                   \
#               > $LOGFILE
#⑥2006/02/20 作業ディレクトリ変更 mod==<

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlldr $DB_USERID/$DB_PASSWORD                   \
#   control=$LDR_CTRL_DIR/qhed_seikyudtl.sql      \
#   data=$SEIKYU_DATA_DIR/qhef_meisai01.hulft \
#   log=$LDR_LOG_DIR/qhed_seikyudtl01.log         \
#   direct=true                                   \
#               > $LOGFILE
sqlldr $DB_USERID/$DB_PASSWORD@$ORACLE_SID       \
   control=$LDR_CTRL_DIR/qhed_seikyudtl.sql      \
   data=$SEIKYU_DATA_DIR/qhef_meisai01.hulft \
   log=$LDR_LOG_DIR/qhed_seikyudtl01.log         \
   direct=true                                   \
               > $LOGFILE
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:QHE4 データロード１ RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

#echo "STEP_2" >> $STEP_F

#000001 ADD NBC.HAYASHI 2006/11/15 START
#----------------------------------------------------------#
#   インデックスエラーのチェック              
#----------------------------------------------------------#
rm -f ${LOGFILE}2 ${LOGFILE}3

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF > ${LOGFILE}2
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF > ${LOGFILE}2
set lin 200
select index_name,status from user_indexes
       where table_name = '$TABLE_NAME'  and
             status     = 'UNUSABLE';
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:QHE4 データロード１（sqlplus） RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF >> ${LOGFILE}2
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF >> ${LOGFILE}2
set lin 200
select index_name,status from user_ind_partitions
       where index_name = '$INDEX_NAME'  and
             status     = 'UNUSABLE';
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:QHE4 データロード１（sqlplus2） RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

grep "UNUSABLE" `find ${USER_LOG_DIR} -name "${JOB_ID}.log2" -print` > ${LOGFILE}3
if !(-z ${LOGFILE}3 ) then
	set MSG = "失敗:QHE4 データロード１（grep） RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

#000001 ADD NBC.HAYASHI 2006/11/15 END

$LOGWRITE "$MODULE" I "終了:QHE4 データロード１" $USERKEY

##################################
# STEP-3 データロード２          #
##################################
STEP_3:

#set cnt = `grep -c "STEP_3" $STEP_F`
#if ( $cnt > 0 ) then
#	goto STEP_4
#endif

set MODULE = 'SQL*LOADER'
$LOGWRITE "$MODULE" I "開始:QHE4 データロード２" $USERKEY

#⑤2002/09/21 新請求書用に修正
#sqlldr $DB_USERID/$DB_PASSWORD                   \
#   control=$LDR_CTRL_DIR/qhad_seikyudtl.sql      \
#   data=$QH_DATA_DIR/monthly/qhaf_meisai02.hulft \
#   log=$LDR_LOG_DIR/qhad_seikyudtl02.log         \
#   direct=true                                   \
#               > $LOGFILE
#⑥2006/02/20 作業ディレクトリ変更 mod==>
#sqlldr $DB_USERID/$DB_PASSWORD                   \
#   control=$LDR_CTRL_DIR/qhed_seikyudtl.sql      \
#   data=$QH_DATA_DIR/monthly/qhef_meisai02.hulft \
#   log=$LDR_LOG_DIR/qhed_seikyudtl02.log         \
#   direct=true                                   \
#               > $LOGFILE
#⑥2006/02/20 作業ディレクトリ変更 mod==<

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlldr $DB_USERID/$DB_PASSWORD                   \
#   control=$LDR_CTRL_DIR/qhed_seikyudtl.sql      \
#   data=$SEIKYU_DATA_DIR/qhef_meisai02.hulft \
#   log=$LDR_LOG_DIR/qhed_seikyudtl02.log         \
#   direct=true                                   \
#               > $LOGFILE
sqlldr $DB_USERID/$DB_PASSWORD@$ORACLE_SID       \
   control=$LDR_CTRL_DIR/qhed_seikyudtl.sql      \
   data=$SEIKYU_DATA_DIR/qhef_meisai02.hulft \
   log=$LDR_LOG_DIR/qhed_seikyudtl02.log         \
   direct=true                                   \
               > $LOGFILE
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:QHE4 データロード２ RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

#echo "STEP_3" >> $STEP_F

#000001 ADD NBC.HAYASHI 2006/11/15 START
#----------------------------------------------------------#
#   インデックスエラーのチェック              
#----------------------------------------------------------#
rm -f ${LOGFILE}2 ${LOGFILE}3

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF > ${LOGFILE}2
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF > ${LOGFILE}2
set lin 200
select index_name,status from user_indexes
       where table_name = '$TABLE_NAME'  and
             status     = 'UNUSABLE';
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:QHE4 データロード２（sqlplus） RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF >> ${LOGFILE}2
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF >> ${LOGFILE}2
set lin 200
select index_name,status from user_ind_partitions
       where index_name = '$INDEX_NAME'  and
             status     = 'UNUSABLE';
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:QHE4 データロード２（sqlplus2） RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

grep "UNUSABLE" `find ${USER_LOG_DIR} -name "${JOB_ID}.log2" -print` > ${LOGFILE}3
if !(-z ${LOGFILE}3 ) then
	set MSG = "失敗:QHE4 データロード２（grep） RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

#000001 ADD NBC.HAYASHI 2006/11/15 END

$LOGWRITE "$MODULE" I "終了:QHE4 データロード２" $USERKEY

##################################
# STEP-4 データロード３          #
##################################
STEP_4:

#set cnt = `grep -c "STEP_4" $STEP_F`
#if ( $cnt > 0 ) then
#	goto STEP_5
#endif

set MODULE = 'SQL*LOADER'
$LOGWRITE "$MODULE" I "開始:QHE4 データロード３" $USERKEY

#⑤2002/09/21 新請求書用に修正
#sqlldr $DB_USERID/$DB_PASSWORD                   \
#   control=$LDR_CTRL_DIR/qhad_seikyudtl.sql      \
#   data=$QH_DATA_DIR/monthly/qhaf_meisai03.hulft \
#   log=$LDR_LOG_DIR/qhad_seikyudtl03.log         \
#   direct=true                                   \
#               > $LOGFILE
#⑥2006/02/20 作業ディレクトリ変更 mod==>
#sqlldr $DB_USERID/$DB_PASSWORD                   \
#   control=$LDR_CTRL_DIR/qhed_seikyudtl.sql      \
#   data=$QH_DATA_DIR/monthly/qhef_meisai03.hulft \
#   log=$LDR_LOG_DIR/qhed_seikyudtl03.log         \
#   direct=true                                   \
#               > $LOGFILE
#⑥2006/02/20 作業ディレクトリ変更 mod==<

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlldr $DB_USERID/$DB_PASSWORD                   \
#   control=$LDR_CTRL_DIR/qhed_seikyudtl.sql      \
#   data=$SEIKYU_DATA_DIR/qhef_meisai03.hulft \
#   log=$LDR_LOG_DIR/qhed_seikyudtl03.log         \
#   direct=true                                   \
#               > $LOGFILE
sqlldr $DB_USERID/$DB_PASSWORD@$ORACLE_SID       \
   control=$LDR_CTRL_DIR/qhed_seikyudtl.sql      \
   data=$SEIKYU_DATA_DIR/qhef_meisai03.hulft \
   log=$LDR_LOG_DIR/qhed_seikyudtl03.log         \
   direct=true                                   \
               > $LOGFILE
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:QHE4 データロード３ RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

#echo "STEP_4" >> $STEP_F

#000001 ADD NBC.HAYASHI 2006/11/15 START
#----------------------------------------------------------#
#   インデックスエラーのチェック              
#----------------------------------------------------------#
rm -f ${LOGFILE}2 ${LOGFILE}3

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF > ${LOGFILE}2
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF > ${LOGFILE}2
set lin 200
select index_name,status from user_indexes
       where table_name = '$TABLE_NAME'  and
             status     = 'UNUSABLE';
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:QHE4 データロード３（sqlplus） RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF >> ${LOGFILE}2
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF >> ${LOGFILE}2
set lin 200
select index_name,status from user_ind_partitions
       where index_name = '$INDEX_NAME'  and
             status     = 'UNUSABLE';
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:QHE4 データロード３（sqlplus2） RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

grep "UNUSABLE" `find ${USER_LOG_DIR} -name "${JOB_ID}.log2" -print` > ${LOGFILE}3
if !(-z ${LOGFILE}3 ) then
	set MSG = "失敗:QHE4 データロード３（grep） RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

#000001 ADD NBC.HAYASHI 2006/11/15 END

$LOGWRITE "$MODULE" I "終了:QHE4 データロード３" $USERKEY

##################################
# STEP-5 データロード４          #
##################################
STEP_5:

#set cnt = `grep -c "STEP_5" $STEP_F`
#if ( $cnt > 0 ) then
#	goto STEP_6
#endif

set MODULE = 'SQL*LOADER'
$LOGWRITE "$MODULE" I "開始:QHE4 データロード４" $USERKEY

#⑤2002/09/21 新請求書用に修正
#sqlldr $DB_USERID/$DB_PASSWORD                   \
#   control=$LDR_CTRL_DIR/qhad_seikyudtl.sql      \
#   data=$QH_DATA_DIR/monthly/qhaf_meisai04.hulft \
#   log=$LDR_LOG_DIR/qhad_seikyudtl04.log         \
#   direct=true                                   \
#               > $LOGFILE
#⑥2006/02/20 作業ディレクトリ変更 mod==>
#sqlldr $DB_USERID/$DB_PASSWORD                   \
#   control=$LDR_CTRL_DIR/qhed_seikyudtl.sql      \
#   data=$QH_DATA_DIR/monthly/qhef_meisai04.hulft \
#   log=$LDR_LOG_DIR/qhed_seikyudtl04.log         \
#   direct=true                                   \
#               > $LOGFILE
#⑥2006/02/20 作業ディレクトリ変更 mod==<

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlldr $DB_USERID/$DB_PASSWORD                   \
#   control=$LDR_CTRL_DIR/qhed_seikyudtl.sql      \
#   data=$SEIKYU_DATA_DIR/qhef_meisai04.hulft \
#   log=$LDR_LOG_DIR/qhed_seikyudtl04.log         \
#   direct=true                                   \
#               > $LOGFILE
sqlldr $DB_USERID/$DB_PASSWORD@$ORACLE_SID       \
   control=$LDR_CTRL_DIR/qhed_seikyudtl.sql      \
   data=$SEIKYU_DATA_DIR/qhef_meisai04.hulft \
   log=$LDR_LOG_DIR/qhed_seikyudtl04.log         \
   direct=true                                   \
               > $LOGFILE
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:QHE4 データロード４ RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

#echo "STEP_5" >> $STEP_F

#000001 ADD NBC.HAYASHI 2006/11/15 START
#----------------------------------------------------------#
#   インデックスエラーのチェック              
#----------------------------------------------------------#
rm -f ${LOGFILE}2 ${LOGFILE}3

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF > ${LOGFILE}2
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF > ${LOGFILE}2
set lin 200
select index_name,status from user_indexes
       where table_name = '$TABLE_NAME'  and
             status     = 'UNUSABLE';
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:QHE4 データロード４（sqlplus） RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF >> ${LOGFILE}2
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF >> ${LOGFILE}2
set lin 200
select index_name,status from user_ind_partitions
       where index_name = '$INDEX_NAME'  and
             status     = 'UNUSABLE';
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:QHE4 データロード４（sqlplus2） RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

grep "UNUSABLE" `find ${USER_LOG_DIR} -name "${JOB_ID}.log2" -print` > ${LOGFILE}3
if !(-z ${LOGFILE}3 ) then
	set MSG = "失敗:QHE4 データロード４（grep） RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

#000001 ADD NBC.HAYASHI 2006/11/15 END

$LOGWRITE "$MODULE" I "終了:QHE4 データロード４" $USERKEY

##################################
# STEP-6 データロード５          #
##################################
STEP_6:

#set cnt = `grep -c "STEP_6" $STEP_F`
#if ( $cnt > 0 ) then
#	goto STEP_7
#endif

set MODULE = 'SQL*LOADER'
$LOGWRITE "$MODULE" I "開始:QHE4 データロード５" $USERKEY

#⑤2002/09/21 新請求書用に修正
#sqlldr $DB_USERID/$DB_PASSWORD                   \
#   control=$LDR_CTRL_DIR/qhad_seikyudtl.sql      \
#   data=$QH_DATA_DIR/monthly/qhaf_meisai05.hulft \
#   log=$LDR_LOG_DIR/qhad_seikyudtl05.log         \
#   direct=true                                   \
#               > $LOGFILE
#⑥2006/02/20 作業ディレクトリ変更 mod==>
#sqlldr $DB_USERID/$DB_PASSWORD                   \
#   control=$LDR_CTRL_DIR/qhed_seikyudtl.sql      \
#   data=$QH_DATA_DIR/monthly/qhef_meisai05.hulft \
#   log=$LDR_LOG_DIR/qhed_seikyudtl05.log         \
#   direct=true                                   \
#               > $LOGFILE
#⑥2006/02/20 作業ディレクトリ変更 mod==<

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlldr $DB_USERID/$DB_PASSWORD                   \
#   control=$LDR_CTRL_DIR/qhed_seikyudtl.sql      \
#   data=$SEIKYU_DATA_DIR/qhef_meisai05.hulft \
#   log=$LDR_LOG_DIR/qhed_seikyudtl05.log         \
#   direct=true                                   \
#               > $LOGFILE
sqlldr $DB_USERID/$DB_PASSWORD@$ORACLE_SID       \
   control=$LDR_CTRL_DIR/qhed_seikyudtl.sql      \
   data=$SEIKYU_DATA_DIR/qhef_meisai05.hulft \
   log=$LDR_LOG_DIR/qhed_seikyudtl05.log         \
   direct=true                                   \
               > $LOGFILE
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:QHE4 データロード５ RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

#echo "STEP_6" >> $STEP_F

#000001 ADD NBC.HAYASHI 2006/11/15 START
#----------------------------------------------------------#
#   インデックスエラーのチェック              
#----------------------------------------------------------#
rm -f ${LOGFILE}2 ${LOGFILE}3

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF > ${LOGFILE}2
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF > ${LOGFILE}2
set lin 200
select index_name,status from user_indexes
       where table_name = '$TABLE_NAME'  and
             status     = 'UNUSABLE';
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:QHE4 データロード５（sqlplus） RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF >> ${LOGFILE}2
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF >> ${LOGFILE}2
set lin 200
select index_name,status from user_ind_partitions
       where index_name = '$INDEX_NAME'  and
             status     = 'UNUSABLE';
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:QHE4 データロード５（sqlplus2） RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

grep "UNUSABLE" `find ${USER_LOG_DIR} -name "${JOB_ID}.log2" -print` > ${LOGFILE}3
if !(-z ${LOGFILE}3 ) then
	set MSG = "失敗:QHE4 データロード５（grep） RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

#000001 ADD NBC.HAYASHI 2006/11/15 END

$LOGWRITE "$MODULE" I "終了:QHE4 データロード５" $USERKEY

##################################
# STEP-7 データロード６          #
##################################
STEP_7:

#set cnt = `grep -c "STEP_7" $STEP_F`
#if ( $cnt > 0 ) then
#	goto STEP_8
#endif

set MODULE = 'SQL*LOADER'
$LOGWRITE "$MODULE" I "開始:QHE4 データロード６" $USERKEY

#⑤2002/09/21 新請求書用に修正
#sqlldr $DB_USERID/$DB_PASSWORD                   \
#   control=$LDR_CTRL_DIR/qhad_seikyudtl.sql      \
#   data=$QH_DATA_DIR/monthly/qhaf_meisai06.hulft \
#   log=$LDR_LOG_DIR/qhad_seikyudtl06.log         \
#   direct=true                                   \
#               > $LOGFILE
#⑥2006/02/20 作業ディレクトリ変更 mod==>
#sqlldr $DB_USERID/$DB_PASSWORD                   \
#   control=$LDR_CTRL_DIR/qhed_seikyudtl.sql      \
#   data=$QH_DATA_DIR/monthly/qhef_meisai06.hulft \
#   log=$LDR_LOG_DIR/qhed_seikyudtl06.log         \
#   direct=true                                   \
#               > $LOGFILE
#⑥2006/02/20 作業ディレクトリ変更 mod==<

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlldr $DB_USERID/$DB_PASSWORD                   \
#   control=$LDR_CTRL_DIR/qhed_seikyudtl.sql      \
#   data=$SEIKYU_DATA_DIR/qhef_meisai06.hulft \
#   log=$LDR_LOG_DIR/qhed_seikyudtl06.log         \
#   direct=true                                   \
#               > $LOGFILE
sqlldr $DB_USERID/$DB_PASSWORD@$ORACLE_SID       \
   control=$LDR_CTRL_DIR/qhed_seikyudtl.sql      \
   data=$SEIKYU_DATA_DIR/qhef_meisai06.hulft \
   log=$LDR_LOG_DIR/qhed_seikyudtl06.log         \
   direct=true                                   \
               > $LOGFILE
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:QHE4 データロード６ RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

#echo "STEP_7" >> $STEP_F

#000001 ADD NBC.HAYASHI 2006/11/15 START
#----------------------------------------------------------#
#   インデックスエラーのチェック              
#----------------------------------------------------------#
rm -f ${LOGFILE}2 ${LOGFILE}3

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF > ${LOGFILE}2
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF > ${LOGFILE}2
set lin 200
select index_name,status from user_indexes
       where table_name = '$TABLE_NAME'  and
             status     = 'UNUSABLE';
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:QHE4 データロード６（sqlplus） RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF >> ${LOGFILE}2
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF >> ${LOGFILE}2
set lin 200
select index_name,status from user_ind_partitions
       where index_name = '$INDEX_NAME'  and
             status     = 'UNUSABLE';
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:QHE4 データロード６（sqlplus2） RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

grep "UNUSABLE" `find ${USER_LOG_DIR} -name "${JOB_ID}.log2" -print` > ${LOGFILE}3
if !(-z ${LOGFILE}3 ) then
	set MSG = "失敗:QHE4 データロード６（grep） RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

#000001 ADD NBC.HAYASHI 2006/11/15 END

$LOGWRITE "$MODULE" I "終了:QHE4 データロード６" $USERKEY

##################################
# STEP-8 データロード７          #
##################################
STEP_8:

#set cnt = `grep -c "STEP_8" $STEP_F`
#if ( $cnt > 0 ) then
#	goto STEP_9
#endif

set MODULE = 'SQL*LOADER'
$LOGWRITE "$MODULE" I "開始:QHE4 データロード７" $USERKEY

#⑤2002/09/21 新請求書用に修正
#sqlldr $DB_USERID/$DB_PASSWORD                   \
#   control=$LDR_CTRL_DIR/qhad_seikyudtl.sql      \
#   data=$QH_DATA_DIR/monthly/qhaf_meisai07.hulft \
#   log=$LDR_LOG_DIR/qhad_seikyudtl07.log         \
#   direct=true                                   \
#               > $LOGFILE
#⑥2006/02/20 作業ディレクトリ変更 mod==>
#sqlldr $DB_USERID/$DB_PASSWORD                   \
#   control=$LDR_CTRL_DIR/qhed_seikyudtl.sql      \
#   data=$QH_DATA_DIR/monthly/qhef_meisai07.hulft \
#   log=$LDR_LOG_DIR/qhed_seikyudtl07.log         \
#   direct=true                                   \
#               > $LOGFILE
#⑥2006/02/20 作業ディレクトリ変更 mod==<

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlldr $DB_USERID/$DB_PASSWORD                   \
#   control=$LDR_CTRL_DIR/qhed_seikyudtl.sql      \
#   data=$SEIKYU_DATA_DIR/qhef_meisai07.hulft \
#   log=$LDR_LOG_DIR/qhed_seikyudtl07.log         \
#   direct=true                                   \
#               > $LOGFILE
sqlldr $DB_USERID/$DB_PASSWORD@$ORACLE_SID       \
   control=$LDR_CTRL_DIR/qhed_seikyudtl.sql      \
   data=$SEIKYU_DATA_DIR/qhef_meisai07.hulft \
   log=$LDR_LOG_DIR/qhed_seikyudtl07.log         \
   direct=true                                   \
               > $LOGFILE
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:QHE4 データロード７ RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

#echo "STEP_8" >> $STEP_F

#000001 ADD NBC.HAYASHI 2006/11/15 START
#----------------------------------------------------------#
#   インデックスエラーのチェック              
#----------------------------------------------------------#
rm -f ${LOGFILE}2 ${LOGFILE}3

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF > ${LOGFILE}2
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF > ${LOGFILE}2
set lin 200
select index_name,status from user_indexes
       where table_name = '$TABLE_NAME'  and
             status     = 'UNUSABLE';
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:QHE4 データロード７（sqlplus） RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF >> ${LOGFILE}2
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF >> ${LOGFILE}2
set lin 200
select index_name,status from user_ind_partitions
       where index_name = '$INDEX_NAME'  and
             status     = 'UNUSABLE';
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:QHE4 データロード７（sqlplus2） RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

grep "UNUSABLE" `find ${USER_LOG_DIR} -name "${JOB_ID}.log2" -print` > ${LOGFILE}3
if !(-z ${LOGFILE}3 ) then
	set MSG = "失敗:QHE4 データロード７（grep） RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

#000001 ADD NBC.HAYASHI 2006/11/15 END

$LOGWRITE "$MODULE" I "終了:QHE4 データロード７" $USERKEY

##################################
# STEP-9 データロード８          #
##################################
STEP_9:

#set cnt = `grep -c "STEP_9" $STEP_F`
#if ( $cnt > 0 ) then
#	goto STEP_10
#endif

set MODULE = 'SQL*LOADER'
$LOGWRITE "$MODULE" I "開始:QHE4 データロード８" $USERKEY

#⑤2002/09/21 新請求書用に修正
#sqlldr $DB_USERID/$DB_PASSWORD                   \
#   control=$LDR_CTRL_DIR/qhad_seikyudtl.sql      \
#   data=$QH_DATA_DIR/monthly/qhaf_meisai08.hulft \
#   log=$LDR_LOG_DIR/qhad_seikyudtl08.log         \
#   direct=true                                   \
#               > $LOGFILE
#⑥2006/02/20 作業ディレクトリ変更 mod==>
#sqlldr $DB_USERID/$DB_PASSWORD                   \
#   control=$LDR_CTRL_DIR/qhed_seikyudtl.sql      \
#   data=$QH_DATA_DIR/monthly/qhef_meisai08.hulft \
#   log=$LDR_LOG_DIR/qhed_seikyudtl08.log         \
#   direct=true                                   \
#               > $LOGFILE
#⑥2006/02/20 作業ディレクトリ変更 mod==<

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlldr $DB_USERID/$DB_PASSWORD                   \
#   control=$LDR_CTRL_DIR/qhed_seikyudtl.sql      \
#   data=$SEIKYU_DATA_DIR/qhef_meisai08.hulft \
#   log=$LDR_LOG_DIR/qhed_seikyudtl08.log         \
#   direct=true                                   \
#               > $LOGFILE
sqlldr $DB_USERID/$DB_PASSWORD@$ORACLE_SID       \
   control=$LDR_CTRL_DIR/qhed_seikyudtl.sql      \
   data=$SEIKYU_DATA_DIR/qhef_meisai08.hulft \
   log=$LDR_LOG_DIR/qhed_seikyudtl08.log         \
   direct=true                                   \
               > $LOGFILE
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:QHE4 データロード８ RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

#echo "STEP_9" >> $STEP_F

#000001 ADD NBC.HAYASHI 2006/11/15 START
#----------------------------------------------------------#
#   インデックスエラーのチェック              
#----------------------------------------------------------#
rm -f ${LOGFILE}2 ${LOGFILE}3

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF > ${LOGFILE}2
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF > ${LOGFILE}2
set lin 200
select index_name,status from user_indexes
       where table_name = '$TABLE_NAME'  and
             status     = 'UNUSABLE';
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:QHE4 データロード８（sqlplus） RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF >> ${LOGFILE}2
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF >> ${LOGFILE}2
set lin 200
select index_name,status from user_ind_partitions
       where index_name = '$INDEX_NAME'  and
             status     = 'UNUSABLE';
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:QHE4 データロード８（sqlplus2） RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

grep "UNUSABLE" `find ${USER_LOG_DIR} -name "${JOB_ID}.log2" -print` > ${LOGFILE}3
if !(-z ${LOGFILE}3 ) then
	set MSG = "失敗:QHE4 データロード８（grep） RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

#000001 ADD NBC.HAYASHI 2006/11/15 END

$LOGWRITE "$MODULE" I "終了:QHE4 データロード８" $USERKEY

##################################
# STEP-10 主キー制約付与         #
##################################
#STEP_10:
#
##set cnt = `grep -c "STEP_10" $STEP_F`
##if ( $cnt > 0 ) then
##	goto STEP_11
##endif
#
#set MODULE = 'SQL*PLUS-2'
#$LOGWRITE "$MODULE" I "開始:QHA4 主キー制約付与" $USERKEY
#
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF > $LOGFILE
#alter table $TABLE_NAME add
#       PRIMARY KEY (QHA4_KeyRecShikibetsu, QHA4_KeySeikyuYm,
#              QHA4_KeySeqNo, QHA4_KeyBunkatsuNo, QHA4_KeyVersionNo,
#              QHA4_KeyRecNo)
#       USING INDEX NOLOGGING
#              TABLESPACE SEIIDX03
#              STORAGE (
#                     INITIAL 2000M
#                     NEXT 200M
#                     MINEXTENTS 1
#                     MAXEXTENTS 100
#                     PCTINCREASE 0
#              );
#quit SQL.SQLCODE
#EOF
#
#set rc = $status
#if ( $rc != 0 ) then
#	set MSG = "失敗:QHA4 主キー制約付与 RC=[$rc]"
#	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
#	exit  1
#endif
#
##echo "STEP_10" >> $STEP_F
#
#$LOGWRITE "$MODULE" I "終了:QHA4 主キー制約付与" $USERKEY
#
##################################
# STEP-11 請求書明細圧縮         #
##################################
#STEP_11:
#
#set MODULE = 'compress'
#$LOGWRITE "$MODULE" I "開始:QHA4 データ圧縮" $USERKEY
#
#compress -f $QH_DATA_DIR/monthly/qhaf_meisai01.hulft
#compress -f $QH_DATA_DIR/monthly/qhaf_meisai02.hulft
#compress -f $QH_DATA_DIR/monthly/qhaf_meisai03.hulft
#compress -f $QH_DATA_DIR/monthly/qhaf_meisai04.hulft
#compress -f $QH_DATA_DIR/monthly/qhaf_meisai05.hulft
#compress -f $QH_DATA_DIR/monthly/qhaf_meisai06.hulft
#compress -f $QH_DATA_DIR/monthly/qhaf_meisai07.hulft
#compress -f $QH_DATA_DIR/monthly/qhaf_meisai08.hulft
#
#$LOGWRITE "$MODULE" I "終了:QHA4 データ圧縮" $USERKEY
#
##########################################
# STEP-99      後始末                    #
##########################################
STEP_99:

#/bin/rm $STEP_F

#set MODULE = 'SHELL'
$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   # 終了メッセージの出力

exit 0
