#!/bin/csh
#　スクリプト名  ： QHTJ66UX
#　 機  能       ： 請求履歴一覧Ｔ登録
#　 作成者       ： FIP
#　 改造         ： ①1999/12/08 compressタイミング終了MSG前に移動
#                ： ②1999/01/13 プライマリーキーの再構築の処理をコメント化。
#                ： ③2000/06/08 SKIP処理を削除
#                ： ④2000/08/15 SQL*Loader後のindexｴﾗｰ確認処理追加
#
# 修正履歴
# 項番   管理番号    修正内容                修正者         修正日
# 000001 0807073     非互換対応              NBC.ISHIDA  2009/03/29
# 000001 0808052     非互換対応              NBC.ISHIDA  2009/03/29
# 000001 0807073     index再作成対応         NBC.ISHIDA  2009/04/27
# 000001 0808052     index再作成対応         NBC.ISHIDA  2009/04/27

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                             # シェル名
setenv JOB_ID       $SHELL_NAME:t                  # ジョブ名
setenv JOBNET_ID   'QHT611UX'                      # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log    # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT       # ログ出力モジュール
setenv USERKEY      'QHTJ66UX'                     # ユーザキー
set    KINOU      = 'QHE8 請求履歴一覧Ｔ登録'

set    QH_SHIFT_DIR = $QH_DATA_DIR/shift
set    QH_SAVE_DIR  = /d271/UFS/data/qh/shift
set    STEP_F       = $QH_DATA_DIR/${JOB_ID}_STEP_.tmp

set TABLE_NAME    = QHE8_SEIITIRANDT                 # 対象テーブル名

set MODULE = 'SHELL'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"      # 開始メッセージの出力

#if ( ! -e $STEP_F ) then
#    touch $STEP_F
#endif

##################################
# STEP-1 主キー制約削除          #
##################################
#STEP_PRM_KEY_DROP_PROC:
#
##set cnt = `grep -c "STEP1" $STEP_F`
##if ( $cnt > 0 ) then
##	goto STEP_SQLLDR_PROC_1
##endif
#
#set MODULE = 'SQL*PLUS-1'
#set STEPKINOU = 'QHE8 主キー制約削除'
#$LOGWRITE "$MODULE" I "開始:$STEPKINOU" $USERKEY
#
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF > $LOGFILE
#alter table $TABLE_NAME drop primary key;
#quit SQL.SQLCODE
#EOF
#
#set rc = $status
#if ( $rc != 0 ) then
#	set MSG = "失敗:$STEPKINOU RC=[$rc]"
#	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
#	exit  1
#endif
#
##echo "STEP1" > $STEP_F
#
#$LOGWRITE "$MODULE" I "終了:$STEPKINOU" $USERKEY
#
#ADD 0807073 クレジット支援システムの再構築 20090427 NBC.ISHIDA start
#ADD 0808052 ＴＣＣ支援システムの再構築     20090427 NBC.ISHIDA start
##################################
# STEP-1.1 インデックス削除        #
##################################
set MODULE = 'SQL*PLUS-1'
$LOGWRITE "$MODULE" I "開始:インデックス削除" $USERKEY

sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF > $LOGFILE
drop index XIEQHE8_SEIITIRANDT;
quit SQL.SQLCODE
EOF

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:インデックス削除 RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

#表領域をまとめる
sqlplus -S $DB_ADMINID/$DB_ADMINPASS@$ORACLE_SID << EOF > $LOGFILE
alter tablespace SEI1IDX01 coalesce;
quit SQL.SQLCODE
EOF

set rc = $status
if ( $rc != 0 ) then
        set MSG = "失敗:インデックス削除（圧縮） RC=[$rc]"
        $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
endif

$LOGWRITE "$MODULE" I "終了:インデックス削除" $USERKEY

#ADD 0807073 クレジット支援システムの再構築 20090427 NBC.ISHIDA end
#ADD 0808052 ＴＣＣ支援システムの再構築     20090427 NBC.ISHIDA end

##################################
# STEP-2 請求一覧データロード１  #
##################################
STEP_SQLLDR_PROC_1:

#set cnt = `grep -c "STEP2" $STEP_F`
#if ( $cnt > 0 ) then
##	goto STEP_PRM_KEY_ADD_PROC
#	goto STEP_END_PROC
#endif

set MODULE = 'SQL*LOADER'
set STEPKINOU = 'QHE8 請求一覧データロード１'
$LOGWRITE "$MODULE" I "開始:$STEPKINOU" $USERKEY

#MOD 0807073 クレジット支援システムの再構築 20090329 NBC.ISHIDA start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 NBC.ISHIDA start
#sqlldr $DB_USERID/$DB_PASSWORD                          \
sqlldr $DB_USERID/$DB_PASSWORD@$ORACLE_SID                          \
   control=$LDR_CTRL_DIR/qhed_seiitiran_shift.sql       \
   data=$QH_SHIFT_DIR/qhef_qhe8itiran01.dat.shiftbackup \
   log=$LDR_LOG_DIR/qhed_seiitiran_shift01.log          \
   direct=true                                          \
               > $LOGFILE
#MOD 0807073 クレジット支援システムの再構築 20090329 NBC.ISHIDA end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 NBC.ISHIDA end

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:$STEPKINOU RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

#----------------------------------------------------------#
#   インデックスエラーのチェック              2000/08/15
#----------------------------------------------------------#
rm -f ${LOGFILE}2 ${LOGFILE}3
#MOD 0807073 クレジット支援システムの再構築 20090329 NBC.ISHIDA start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 NBC.ISHIDA start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF > ${LOGFILE}2
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF > ${LOGFILE}2
set lin 200
select index_name,status from user_indexes
       where table_name = '$TABLE_NAME'  and
             status     = 'UNUSABLE';
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 NBC.ISHIDA end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 NBC.ISHIDA end

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:$STEPKINOU（sqlplus） RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif
grep "UNUSABLE" `find ${USER_LOG_DIR} -name "${JOB_ID}.log2" -print` > ${LOGFILE}3
if !(-z ${LOGFILE}3 ) then
	set MSG = "失敗:$STEPKINOU（grep） RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

#echo "STEP2" >> $STEP_F

$LOGWRITE "$MODULE" I "終了:$STEPKINOU" $USERKEY

##################################
# STEP-3  主キー制約付与         #
##################################
#STEP_PRM_KEY_ADD_PROC:
#
##set cnt = `grep -c "STEP3" $STEP_F`
##if ( $cnt > 0 ) then
##	goto STEP_END_PROC
##endif
#
#set MODULE = 'SQL*PLUS-9'
#set STEPKINOU = 'QHE8 主キー制約付与'
#$LOGWRITE "$MODULE" I "開始:$STEPKINOU" $USERKEY
#
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF > $LOGFILE
#alter table $TABLE_NAME add
#       PRIMARY KEY (QHE8_KeySeikyuYm, QHE8_KeySeqNo,
#              QHE8_KeyBunkatsuNo, QHE8_KeyVersionNo)
#       USING INDEX NOLOGGING
#              TABLESPACE SEIIDX02
#              STORAGE (
#                     INITIAL 1900M
#                     NEXT 200M
#              );
#quit SQL.SQLCODE
#EOF
#
#set rc = $status
#if ( $rc != 0 ) then
#	set MSG = "失敗:$STEPKINOU RC=[$rc]"
#	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
#	exit  1
#endif
#
#compress -f $QH_SHIFT_DIR/qhef_qhe8itiran??.dat.shiftbackup
#
##echo "STEP3" >> $STEP_F
#
#$LOGWRITE "$MODULE" I "終了:$STEPKINOU" $USERKEY
#
#ADD 0807073 クレジット支援システムの再構築 20090427 NBC.ISHIDA start
#ADD 0808052 ＴＣＣ支援システムの再構築     20090427 NBC.ISHIDA start
##################################
# STEP-3.1  インデックス作成     #
##################################
set MODULE = 'SQL*PLUS-2'
$LOGWRITE "$MODULE" I "開始:インデックス作成" $USERKEY

sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF > $LOGFILE
CREATE INDEX XIEQHE8_SEIITIRANDT ON QHE8_SEIITIRANDT
(QHE8_KIGYOCD, QHE8_SUBRNG, QHE8_NAIBUKAIIN)
PCTFREE 10
INITRANS 2
MAXTRANS 255
TABLESPACE SEI1IDX01
STORAGE(
        INITIAL 210M
        NEXT 21M
        MINEXTENTS 1
        MAXEXTENTS 100
        PCTINCREASE 0
        FREELISTS 1
        FREELIST GROUPS 1
        BUFFER_POOL DEFAULT
       );
quit SQL.SQLCODE
EOF

set rc = $status
if ( $rc != 0 ) then
    set MSG = "失敗:インデックス作成 RC=[$rc]"
    $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
    exit  1
endif

$LOGWRITE "$MODULE" I "終了:インデックス作成" $USERKEY

#ADD 0807073 クレジット支援システムの再構築 20090427 NBC.ISHIDA end
#ADD 0808052 ＴＣＣ支援システムの再構築     20090427 NBC.ISHIDA end
##########################################
# STEP-99      後始末                    #
##########################################
STEP_END_PROC:

#/bin/rm $STEP_F

#compress -f $QH_SHIFT_DIR/qhef_qhe8itiran??.dat.shiftbackup

set MODULE = 'SHELL'
$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   # 終了メッセージの出力

exit 0
