#!/bin/csh
#　スクリプト名  ： QHET01UX
#　 機  能       ： 請求管理バッチリカバリ処理
#　 作成者       ： FIP
#

##################################
#           環境設定             #
##################################

set    SHELL_NAME = $0                             # シェル名
setenv JOB_ID       $SHELL_NAME:t                  # ジョブ名
setenv JOBNET_ID   'QHET01UX'                      # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log    # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT       # ログ出力モジュール
setenv USERKEY      'QHTJG1UX'                     # ユーザキー
set    KINOU      = '請求管理バッチリカバリ処理'

set MODULE = 'SHELL'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"      # 開始メッセージの出力

##################################
# STEP-1 請求会員テーブルシフト処理
##################################

set MODULE = 'QH_kill.sh'
set STEPKINOU = '請求会員テーブルシフト処理 削除'
$LOGWRITE "$MODULE" I "開始:$STEPKINOU" $USERKEY


#-----強制休止プロセス名設定／休止シェルファイル作成-----------------------------
#                         "xxxxx"を対象プログラム名として記入する.
ps -ef | awk '{if ( $8 == "QHTJ61UX" ) { printf ("kill -9 %d \n" , $2 ) } }' >  QH_kill.sh
ps -ef | awk '{if ( $8 == "QHTJ62UX" ) { printf ("kill -9 %d \n" , $2 ) } }' >> QH_kill.sh
ps -ef | awk '{if ( $8 == "QHTJ63UX" ) { printf ("kill -9 %d \n" , $2 ) } }' >> QH_kill.sh
ps -ef | awk '{if ( $8 == "QHTJ64UX" ) { printf ("kill -9 %d \n" , $2 ) } }' >> QH_kill.sh
ps -ef | awk '{if ( $8 == "QHTJ65UX" ) { printf ("kill -9 %d \n" , $2 ) } }' >> QH_kill.sh
ps -ef | awk '{if ( $8 == "QHTJ66UX" ) { printf ("kill -9 %d \n" , $2 ) } }' >> QH_kill.sh

#-----プロセス強制休止-----------------------------------------------------------
chmod 777 QH_kill.sh
QH_kill.sh



$LOGWRITE "$MODULE" I "終了:$STEPKINOU" $USERKEY


##################################
# STEP-2 請求明細テーブルシフト処理 
##################################

set MODULE = 'QH_kill.sh'
set STEPKINOU = '請求明細テーブルシフト処理 削除'
$LOGWRITE "$MODULE" I "開始:$STEPKINOU" $USERKEY


#-----強制休止プロセス名設定／休止シェルファイル作成-----------------------------
#                         "xxxxx"を対象プログラム名として記入する.
ps -ef | awk '{if ( $8 == "QHTJ71UX" ) { printf ("kill -9 %d \n" , $2 ) } }' >  QH_kill.sh
ps -ef | awk '{if ( $8 == "QHTJ72UX" ) { printf ("kill -9 %d \n" , $2 ) } }' >> QH_kill.sh
ps -ef | awk '{if ( $8 == "QHTJ73UX" ) { printf ("kill -9 %d \n" , $2 ) } }' >> QH_kill.sh
ps -ef | awk '{if ( $8 == "QHTJ74UX" ) { printf ("kill -9 %d \n" , $2 ) } }' >> QH_kill.sh
ps -ef | awk '{if ( $8 == "QHTJ75UX" ) { printf ("kill -9 %d \n" , $2 ) } }' >> QH_kill.sh
ps -ef | awk '{if ( $8 == "QHTJ76UX" ) { printf ("kill -9 %d \n" , $2 ) } }' >> QH_kill.sh

#-----プロセス強制休止-----------------------------------------------------------
chmod 777 QH_kill.sh
QH_kill.sh


$LOGWRITE "$MODULE" I "終了:$STEPKINOU" $USERKEY


##################################
# STEP-3 請求メモテーブルシフト処理 
##################################

set MODULE = 'QH_kill.sh'
set STEPKINOU = '請求メモテーブルシフト処理 削除'
$LOGWRITE "$MODULE" I "開始:$STEPKINOU" $USERKEY


#-----強制休止プロセス名設定／休止シェルファイル作成-----------------------------
#                         "xxxxx"を対象プログラム名として記入する.
ps -ef | awk '{if ( $8 == "QHTJ81UX" ) { printf ("kill -9 %d \n" , $2 ) } }' >  QH_kill.sh
ps -ef | awk '{if ( $8 == "QHTJ82UX" ) { printf ("kill -9 %d \n" , $2 ) } }' >> QH_kill.sh
ps -ef | awk '{if ( $8 == "QHTJ83UX" ) { printf ("kill -9 %d \n" , $2 ) } }' >> QH_kill.sh

#-----プロセス強制休止-----------------------------------------------------------
chmod 777 QH_kill.sh
QH_kill.sh


$LOGWRITE "$MODULE" I "終了:$STEPKINOU" $USERKEY


##################################
# STEP-4 請求会員テーブル登録処理
##################################

set MODULE = 'QH_kill.sh'
set STEPKINOU = '請求会員テーブル登録処理 削除'
$LOGWRITE "$MODULE" I "開始:$STEPKINOU" $USERKEY


#-----強制休止プロセス名設定／休止シェルファイル作成-----------------------------
#                         "xxxxx"を対象プログラム名として記入する.
ps -ef | awk '{if ( $8 == "QHTJO1UX" ) { printf ("kill -9 %d \n" , $2 ) } }' >  QH_kill.sh

#-----プロセス強制休止-----------------------------------------------------------
chmod 777 QH_kill.sh
QH_kill.sh


$LOGWRITE "$MODULE" I "終了:$STEPKINOU" $USERKEY


##################################
# STEP-5 請求明細テーブル登録処理
##################################

set MODULE = 'QH_kill.sh'
set STEPKINOU = '請求明細テーブル登録処理 削除'
$LOGWRITE "$MODULE" I "開始:$STEPKINOU" $USERKEY


#-----強制休止プロセス名設定／休止シェルファイル作成-----------------------------
#                         "xxxxx"を対象プログラム名として記入する.
ps -ef | awk '{if ( $8 == "QHTJO2UX" ) { printf ("kill -9 %d \n" , $2 ) } }' >  QH_kill.sh

#-----プロセス強制休止-----------------------------------------------------------
chmod 777 QH_kill.sh
QH_kill.sh


$LOGWRITE "$MODULE" I "終了:$STEPKINOU" $USERKEY


##################################
# STEP-6 請求メモテーブル登録処理
##################################

set MODULE = 'QH_kill.sh'
set STEPKINOU = '請求メモテーブル登録処理 削除'
$LOGWRITE "$MODULE" I "開始:$STEPKINOU" $USERKEY


#-----強制休止プロセス名設定／休止シェルファイル作成-----------------------------
#                         "xxxxx"を対象プログラム名として記入する.
ps -ef | awk '{if ( $8 == "QHTJO3UX" ) { printf ("kill -9 %d \n" , $2 ) } }' >  QH_kill.sh

#-----プロセス強制休止-----------------------------------------------------------
chmod 777 QH_kill.sh
QH_kill.sh


$LOGWRITE "$MODULE" I "終了:$STEPKINOU" $USERKEY



##########################################
# STEP-99      後始末                    #
##########################################

STEP_99:

set MODULE = 'SHELL'

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   # 終了メッセージの出力

exit 0

