#!/bin/csh
# 　スクリプト名 ： QLDJA9UX
#　 機  能       ： 日次配信要求1・クレジット帳票 (赤黒非表示追加プルーフリスト)
#　 作成者       ： FIP
#

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                                 # シェル名
setenv JOB_ID       $SHELL_NAME:t                      # ジョブ名
setenv JOBNET_ID   'QLDHY1UX'                          # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
set    USERKEY    = 'HAISIN-YOUKYUU'                   # ユーザキー
set    KINOU      = '日次配信要求1・クレジット帳票 (赤黒非表示追加プルーフリスト)' # 機能

#########################################
# STEP-1                                #
#########################################

set MODULE = 'utlrecv'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"   # 開始メッセージの出力

### 送信要求の実行 ###
utlrecv  -f OFQF09 -sync
set rc = $status

if ( $rc != 0 ) then
        $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
        exit  1                                      # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   # 終了メッセージの出力
exit 0                                           # 正常終了
