#!/bin/csh
#　スクリプト名  ： QLDJRDUX
#　 機  能       ： 日次受信Ｆリカバリ・クレジット帳票 (他口座預り金結果リスト)
#　 作成者       ： FIP
#

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                                 # シェル名
setenv JOB_ID       $SHELL_NAME:t                      # ジョブ名
setenv JOBNET_ID   'QLER01UX'                          # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
set    USERKEY    = 'JYUSIN-BACKUP'                    # ユーザキー
set    KINOU      = '日次受信Ｆリカバリ・クレジット帳票 (他口座預り金結果リスト)'

#########################################
# STEP-1                                #
#########################################
set MODULE = 'SHELL'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"   # 開始メッセージの出力

### 受信ファイルを繰越ファイルにコピーする ###

cp $QV_DATA_DIR/qv/data/host/merge/QVAF_S001400.hft $QV_DATA_DIR/qv/data/host/zen/QVAF_S001400.kur

set rc = $status

if ( $rc != 0 ) then
        $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
        exit  1                                      # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   # 終了メッセージの出力
exit 0                                           # 正常終了
