#!/bin/csh
# 　スクリプト名 ： QLDJX1UX
#　 機  能       ： 早朝日次バッチ終了通知
#　 作成者       ： FIP
#

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                                 # シェル名
setenv JOB_ID       $SHELL_NAME:t                      # ジョブ名
setenv JOBNET_ID   'QLDHS3UX'                          # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
set    USERKEY    = '0KEN-HAISIN'                      # ユーザキー
set    KINOU      = '早朝日次バッチ終了通知'           # 機能

#########################################
# STEP-1                                #
#########################################

set MODULE = 'utlsend'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"   # 開始メッセージの出力

### 送信要求の実行 ###
utlsend  -f OFQA79 -sync
set rc = $status

if ( $rc != 0 ) then
        $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
        exit  1                                      # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   # 終了メッセージの出力
exit 0                                           # 正常終了
