#!/bin/csh
#　 スクリプト名 ： QLHJ15UX
#　 業  務       : クレジット帳票
#　 機  能       ： 現行期末処理
#　 作成者       ： FIP
#
#　 修正履歴
# 項番   管理番号    修正内容                修正者         修正日
# 000001 0807073     非互換対応              NBC.SHIBUICHI  2009/03/29
# 000001 0808052     非互換対応              NBC.SHIBUICHI  2009/03/29

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                                 # シェル名 file 名=job名
setenv JOB_ID       $SHELL_NAME:t                      # ジョブ名
setenv JOBNET_ID   'QLH141UX'                          # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
set    USERKEY    = $JOBNET_ID                         # ユーザキー
set    PRM_JOBNET = "'"$JOBNET_ID"'"
set    PRM_JOB    = "'"$JOB_ID"'"


###################################################################
# STEP-1     ＳＱＬローダーの実行                                 #
###################################################################

###################################################################
##set   LDR_CTRL_DIR  = '/home/ipc/qv/ldr'                #LOADER CONTROL DIR
##set   DATAV_DIR     = '/home/ipc/qv/host_data'          #DATA DIR
##set   USER_LOG_DIR  = '/home/ipc/qv/ldrlog'             #LOADER LOG DIR
##set   LDR_LOG_DIR   = '/home/ipc/qv/ldrlog'
set   DATAV_DIR     = $QV_DATA_DIR'/qv/data/host/merge'   #DATA DIR
set   DATAV_S     = '.hft'  			          #DATA 拡張子

###################################################################
# STEP-1.1   ＳＱＬローダーの実行  店間決済データ(受託分)決済半月 #
###################################################################
set    KINOU      = 'クレジット帳票：現行期末処理 LOADER(店間決済データ(受託分)決済半月)'
set    CTLID      = 'QVAD_SLD4200'              #LOADER CONTROL F名
set    DATAID     = 'QVBF_S004200'$DATAV_S      #DATA
set    MODULE     = $CTLID 
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"  # 開始メッセージの出力
setenv NLS_LANG Japanese_Japan.JA16SJIS

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlldr $DB_USERID/$DB_PASSWORD           \
sqlldr $DB_USERID/$DB_PASSWORD@$ORACLE_SID\
       control=$LDR_CTRL_DIR/$CTLID.ctl  \
       data=$DATAV_DIR/$DATAID           \
       log=$LDR_LOG_DIR/ldr.log          \
       >& $USER_LOG_DIR/ldr1.log
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

#echo 'normal end'
set rc = $status
setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
        $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
        exit  1                                  # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"  # 終了メッセージの出力


###################################################################
# STEP-1.2 ＳＱＬローダーの実行 店間決済データ(総合斡旋分)決済半月#
###################################################################
set    KINOU      = 'クレジット帳票：現行期末処理 LOADER(店間決済データ(総合斡旋分)決済半月)'
set    CTLID      = 'QVAD_SLD4300'              #LOADER CONTROL F名
set    DATAID     = 'QVBF_S004300'$DATAV_S      #DATA
set    MODULE     = $CTLID 
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"  # 開始メッセージの出力
setenv NLS_LANG Japanese_Japan.JA16SJIS

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlldr $DB_USERID/$DB_PASSWORD           \
sqlldr $DB_USERID/$DB_PASSWORD@$ORACLE_SID\
       control=$LDR_CTRL_DIR/$CTLID.ctl  \
       data=$DATAV_DIR/$DATAID           \
       log=$LDR_LOG_DIR/ldr.log          \
       >& $USER_LOG_DIR/ldr1.log 
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

#echo 'normal end'
set rc = $status
setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
        $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
        exit  1                                  # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"  # 終了メッセージの出力


###################################################################
# STEP-1.3  ＳＱＬローダーの実行     店間決済合計表データ決済半月 #
###################################################################
set    KINOU      = 'クレジット帳票：現行期末処理 LOADER(店間決済合計表データ決済半月)'
set    CTLID      = 'QVAD_SLD4400'              #LOADER CONTROL F名
set    DATAID     = 'QVBF_S004400'$DATAV_S      #DATA
set    MODULE     = $CTLID 
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"  # 開始メッセージの出力
setenv NLS_LANG Japanese_Japan.JA16SJIS

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlldr $DB_USERID/$DB_PASSWORD           \
sqlldr $DB_USERID/$DB_PASSWORD@$ORACLE_SID\
       control=$LDR_CTRL_DIR/$CTLID.ctl  \
       data=$DATAV_DIR/$DATAID           \
       log=$LDR_LOG_DIR/ldr.log          \
       >& $USER_LOG_DIR/ldr1.log 
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

#echo 'normal end'
set rc = $status
setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
        $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
        exit  1                                  # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"  # 終了メッセージの出力

###################################################################
# STEP-1.4    ＳＱＬローダーの実行     関係会社決済データ決済半月 #
###################################################################
set    KINOU      = 'クレジット帳票：現行期末処理 LOADER(関係会社決済データ決済半月)'
set    CTLID      = 'QVAD_SLD4500'              #LOADER CONTROL F名
set    DATAID     = 'QVBF_S004500'$DATAV_S      #DATA
set    MODULE     = $CTLID 
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"  # 開始メッセージの出力
setenv NLS_LANG Japanese_Japan.JA16SJIS

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlldr $DB_USERID/$DB_PASSWORD           \
sqlldr $DB_USERID/$DB_PASSWORD@$ORACLE_SID\
       control=$LDR_CTRL_DIR/$CTLID.ctl  \
       data=$DATAV_DIR/$DATAID           \
       log=$LDR_LOG_DIR/ldr.log          \
       >& $USER_LOG_DIR/ldr1.log 
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

#echo 'normal end'
set rc = $status
setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
        $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
        exit  1                                  # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"  # 終了メッセージの出力


###################################################################
# STEP-1.5    ＳＱＬローダーの実行   事務手数料算出データ決済半月 #
###################################################################
set    KINOU      = 'クレジット帳票：現行期末処理 LOADER(事務手数料算出データ決済半月)'
set    CTLID      = 'QVAD_SLD4600'              #LOADER CONTROL F名
set    DATAID     = 'QVBF_S004600'$DATAV_S      #DATA
set    MODULE     = $CTLID 
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"  # 開始メッセージの出力
setenv NLS_LANG Japanese_Japan.JA16SJIS

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlldr $DB_USERID/$DB_PASSWORD           \
sqlldr $DB_USERID/$DB_PASSWORD@$ORACLE_SID\
       control=$LDR_CTRL_DIR/$CTLID.ctl  \
       data=$DATAV_DIR/$DATAID           \
       log=$LDR_LOG_DIR/ldr.log          \
       >& $USER_LOG_DIR/ldr1.log 
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

#echo 'normal end'
set rc = $status
setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
        $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
        exit  1                                  # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"  # 終了メッセージの出力


###################################################################
# STEP-2     ストアド・プロシジャの実行                           #
###################################################################
set   MODULE = 'qusc_sspexec.exe'

########################################################################
# STEP-2.1 ストアド・プロシジャの実行 債権債務決済表（受託分）パート１ #
########################################################################
set    KINOU      = 'クレジット帳票：現行期末処理(債権債務決済表（受託分）パート１)'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"  # 開始メッセージの出力
setenv NLS_LANG Japanese_Japan.JA16SJIS
set    PRM_Data = "'5'"                          #付与ﾊﾟﾗﾒｰﾀ

$EXE_DIR/qusc_sspexec.exe  $JOBNET_ID  $JOB_ID  "QVAP_S000600Pkg.QVAP_S000600( $PRM_JOBNET, $PRM_JOB,$PRM_Data)"

set rc = $status
setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
        $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
        exit  1                                  # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"  # 終了メッセージの出力


########################################################################
# STEP-2.2 ストアド・プロシジャの実行 債権債務決済表（受託分）パート２ #
########################################################################
set    KINOU      = 'クレジット帳票：現行期末処理(債権債務決済表（受託分）パート２)'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"  # 開始メッセージの出力
setenv NLS_LANG Japanese_Japan.JA16SJIS
set    PRM_Data = "'5'"                          #付与ﾊﾟﾗﾒｰﾀ

$EXE_DIR/qusc_sspexec.exe  $JOBNET_ID  $JOB_ID  "QVAP_S000700Pkg.QVAP_S000700( $PRM_JOBNET, $PRM_JOB,$PRM_Data)"

set rc = $status
setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
        $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
        exit  1                                  # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"  # 終了メッセージの出力


########################################################################
# STEP-2.3 ストアド・プロシジャの実行   債権債務決済表(総合斡旋分)     #
########################################################################
set    KINOU      = 'クレジット帳票：現行期末処理(債権債務決済表(総合斡旋分))'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"  # 開始メッセージの出力
setenv NLS_LANG Japanese_Japan.JA16SJIS
set    PRM_Data = "'5'"                          #付与ﾊﾟﾗﾒｰﾀ

$EXE_DIR/qusc_sspexec.exe  $JOBNET_ID  $JOB_ID  "QVAP_S000800Pkg.QVAP_S000800( $PRM_JOBNET, $PRM_JOB,$PRM_Data)"

set rc = $status
setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
        $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
        exit  1                                  # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"  # 終了メッセージの出力



########################################################################
# STEP-2.4 ストアド・プロシジャの実行   店間決済合計表作成             #
########################################################################
set    KINOU      = 'クレジット帳票：現行期末処理(店間決済合計表作成)'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"  # 開始メッセージの出力
setenv NLS_LANG Japanese_Japan.JA16SJIS
set    PRM_Data = "'5'"                          #付与ﾊﾟﾗﾒｰﾀ

$EXE_DIR/qusc_sspexec.exe  $JOBNET_ID  $JOB_ID  "QVAP_S000900Pkg.QVAP_S000900( $PRM_JOBNET, $PRM_JOB,$PRM_Data)"

set rc = $status
setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
        $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
        exit  1                                  # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"  # 終了メッセージの出力


########################################################################
# STEP-2.5 ストアド・プロシジャの実行   関係会社決済表パート１作成     #
########################################################################
set    KINOU      = 'クレジット帳票：現行期末処理(関係会社決済表パート１作成)'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"  # 開始メッセージの出力
setenv NLS_LANG Japanese_Japan.JA16SJIS
set    PRM_Data = "'5'"                          #付与ﾊﾟﾗﾒｰﾀ

$EXE_DIR/qusc_sspexec.exe  $JOBNET_ID  $JOB_ID  "QVAP_S001000Pkg.QVAP_S001000( $PRM_JOBNET, $PRM_JOB,$PRM_Data)"

set rc = $status
setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
        $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
        exit  1                                  # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"  # 終了メッセージの出力


########################################################################
# STEP-2.6 ストアド・プロシジャの実行   関係会社決済表パート２作成     #
########################################################################
set    KINOU      = 'クレジット帳票：現行期末処理(関係会社決済表パート２作成)'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"  # 開始メッセージの出力
setenv NLS_LANG Japanese_Japan.JA16SJIS
set    PRM_Data = "'5'"                          #付与ﾊﾟﾗﾒｰﾀ

$EXE_DIR/qusc_sspexec.exe  $JOBNET_ID  $JOB_ID  "QVAP_S001100Pkg.QVAP_S001100( $PRM_JOBNET, $PRM_JOB,$PRM_Data)"

set rc = $status
setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
        $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
        exit  1                                  # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"  # 終了メッセージの出力


########################################################################
# STEP-2.7 ストアド・プロシジャの実行   事務手数料算出表作成           #
########################################################################
set    KINOU      = 'クレジット帳票：現行期末処理(事務手数料算出表作成)'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"  # 開始メッセージの出力
setenv NLS_LANG Japanese_Japan.JA16SJIS
set    PRM_Data = "'5'"                          #付与ﾊﾟﾗﾒｰﾀ

$EXE_DIR/qusc_sspexec.exe  $JOBNET_ID  $JOB_ID  "QVAP_S001200Pkg.QVAP_S001200( $PRM_JOBNET, $PRM_JOB,$PRM_Data)"

set rc = $status
setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
        $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
        exit  1                                  # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"  # 終了メッセージの出力


###################################################################
#                           終 了                                 #
###################################################################
exit 0                                           # 正常終了

~
