#!/bin/csh
#-------------------------------------------------------#
#　スクリプト名  ： QLTJW1UX
#  機能          ： 立替金内訳表LOAD処理
#  作成日        ： 2018/8/2
#  作成者        ： FIP
#-------------------------------------------------------#
# 修正履歴

########################################################
#   環境設定
########################################################
set    SHELL_NAME = $0                                  # シェル名
setenv JOBNET_ID    'QLTW01UX'                          # ジョブネット名
setenv JOB_ID       'QLTJW1UX'                          # ジョブ名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log         # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT            # ログ出力モジュール
setenv USERKEY      'QLTJW1UX'                          # ユーザキー
set    MODULE     = $JOB_ID
set    QA_HUL_DIR = /s030/UFS/fromhost/qv/rcv           # ハルフトエリア（本番用）

########################################################
#   開始
########################################################
echo "***<< $MODULE STR (`date +%y%m%d`/`date +%H%M%S`) >>***"
echo "***<< $MODULE STR (`date +%y%m%d`/`date +%H%M%S`) >>***" > $LOGFILE
set    KINOU      = '立替金内訳表LOAD処理'
$LOGWRITE  "$MODULE" I "ＪＯＢ開始:$KINOU" "$USERKEY"         # 開始メッセージの出力

sqlldr $DB_USERID/$DB_PASSWORD@$ORACLE_SID              \
       control = $LDR_CTRL_DIR/Loader_QLTL1.cntl        \
       data    = $QA_HUL_DIR/OFEK37.csv                 \
       log     = $LDR_LOG_DIR/Loader_QLTJ.log           \
       errors=999999                              >> $LOGFILE

set rc = $status
if $rc != 0 then
   $LOGWRITE "$MODULE " E "ERROR :$KINOU RC=[$rc]" "$USERKEY"
   echo "*****<< SQL*LOADER ERROR RC=[$rc] >>*****"
   exit(1)
endif

########################################################
#   終了
########################################################
echo "***<< $MODULE END (`date +%y%m%d`/`date +%H%M%S`) >>***"
echo "***<< $MODULE END (`date +%y%m%d`/`date +%H%M%S`) >>***" >> $LOGFILE
$LOGWRITE  "$MODULE" I "ＪＯＢ終了:$KINOU" "$USERKEY"         # 終了メッセージの出力

exit(0)
