#!/bin/csh
# 　スクリプト名 ： QLYJN4UX
#　 機  能       ： 年末配信要求16・クレジット帳票 (売掛金残高表（年計）) 
#　 作成者       ： FIP
#

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                                 # シェル名
setenv JOB_ID       $SHELL_NAME:t                      # ジョブ名
setenv JOBNET_ID   'QVYHS2UX'                          # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
set    USERKEY    = '0KEN-HAISIN'                      # ユーザキー
set    KINOU      = '年末配信要求16・クレジット帳票 (売掛金残高表（年計）) '  # 機能

#########################################
# STEP-1                                #
#########################################

set MODULE = 'utlsend'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"   # 開始メッセージの出力

### 0件ファイル生成 ###
rm     $FROMHOST2_DIR/qv/rcv/QVCF_S005500.jsn
touch  $FROMHOST2_DIR/qv/rcv/QVCF_S005500.jsn

### 送信要求の実行 ###
utlsend  -f OFQF56 -sync
set rc = $status

if ( $rc != 0 ) then
        $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
        exit  1                                      # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   # 終了メッセージの出力
exit 0                                           # 正常終了
