#!/bin/csh
#　スクリプト名  ： QMEJ01UX
#　 機  能       ： 日次バッチリカバリ処理・臨時カードポイント還元データ繰越Ｆ作成
#　 作成者       ： 芦久保
#

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                                 # シェル名
setenv JOB_ID       $SHELL_NAME:t                      # ジョブ名
setenv JOBNET_ID   'QMD001UX'                          # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
set    USERKEY    = 'QMEJ01UX'
set    KINOU      = '日次バッチリカバリ処理・臨時カードポイント還元データ繰越Ｆ作成'

#########################################
# STEP-1                                #
#########################################
set MODULE = 'SHELL'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"   # 開始メッセージの出力

### 受信ファイルを繰越ファイルにコピーする ###

cp $QJ_DATA_DIR/qm/data/host/merge/qmbf_pointkangen.hft $QJ_DATA_DIR/qm/data/host/zen/qmbf_pointkangen.kur

set rc = $status

if ( $rc != 0 ) then
	$LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
	exit  1                                      # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   # 終了メッセージの出力
exit 0                                           # 正常終了

