#!/bin/csh
#　スクリプト名  ： QMTJ68UX
#　 プロセス     ： 抽選結果取込
#　 機  能       ： ポイント付与抽選結果テーブル登録
#　 作成者       ： FIP
#　 更新者       ：
#
#　 修正履歴
# 項番   管理番号    修正内容                修正者         修正日
# 000001 0807073     非互換対応              NBC.SHIBUICHI  2009/03/29
# 000001 0808052     非互換対応              NBC.SHIBUICHI  2009/03/29

##########################################
#         共通環境設定                   #
##########################################
set    SHELL_NAME = $0                                      # シェル名
setenv JOB_ID       $SHELL_NAME:t                           # ジョブ名
setenv JOBNET_ID    'QMT408UX'                              # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log             # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT                # ログ出力モジュール
setenv USERKEY      'QMTJ68UX'                              # ユーザキー
set    KINOU      = 'ポイント付与・抽選結果テーブル登録'

##########################################
#         固有環境設定                   #
##########################################
set    DATDIR     = /d321/UFS/data/qma
setenv INFILE1      $DATDIR/qmab_s001000_OT1.dat

##########################################
#         処理開始メッセージ             #
##########################################
set MODULE        = 'SHELL'                                 # モジュール
$LOGWRITE "$MODULE" I "開始：$KINOU" "$USERKEY"             # 開始メッセージの出力

#########################################
# STEP-1 インデックスの削除             #
#########################################
STEP_1:

set    MODULE     = 'SQL*PLUS'
set    STEPKINOU  = 'QMA6 インデックス削除'
$LOGWRITE "$MODULE" I "開始：$STEPKINOU" $USERKEY

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF > $LOGFILE
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF > $LOGFILE
drop index XIE1QMA6_PCANKEKKAT;

quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
     set MSG = "失敗: $STEPKINOU RC=[$rc]"
    $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
    exit  1
endif

$LOGWRITE "$MODULE" I "終了：$STEPKINOU" $USERKEY

##########################################
# STEP-2 主キー制約削除                  #
##########################################
STEP_2:

set    MODULE     = 'SQL*PLUS'
set    STEPKINOU  = 'QMA6 主キー制約削除'

$LOGWRITE "$MODULE" I "開始：$STEPKINOU" $USERKEY

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF > $LOGFILE
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF > $LOGFILE
ALTER TABLE QMA6_PCANKEKKAT   drop primary key;
QUIT SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
     set MSG = "失敗: $STEPKINOU RC=[$rc]"
     $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
     exit  1
endif

$LOGWRITE "$MODULE" I "終了：$STEPKINOU" $USERKEY

##################################
# STEP-3 データロード            #
##################################
STEP_3:
set STEPKINOU    = 'ポイント付与抽選結果ＴＬＯＡＤ'
set TABLE_NAME   = QMA6_PCANKEKKAT                        #対象テーブル名
set MODULE       = 'SQL*LOADER'

$LOGWRITE  "$MODULE" I "開始：$STEPKINOU  " "$USERKEY"

setenv NLS_LANG  Japanese_Japan.JA16SJIS

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlldr $DB_USERID/$DB_PASSWORD                  \
sqlldr $DB_USERID/$DB_PASSWORD@$ORACLE_SID       \
   control=$LDR_CTRL_DIR/QMA6_PCANKEKKAT.ctl    \
   data=$INFILE1                                \
   log=$LDR_LOG_DIR/QMA6_PCANKEKKAT.log         \
   direct=true                                  \
               > $LOGFILE
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
setenv NLS_LANG  Japanese_Japan.JA16EUC
if ($rc != 0) then
   set MSG = "失敗：$STEPKINOU  RC=[$rc]"
    $LOGWRITE "$MODULE" E "$MSG" "$USERKEY"
   exit(1)                                                #異常終了
endif

$LOGWRITE "$MODULE" I "終了：$STEPKINOU " "$USERKEY"

#########################################
# STEP-4 インデックスの付与             #
#########################################
STEP_4:

set MODULE     = 'SQL*PLUS'
set STEPKINOU  = 'QMA6 ポイント付与・キー付与'

$LOGWRITE  "$MODULE" I "開始：$STEPKINOU  " "$USERKEY"

setenv NLS_LANG  Japanese_Japan.JA16SJIS      #文字コード体系をSJISにする

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF > $LOGFILE
#CREATE INDEX XIE1QMA6_PCANKEKKAT
#     ON QMA6_PCANKEKKAT
#          (
#               QMA6_CARDNO
#          )
#          TABLESPACE  POINTHUY
#               STORAGE (
#                    INITIAL      18330K
#                    NEXT         1334K
#                    MINEXTENTS   1
#                    MAXEXTENTS   100
#                    PCTINCREASE  5
#                    );
#quit SQL.SQLCODE
#EOF

sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF > $LOGFILE
CREATE INDEX XIE1QMA6_PCANKEKKAT
     ON QMA6_PCANKEKKAT
          (
               QMA6_CARDNO
          )
          TABLESPACE  POINTHUY
               STORAGE (
                    INITIAL        12M
                    NEXT         1334K
                    MINEXTENTS       1
                    MAXEXTENTS     100
                    PCTINCREASE      5
                    );
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
    set MSG = "失敗：$STEPKINOU  RC=[$rc]"
    $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
    exit  1
endif

$LOGWRITE "$MODULE" I "終了：$STEPKINOU " "$USERKEY"

##########################################
# STEP-5 主キー制約付与                  #
##########################################
STEP_5:

set MODULE     = 'SQL*PLUS'
set STEPKINOU  = 'QMA6 ポイント付与・主キー付与'

$LOGWRITE  "$MODULE" I "開始：$STEPKINOU  " "$USERKEY"

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF > $LOGFILE
#ALTER TABLE QMA6_PCANKEKKAT ADD
#     PRIMARY KEY
#          (QMA6_PRMPCANID1,
#           QMA6_PRMPCANID2,
#           QMA6_PRMOYOKORENBAN,
#           QMA6_PRMKIGYOUCD,
#           QMA6_PRMSUBRANGEKEY,
#           QMA6_PRMNAIBUKAIINNO,
#           QMA6_PRMRIYOUSHACD)
#          USING INDEX NOLOGGING
#          TABLESPACE POINTHUY
#          STORAGE (
#               INITIAL     18330K
#               NEXT        1334K
#               MINEXTENTS  1
#               MAXEXTENTS  100
#               PCTINCREASE 5
#               );
#quit SQL.SQLCODE
#EOF

sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF > $LOGFILE
ALTER TABLE QMA6_PCANKEKKAT ADD
     PRIMARY KEY
          (QMA6_PRMPCANID1,
           QMA6_PRMPCANID2,
           QMA6_PRMOYOKORENBAN,
           QMA6_PRMKIGYOUCD,
           QMA6_PRMSUBRANGEKEY,
           QMA6_PRMNAIBUKAIINNO,
           QMA6_PRMRIYOUSHACD)
          USING INDEX NOLOGGING
          TABLESPACE POINTHUY
          STORAGE (
               INITIAL       12M
               NEXT        1334K
               MINEXTENTS      1
               MAXEXTENTS    100
               PCTINCREASE     5
               );
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
    set MSG = "失敗：$STEPKINOU  RC=[$rc]"
    $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
    exit  1
endif

$LOGWRITE "$MODULE" I "終了：$STEPKINOU " "$USERKEY"

##########################################
# STEP-6 中間ファイル削除                #
##########################################
STEP_6:
rm $INFILE1

##################################
# STEP-99  終了メッセージ出力    #
##################################
STEP_99:
set MODULE = 'SHELL'
$LOGWRITE "$MODULE" I "終了：$KINOU" "$USERKEY"           # 終了メッセージの出力

exit(0)
