#!/bin/csh
#　スクリプト名  ： QMTJ45UX
#　 プロセス     ： ポイント付与候補者抽出
#　 機  能       ： 抽出条件テーブル登録
#　 作成者       ： FIP
#　 更新者       ：
# 修正履歴
# 項番   管理番号    修正内容                修正者         修正日
# 000001 0807073     非互換対応              NBC.ISHIDA  2009/03/29
# 000001 0808052     非互換対応              NBC.ISHIDA  2009/03/29

##########################################
#         共通環境設定                   #
##########################################
set    SHELL_NAME = $0                                      # シェル名
setenv JOB_ID       $SHELL_NAME:t                           # ジョブ名
setenv JOBNET_ID    'QMT403UX'                              # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log             # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT                # ログ出力モジュール
setenv USERKEY      'QMTJ45UX'                              # ユーザキー
set    KINOU      = 'ポイント付与・抽出条件テーブル登録'

##########################################
#         固有環境設定                   #
##########################################
set    DATDIR     = /d321/UFS/data/qma
setenv INFILE1      $DATDIR/qmab_s000400_OT1.dat

##########################################
#         処理開始メッセージ             #
##########################################
set MODULE        = 'SHELL'                                 # モジュール
$LOGWRITE "$MODULE" I "開始：$KINOU" "$USERKEY"             # 開始メッセージの出力

##########################################
# STEP-1 主キー制約削除                  #
##########################################
STEP_1:

set    MODULE     = 'SQL*PLUS'
set    STEPKINOU  = 'QMA7 主キー制約削除'

$LOGWRITE "$MODULE" I "開始：$STEPKINOU" $USERKEY
#MOD 0807073 クレジット支援システムの再構築 20090329 NBC.ISHIDA start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 NBC.ISHIDA start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF > $LOGFILE
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF > $LOGFILE
ALTER TABLE QMA7_PCANPAINWT   drop primary key;
QUIT SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 NBC.ISHIDA end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 NBC.ISHIDA end

set rc = $status
if ( $rc != 0 ) then
     set MSG = "失敗: $STEPKINOU RC=[$rc]"
     $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
     exit  1
endif

$LOGWRITE "$MODULE" I "終了：$STEPKINOU" $USERKEY

##################################
# STEP-2 データロード            #
##################################
STEP_2:
set STEPKINOU    = '抽出条件ＴＬＯＡＤ'
set TABLE_NAME   = QMA7_PCANPAINWT                        #対象テーブル名
set MODULE       = 'SQL*LOADER'
    $LOGWRITE  "$MODULE" I "開始：$STEPKINOU  " "$USERKEY"

setenv NLS_LANG  Japanese_Japan.JA16SJIS
#MOD 0807073 クレジット支援システムの再構築 20090329 NBC.ISHIDA start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 NBC.ISHIDA start
#sqlldr $DB_USERID/$DB_PASSWORD                  \
sqlldr $DB_USERID/$DB_PASSWORD@$ORACLE_SID                  \
   control=$LDR_CTRL_DIR/QMA7_PCANPAINWT.ctl    \
   data=$INFILE1                                \
   log=$LDR_LOG_DIR/QMA7_PCANPAINWT.log         \
   direct=true                                  \
               > $LOGFILE
#MOD 0807073 クレジット支援システムの再構築 20090329 NBC.ISHIDA end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 NBC.ISHIDA end

set rc = $status
setenv NLS_LANG  Japanese_Japan.JA16EUC
if ($rc != 0) then
   set MSG = "失敗：$STEPKINOU  RC=[$rc]"
    $LOGWRITE "$MODULE" E "$MSG" "$USERKEY"
   exit(1)                                                #異常終了
endif

  $LOGWRITE "$MODULE" I "終了：$STEPKINOU " "$USERKEY"

##########################################
# STEP-3 主キー制約付与                  #
##########################################
STEP_3:

set MODULE     = 'SQL*PLUS'
set STEPKINOU  = 'QMA7 主キー付与'

$LOGWRITE  "$MODULE" I "開始：$STEPKINOU  " "$USERKEY"
#MOD 0807073 クレジット支援システムの再構築 20090329 NBC.ISHIDA start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 NBC.ISHIDA start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF > $LOGFILE
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF > $LOGFILE
ALTER TABLE QMA7_PCANPAINWT ADD
     PRIMARY KEY
          (QMA7_PRMRENBAN,
           QMA7_PRMPCANID1,
           QMA7_PRMPCANID2,
           QMA7_PRMOYOKORENBAN)
          USING INDEX NOLOGGING
          TABLESPACE POINTHUY
          STORAGE (
               INITIAL     4K
               NEXT        2K
               MINEXTENTS  1
               MAXEXTENTS  100
               PCTINCREASE 5
               );
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 NBC.ISHIDA end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 NBC.ISHIDA end

set rc = $status
if ( $rc != 0 ) then
    set MSG = "失敗：$STEPKINOU  RC=[$rc]"
    $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
    exit  1
endif

$LOGWRITE "$MODULE" I "終了：$STEPKINOU " "$USERKEY"

##########################################
# STEP-4 中間ファイル削除                #
##########################################
STEP_4:
rm $INFILE1

##########################################
# STEP-99  終了メッセージ出力            #
##########################################
STEP_99:
set MODULE        = 'SHELL'
$LOGWRITE "$MODULE" I "終了：$KINOU" "$USERKEY"             # 終了メッセージの出力

exit(0)
