#!/bin/csh
#　スクリプト名  ： QPDJK2UX
#　 機  能       ： 社員融資Ｔ期日管理
#　 作成者       ： FIP
#

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                                 # シェル名
setenv JOB_ID       $SHELL_NAME:t                      # ジョブ名
setenv JOBNET_ID   'QPDBB1UX'                          # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
setenv USERKEY      'QPDJK2UX'                         # ユーザキー
set    KINOU      = '小口融資Ｔ期日管理'
set    QP_DATA_DIR  = /d051/UFS/data/qp                #TMP FILE DIR
set    QP_HUL_DIR   = /s020/UFS/fromhost/qp/rcv        #TMP FILE DIR

#########################################
# STEP-1 小口融資Ｔ期日管理             #
#########################################

set MODULE = 'COBOL'
$LOGWRITE "$MODULE" I "開始:社員貸付・社員融資Ｔ期日管理" "$USERKEY"     # 開始メッセージの出力

set PROGRAM = $EXE_DIR/qpab_s000710.exe

if ( -x $PROGRAM ) then
    #  ファイル識別子の設定
    #
    #
    #
    setenv NLS_LANG Japanese_Japan.JA16SJIS      # 文字コード体系をSJISにする
    $PROGRAM > &  $LOGFILE                                  # プログラム起動
    set rc = $status                             # リターンステータス待避
    setenv NLS_LANG Japanese_Japan.JA16EUC       # 文字コード体系をEUCに戻す
else
    $LOGWRITE  "$MODULE"  E  "実行プログラム[$PROGRAM]が存在しない。" "$USERKEY"
    exit 1                                       # 異常終了
endif

if ( $rc != 0 ) then                              # リターンステータス判定
    exit  1                                      # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:社員貸付・社員融資Ｔ期日管理" "$USERKEY"     # 終了メッセージの出力

exit 0                                           # 正常終了

