#!/bin/csh
#　スクリプト名  ： QPDJB3UX
#　 機  能       ： ホスト貸付データロード
#　 作成者       ： FIP
#
#  修正番号 修正者   修正日次   修正内容
# 2004/09/16 入力データクリア処理を削除 IMZ.YAMADA
#  000001   hayashi  2007/07/13 ﾛｰﾀﾞｰ後ｲﾝﾃﾞｯｸｽﾁｪｯｸ追加

#　 修正履歴
# 項番   管理番号    修正内容                修正者         修正日
# 000001 0807073     非互換対応              NBC.SHIBUICHI  2009/03/29
# 000001 0808052     非互換対応              NBC.SHIBUICHI  2009/03/29

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                                 # シェル名
setenv JOB_ID       $SHELL_NAME:t                      # ジョブ名
setenv JOBNET_ID   'QPDIXXUX'                          # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
setenv USERKEY      'QPDJB3UX'                         # ユーザキー
set    KINOU      = 'ホスト貸付データロード'
set    QP_DATA_DIR  = /d051/UFS/data/qp                #TMP FILE DIR
set    QP_HUL_DIR   = /s020/UFS/fromhost/qp/rcv        #TMP FILE DIR
# 000001 hayashi add 2007/07/13 start
set TABLE_NAME = QPA6_KGCKASITUKET            # 対象テーブル名
# 000001 hayashi add 2007/07/13 end

#########################################
# STEP-1  ﾊﾙﾌﾄﾌｧｲﾙのﾍｯﾀﾞｰ取除きCOBOL    #
#########################################

set MODULE = 'COBOL'
$LOGWRITE "$MODULE" I "開始:社員貸付・控除テーブルデータﾍｯﾀﾞｰ処理" "$USERKEY"     # 開始メッセージの出力

set PROGRAM = $EXE_DIR/qpab_s000600.exe

if ( -x $PROGRAM ) then
    #  ファイル識別子の設定
    setenv INFILE   $QP_DATA_DIR/qpb1_hostkasituke.dat
    setenv OTFILE   $QP_DATA_DIR/qpb1_hostkasituke.dat1
    #
    #
    setenv NLS_LANG Japanese_Japan.JA16SJIS      # 文字コード体系をSJISにする
    $PROGRAM > &  $LOGFILE                                  # プログラム起動
    set rc = $status                             # リターンステータス待避
    setenv NLS_LANG Japanese_Japan.JA16EUC       # 文字コード体系をEUCに戻す
else
    $LOGWRITE  "$MODULE"  E  "実行プログラム[$PROGRAM]が存在しない。" "$USERKEY"
    exit 1                                       # 異常終了
endif

if ( $rc != 0 ) then                              # リターンステータス判定
    exit  1                                      # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:社員貸付・社員貸付・控除テーブルデータﾍｯﾀﾞｰ処理" "$USERKEY"     # 終了メッセージの出力


#########################################
# STEP-2  ファイルコピー                #
#########################################

set MODULE = 'shell'
$LOGWRITE "$MODULE" I "開始:控除ﾃｰﾌﾞﾙﾃﾞｰﾀﾌｧｲﾙコピー" "$USERKEY"    # 開始メッセージの出力
  cp $QP_DATA_DIR/qpb1_hostkasituke.dat1 $QP_DATA_DIR/qpb1_hostkasituke.dat
$LOGWRITE "$MODULE" I "終了:控除ﾃｰﾌﾞﾙﾃﾞｰﾀﾌｧｲﾙコピー" "$USERKEY"    # 終了メッセージの出力

#########################################
# STEP-3  控除ﾃｰﾌﾞﾙへロード             #
#########################################

set MODULE = 'SQL*LOADER'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"    # 開始メッセージの出力

#外字を含むﾎｽﾄﾃﾞｰﾀを従来型ﾊﾟｽﾛｰﾄﾞでﾛｰﾄﾞ
setenv NLS_LANG Japanese_Japan.JA16SJIS

### SQL*LOADERの実行 ###
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlldr $DB_USERID/$DB_PASSWORD                           \
sqlldr $DB_USERID/$DB_PASSWORD@$ORACLE_SID                \
   control = $LDR_CTRL_DIR/qpb1_hostkasituke.sql         \
   data    = $QP_DATA_DIR/qpb1_hostkasituke.dat          \
   log     = $LDR_LOG_DIR/qpb1_hostkasituke.log          \
   direct=true                                           \
             > $LOGFILE
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status

#外字を含むﾎｽﾄﾃﾞｰﾀを従来型ﾊﾟｽﾛｰﾄﾞでﾛｰﾄﾞ
setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
    $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
    exit  1                                      # 異常終了
endif
# 000001 hayashi add 2007/07/13 start
#----------------------------------------------------------#
#   インデックスエラーのチェック
#----------------------------------------------------------#
rm -f ${LOGFILE}2 ${LOGFILE}3

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF > ${LOGFILE}2
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF > ${LOGFILE}2
set lin 200
select index_name,status from user_indexes
       where table_name = '$TABLE_NAME'  and
             status     = 'UNUSABLE';
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
    set MSG = "失敗:データロード(sqlplus) RC=[$rc]"
    $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
    exit  1
endif
grep "UNUSABLE" `find ${USER_LOG_DIR} -name "${JOB_ID}.log2" -print` > ${LOGFILE}3
if !(-z ${LOGFILE}3 ) then
    set MSG = "失敗:データロード(grep) RC=[$rc]"
    $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
    exit  1
endif
# 000001 hayashi add 2007/07/13 end
$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"    # 終了メッセージの出力

#########################################
# STEP-1  ﾌｧｲﾙ０件処理                  #
#########################################
# 2004/09/15 -->
#set MODULE = 'shell'
#$LOGWRITE "$MODULE" I "開始:控除ﾃｰﾌﾞﾙﾃﾞｰﾀdatﾌｧｲﾙ０件処理" "$USERKEY"    # 開始メッセージの出力
#  cp /dev/null $QP_DATA_DIR/qpb1_hostkasituke.dat
#$LOGWRITE "$MODULE" I "終了:控除ﾃｰﾌﾞﾙﾃﾞｰﾀdatﾌｧｲﾙ０件処理" "$USERKEY"    # 終了メッセージの出力
# 2004/09/15 <--

exit 0                                           # 正常終了

