#!/bin/csh
# 　スクリプト名 ： QPHJB3UX
#　 業  務       ： 社員貸付システム
#　 機  能       ： 履歴登録処理、賞与控除データ処理（社員貸付二次）
#　 作成者       ： FIP
#
#   項番     修正日      修正者         修正内容
#

##################################
#           環境設定             #
##################################
set    SHELL_NAME  = $0                                 # シェル名
setenv JOB_ID        $SHELL_NAME:t                      # ジョブ名
setenv JOBNET_ID    'QPHBE1UX'                          # ジョブネット名
set    LOGFILE     = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE    = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
set    USERKEY     = 'QPHJB3UX'                         # ユーザキー 
set    KINOU       = '社員貸付履歴登録・賞与控除データ登録'
set    MODULE      = 'SHELL'
set    PRM_JOBNET  =  "'"$JOBNET_ID"'"
set    PRM_JOB     = "'"$JOB_ID"'"

$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"     # 開始メッセージの出力


#########################################
# STEP-1 賞与控除データ登録             #
#########################################
set MODULE = 'qusc_sspexec.exe'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"     # 開始メッセージの出力

setenv NLS_LANG Japanese_Japan.JA16SJIS

$EXE_DIR/qusc_sspexec.exe  $JOBNET_ID  $JOB_ID "tccuser.QPAP_CEnt1530PkG.QPAP_ZNDK_SYKJTURK($PRM_JOBNET, $PRM_JOB)"

set rc = $status
setenv NLS_LANG Japanese_Japan.JA16EUC
if ($rc != 0) then
    $LOGWRITE "$MODULE" E "異常:$KINOU QPAP_CEnt1530PkG.QPAP_ZNDK_SYKJTURK RC=[$rc]" "$USERKEY"
    echo "QPAP_CEnt1530PkG.QPAP_ZNDK_SYKJTURK ABNORMAL ENDED : RC=[$rc]"
    exit 1
endif
$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"     # 終了メッセージの出力


#########################################
# STEP-4 終了処理                       #
#########################################
set    MODULE     = 'SHELL'
$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"     # 終了メッセージの出力
exit 0                                             # 正常終了
