#!/bin/csh
#　スクリプト名  ： QPTJG6UX
#　 機  能       ： 社員マスタデータファイルマージ
#　 作成者       ： FIP
#
#-------------------------------------------------------------------------
#          修  正  履  歴
# 管理No              修正内容                    担当者      修正日付
#--------------------------------------------------------------------------
##################################
#           環境設定             #
##################################
set    SHELL_NAME   = $0                                 # シェル名
setenv JOB_ID         $SHELL_NAME:t                      # ジョブ名
setenv JOBNET_ID      'QPTGA1UX'                         # ジョブネット名
set    LOGFILE      = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE     = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
setenv USERKEY        'QPTJG6UX'                         # ユーザキー
set    KINOU        = '社員マスタ登録用データファイル作成'
set    QP_DATA_DIR  = $QV_DATA_DIR/qp                    #TMP FILE DIR
set    MODULE       = 'COBOL'

$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"           # 開始メッセージの出力

##############################################################
# STEP-1 社員マスタ・人事マスタファイルマージ                #
##############################################################
set PROGRAM = $EXE_DIR/qpab_s000130.exe
if ( -x $PROGRAM ) then
    #
    #  ファイル識別子の設定
    setenv INFIL1   $QP_DATA_DIR/zinzisort.dat           # 人事マスタソートファイル
    setenv INFIL2   $QP_DATA_DIR/prezinzisort.dat        # 社員マスタソートファイル
    setenv OTFILE   $QP_DATA_DIR/zinzim.dat              # マージファイル
    #
    setenv NLS_LANG Japanese_Japan.JA16SJIS              # 文字コード体系をSJISにする
    $PROGRAM > &  $LOGFILE                               # プログラム起動
    set rc = $status                                     # リターンステータス待避
    setenv NLS_LANG Japanese_Japan.JA16EUC               # 文字コード体系をEUCに戻す
else
    $LOGWRITE "$MODULE" E "実行プログラム[$PROGRAM]が存在しない。" "$USERKEY"
    exit 1                                               # 異常終了
endif

if ( $rc != 0 ) then                                     # リターンステータス判定
    set MSG = "失敗:$KINOU RC=[$rc]"
    $LOGWRITE "$MODULE" E "$MSG" $USERKEY
    exit 1                                               # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"           # 終了メッセージの出力

exit 0                                                   # 正常終了

