#!/bin/csh
#
#  オラクル開始[早朝バッチ運用モード開始前]  (QSDJS1UX)
#
#     機  能：1.リスナーが万が一起動されていなかったら起動する。
#             2.主データベースを起動する。
#             3.コンソールログライタを起動する。 ADD '99.10.04(OGAWA)
#     引  数：
#
#     EXIT値：0 --- 正常
#             1 --- エラー発生
#
# 変 更 履 歴
# 項番	日      付	修                正	担 当 者
# ----+-------------+-------------------------+---------
# 001	2006/08/08	リスナー確認方法変更	NBC 齋藤
# 002	2006/11/28	アーカイブログ出力設定	NBC 齋藤
#
set  SHELL_NAME = $0                                    # シェル名
set  MODULE   =  $SHELL_NAME:t                          # モジュール名
set  LOGFILE  = $USER_LOG_DIR/db_ope.log                # ログファイル名
set  LOGWRITE = "$EXE_DIR/QUAJ_BATCHLOG.BAT ($MODULE)"  # ログ出力用共通シェル

if ( $#argv == 1 ) then                                                         # 引数が指定されていた場合
    setenv ORACLE_SID   $1                                                      # 環境変数ORACLE_SIDを設定
endif

$LOGWRITE  "オラクル開始[早朝バッチ運用モード]" >> $LOGFILE

#####################################################
# 1. リスナーが万が一起動されていなかったら起動する #
#####################################################

# MOD-START 001 2006/08/08
# set PRCNUM = `ps -ef | grep -v 'grep' | grep -c "tnslsnr"`
# if ( $PRCNUM == 0 ) then
lsnrctl status LISTENER
set RC = $status
if ( $RC != 0 ) then
# MOD-END 001

	$EXE_DIR/QUAJ_LSNRSTART.BAT 
	if ( $status != 0 ) then
		exit 1
	endif
endif

#########################
# 2. 主データベース開始 #
#########################
# MOD-START 002 2006/11/28
#$EXE_DIR/QUAJ_DBSTART.BAT  tcc
$EXE_DIR/QUAJ_DBSTART_3.BAT  tcc
# MOD-START 002 2006/11/28
if ( $status != 0 ) then
	exit 1
endif

$LOGWRITE  "オラクル開始[早朝バッチ運用モード]正常終了" >> $LOGFILE

####################################################
# 3.   コンスログライタ起動(バックグランドシェル)  #
####################################################
$EXE_DIR/QUAJ_LWTRSTART.BAT  conslog  $ORACLE_SID &     # 非同期モードにてコンソールログライタの起動
set RC = $status
if ( $RC != 0 ) then
    exit 1
endif

echo "ConslogWriter Normaly Starting"
$LOGWRITE  "ConslogWriter Normaly Starting" >> $LOGFILE

exit 0
