#!/bin/csh
# 　スクリプト名 ： QSDJL6UX
#　 機  能       ： ＥＭＣログファイルの整理
#   実行USER     ： root
#　 作成者       ： FIP(藤川)
#
set  MODULE   = QSDJL6UX                          	# モジュール名
set  OPELOG  = $USER_LOG_DIR/db_ope.log                # ログファイル名
set  LOGWRITE = "$EXE_DIR/QUAJ_BATCHLOG.BAT ($MODULE)"  # ログ出力用共通シェル
set  EMC_EXE_DIR  = /usr/symmapps
set  LOGFILE      = $EMC_EXE_DIR/bcv.log
set  SAVE_LOGFILE = ${LOGFILE:r}_
set  SUFFIX       = ${LOGFILE:e}

set YOUBI = `date +%u`
switch ( $YOUBI )
	case  1:
		set OSIRI = sun
		breaksw
	case  2:
		set OSIRI = mon
		breaksw
	case  3:
		set OSIRI = tue
		breaksw
	case  4:
		set OSIRI = wed
		breaksw
	case  5:
		set OSIRI = thu
		breaksw
	case  6:
		set OSIRI = fri
		breaksw
	case  7:
		set OSIRI = sat
		breaksw
	default:
		set OSIRI = xxx
		breaksw
endsw

$LOGWRITE  "ＥＭＣログファイルの整理＿開始" >> $OPELOG
set SAVE_LOGFILE = ${SAVE_LOGFILE}${OSIRI}.${SUFFIX}
if ( -e $LOGFILE ) then
	su  root -c "mv  $LOGFILE $SAVE_LOGFILE"
	set RCD = $status
	$LOGWRITE  "$SAVE_LOGFILE 退避(mv)復帰値 [$RCD]" >> $OPELOG

	su  root -c "touch $LOGFILE"
	set RCD = $status
	$LOGWRITE  "$LOGFILE 生成(touch)復帰値 [$RCD]" >> $OPELOG
endif
$LOGWRITE  "ＥＭＣログファイルの整理＿終了" >> $OPELOG

exit 0

