#!/bin/csh
# 　スクリプト名 ： QSDJL9UX
#　 機  能       ： コンソール＆オペレーションログ削除処理を行う。対象は1ヵ月前とする。
#　 作成者       ： FIP(藤川)
#
# 000001 0807073     非互換対応              NBC.ishida  2009/03/29
# 000001 0808052     非互換対応              NBC.ishida  2009/03/29

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                                          # シェル名
set    MODULE     = $SHELL_NAME:t                                # モジュール名
set    LOGFILE    = $USER_LOG_DIR/db_ope.log                    # ログファイル名
set    LOGWRITE   = "$EXE_DIR/QUAJ_BATCHLOG.BAT ($MODULE)"    # ログ出力モジュール

##################################
# コンソールログ削除処理索       #
##################################
$LOGWRITE "コンソールログ削除処理開始"  >> $LOGFILE  # 開始メッセージの出力
#MOD 0807073 クレジット支援システムの再構築 20090329 NBC.ishida start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 NBC.ishida start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF >> $LOGFILE
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF >> $LOGFILE
set sqlp ""
set sqln off
set pause off
set serveroutput on

DECLARE
    numKENSU    NUMBER := 0 ;
    numCNT      NUMBER := 0 ;
    numROWID    VARCHAR2(18) ;
    CURSOR CurQUS1_CONSLOGT  IS
           select ROWID from QUS1_CONSLOGT
           where  QUS1_DATETIME < ADD_MONTHS(SYSDATE,-1);

BEGIN
    OPEN CurQUS1_CONSLOGT ;
    LOOP
         FETCH CurQUS1_CONSLOGT INTO numROWID ;
         delete from QUS1_CONSLOGT where ROWID = numROWID ;
         if  CurQUS1_CONSLOGT%NOTFOUND  then
             exit ;
         end if ;
         numKENSU := numKENSU + 1 ;
         numCNT   := numCNT   + 1 ;
         if  numCNT = 10000 then
             COMMIT ;
             numCNT := 0 ;
         end if ;
    END LOOP ;
    DBMS_OUTPUT.PUT_LINE(numKENSU || ' 件削除しました' ) ;
    CLOSE CurQUS1_CONSLOGT  ;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
         DBMS_OUTPUT.PUT_LINE( SQLCODE || ',' || SQLERRM ) ;
    WHEN OTHERS THEN
         ROLLBACK;
END;
/
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 NBC.ishida end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 NBC.ishida end

set rc = $status
if ( $rc != 0 ) then
        set MSG = "失敗:コンソールログ削除 RC=[$rc]"
        $LOGWRITE  "$MSG"  >> $LOGFILE"
        exit  1
endif

$LOGWRITE "コンソールログ削除処理終了"  >> $LOGFILE   # 終了メッセージの出力

##################################
# オペレーションログ削除処理索   #
##################################
$LOGWRITE "オペレーションログ削除処理開始"  >> $LOGFILE  # 開始メッセージの出力
#MOD 0807073 クレジット支援システムの再構築 20090329 NBC.ishida start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 NBC.ishida start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF >> $LOGFILE
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF >> $LOGFILE
set sqlp ""
set sqln off
set pause off
set serveroutput on

DECLARE
    numKENSU    NUMBER := 0 ;
    numCNT      NUMBER := 0 ;
    numROWID    VARCHAR2(18) ;
    CURSOR CurQUS2_OPELOGT  IS
           select ROWID from QUS2_OPELOGT
           where  QUS2_DATETIME < ADD_MONTHS(SYSDATE,-1);

BEGIN
    OPEN CurQUS2_OPELOGT ;
    LOOP
         FETCH  CurQUS2_OPELOGT INTO  numROWID ;
         delete from QUS2_OPELOGT where ROWID = numROWID ;
         if  CurQUS2_OPELOGT%NOTFOUND  then
               exit ;
         end if ;
         numKENSU := numKENSU + 1 ;
         numCNT   := numCNT   + 1 ;
         if  numCNT = 10000 then
             COMMIT ;
             numCNT := 0 ;
         end if ;
    END LOOP ;
    DBMS_OUTPUT.PUT_LINE(numKENSU || ' 件削除しました' ) ;
    CLOSE CurQUS2_OPELOGT  ;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
         DBMS_OUTPUT.PUT_LINE( SQLCODE || ',' || SQLERRM ) ;
    WHEN OTHERS THEN
         ROLLBACK;
END;
/
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 NBC.ishida end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 NBC.ishida end

set rc = $status
if ( $rc != 0 ) then
        set MSG = "失敗:オペレーションログ削除 RC=[$rc]"
        $LOGWRITE  "$MSG"  >> $LOGFILE"
        exit  1
endif

$LOGWRITE "オペレーションログ削除処理終了"  >> $LOGFILE   # 終了メッセージの出力

exit 0


