#!/bin/csh
#　スクリプト名  ： QSDJ31UX
#　 機  能       ： 督促明細抽出処理
#　 作成者       ： FIP
#

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                                 # シェル名
setenv JOB_ID       $SHELL_NAME:t                      # ジョブ名
setenv JOBNET_ID   'QSD201UX'                          # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
setenv USERKEY      'QSDJ31UX'                         # ユーザキー 
set    KINOU      = '督促明細抽出処理'

#########################################
# STEP-1                                #
#########################################
set MODULE = 'COBOL'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"     # 開始メッセージの出力

set PROGRAM = $EXE_DIR/qtab_s004000.exe
if ( -x $PROGRAM ) then
    #
    #  ファイル識別子の設定
    setenv OTFILE1 $DATA4_DIR/qtaf_tokuriyoud.dat
    setenv OTFILE2 $DATA4_DIR/qtaf_tokukeijou.dat
    setenv OTFILE3 $DATA4_DIR/qtaf_tokubunkai.dat
    #
    #
    if ( ! -e $OTFILE1 ) then
        touch $OTFILE1
    endif
    if ( ! -e $OTFILE2 ) then
        touch $OTFILE2
    endif
    if ( ! -e $OTFILE3 ) then
        touch $OTFILE3
    endif
    #
    #
    setenv NLS_LANG Japanese_Japan.JA16SJIS      # 文字コード体系をSJISにする
    $PROGRAM                                     # プログラム起動
    set rc = $status                             # リターンステータス待避
    setenv NLS_LANG Japanese_Japan.JA16EUC       # 文字コード体系をEUCに戻す
else
    $LOGWRITE  "$MODULE"  E  "実行プログラム[$PROGRAM]が存在しない。" "$USERKEY"
    exit 1                                       # 異常終了
endif

if ( $rc != 0 ) then                              # リターンステータス判定
   exit  1                                      # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"     # 終了メッセージの出力

exit 0                                           # 正常終了

