#!/bin/csh
# 　スクリプト名 ： QSDJICUX
#　 機  能       ： 日次配信２・対応履歴登録データ作成
#　 作成者       ： ＦＩＰ．横山
#

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                                 # シェル名
setenv JOB_ID       $SHELL_NAME:t                      # ジョブ名
setenv JOBNET_ID   'QSDHS2UX'                          # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
set    USERKEY    = '0KEN-HAISIN'                      # ユーザキー 
set    KINOU      = '日次配信２・対応履歴登録データ作成' # 機能
set    QX_DATA_DIR = '/d321/UFS'

#########################################
# STEP-1                                #
#########################################

rm $QX_DATA_DIR/fromhost/qt/snd/OFQWA1.hft
touch $QX_DATA_DIR/fromhost/qt/snd/OFQWA1.hft

set MODULE = 'utlsend'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"   # 開始メッセージの出力

### 送信の実行 ###
utlsend  -f OFQWA1 -sync
set rc = $status

if ( $rc != 0 ) then
	$LOGWRITE  "$MODULE" E "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
	exit  1                                      # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   # 終了メッセージの出力
exit 0                                           # 正常終了

