#!/bin/csh
#　スクリプト名  ： QSEJ11UX
#　 機  能       ： 月次受信ファイル作成（入金計上登録データ）
#　 作成者       ： FIP
#

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                                 # シェル名
setenv JOB_ID       $SHELL_NAME:t                      # ジョブ名
setenv JOBNET_ID   'QUER02UX'                          # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
set    USERKEY    = 'QSEJ11UX'                         # ユーザキー 
set    KINOU      = '月次受信ファイル作成・リカバリ（入金計上登録データ）'

#########################################
# STEP-1                                #
#########################################
set MODULE = 'SHELL'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"   # 開始メッセージの出力

### 受信ファイルを繰越ファイルにコピーする ###

cp $QJ_DATA_DIR/qt/data/host/merge/qjaf_mnyukin.hft  $QJ_DATA_DIR/qt/data/host/zen/qjaf_mnyukin.kur

set rc = $status

if ( $rc != 0 ) then
	$LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
	exit  1                                      # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   # 終了メッセージの出力
exit 0                                           # 正常終了

