#!/bin/csh
#　スクリプト名  ： QSHJF1UX
#　 機  能       ： 期次用受信ファイル作成（会員マスタ・カード更新）
#　 作成者       ： FIP
#

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                                 # シェル名
setenv JOB_ID       $SHELL_NAME:t                      # ジョブ名
setenv JOBNET_ID   'QSH111UX'                          # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
setenv USERKEY      'QSHJF1UX'                         # ユーザキー 
set    KINOU      = '期次用受信ファイルの作成（会員マスタ・カード更新）'

#########################################
# STEP-1                                #
#########################################
set MODULE = 'SHELL'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"   # 開始メッセージの出力

#setenv NLS_LANG Japanese_Japan.JA16SJIS  

### ファイルをマージする ###
cat $FROMHOST1_DIR/qt/rcv/qtaf_kaiin4.jsn $QJ_DATA_DIR/qt/data/host/zen/qtaf_kaiin4.kur > $QJ_DATA_DIR/qt/data/host/merge/qtaf_kaiin4.hft

set rc = $status

#setenv NLS_LANG Japanese_Japan.JA16EUC  

if ( $rc != 0 ) then
	$LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
	exit  1                                      # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   # 終了メッセージの出力
exit 0                                           # 正常終了

