#!/bin/csh
#　スクリプト名  ： QSTJJ2UX
#　 機  能       ： 月次受信後処理（自振返戻結果テーブル）
#　 作成者       ： FIP
#

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                                 # シェル名
setenv JOB_ID       $SHELL_NAME:t                      # ジョブ名
setenv JOBNET_ID   'QSTJ10UX'                          # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
set    USERKEY    = 'QSDJJ2UX'                         # ユーザキー 
set    KINOU      = '月次受信後処理（自振返戻結果テーブル）'

#########################################
# STEP-1                                #
#########################################
set MODULE = 'SHELL'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"   # 開始メッセージの出力

### ファイルを削除する ###

rm $FROMHOST1_DIR/qt/rcv/qsaf_jfhenrei.jsn

set rc = $status

if ( $rc != 0 ) then
	$LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
	exit  1                                      # 異常終了
endif

### ファイルを０件にする ###

cp $QJ_DATA_DIR/qt/data/host/zen/dmy  $QJ_DATA_DIR/qt/data/host/zen/qsaf_jfhenrei.kur

set rc = $status

if ( $rc != 0 ) then
	$LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
	exit  1                                      # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   # 終了メッセージの出力
exit 0                                           # 正常終了

