#!/bin/csh
#　スクリプト名  ： QSTJ37UX
#　 機  能       ： 期日後入金データ期日管理
#　 作成者       ： FIP
#

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                              # シェル名
setenv JOB_ID       $SHELL_NAME:t                   # ジョブ名
setenv JOBNET_ID   'QST135UX'                       # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log     # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT        # ログ出力モジュール
setenv USERKEY      'QSTJ37UX'                      # ユーザキー
set    KINOU      = ' 期日後入金データ期日管理'

set MODULE = 'SHELL'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"   #開始メッセージの出力


###############################################
# STEP-1 期日後入金データ期日管理   		      #
###############################################
set MODULE = 'qsab_s000600'
set STEPKINOU = '期日後入金データ期日管理'
$LOGWRITE "$MODULE" I "開始:$STEPKINOU" "$USERKEY"     # 開始メッセージの出力

set PROGRAM = $EXE_DIR/qsab_s000600.exe

if ( -x $PROGRAM ) then
    #  ファイル識別子の設定
    #  出力ファイルの数だけ設定する(削除ファイルはﾊﾞｯｸｱｯﾌﾟしないためﾀﾞﾐｰ)
    setenv OT1FILE $DATA4_DIR/DUMMY.dat
    #
    setenv NLS_LANG Japanese_Japan.JA16SJIS      # 文字コード体系をSJISにする
    $PROGRAM       >&  $LOGFILE                  # プログラム起動
    set rc = $status                             # リターンステータス待避
    setenv NLS_LANG Japanese_Japan.JA16EUC       # 文字コード体系をEUCに戻す
else
    $LOGWRITE  "$MODULE"  E  "実行プログラム[$PROGRAM]が存在しない。" "$USERKEY"
    exit 1                                       # 異常終了
endif

if ( $rc != 0 ) then                             # リターンステータス判定
    set MSG = "失敗:$STEPKINOU RC=[$rc]"
    $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
    exit  1                                      # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$STEPKINOU" "$USERKEY"   # 終了メッセージの出力
##########################################
# STEP-99      後始末                    #
##########################################
STEP_99:

set MODULE = 'SHELL'

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   # 終了メッセージの出力

exit 0
