#!/bin/csh
#　スクリプト名  ： QSTJ13UX
#　 機  能       ： 期日管理（領収証テーブル）
#　 作成者       ： FIP
#

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                                 # シェル名
setenv JOB_ID       $SHELL_NAME:t                      # ジョブ名
setenv JOBNET_ID   'QST111UX'                          # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
set    USERKEY    = 'QSTJ13UX'                         # ユーザキー 
set    KINOU      = '期日管理（領収証テーブル）'

#########################################
# STEP-1                                #
#########################################
set MODULE = 'qusc_sspexec.exe'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"   # 開始メッセージの出力

setenv NLS_LANG Japanese_Japan.JA16SJIS  

#########################################
# ストアード・プロシジャーで対応        #
#########################################

$EXE_DIR/qusc_sspexec.exe  $JOBNET_ID  $JOB_ID  "QJAP_KijitsuPKG.QSTJ13UX()" >& $LOGFILE

set rc = $status

setenv NLS_LANG Japanese_Japan.JA16EUC  

if ( $rc != 0 ) then
	$LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
	exit  1                                      # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   # 終了メッセージの出力
exit 0                                           # 正常終了

