#!/bin/csh
#   スクリプト名 ： QSTJ72UX
#   機  能       ： 入金計上テーブル最古データ抽出 &
#                   加盟店原伝ファイル最古データ抽出 &
#                   入金分解テーブル最古データ抽出
#   作成者       ： imz.Yoshida
#   作成日       ： 2006/06/18
#   修正履歴
#   項番     修正日      修正者         修正内容
#   00001    2006/07/14  nbc.Arihara    入金分解テーブル最古データ抽出の追加
#   00002    2007/02/19  nbc.hayashi    入金分解１Gの壁対応
#   00003    2007/03/18  fip.Eriguchi   入金計上１Gの壁対応（出力件数を250万件ごとに分ける）
#   00004    2008/05/09  nbc.ishida     workディスク変更

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                                 # シェル名
setenv JOB_ID       $SHELL_NAME:t                      # ジョブ名
setenv JOBNET_ID    'QST191UX'                         # ジョブネット名
setenv USERKEY      'QSTJ72UX'                         # ユーザキー
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
set    STEP_F     = $DATA4_DIR/${JOB_ID}_step.tmp
set    KINOU      = '入金計上テーブル吸い上げ'
# 00004 mod nbc.ishida 2008/05/09 start
#set WK_DATA4_DIR  = '/d370/UFS/data/qt/shift'
set WK_DATA5_DIR  = '/d370/UFS/data/qt/shift'          #保存ディスク
set WK_DATA4_DIR  = '/d320/UFS/data/qt/shift'          #本番用workディスク
# 00004 mod nbc.ishida 2008/05/09 end

set MODULE = 'SHELL'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"         # 開始メッセージの出力

#########################################
# STEP-1 締め日取得                     #
#########################################
set sime  = 15                                         # 締日
set year  = `date +%Y`                                 # 処理年 (システム日付より)
set month = `date +%m`                                 # 処理月 (システム日付より)
set day   = `date +%d`                                 # 処理日 (システム日付より)

# 処理月Leading Zero Suppress
@ month ++
@ month --

if ( $month < 10 ) then
   set month = 0$month
endif

# 処理日Leading Zero Suppress
@ day ++
@ day --

if ( $day < 10 ) then
   set day = 0$day
endif

set wk_sime = $sime
@ wk_sime ++    # 締の翌日

if ( $wk_sime < 10 ) then
   set wk_sime = 0$wk_sime
endif


#########################################
# STEP-2 入金計上テーブル最古データ抽出 #
#########################################
set STEPKINOU = "入金計上テーブル最古データ抽出"
$LOGWRITE "COBOL" I "開始:$STEPKINOU" "$USERKEY"        # 開始メッセージの出力

# 00004 mod nbc.ishida 2008/05/09 start
#rm -f $WK_DATA4_DIR/qtaf_nyukin.dat.cidatacenter.$year$month$day.Z
##00003 add by fip.Eriguchi 2007/03/18 start
#rm -f $WK_DATA4_DIR/qtaf_nyukin.dat.cidatacenter.$year$month$day.2.Z
##00003 add by fip.Eriguchi 2007/03/18   end
rm -f $WK_DATA5_DIR/qtaf_nyukin.dat.cidatacenter.$year$month$day.Z
rm -f $WK_DATA5_DIR/qtaf_nyukin.dat.cidatacenter.$year$month$day.2.Z
# 00004 mod nbc.ishida 2008/05/09 end

setenv OTFILE   $WK_DATA4_DIR/qtaf_nyukin.dat.cidatacenter.$year$month$day
#00003 add by fip.Eriguchi 2007/03/18 start
setenv OTFILE2  $WK_DATA4_DIR/qtaf_nyukin.dat.cidatacenter.$year$month$day.2
#00003 add by fip.Eriguchi 2007/03/18   end
setenv SIMEYOKU $wk_sime

set PROGRAM = $EXE_DIR/qtab_s001910.exe
if ( -x $PROGRAM ) then
   setenv NLS_LANG Japanese_Japan.JA16SJIS              # 文字コード体系をSJISにする
   $PROGRAM | sjtoeuc >& $LOGFILE                       # プログラム起動
   set rc = $status                                     # リターンステータス待避
   setenv NLS_LANG Japanese_Japan.JA16EUC               # 文字コード体系をEUCに戻す
else
   $LOGWRITE  $PROGRAM:t  E  '実行プログラム[$PROGRAM]が存在しない。'
   exit 1                                               # 異常終了
endif
if ( $rc != 0 ) then                                    # リターンステータス判定
   set MSG = "失敗:$STEPKINOU RC=[$rc]"
   $LOGWRITE "COBOL" E "$MSG" $USERKEY
   exit  1                                              # 異常終了
endif

# 00004 add nbc.ishida 2008/05/09 start
#compress $WK_DATA4_DIR/qtaf_nyukin.dat.cidatacenter.$year$month$day
##00003 add by fip.Eriguchi 2007/03/18 start
#compress $WK_DATA4_DIR/qtaf_nyukin.dat.cidatacenter.$year$month$day.2
##00003 add by fip.Eriguchi 2007/03/18   end
compress -f $WK_DATA4_DIR/qtaf_nyukin.dat.cidatacenter.$year$month$day*
# 00004 add nbc.ishida 2008/05/09 end

$LOGWRITE "COBOL" I "終了:$STEPKINOU" "$USERKEY"        # 終了メッセージの出力

# 00004 add nbc.ishida 2008/05/09 start
####ファイル移動####
mv $WK_DATA4_DIR/qtaf_nyukin.dat.cidatacenter.$year$month$day*.Z $WK_DATA5_DIR/
set rc = $status                                   # リターンステータス待避
if ( $rc != 0 ) then                               # リターンステータス判定
   set MSG = "失敗:ファイル移動(qtaf_riyougyou) RC=[$rc]"
   $LOGWRITE  "$MODULE" E "$MSG" $USERKEY
   exit 1                                          # 異常終了
endif


# 00004 add nbc.ishida 2008/05/09 end

#############################################
# STEP-3 加盟店原伝ファイル最古データ抽出   #
#############################################
set STEPKINOU = "加盟店原伝ファイル最古データ抽出"
$LOGWRITE "COBOL" I "開始:$STEPKINOU" "$USERKEY"       # 開始メッセージの出力

# 00004 mod nbc.ishida 2008/05/09 start
#rm -f $WK_DATA4_DIR/qtaf_kameiten.dat.cidatacenter.$year$month$day.Z
rm -f $WK_DATA5_DIR/qtaf_kameiten.dat.cidatacenter.$year$month$day.Z
# 00004 mod nbc.ishida 2008/05/09 end

setenv OTFILE   $WK_DATA4_DIR/qtaf_kameiten.dat.cidatacenter.$year$month$day
setenv SIMEYOKU $wk_sime

set PROGRAM = $EXE_DIR/qtab_s001740.exe
if ( -x $PROGRAM ) then
   setenv NLS_LANG Japanese_Japan.JA16SJIS             # 文字コード体系をSJISにする
   $PROGRAM | sjtoeuc >& $LOGFILE                      # プログラム起動
   set rc = $status                                    # リターンステータス待避
   setenv NLS_LANG Japanese_Japan.JA16EUC              # 文字コード体系をEUCに戻す
else
   $LOGWRITE  $PROGRAM:t  E  '実行プログラム[$PROGRAM]が存在しない。'
   exit 1                                              # 異常終了
endif
if ( $rc != 0 ) then                                   # リターンステータス判定
   set MSG = "失敗:$STEPKINOU RC=[$rc]"
   $LOGWRITE "COBOL" E "$MSG" $USERKEY
   exit 1                                              # 異常終了
endif

# 00004 mod nbc.ishida 2008/05/09 start
#compress $WK_DATA4_DIR/qtaf_kameiten.dat.cidatacenter.$year$month$day
compress -f $WK_DATA4_DIR/qtaf_kameiten.dat.cidatacenter.$year$month$day
# 00004 mod nbc.ishida 2008/05/09 end

$LOGWRITE "COBOL" I "終了:$STEPKINOU" "$USERKEY"       # 終了メッセージの出力

# 00004 add nbc.ishida 2008/05/09 start
####ファイル移動####
mv $WK_DATA4_DIR/qtaf_kameiten.dat.cidatacenter.$year$month$day.Z $WK_DATA5_DIR/
set rc = $status                                   # リターンステータス待避
if ( $rc != 0 ) then                               # リターンステータス判定
   set MSG = "失敗:ファイル移動(qtaf_kameiten) RC=[$rc]"
   $LOGWRITE  "$MODULE" E "$MSG" $USERKEY
   exit 1                                          # 異常終了
endif

# 00004 add nbc.ishida 2008/05/09 end

#00001 add by nbc.Arihara 2006/07/14 start ==>
#########################################
# STEP-4 入金分解テーブル最古データ抽出 #
#########################################
set STEPKINOU = "入金分解テーブル最古データ抽出"
$LOGWRITE "COBOL" I "開始:$STEPKINOU" "$USERKEY"       # 開始メッセージの出力

# 00004 mod nbc.ishida 2008/05/09 start
#rm -f $WK_DATA4_DIR/qtaf_bunkai.dat.cidatacenter.$year$month$day.Z
##00002 add by nbc.hayashi 2007/02/19 start ==>
#rm -f $WK_DATA4_DIR/qtaf_bunkai.dat.cidatacenter.$year$month$day.2.Z
##00002 add by nbc.hayashi 2007/02/19 end <==
rm -f $WK_DATA5_DIR/qtaf_bunkai.dat.cidatacenter.$year$month$day.Z
rm -f $WK_DATA5_DIR/qtaf_bunkai.dat.cidatacenter.$year$month$day.2.Z
# 00004 mod nbc.ishida 2008/05/09 end

setenv OTFILE $WK_DATA4_DIR/qtaf_bunkai.dat.cidatacenter.$year$month$day
#00002 add by nbc.hayashi 2007/02/19 start ==>
setenv OTFILE2 $WK_DATA4_DIR/qtaf_bunkai.dat.cidatacenter.$year$month$day.2
#00002 add by nbc.hayashi 2007/02/19 end <==
setenv SIMEYOKU $wk_sime

set PROGRAM = $EXE_DIR/qtab_s002010.exe
if ( -x $PROGRAM ) then
   setenv NLS_LANG Japanese_Japan.JA16SJIS    # 文字コード体系をSJISにする
   $PROGRAM | sjtoeuc >& $LOGFILE             # プログラム起動
   set rc = $status                           # リターンステータス待避
   setenv NLS_LANG Japanese_Japan.JA16EUC     # 文字コード体系をEUCに戻す
else
   $LOGWRITE  $PROGRAM:t  E  '実行プログラム[$PROGRAM]が存在しない。'
   exit 1                                     # 異常終了
endif
if ( $rc != 0 ) then                           # リターンステータス判定
   set MSG = "失敗:$STEPKINOU RC=[$rc]"
   $LOGWRITE  "COBOL" E "$MSG" $USERKEY
   exit 1                                    # 異常終了
endif

# 00004 mod nbc.ishida 2008/05/09 start
#compress $WK_DATA4_DIR/qtaf_bunkai.dat.cidatacenter.$year$month$day
##00002 add by nbc.hayashi 2007/02/19 start ==>
#compress $WK_DATA4_DIR/qtaf_bunkai.dat.cidatacenter.$year$month$day.2
##00002 add by nbc.hayashi 2007/02/19 end <==
compress -f $WK_DATA4_DIR/qtaf_bunkai.dat.cidatacenter.$year$month$day*
# 00004 mod nbc.ishida 2008/05/09 end

$LOGWRITE "COBOL" I "終了:$STEPKINOU" "$USERKEY"       # 終了メッセージの出力
#00001 add nbc.Arihara 2006/07/14 end <==

# 00004 add nbc.ishida 2008/05/09 start
####ファイル移動####
mv $WK_DATA4_DIR/qtaf_bunkai.dat.cidatacenter.$year$month$day*.Z $WK_DATA5_DIR/
set rc = $status                                   # リターンステータス待避
if ( $rc != 0 ) then                               # リターンステータス判定
   set MSG = "失敗:ファイル移動(qtaf_bunkai) RC=[$rc]"
   $LOGWRITE  "$MODULE" E "$MSG" $USERKEY
   exit 1                                          # 異常終了
endif

# 00004 add nbc.ishida 2008/05/09 end

##########################################
# STEP-99      後始末                    #
##########################################
$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"         # 終了メッセージの出力

exit 0
