#!/bin/csh
#　スクリプト名  ： QSTJ38UX
#　 機  能       ： 期日後入金データ作成
#　 作成者       ： FIP
#　 修正者       ： 2005/08/02 imz.Yoshidaメッセージ追加
#   項番     修正日      修正者         修正内容
#   00002    2005/11/25  imz.Yoshida    登録用ファイル、ディレクトリ変更
#   00003    2007/03/21  fip.Eriguchi   ファイル数変更による処理回数の変更
#   00004    2007/03/30  fip.Eriguchi   3/21の障害による修正（表領域圧縮作業を減らす）
#
#　 修正履歴
# 項番   管理番号    修正内容                修正者         修正日
# 000001 0807073     非互換対応              NBC.SHIBUICHI  2009/03/29
# 000001 0808052     非互換対応              NBC.SHIBUICHI  2009/03/29

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                              # シェル名
setenv JOB_ID       $SHELL_NAME:t                   # ジョブ名
setenv JOBNET_ID   'QST136UX'                       # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log     # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT        # ログ出力モジュール
setenv USERKEY      'QSTJ38UX'                      # ユーザキー
set    KINOU      = '期日後入金データ作成'

# 00002 add by imz.Yoshida 2005/11/25 ==>
# 作業ディレクトリは、環境変数で作成しているので、新規にディレクトリに変更する
set WK_DATA4_DIR  = '/d370/UFS/data/qt/shift'
# 00002 add by imz.Yoshida 2005/11/25 <==

set MODULE = 'SHELL'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"   #開始メッセージの出力

set backupDate  = 19          # 期日後入金データ作成日付
set year  = `date +%Y`        # 処理年 (システム日付より)
set month = `date +%m`        # 処理月 (システム日付より)
set day   = `date +%d`        # 処理日 (システム日付より)

# 処理月Leading Zero Suppress
@ month ++
@ month --

if ( $month < 10 ) then
	set month = 0$month
endif

# 処理日Leading Zero Suppress
@ day ++
@ day --

if ( $day < 10 ) then
	set day = 0$day
endif
##################################
# STEP-1 インデックス１削除      #
##################################
set MODULE = 'SQL*PLUS-1'
$LOGWRITE "$MODULE" I "開始:インデックス１削除" $USERKEY

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S tccuser/tccuser << EOF > $LOGFILE
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF > $LOGFILE
drop index XIE1QTAW_KIJITUGONKT;
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:インデックス１削除 RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

#表領域をまとめる
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S tccadmin/tccadmin << EOF > $LOGFILE
sqlplus -S $DB_ADMINID/$DB_ADMINPASS@$ORACLE_SID << EOF > $LOGFILE
alter tablespace OLDNKT coalesce;
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
        set MSG = "失敗:インデックス１削除（圧縮） RC=[$rc]"
        $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
endif

$LOGWRITE "$MODULE" I "終了:インデックス１削除" $USERKEY

##################################
# STEP-2 インデックス２削除      #
##################################
set MODULE = 'SQL*PLUS-2'
$LOGWRITE "$MODULE" I "開始:インデックス２削除" $USERKEY

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S tccuser/tccuser << EOF > $LOGFILE
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF > $LOGFILE
drop index XIE2QTAW_KIJITUGONKT;
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:インデックス２削除 RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

#表領域をまとめる
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S tccadmin/tccadmin << EOF > $LOGFILE
sqlplus -S $DB_ADMINID/$DB_ADMINPASS@$ORACLE_SID << EOF > $LOGFILE
alter tablespace OLDNKT coalesce;
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
        set MSG = "失敗:インデックス２削除（圧縮） RC=[$rc]"
        $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
endif

$LOGWRITE "$MODULE" I "終了:インデックス２削除" $USERKEY


###############################################
# STEP-2 期日後入金データファイル解凍　       #
###############################################
set STEPKINOU = '期日後入金データ解凍'
$LOGWRITE "$MODULE" I "開始:$STEPKINOU" "$USERKEY"     # 開始メッセージの出力

# 00002 mod by imz.Yoshida 2005/11/25 ==>
#uncompress  $DATA4_DIR/qtaf_nyukin.dat.cidatacenter.$year$month*.Z
uncompress  $WK_DATA4_DIR/qtaf_nyukin.dat.cidatacenter.$year$month*.Z
# 00002 mod by imz.Yoshida 2005/11/25 <==

# Added by imz.Yoshida 2005/08/02 メッセージ追加 ==>
set rc = $status                                 # リターンステータス待避
if ( $rc != 0 ) then                             # リターンステータス判定
    set MSG = "失敗:$STEPKINOU RC=[$rc]"
    $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
    exit  1                                      # 異常終了
endif
# Added by imz.Yoshida 2005/08/02 メッセージ追加 <==
$LOGWRITE "$MODULE" I "終了:$STEPKINOU" "$USERKEY"   # 終了メッセージの出力

###################################################
# STEP-3 期日後入金テーブルロード用ファイル作成   #
###################################################
set MODULE = 'qsab_s000500'
set STEPKINOU = ' 期日後入金テーブルロード用ファイル作成'
$LOGWRITE "$MODULE" I "開始:$STEPKINOU" "$USERKEY"     # 開始メッセージの出力

set PROGRAM = $EXE_DIR/qsab_s000500.exe

if ( -x $PROGRAM ) then
    #  ファイル識別子の設定
    #  出力ファイルの数だけ設定する
    # 00003 mod by fip.Eriguchi 2007/03/21 ==>
    ## 00002 mod by imz.Yoshida 2005/11/25 ==>
    ##setenv INFILE $DATA4_DIR/qtaf_nyukin.dat.cidatacenter.$year$month*
    #setenv INFILE $WK_DATA4_DIR/qtaf_nyukin.dat.cidatacenter.$year$month*
    setenv INFILE $WK_DATA4_DIR/qtaf_nyukin.dat.cidatacenter.$year${month}??
    ## 00002 mod by imz.Yoshida 2005/11/25 <==
    # 00003 mod by fip.Eriguchi 2007/03/21 <==
    setenv OTFILE $DATA4_DIR/qtaf_kjgnyukin.dat

    #
    setenv NLS_LANG Japanese_Japan.JA16SJIS      # 文字コード体系をSJISにする
    $PROGRAM       >&  $LOGFILE                  # プログラム起動
    set rc = $status                             # リターンステータス待避
    setenv NLS_LANG Japanese_Japan.JA16EUC       # 文字コード体系をEUCに戻す
else
    $LOGWRITE  "$MODULE"  E  "実行プログラム[$PROGRAM]が存在しない。" "$USERKEY"
    exit 1                                       # 異常終了
endif

if ( $rc != 0 ) then                             # リターンステータス判定
    set MSG = "失敗:$STEPKINOU RC=[$rc]"
    $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
    exit  1                                      # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$STEPKINOU" "$USERKEY"   # 終了メッセージの出力

###############################################
# STEP-4 期日後入金テーブルデータロード        #
###############################################
set MODULE = 'SQL*LOADER'
$LOGWRITE "$MODULE" I "開始:期日後入金テーブルデータロード" $USERKEY

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlldr $DB_USERID/$DB_PASSWORD                \
sqlldr $DB_USERID/$DB_PASSWORD@$ORACLE_SID     \
   control=$LDR_CTRL_DIR/qtad_kjgnyukin.sql        \
   data=$DATA4_DIR/qtaf_kjgnyukin.dat       \
   log=$LDR_LOG_DIR/qtad_kjgnyukin.log             \
   direct=true                                \
               > $LOGFILE
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
        set MSG = "失敗:期日後入金テーブルデータロード  RC=[$rc]"
        $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
        exit  1
endif

#00004 del by fip.Eriguchi 2007/03/30 ==>
##表領域をまとめる
#sqlplus -S tccadmin/tccadmin << EOF > $LOGFILE
#alter tablespace OLDNKT coalesce;
#quit SQL.SQLCODE
#EOF
#
#set rc = $status
#if ( $rc != 0 ) then
#        set MSG = "失敗:期日後入金テーブルデータロード（圧縮）  RC=[$rc]"
#        $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
#endif
#00004 del by fip.Eriguchi 2007/03/30 <==

$LOGWRITE "$MODULE" I "終了:期日後入金テーブルデータロード" $USERKEY

# 00003 add by fip.Eriguchi 2007/03/21 ==>
# ２つ目のファイルにデータが存在する時
# ２度目のローダ処理を実行
#---------------------------------------------------
if !( -z $WK_DATA4_DIR/qtaf_nyukin.dat.cidatacenter.$year${month}??.2 ) then

####################################################
# STEP-3.2 期日後入金テーブルロード用ファイル作成２ #
####################################################
    set MODULE = 'qsab_s000500'
    set STEPKINOU = ' 期日後入金テーブルロード用ファイル作成（２）'
    $LOGWRITE "$MODULE" I "開始:$STEPKINOU" "$USERKEY"     # 開始メッセージの出力

    set PROGRAM = $EXE_DIR/qsab_s000500.exe

    if ( -x $PROGRAM ) then
        #  ファイル識別子の設定
        #  出力ファイルの数だけ設定する
        setenv INFILE $WK_DATA4_DIR/qtaf_nyukin.dat.cidatacenter.$year${month}??.2
        setenv OTFILE $DATA4_DIR/qtaf_kjgnyukin.dat.2

        #
        setenv NLS_LANG Japanese_Japan.JA16SJIS      # 文字コード体系をSJISにする
        $PROGRAM       >&  $LOGFILE                  # プログラム起動
        set rc = $status                             # リターンステータス待避
        setenv NLS_LANG Japanese_Japan.JA16EUC       # 文字コード体系をEUCに戻す
    else
        $LOGWRITE  "$MODULE"  E  "実行プログラム[$PROGRAM]が存在しない。" "$USERKEY"
        exit 1                                       # 異常終了
    endif

    if ( $rc != 0 ) then                             # リターンステータス判定
        set MSG = "失敗:$STEPKINOU RC=[$rc]"
        $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
        exit  1                                      # 異常終了
    endif

    $LOGWRITE "$MODULE" I "終了:$STEPKINOU" "$USERKEY"   # 終了メッセージの出力

###############################################
# STEP-4.2 期日後入金テーブルデータロード ２   #
###############################################
    set MODULE = 'SQL*LOADER'
    $LOGWRITE "$MODULE" I "開始:期日後入金テーブルデータロード（２）" $USERKEY

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#    sqlldr $DB_USERID/$DB_PASSWORD                \
    sqlldr $DB_USERID/$DB_PASSWORD@$ORACLE_SID     \
       control=$LDR_CTRL_DIR/qtad_kjgnyukin.sql        \
       data=$DATA4_DIR/qtaf_kjgnyukin.dat.2       \
       log=$LDR_LOG_DIR/qtad_kjgnyukin.log.2           \
       direct=true                                \
                   > $LOGFILE
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

    set rc = $status
    if ( $rc != 0 ) then
            set MSG = "失敗:期日後入金テーブルデータロード（２）  RC=[$rc]"
            $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
            exit  1
    endif

# 00004 del by fip.Eriguchi 2007/03/30 ==>
#    #表領域をまとめる
#    sqlplus -S tccadmin/tccadmin << EOF > $LOGFILE
#    alter tablespace OLDNKT coalesce;
#    quit SQL.SQLCODE
#    EOF
#
#    set rc = $status
#    if ( $rc != 0 ) then
#            set MSG = "失敗:期日後入金テーブルデータロード（圧縮２）  RC=[$rc]"
#            $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
#    endif
# 00004 del by fip.Eriguchi 2007/03/30 <==

    $LOGWRITE "$MODULE" I "終了:期日後入金テーブルデータロード（２）" $USERKEY

#---------------------------------------------------

else
    set MSG = '２回目のローダ処理省略'
    $LOGWRITE "$MODULE" "I" "$MSG" "$USERKEY"
endif
# 00003 add by fip.Eriguchi 2007/03/21 <==
# 00004 add by fip.Eriguchi 2007/03/30 ==>

#表領域をまとめる
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S tccadmin/tccadmin << EOF > $LOGFILE
sqlplus -S $DB_ADMINID/$DB_ADMINPASS@$ORACLE_SID << EOF > $LOGFILE
alter tablespace OLDNKT coalesce;
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start

set rc = $status
if ( $rc != 0 ) then
        set MSG = "失敗:期日後入金テーブルデータロード（圧縮）  RC=[$rc]"
        $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
endif
# 00004 add by fip.Eriguchi 2007/03/30 <==
##################################
# STEP-5  インデックス１作成     #
##################################
set MODULE = 'SQL*PLUS-3'
$LOGWRITE "$MODULE" I "開始:インデックス１作成" $USERKEY

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF > $LOGFILE
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF > $LOGFILE
CREATE INDEX XIE1QTAW_KIJITUGONKT ON QTAW_KIJITUGONKT
(
       QTAW_NYUKINBI                  ASC
)
       TABLESPACE OLDNKT
       STORAGE ( 
              INITIAL 1500M
              NEXT 150M
              MINEXTENTS 1
              MAXEXTENTS 100
              PCTINCREASE 0
       ) ;
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
    set MSG = "失敗:インデックス１作成 RC=[$rc]"
    $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
    exit  1
endif

$LOGWRITE "$MODULE" I "終了:インデックス１作成" $USERKEY

##################################
# STEP-6  インデックス２作成     #
##################################
set MODULE = 'SQL*PLUS-4'
$LOGWRITE "$MODULE" I "開始:インデックス２作成" $USERKEY

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF > $LOGFILE
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF > $LOGFILE
CREATE INDEX XIE2QTAW_KIJITUGONKT ON QTAW_KIJITUGONKT
(
       QTAW_KIGYOCD                   ASC,
       QTAW_SUBRANJEKEY               ASC,
       QTAW_NAIBUKAIINNO              ASC
)
       TABLESPACE OLDNKT
       STORAGE ( 
              INITIAL 1000M
              NEXT 200M
              MINEXTENTS 1
              MAXEXTENTS 100
              PCTINCREASE 0
       ) 
;
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:インデックス２作成 RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

$LOGWRITE "$MODULE" I "終了:インデックス２作成" $USERKEY

##########################################
# STEP-99      後始末                    #
##########################################
STEP_99:
# 00003 mod by fip.Eriguchi 2007/03/21 ==>
#/bin/rm $DATA4_DIR/qtaf_kjgnyukin.dat
/bin/rm $DATA4_DIR/qtaf_kjgnyukin.dat*
# 00003 mod by fip.Eriguchi 2007/03/21 <==

# 00002 mod by imz.Yoshida 2005/11/25 ==>
#compress -f $DATA4_DIR/qtaf_nyukin.dat.cidatacenter.$year$month*
compress -f $WK_DATA4_DIR/qtaf_nyukin.dat.cidatacenter.$year$month*
# 00002 mod by imz.Yoshida 2005/11/25 <==

# Added by imz.Yoshida 2005/08/02 メッセージ追加 ==>
set rc = $status                                 # リターンステータス待避
if ( $rc != 0 ) then                             # リターンステータス判定
    set MSG = "失敗:$STEPKINOU RC=[$rc]"
    $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
    exit  1                                      # 異常終了
endif
# Added by imz.Yoshida 2005/08/02 メッセージ追加 <==

set MODULE = 'SHELL'

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   # 終了メッセージの出力

exit 0
