#!/bin/csh
#　スクリプト名  ： QTDJ72UX
#　 機  能       ： 対応履歴登録・統合メモテーブル追加登録処理
#　 作成者       ： ＦＩＰ．横山
#
#
#　 修正履歴
# 項番   管理番号    修正内容                   修正者         修正日
# 000001             文字コード変換エラー対応   APS.YOKOYAMA   2006/06/09
# 000002 0807073     非互換対応              NBC.SHIBUICHI  2009/03/29
# 000002 0808052     非互換対応              NBC.SHIBUICHI  2009/03/29


##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                                 # シェル名
setenv JOB_ID       $SHELL_NAME:t                      # ジョブ名
setenv JOBNET_ID   'QTD401UX'                          # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
setenv USERKEY      'QTDJ72UX'                         # ユーザキー
set    KINOU      = '対応履歴登録・統合メモテーブル追加登録処理'
set    QX_DATA_DIR = '/d321/UFS'

#########################################
# STEP-1                                #
#########################################

set MODULE = 'SQL*LOADER'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"    # 開始メッセージの出力


# add 000001 APS.YOKOYAMA 2006/06/09 start
#外字を含むﾎｽﾄﾃﾞｰﾀを従来型ﾊﾟｽﾛｰﾄﾞでﾛｰﾄﾞ
setenv NLS_LANG Japanese_Japan.JA16SJIS
# add 000001 APS.YOKOYAMA 2006/06/09 end


   ### SQL*LOADERの実行 ###
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#   sqlldr $DB_USERID/$DB_PASSWORD                    \
   sqlldr $DB_USERID/$DB_PASSWORD@$ORACLE_SID                    \
      control = $LDR_CTRL_DIR/QSA7_TOGOMEMOT.ctl        \
      data    = $QX_DATA_DIR/data/qt/QSA7_TOGOMEMOT.txt      \
      log     = $LDR_LOG_DIR/qt/QSA7_TOGOMEMOT.log       \
             > $LOGFILE
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

   set rc = $status

# add 000001 APS.YOKOYAMA 2006/06/09 start
#外字を含むﾎｽﾄﾃﾞｰﾀを従来型ﾊﾟｽﾛｰﾄﾞでﾛｰﾄﾞ
setenv NLS_LANG Japanese_Japan.JA16EUC
# add 000001 APS.YOKOYAMA 2006/06/09 end

   if ( $rc != 0 ) then
            $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
            exit 1
   endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"    # 終了メッセージの出力

exit 0                                           # 正常終了
