#!/bin/csh
#　 スクリプト名 ： QTEJ60UX
#　 機  能       ： 家族マスタデータ削除･追加処理
#　 作成者       ： 江口
#　 作成日       ： 2006/08/06
#
#  修正番号 修正者   修正日時   修正内容
#  000001   hayashi  2007/07/13 ﾛｰﾀﾞｰ後ｲﾝﾃﾞｯｸｽﾁｪｯｸ追加
#  000002   hayashi  2007/08/17 ネット名の修正
#
#　 修正履歴
# 項番   管理番号    修正内容                修正者         修正日
# 000001 0807073     非互換対応              NBC.SHIBUICHI  2009/03/29
# 000001 0808052     非互換対応              NBC.SHIBUICHI  2009/03/29

##################################
#           環境設定             #
##################################
set    SHELL_NAME   = $0                                   # シェル名
setenv JOB_ID         $SHELL_NAME:t                        # ジョブ名
#000002 MOD hayashi 2007/08/17 START
#setenv JOBNET_ID      'QTEH20UX'                           # ジョブネット名
setenv JOBNET_ID      'QTEI10UX'                           # ジョブネット名
#000002 MOD hayashi 2007/08/17 END
set    USERKEY      = 'QTEJ60UX'                           # ユーザキー
set    LOGFILE      = $USER_LOG_DIR/${JOB_ID}.log          # ログファイル名
set    LOGWRITE     = $EXE_DIR/QUAJ_MSGLOG.BAT             # ログ出力モジュール
set    KINOU        = '家族マスタデータ削除･追加処理'      # 機能
set    MODULE       = 'SHELL'
# 000001 hayashi add 2007/07/13 start
set TABLE_NAME = QTA2_KAIINKAZOKM            # 対象テーブル名
# 000001 hayashi add 2007/07/13 end

$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"             # 開始メッセージの出力

#########################################
# STEP-1 家族マスタの削除               #
#########################################
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF > $LOGFILE
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF > $LOGFILE
TRUNCATE TABLE qta2_kaiinkazokm ;
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
   set MSG = "失敗:家族マスタデータクリア RC=[$rc]"
   $LOGWRITE "SQL*PLUS"  E  "$MSG" $USERKEY
   exit  1
endif

#########################################
# STEP-2 家族マスタの登録               #
#########################################
$LOGWRITE "SQL-LOADER" I "開始:家族マスタデータ追加処理" $USERKEY

set    SOTFILE      = qtab_s000500.dat
set    QT_WORK_DIR  = /d380/UFS/data/qt/svr                # 登録用ディレクトり

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlldr $DB_USERID/$DB_PASSWORD                   \
sqlldr $DB_USERID/$DB_PASSWORD@$ORACLE_SID        \
       $LDR_CTRL_DIR/ikou/qtad_kazoku_iko.sql    \
   data   = $QT_WORK_DIR/qtab_s000500.dat        \
   log    = $LDR_LOG_DIR/$SOTFILE.log            \
   bad    = $QT_WORK_DIR/$SOTFILE.bad            \
   errors = 1000                                 \
   direct = true
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
   set MSG = "失敗:家族マスタデータ追加処理 RC=[$rc]"
   $LOGWRITE "SQL-LOADER"  E  "$MSG" $USERKEY
   exit  1
endif
# 000001 hayashi add 2007/07/13 start
#----------------------------------------------------------#
#   インデックスエラーのチェック
#----------------------------------------------------------#
rm -f ${LOGFILE}2 ${LOGFILE}3

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF > ${LOGFILE}2
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF > ${LOGFILE}2
set lin 200
select index_name,status from user_indexes
       where table_name = '$TABLE_NAME'  and
             status     = 'UNUSABLE';
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
    set MSG = "失敗:データロード(sqlplus) RC=[$rc]"
    $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
    exit  1
endif
grep "UNUSABLE" `find ${USER_LOG_DIR} -name "${JOB_ID}.log2" -print` > ${LOGFILE}3
if !(-z ${LOGFILE}3 ) then
    set MSG = "失敗:データロード(grep) RC=[$rc]"
    $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
    exit  1
endif
# 000001 hayashi add 2007/07/13 end
$LOGWRITE "SQL-LOADER" I "終了:家族マスタデータ追加処理" $USERKEY

#########################################
# STEP-3    テーブルの表領域まとめる    #
#########################################
#表領域をまとめる
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S tccadmin/tccadmin << EOF > $LOGFILE
sqlplus -S $DB_ADMINID/$DB_ADMINPASS << EOF > $LOGFILE
alter tablespace KAIINMST coalesce;
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
   set MSG = "失敗:テーブルの表領域まとめる  RC=[$rc]"
   $LOGWRITE "SQL*PLUS"  E  "$MSG" $USERKEY
   exit  1
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"            # 終了メッセージの出力

exit 0
