#!/bin/csh
#   スクリプト名 ： QTEJS1UX
#   機  能       ： コンソールログ取得処理
#   作成者       ： NBC hayashi 2007/08/16
#
#
#　 修正履歴
# 項番   管理番号    修正内容                修正者         修正日
# 000002 0807073     非互換対応              NBC.ISHIDA  2009/03/29
# 000002 0808052     非互換対応              NBC.ISHIDA  2009/03/29

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                                 # シェル名
setenv JOB_ID       $SHELL_NAME:t                      # ジョブ名
setenv JOBNET_ID   'QTES01UX'                          # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
setenv USERKEY      'QTEJS1UX'                         #
set    KINOU      = 'コンソールログ取得処理'
set    DAY        = `date +%y%m%d%H%M%S`
set    FILE       =  $USER_LOG_DIR/CONSLOG.log_
set    CONSLOGFILE = $FILE$DAY
set MODULE = 'SHELL'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"   # 開始メッセージの出力

##################################
#  コンソールログの取得          #
##################################

set MODULE = 'SQL'
$LOGWRITE "$MODULE" I "開始:コンソールログ取得処理 SQL" $USERKEY

#MOD 0807073 クレジット支援システムの再構築 20090329 NBC.ISHIDA start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 NBC.ISHIDA start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF > $CONSLOGFILE
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF > $CONSLOGFILE
set lin 1200
set colsep ','
set pages 0
SELECT * FROM QUS1_CONSLOGT
WHERE QUS1_DATETIME >= (SELECT QSA5_SYORIYMD FROM QSA5_DATECTRLT);
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 NBC.ISHIDA end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 NBC.ISHIDA end
set rc = $status
if ( $rc != 0 ) then
    set MSG = "失敗:コンソールログ取得処理 RC=[$rc]"
    $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
    exit  1
endif

$LOGWRITE "$MODULE" I "終了:コンソールログ取得処理 SQL" $USERKEY

##########################################
# STEP-99      後始末                    #
##########################################

set MODULE = 'SHELL'
$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   # 終了メッセージの出力

exit 0
