#!/bin/csh
#　スクリプト名  ： QTEJG1UX
#　 機  能       ： 原伝精算繰越ファイル作成
#　 作成者       ： NBC.hayashi
#
#
##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                             # シェル名
setenv JOB_ID       $SHELL_NAME:t                  # ジョブ名
setenv JOBNET_ID   'QLER02UX'                      # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log    # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT       # ログ出力モジュール
setenv USERKEY      'QTEJG1UX'                     # ユーザキー
set    KINOU      = '原伝精算繰越ファイル作成'
set    HUL_DIR = /s020/UFS/fromhost/qt/rcv
set    DAT_DIR = /d051/UFS/data/qt
set MODULE = 'SHELL'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"      # 開始メッセージの出力

#######################################################
# STEP-1 発券データ繰越ファイル退避                   #
#######################################################
STEP_01:

set MODULE = 'command:cp'
set STEPKINOU = '原伝精算ファイル退避'
$LOGWRITE "$MODULE" I "開始:$STEPKINOU" $USERKEY


cp $HUL_DIR/qtax_gendensum.rcv  \
   $HUL_DIR/qtax_gendensum.rcv.taihi
set rc = $status

if ( $rc != 0 ) then
	set MSG = "失敗:$STEPKINOU RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1                                      # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$STEPKINOU" $USERKEY

#000001 ADD hayashi 2007/07/24 START
STEP_02:

set MODULE = 'command:cat'
set STEPKINOU = '原伝精算繰越ファイルマージ'
$LOGWRITE "$MODULE" I "開始:$STEPKINOU" $USERKEY

cat $DAT_DIR/qtax_gendensum.kur   \
    $HUL_DIR/qtax_gendensum.rcv.taihi \
  > $DAT_DIR/qtax_gendensum.marge
set rc = $status

if ( $rc != 0 ) then
	set MSG = "失敗:$STEPKINOU RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1                                      # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$STEPKINOU" $USERKEY

STEP_03:

set MODULE = 'command:mv'
set STEPKINOU = '原伝精算繰越ファイルリネーム'
$LOGWRITE "$MODULE" I "開始:$STEPKINOU" $USERKEY

mv $DAT_DIR/qtax_gendensum.marge \
   $DAT_DIR/qtax_gendensum.kur
set rc = $status

if ( $rc != 0 ) then
	set MSG = "失敗:$STEPKINOU RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1                                      # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$STEPKINOU" $USERKEY


##########################################
# STEP-99      後始末                    #
##########################################
STEP_99:

set MODULE = 'SHELL'

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   # 終了メッセージの出力

exit 0

