#!/bin/csh
# 　スクリプト名 ： QTEJ47UX
#　 機  能       ： 会員・家族マスタ入替データ作成 ７
#　 作成日       ： 2007/02/06
#　 作成者       ： FIP.ERIGUCHI
#　 修正履歴     ： No.   修正内容               修正者       修正日
#
###################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                                 # シェル名
setenv JOB_ID       $SHELL_NAME:t                      # ジョブ名
setenv JOBNET_ID   'QTEI07UX'                          # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
set    USERKEY    = '0KEN-HAISIN'                      # ユーザキー 
set    KINOU      = '会員・家族マスタ入替データ作成 7' # 機能
set    FROMHOST_DIR = /d380/UFS/fromhost/qt/rcv        # ＨＵＬＦＴ受信用ディレクトリ
set    QT_DATA_DIR  = /d380/UFS/data/qt/host           # 作業用ディレクトリ
#########################################
# STEP-1                                #
#########################################

set MODULE = 'utlsend'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"   # 開始メッセージの出力

### ファイルコピー ###
cp $FROMHOST_DIR/qtaf_kaiin9_7.jsn $QT_DATA_DIR/qtaf_kaiin9_7.hft
set rc = $status
if ( $rc != 0 ) then
        $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
        exit  1                                  # 異常終了
endif

cat $FROMHOST_DIR/qtaf_kazoku9_7.jsn >> $QT_DATA_DIR/qtaf_kazoku9.hft
set rc = $status
if ( $rc != 0 ) then
        $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
        exit  1                                  # 異常終了
endif

### 0件ファイル生成 ###
rm     $FROMHOST_DIR/qtaf_kaiin9_7.jsn
rm     $FROMHOST_DIR/qtaf_kazoku9_7.jsn
touch  $FROMHOST_DIR/qtaf_kaiin9_7.jsn
touch  $FROMHOST_DIR/qtaf_kazoku9_7.jsn

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   # 終了メッセージの出力
exit 0                                           # 正常終了

