#!/bin/csh
#　 スクリプト名 ： QTEJ50UX
#　 機  能       ： 会員マスタデータ削除･追加処理
#　 作成者       ： 江口
#　 作成日       ： 2006/08/06
#　 修正履歴     ： 00001 ７回目の処理を追加            FIP.ERIGUCHI 2007/02/06
# 項番   管理番号    修正内容                修正者         修正日
# 000002 0807073     非互換対応              NBC.SHIBUICHI  2009/03/29
# 000002 0808052     非互換対応              NBC.SHIBUICHI  2009/03/29

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                                 # シェル名
setenv JOB_ID       $SHELL_NAME:t                      # ジョブ名
setenv JOBNET_ID    'QTEI10UX'                         # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
set    USERKEY    = $JOB_ID                            # ユーザキー
set    KINOU      = '会員マスタデータ削除･追加処理'    # 機能
set    MODULE     = 'SHELL'

set   QT_WORK_DIR = /d380/UFS/data/qt/svr              # 作業用ディレクトリ
set WLDR_CTRL_DIR = $LDR_CTRL_DIR/ikou                 # ローダー用ディレクトリ

$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"         # 開始メッセージの出力

#########################################
# STEP-1                                #
#########################################
$LOGWRITE "SQL*PLUS" I "開始:会員マスタデータクリア処理" $USERKEY

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF > $LOGFILE
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF > $LOGFILE
TRUNCATE TABLE qta1_kaiinm ;
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
   set MSG = "失敗:会員マスタデータクリア処理  RC=[$rc]"
   $LOGWRITE  "SQL*PLUS"  E  "$MSG" $USERKEY
   exit  1
endif

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S tccadmin/tccadmin << EOF > $LOGFILE
sqlplus -S $DB_ADMINID/$DB_ADMINPASS << EOF > $LOGFILE
alter tablespace KAIINMST coalesce;
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
   set MSG = "失敗:会員マスタテーブルコアレス処理  RC=[$rc]"
   $LOGWRITE  "SQL*PLUS"  E  "$MSG" $USERKEY
   exit  1
endif

$LOGWRITE "SQL*PLUS" I "終了:会員マスタデータクリア処理" $USERKEY

#########################################
# STEP-2                                #
#########################################
$LOGWRITE "$MODULE" I "開始:会員マスタデータ登録処理" $USERKEY

#########################################
# STEP-2.1                              #
#########################################
$EXE_DIR/qtab_s000102.csh 1 $QT_WORK_DIR $WLDR_CTRL_DIR
set rc = $status
if ( $rc != 0 ) then
   set MSG = "失敗:会員マスタデータ追加処理 １ RC=[$rc]"
   $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
   exit  1
endif

#########################################
# STEP-2.2                              #
#########################################
$EXE_DIR/qtab_s000102.csh 2 $QT_WORK_DIR $WLDR_CTRL_DIR
set rc = $status
if ( $rc != 0 ) then
   set MSG = "失敗:会員マスタデータ追加処理 ２ RC=[$rc]"
   $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
   exit  1
endif

#########################################
# STEP-2.3                              #
#########################################
$EXE_DIR/qtab_s000102.csh 3 $QT_WORK_DIR $WLDR_CTRL_DIR
set rc = $status
if ( $rc != 0 ) then
   set MSG = "失敗:会員マスタデータ追加処理 ３ RC=[$rc]"
   $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
   exit  1
endif

#########################################
# STEP-2.4                              #
#########################################
$EXE_DIR/qtab_s000102.csh 4 $QT_WORK_DIR $WLDR_CTRL_DIR
set rc = $status
if ( $rc != 0 ) then
   set MSG = "失敗:会員マスタデータ追加処理 ４ RC=[$rc]"
   $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
   exit  1
endif

#########################################
# STEP-2.5                              #
#########################################
$EXE_DIR/qtab_s000102.csh 5 $QT_WORK_DIR $WLDR_CTRL_DIR
set rc = $status
if ( $rc != 0 ) then
   set MSG = "失敗:会員マスタデータ追加処理 ５ RC=[$rc]"
   $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
   exit  1
endif

#########################################
# STEP-2.6                              #
#########################################
$EXE_DIR/qtab_s000102.csh 6 $QT_WORK_DIR $WLDR_CTRL_DIR
set rc = $status
if ( $rc != 0 ) then
   set MSG = "失敗:会員マスタデータ追加処理 ６ RC=[$rc]"
   $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
   exit  1
endif

# add start 2007/02/06 00001 ==>
#########################################
# STEP-2.7                              #
#########################################
$EXE_DIR/qtab_s000102.csh 7 $QT_WORK_DIR $WLDR_CTRL_DIR
set rc = $status
if ( $rc != 0 ) then
   set MSG = "失敗:会員マスタデータ追加処理 ７ RC=[$rc]"
   $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
   exit  1
endif
# add end   2007/02/06 00001 <==

$LOGWRITE "$MODULE" I "終了:会員マスタデータ登録処理" $USERKEY

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"         # 終了メッセージの出力

exit 0
