#!/bin/csh
#　 スクリプト名 ： QTEJE1UX
#　 機  能       ： 会員マスタデータファイル作成処理
#　 作成者       ： 江口
#　 作成日       ： 2006/08/06
#
#　 修正履歴     ： 00001 ７個目のファイル作成処理を追加    FIP.ERIGUCHI 2007/02/06

##################################
#           環境設定             #
##################################
set    SHELL_NAME   = $0                                   # シェル名
setenv JOB_ID         $SHELL_NAME:t                        # ジョブ名
setenv JOBNET_ID      'QTEIB1UX'                           # ジョブネット名
set    LOGFILE      = $USER_LOG_DIR/${JOB_ID}.log          # ログファイル名
set    LOGWRITE     = $EXE_DIR/QUAJ_MSGLOG.BAT             # ログ出力モジュール
set    USERKEY      = 'QTEJE1UX'                           # ユーザキー
set    KINOU        = '会員マスタデータファイル作成処理'   # 機能
set    MODULE       = 'SHELL'
set    QT_DATA_DIR  = /d380/UFS/data/qt/host               # ＨＵＬＦＴ受信用ディレクトリ
set    QT_WORK_DIR  = /d380/UFS/data/qt/svr                # 作業用ディレクトリ

$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"             # 開始メッセージの出力

#########################################
# STEP-1                                #
#########################################
$EXE_DIR/qtab_s000101.csh 1 $QT_DATA_DIR $QT_WORK_DIR
set rc = $status
if ( $rc != 0 ) then
   $LOGWRITE  "$MODULE 1"  E  "失敗:$KINOU 1 RC=[$rc]" $USERKEY
   exit  1
endif

#########################################
# STEP-2                                #
#########################################
$EXE_DIR/qtab_s000101.csh 2 $QT_DATA_DIR $QT_WORK_DIR
set rc = $status
if ( $rc != 0 ) then
   $LOGWRITE  "$MODULE 2"  E  "失敗:$KINOU 2 RC=[$rc]" $USERKEY
   exit  1
endif

#########################################
# STEP-3                                #
#########################################
$EXE_DIR/qtab_s000101.csh 3 $QT_DATA_DIR $QT_WORK_DIR
set rc = $status
if ( $rc != 0 ) then
   $LOGWRITE  "$MODULE 3"  E  "失敗:$KINOU 3 RC=[$rc]" $USERKEY
   exit  1
endif

#########################################
# STEP-4                                #
#########################################
$EXE_DIR/qtab_s000101.csh 4 $QT_DATA_DIR $QT_WORK_DIR
set rc = $status
if ( $rc != 0 ) then
   $LOGWRITE  "$MODULE 4"  E  "失敗:$KINOU 4 RC=[$rc]" $USERKEY
   exit  1
endif

#########################################
# STEP-5                                #
#########################################
$EXE_DIR/qtab_s000101.csh 5 $QT_DATA_DIR $QT_WORK_DIR
set rc = $status
if ( $rc != 0 ) then
   $LOGWRITE  "$MODULE 5"  E  "失敗:$KINOU 5 RC=[$rc]" $USERKEY
   exit  1
endif

#########################################
# STEP-6                                #
#########################################
$EXE_DIR/qtab_s000101.csh 6 $QT_DATA_DIR $QT_WORK_DIR
set rc = $status
if ( $rc != 0 ) then
   $LOGWRITE  "$MODULE 6"  E  "失敗:$KINOU 6 RC=[$rc]" $USERKEY
   exit  1
endif

# add start 2007/02/06 00001 ==>
#########################################
# STEP-7                                #
#########################################
$EXE_DIR/qtab_s000101.csh 7 $QT_DATA_DIR $QT_WORK_DIR
set rc = $status
if ( $rc != 0 ) then
   $LOGWRITE  "$MODULE 7"  E  "失敗:$KINOU 7 RC=[$rc]" $USERKEY
   exit  1
endif
# add end   2007/02/06 00001 <==

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"           # 終了メッセージの出力

exit 0
