#!/bin/csh
#　 スクリプト名 ： QTTJFLUX
#　 機  能       ： 会員基本属性　暴追用ファイル作成１
#　 作成者       ： FIP
#　 修正履歴     ： 
#------------------------------------------------------#
# 環境設定                                             #
#------------------------------------------------------#
setenv JOBNET_ID    QTT4BDUX                           # ジョブネット名
set    SHELL_NAME = $0                                 # シェル名
setenv JOB_ID       $SHELL_NAME:t                      # ジョブ名
setenv USERKEY      $JOB_ID                            # ユーザキー
set    KINOU      = '会員基本属性　暴追用ファイル作成1'# 機能
set    HULFT_DIR1 = (/d290/UFS/data/qta)               # HULFT受信ＤＩＲ１
set    HULFT_DIR2 = (/d311/UFS/data/qta)               # HULFT受信ＤＩＲ２
set    HULFT_DIR3 = (/d371/UFS/data/qta)               # HULFT受信ＤＩＲ３
#et    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
#------------------------------------------------------#
# STEP-1                                               #
#------------------------------------------------------#
set    MODULE     = COBOL                              # モジュール名
$LOGWRITE "$MODULE" I "開始:$KINOU A" "$USERKEY"         # 開始メッセージの出力
#------------------------------------------------------#
#　 機  能       ： 会員基本属性　暴追用ファイル作成
set    IN_FA      = ($HULFT_DIR3/qtab_s008001.1datA)   #入力Ｆ
set    OT_FA      = ($HULFT_DIR3/qtab_s008010.1datA)   #出力Ｆ
setenv INFILE_Z  ${IN_FA}.Z                            #入力Ｆ（圧縮）
setenv INFILE    ${IN_FA}.${JOB_ID}                    #入力Ｆ（WORK）
setenv OTFILE    $OT_FA                                #出力Ｆ
echo   "入力ファイル名：${INFILE_Z}"
echo   "出力ファイル名：$OTFILE"
#------------------------------------------------------#
echo "***<< STR > (`date +%y%m%d`/`date +%H%M%S`) >>***"

#------------------------------------------------------#
#　 入力ファイル解凍                                   #
#------------------------------------------------------#
set    MODULE     = zcat                               # モジュール名
zcat          ${INFILE_Z}   >   $INFILE
set rc = $status

if ( $rc != 0 ) then
    $LOGWRITE  "$MODULE"  E  "失敗:$KINOU A RC=[$rc]"  "$USERKEY"
    echo "***<< ABNORMAL zcat RC=[$rc] >>***"
    exit(1)
endif

#------------------------------------------------------#
#　 プログラム実行                                     #
#------------------------------------------------------#
set    MODULE     = COBOL                              # モジュール名
setenv NLS_LANG Japanese_Japan.JA16SJIS

$EXE_DIR/qtab_s006900.exe

set rc = $status

setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
    $LOGWRITE  "$MODULE"  E  "失敗:$KINOU A RC=[$rc]"  "$USERKEY"
    echo "***<< ABNORMAL END qtab_s006900 A RC=[$rc] >>***"
    exit(1)
endif
echo "***<< END > (`date +%y%m%d`/`date +%H%M%S`) >>***"
#------------------------------------------------------#
#　 入力ファイル（WORK）削除                           #
#------------------------------------------------------#
rm -f       $INFILE

$LOGWRITE "$MODULE" I "終了:$KINOU A" "$USERKEY"         # 終了メッセージの出力

#------------------------------------------------------#
# STEP-2                                               #
#------------------------------------------------------#
set    MODULE     = COBOL                              # モジュール名
$LOGWRITE "$MODULE" I "開始:$KINOU B" "$USERKEY"         # 開始メッセージの出力
#------------------------------------------------------#
#　 機  能       ： 会員基本属性　暴追用ファイル作成
set    IN_FB      = ($HULFT_DIR3/qtab_s008001.1datB)   #入力Ｆ
set    OT_FB      = ($HULFT_DIR3/qtab_s008010.1datB)   #出力Ｆ
setenv INFILE_Z  ${IN_FB}.Z                            #入力Ｆ（圧縮）
setenv INFILE    ${IN_FB}.${JOB_ID}                    #入力Ｆ（WORK）
setenv OTFILE    $OT_FB                                #出力Ｆ
echo   "入力ファイル名：${INFILE_Z}"
echo   "出力ファイル名：$OTFILE"
#------------------------------------------------------#
echo "***<< STR > (`date +%y%m%d`/`date +%H%M%S`) >>***"

#------------------------------------------------------#
#　 入力ファイル解凍                                   #
#------------------------------------------------------#
set    MODULE     = zcat                               # モジュール名
zcat          ${INFILE_Z}   >   $INFILE
set rc = $status

if ( $rc != 0 ) then
    $LOGWRITE  "$MODULE"  E  "失敗:$KINOU B RC=[$rc]"  "$USERKEY"
    echo "***<< ABNORMAL zcat RC=[$rc] >>***"
    exit(1)
endif

#------------------------------------------------------#
#　 プログラム実行                                     #
#------------------------------------------------------#
set    MODULE     = COBOL                              # モジュール名
setenv NLS_LANG Japanese_Japan.JA16SJIS

$EXE_DIR/qtab_s006900.exe

set rc = $status

setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
    $LOGWRITE  "$MODULE"  E  "失敗:$KINOU B RC=[$rc]"  "$USERKEY"
    echo "***<< ABNORMAL END qtab_s006900 B RC=[$rc] >>***"
    exit(1)
endif
echo "***<< END > (`date +%y%m%d`/`date +%H%M%S`) >>***"
#------------------------------------------------------#
#　 入力ファイル（WORK）削除                           #
#------------------------------------------------------#
rm -f       $INFILE

$LOGWRITE "$MODULE" I "終了:$KINOU B" "$USERKEY"         # 終了メッセージの出力

exit 0                                                 # 正常終了
