#!/bin/csh
#　 スクリプト名 ： QTTJE7UX
#　 機  能       ： 顧客分析データ会員ファイル作成　３
#　 作成者       ： FIP
#------------------------------------------------------#
# 環境設定                                             #
#------------------------------------------------------#
setenv JOBNET_ID    QTT4B8UX                           # ジョブネット名
setenv JOB_ID       QTTJE7UX                           # ジョブ名
setenv USERKEY      QTTJE7UX                           # ユーザキー
set    KINOU      = '顧客分析ﾃﾞｰﾀ会員･利用･ｻﾏﾘ3･4'     # 機能
set    HULFT_DIR1 = (/d290/UFS/data/qta)               # HULFT受信ＤＩＲ１
set    HULFT_DIR2 = (/d311/UFS/data/qta)               # HULFT受信ＤＩＲ２
#et    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
#------------------------------------------------------#
# STEP-1                                               #
#------------------------------------------------------#
set    MODULE     = COBOL                              # モジュール名
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"         # 開始メッセージの出力
#------------------------------------------------------#
#　 機  能       ： 会員属性情報抽出（ポイント情報付）Ａ
echo "*** qtab_s006000 ***"
set    IN_F       = ($HULFT_DIR1/qtab_s006700.3datA)
set    OT_F       = ($HULFT_DIR1/qtab_s006000.3datA)
echo   "入力ファイル名：$IN_F"
echo   "出力ファイル名：$OT_F"
setenv INFILE     $IN_F
setenv OTFILE     $OT_F
#-------------------------------------------------------#
echo "***<< STR > (`date +%y%m%d`/`date +%H%M%S`) >>***"

setenv NLS_LANG Japanese_Japan.JA16SJIS

$EXE_DIR/qtab_s006000.exe

set rc = $status

setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
    $LOGWRITE  "$MODULE"  E  "失敗:$KINOU A RC=[$rc]"  "$USERKEY"
    echo "***<< ABNORMAL END qtab_s006000 A RC=[$rc] >>***"
    exit(1)
endif
echo "***<< END > (`date +%y%m%d`/`date +%H%M%S`) >>***"
#------------------------------------------------------#
set    MODULE     = compress                           # モジュール名
compress -f       $IN_F

set rc = $status

if ( $rc != 0 ) then
    $LOGWRITE  "$MODULE"  E  "失敗:$KINOU A RC=[$rc]"  "$USERKEY"
    echo "***<< ABNORMAL compress A RC=[$rc] >>***"
    exit(1)
endif
#------------------------------------------------------#
set    MODULE     = COBOL                              # モジュール名
#　 機  能       ： 会員属性情報抽出（ポイント情報付）Ｂ
echo "*** qtab_s006000 ***"
set    IN_F       = ($HULFT_DIR1/qtab_s006700.3datB)
set    OT_F       = ($HULFT_DIR1/qtab_s006000.3datB)
echo   "入力ファイル名：$IN_F"
echo   "出力ファイル名：$OT_F"
setenv INFILE     $IN_F
setenv OTFILE     $OT_F
#-------------------------------------------------------#
echo "***<< STR > (`date +%y%m%d`/`date +%H%M%S`) >>***"

setenv NLS_LANG Japanese_Japan.JA16SJIS

$EXE_DIR/qtab_s006000.exe

set rc = $status

setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
    $LOGWRITE  "$MODULE"  E  "失敗:$KINOU B RC=[$rc]"  "$USERKEY"
    echo "***<< ABNORMAL END qtab_s006000 B RC=[$rc] >>***"
    exit(1)
endif
echo "***<< END > (`date +%y%m%d`/`date +%H%M%S`) >>***"
#------------------------------------------------------#
set    MODULE     = compress                           # モジュール名
compress -f       $IN_F

set rc = $status

if ( $rc != 0 ) then
    $LOGWRITE  "$MODULE"  E  "失敗:$KINOU B RC=[$rc]"  "$USERKEY"
    echo "***<< ABNORMAL compress B RC=[$rc] >>***"
    exit(1)
endif
#------------------------------------------------------#
set    MODULE     = COBOL                              # モジュール名
$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"         # 終了メッセージの出力
exit 0                                                 # 正常終了
