#!/bin/csh
#　スクリプト名  ： QTTJF3UX
#　 機  能       ： ＨＵＬＦＴ処理（入会管理ファイル）
#　 作成者       ： FIP
#　修　正　履　歴： 終了ログ出力追加        IMZ.YOSHIDA 2005/08/02
#　　　　　　　　： ディレクトリ変更        IMZ.YOSHIDA 2005/10/26
#------------------------------------------------------#
# 環境設定                                             #
#------------------------------------------------------#
setenv JOBNET_ID    QTT4C3UX                           # ジョブネット名
setenv JOB_ID       QTTJF3UX                           # ジョブ名
setenv USERKEY      QTTJF3UX                           # ユーザキー
# mod by IMZ.YOSHIDA 2005/10/26 ==>
#set    HULFT_DIR1 = (/d290/UFS/data/qta)               # HULFT受信ＤＩＲ１
#set    HULFT_DIR2 = (/d311/UFS/data/qta)               # HULFT受信ＤＩＲ２
set    HULFT_DIR1 = (/d371/UFS/data/qta)               # HULFT受信ＤＩＲ１
set    HULFT_DIR2 = (/d371/UFS/data/qta)               # HULFT受信ＤＩＲ２
# mod by IMZ.YOSHIDA 2005/10/26 <==
#et    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
#------------------------------------------------------#
#1  ＨＵＬＦＴ送信（会員基本情報ファイル）      s008000#OFQY38
#2  ＨＵＬＦＴ送信（会員家族情報ファイル）      s008100#OFQY39
#3○ＨＵＬＦＴ送信（入会管理ファイル）          s008200#OFQY40
#4  ＨＵＬＦＴ送信（当月利用サマリファイル）    s008500#OFQY41
#5  ＨＵＬＦＴ送信（当月利用伝票情報ファイル）  s008300#OFQY42
#6  ＨＵＬＦＴ送信（当月利用行情報ファイル）    s008400#OFQY43
#------------------------------------------------------#
# STEP-1                                               #
#------------------------------------------------------#
set    MODULE     = HULFT                              # モジュール名
set    KINOU      = 'ＨＵＬＦＴ送信（入会管理ファイル）'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"         # 開始メッセージの出力
#------------------------------------------------------#
echo "***<< STR > (`date +%y%m%d`/`date +%H%M%S`) >>***"
ls -l  $HULFT_DIR2/qtab_s008200.dat
#------------------------------------------------------#
mv     $HULFT_DIR2/qtab_s008200.dat    $HULFT_DIR1/O.F.QY40.hft
set rc = $status
if $rc != 0 then
    $LOGWRITE  "$MODULE"  E  "失敗:$KINOU mv1 RC=[$rc]"  "$USERKEY"
    echo "***<< mv1 ABNORMAL END RC=[$rc] >>***"
    exit(1)
endif
#------------------------------------------------------#
utlsend -f OFQY40 -sync
set rc = $status
if ( $rc != 0 ) then
    $LOGWRITE  "$MODULE"  E  "失敗:$KINOU utlsend RC=[$rc]"  "$USERKEY"
    echo "***<< utlsend ABNORMAL END RC=[$rc] >>***"
    exit(1)
endif
#------------------------------------------------------#
mv     $HULFT_DIR1/O.F.QY40.hft        $HULFT_DIR1/qtab_s008200.dat
if $rc != 0 then
    $LOGWRITE  "$MODULE"  E  "失敗:$KINOU mv2 RC=[$rc]"  "$USERKEY"
    echo "***<< mv2 ABNORMAL END RC=[$rc] >>***"
    exit(1)
endif
#------------------------------------------------------#
compress     -f    $HULFT_DIR1/qtab_s008200.dat
set rc = $status
if $rc != 0 then
    $LOGWRITE  "$MODULE"  E  "失敗:$KINOU compress RC=[$rc]"  "$USERKEY"
    echo "***<< compress ABNORMAL END RC=[$rc] >>***"
    exit(1)
endif
#-------------------------------------------------------#
echo "***<< END > (`date +%y%m%d`/`date +%H%M%S`) >>***"
#Added by IMZ.YOSHIDA 2005/08/02 終了ログ出力追加 ==>
$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"         # 終了メッセージの出力
#Added by IMZ.YOSHIDA 2005/08/02 終了ログ出力追加 <==
exit(0)
