#!/bin/csh
#　 スクリプト名 ： QTTJFGUX
#　 機  能       ： 顧客分析データ利用伝票ファイル作成　５後
#　 作成者       ： FIP
#------------------------------------------------------#
# 環境設定                                             #
#------------------------------------------------------#
setenv JOBNET_ID    QTT4B7UX                           # ジョブネット名
setenv JOB_ID       QTTJFGUX                           # ジョブ名
setenv USERKEY      QTTJFGUX                           # ユーザキー
set    KINOU      = '顧客分析ﾃﾞｰﾀ会員･利用･ｻﾏﾘ5･6'     # 機能
set    HULFT_DIR1 = (/d290/UFS/data/qta)               # HULFT受信ＤＩＲ１
set    HULFT_DIR2 = (/d311/UFS/data/qta)               # HULFT受信ＤＩＲ２
#et    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
#------------------------------------------------------#
# STEP-1                                               #
#------------------------------------------------------#
set    MODULE     = COBOL                              # モジュール名
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"         # 開始メッセージの出力
#------------------------------------------------------#
set    MODULE     = YYMMDD                             # モジュール名
set    YYYYMM     = `cut -b1-6 $HULFT_DIR1/QTAB_YYYYMM.txt`
set rc = $status

if ( $rc != 0 ) then
    $LOGWRITE  "$MODULE"  E  "失敗:$KINOU RC=[$rc]"  "$USERKEY"
    echo "***<< ABNORMAL END QTAB_YYYYMM  RC=[$rc] >>***"
    exit(1)
endif
#------------------------------------------------------#
set    MODULE     = COBOL                              # モジュール名
#　 機  能       ： 利用明細伝票抽出Ａ
echo "*** qtab_s006300 ***"
set    IN_F       = ($HULFT_DIR2/qtab_s006000.5datB)
set    OT_F       = ($HULFT_DIR2/qtab_s006300.5datB)
echo   "入力ファイル名：$IN_F"
echo   "出力ファイル名：$OT_F"
setenv INFILE     $IN_F
setenv OTFILE     $OT_F
#-------------------------------------------------------#
echo "***<< STR > (`date +%y%m%d`/`date +%H%M%S`) >>***"

setenv NLS_LANG Japanese_Japan.JA16SJIS

$EXE_DIR/qtab_s006300.exe $YYYYMM

set rc = $status

setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
    $LOGWRITE  "$MODULE"  E  "失敗:$KINOU B RC=[$rc]"  "$USERKEY"
    echo "***<< ABNORMAL END qtab_s006300 B RC=[$rc] >>***"
    exit(1)
endif
echo "***<< END > (`date +%y%m%d`/`date +%H%M%S`) >>***"
#------------------------------------------------------#
set    MODULE     = COBOL                              # モジュール名
$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"         # 終了メッセージの出力
exit 0                                                 # 正常終了
