#!/bin/csh
#　 スクリプト名 ： QTTJE3UX
#　 機  能       ： 顧客分析データ会員ｽﾃｰﾀｽﾌｧｲﾙ取得３
#　 作成者       ： FIP
#------------------------------------------------------#
# 環境設定                                             #
#------------------------------------------------------#
setenv JOBNET_ID    QTT4B3UX                           # ジョブネット名
setenv JOB_ID       QTTJE3UX                           # ジョブ名
setenv USERKEY      QTTJE3UX                           # ユーザキー
set    KINOU      = '顧客分析データ会員ｽﾃｰﾀｽﾌｧｲﾙ取得３'  # 機能
set    HULFT_DIR1 = (/d290/UFS/data/qta)               # HULFT受信ＤＩＲ１
set    HULFT_DIR2 = (/d311/UFS/data/qta)               # HULFT受信ＤＩＲ２
#et    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
#------------------------------------------------------#
# STEP-1                                               #
#------------------------------------------------------#
set    MODULE     = COBOL                              # モジュール名
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"         # 開始メッセージの出力
#------------------------------------------------------#
#　 機  能       ： 会員ステータスファイル変換
echo "*** qtab_s006700 ***"
set    IN_F       = ($HULFT_DIR1/O.F.QA09.hft)
set    OT_FA      = ($HULFT_DIR1/qtab_s006700.3datA)
set    OT_FB      = ($HULFT_DIR1/qtab_s006700.3datB)
echo   "入力ファイル名：$IN_F"
echo   "出力ファイルＡ：$OT_FA"
echo   "出力ファイルＢ：$OT_FB"
setenv INFILE     $IN_F
setenv OTFILE1    $OT_FA
setenv OTFILE2    $OT_FB
#-------------------------------------------------------#
echo "***<< STR > (`date +%y%m%d`/`date +%H%M%S`) >>***"

setenv NLS_LANG Japanese_Japan.JA16SJIS

$EXE_DIR/qtab_s006700.exe

set rc = $status

setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
    $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
    echo "***<< ABNORMAL END qtab_s006700 RC=[$rc] >>***"
    exit(1)
endif
echo "***<< END > (`date +%y%m%d`/`date +%H%M%S`) >>***"
#------------------------------------------------------#
set    MODULE     = mv                                 # モジュール名
mv     $IN_F      $HULFT_DIR1/qtab_OFQA09

set rc = $status

if ( $rc != 0 ) then
    $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
    echo "***<< ABNORMAL END mv RC=[$rc] >>***"
    exit(1)
endif
#------------------------------------------------------#
set    MODULE     = compress                           # モジュール名
compress -f       $HULFT_DIR1/qtab_OFQA09

set rc = $status

if ( $rc != 0 ) then
    $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
    echo "***<< ABNORMAL compress RC=[$rc] >>***"
    exit(1)
endif
#------------------------------------------------------#
set    MODULE     = COBOL                              # モジュール名
$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"         # 終了メッセージの出力
exit 0                                                 # 正常終了
