#!/bin/csh
#　 スクリプト名 ： QTTJF9UX
#　 機  能       ： 顧客分析データ家族ファイル作成　５
#　 作成者       ： FIP
#　 修正履歴     ： 00001 ディレクトリ変更        IMZ.YOSHIDA 2005/11/25
#------------------------------------------------------#
# 環境設定                                             #
#------------------------------------------------------#
setenv JOBNET_ID    QTT4B5UX                           # ジョブネット名
setenv JOB_ID       QTTJF9UX                           # ジョブ名
setenv USERKEY      QTTJF9UX                           # ユーザキー
set    KINOU      = '顧客分析データ家族・利用行5･6'    # 機能
set    HULFT_DIR1 = (/d290/UFS/data/qta)               # HULFT受信ＤＩＲ１
set    HULFT_DIR2 = (/d311/UFS/data/qta)               # HULFT受信ＤＩＲ２
# add by IMZ.YOSHIDA 2005/11/25 00001 ==>
set    HULFT_DIR3 = (/d371/UFS/data/qta)               # HULFT受信ＤＩＲ３
# add by IMZ.YOSHIDA 2005/11/25 00001 <==
#et    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
#------------------------------------------------------#
# STEP-1                                               #
#------------------------------------------------------#
set    MODULE     = COBOL                              # モジュール名
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"         # 開始メッセージの出力
#------------------------------------------------------#
#　 機  能       ： 会員家族情報抽出Ａ
echo "*** qtab_s006100 ***"
set    IN_F       = ($HULFT_DIR2/qtab_s006700.5datA)
set    OT_F       = ($HULFT_DIR2/qtab_s006100.5datA)
echo   "入力ファイル名：$IN_F"
echo   "出力ファイル名：$OT_F"
setenv INFILE     $IN_F
setenv OTFILE     $OT_F
#-------------------------------------------------------#
echo "***<< STR > (`date +%y%m%d`/`date +%H%M%S`) >>***"

setenv NLS_LANG Japanese_Japan.JA16SJIS

$EXE_DIR/qtab_s006100.exe

set rc = $status

setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
    $LOGWRITE  "$MODULE"  E  "失敗:$KINOU A RC=[$rc]"  "$USERKEY"
    echo "***<< ABNORMAL END qtab_s006100 A RC=[$rc] >>***"
    exit(1)
endif
echo "***<< END > (`date +%y%m%d`/`date +%H%M%S`) >>***"
#-------------------------------------------------------#
#　 機  能       ： コンバート変換（会員家族情報）
# mod by IMZ.YOSHIDA 2005/11/25 00001 ==>
#set    OT_F2      = ($HULFT_DIR2/qtab_s008100.5datA)
set    OT_F2      = ($HULFT_DIR3/qtab_s008100.5datA)
# mod by IMZ.YOSHIDA 2005/11/25 00001 <==
echo   "入力ファイル名：$OT_F"
echo   "出力ファイル名：$OT_F2"
setenv IQTS810    $OT_F
setenv OQTS810    $OT_F2
#-------------------------------------------------------#
echo "***<< STR > (`date +%y%m%d`/`date +%H%M%S`) >>***"

setenv NLS_LANG Japanese_Japan.JA16SJIS

$EXE_DIR/qtab_s006600.exe QTS810

set rc = $status

setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
    $LOGWRITE  "$MODULE"  E  "失敗:$KINOU A RC=[$rc]"  "$USERKEY"
    echo "***<< ABNORMAL END qtab_s006600 A RC=[$rc] >>***"
    exit(1)
endif
echo "***<< END > (`date +%y%m%d`/`date +%H%M%S`) >>***"
#------------------------------------------------------#
set    MODULE     = compress                           # モジュール名
compress -f       $OT_F

set rc = $status

if ( $rc != 0 ) then
    $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
    echo "***<< ABNORMAL compress RC=[$rc] >>***"
    exit(1)
endif
#------------------------------------------------------#
compress -f       $OT_F2

set rc = $status

if ( $rc != 0 ) then
    $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
    echo "***<< ABNORMAL compress RC=[$rc] >>***"
    exit(1)
endif
#------------------------------------------------------#
set    MODULE     = COBOL                              # モジュール名
#　 機  能       ： 会員家族情報抽出Ｂ
echo "*** qtab_s006100 ***"
set    IN_F       = ($HULFT_DIR2/qtab_s006700.5datB)
set    OT_F       = ($HULFT_DIR2/qtab_s006100.5datB)
echo   "入力ファイル名：$IN_F"
echo   "出力ファイル名：$OT_F"
setenv INFILE     $IN_F
setenv OTFILE     $OT_F
#-------------------------------------------------------#
echo "***<< STR > (`date +%y%m%d`/`date +%H%M%S`) >>***"

setenv NLS_LANG Japanese_Japan.JA16SJIS

$EXE_DIR/qtab_s006100.exe

set rc = $status

setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
    $LOGWRITE  "$MODULE"  E  "失敗:$KINOU B RC=[$rc]"  "$USERKEY"
    echo "***<< ABNORMAL END qtab_s006100 B RC=[$rc] >>***"
    exit(1)
endif
echo "***<< END > (`date +%y%m%d`/`date +%H%M%S`) >>***"
#-------------------------------------------------------#
#　 機  能       ： コンバート変換（会員家族情報）
# mod by IMZ.YOSHIDA 2005/11/25 00001 ==>
#set    OT_F2      = ($HULFT_DIR2/qtab_s008100.5datB)
set    OT_F2      = ($HULFT_DIR3/qtab_s008100.5datB)
# mod by IMZ.YOSHIDA 2005/11/25 00001 <==
echo   "入力ファイル名：$OT_F"
echo   "出力ファイル名：$OT_F2"
setenv IQTS810    $OT_F
setenv OQTS810    $OT_F2
#-------------------------------------------------------#
echo "***<< STR > (`date +%y%m%d`/`date +%H%M%S`) >>***"

setenv NLS_LANG Japanese_Japan.JA16SJIS

$EXE_DIR/qtab_s006600.exe QTS810

set rc = $status

setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
    $LOGWRITE  "$MODULE"  E  "失敗:$KINOU B RC=[$rc]"  "$USERKEY"
    echo "***<< ABNORMAL END qtab_s006600 B RC=[$rc] >>***"
    exit(1)
endif
echo "***<< END > (`date +%y%m%d`/`date +%H%M%S`) >>***"
#------------------------------------------------------#
set    MODULE     = compress                           # モジュール名
compress -f       $OT_F

set rc = $status

if ( $rc != 0 ) then
    $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
    echo "***<< ABNORMAL compress RC=[$rc] >>***"
    exit(1)
endif
#------------------------------------------------------#
compress -f       $OT_F2

set rc = $status

if ( $rc != 0 ) then
    $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
    echo "***<< ABNORMAL compress RC=[$rc] >>***"
    exit(1)
endif
#------------------------------------------------------#
set    MODULE     = COBOL                              # モジュール名
$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"         # 終了メッセージの出力
exit 0                                                 # 正常終了
