#!/bin/csh
#　 スクリプト名 ： QTTJEDUX
#　 機  能       ： 顧客分析データ入会情報ファイル作成
#　 作成者       ： FIP
#　 修正履歴     ： 00001 ディレクトリ変更        IMZ.YOSHIDA 2005/11/25
#------------------------------------------------------#
# 環境設定                                             #
#------------------------------------------------------#
setenv JOBNET_ID    QTT4B9UX                           # ジョブネット名
setenv JOB_ID       QTTJEDUX                           # ジョブ名
setenv USERKEY      QTTJEDUX                           # ユーザキー
set    KINOU      = '顧客分析データ入会情報'           # 機能
set    HULFT_DIR1 = (/d290/UFS/data/qta)               # HULFT受信ＤＩＲ１
set    HULFT_DIR2 = (/d311/UFS/data/qta)               # HULFT受信ＤＩＲ２
# add by IMZ.YOSHIDA 2005/11/25 00001 ==>
set    HULFT_DIR3 = (/d371/UFS/data/qta)               # HULFT受信ＤＩＲ３
# add by IMZ.YOSHIDA 2005/11/25 00001 <==
#et    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
#------------------------------------------------------#
# STEP-1                                               #
#------------------------------------------------------#
set    MODULE     = COBOL                              # モジュール名
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"         # 開始メッセージの出力
#------------------------------------------------------#
set    MODULE     = YYMMDD                             # モジュール名
set    YYYYMM     = `cut -b1-6 $HULFT_DIR1/QTAB_YYYYMM.txt`
set rc = $status

if ( $rc != 0 ) then
    $LOGWRITE  "$MODULE"  E  "失敗:$KINOU RC=[$rc]"  "$USERKEY"
    echo "***<< ABNORMAL END QTAB_YYYYMM  RC=[$rc] >>***"
    exit(1)
endif
#------------------------------------------------------#
#　 機  能       ： 入会管理情報抽出
echo "*** qtab_s006200 ***"
# mod by IMZ.YOSHIDA 2005/11/25 00001 ==>
#set    OT_F       = ($HULFT_DIR2/qtab_s008200.dat)
set    OT_F       = ($HULFT_DIR3/qtab_s008200.dat)
# mod by IMZ.YOSHIDA 2005/11/25 00001 <==

echo   "出力ファイル名：$OT_F"
setenv OTFILE     $OT_F
#-------------------------------------------------------#
echo "***<< STR > (`date +%y%m%d`/`date +%H%M%S`) >>***"

setenv NLS_LANG Japanese_Japan.JA16SJIS

$EXE_DIR/qtab_s006200.exe $YYYYMM

set rc = $status

setenv NLS_LANG Japanese_Japan.JA16EUC

if ( $rc != 0 ) then
    $LOGWRITE  "$MODULE"  E  "失敗:$KINOU RC=[$rc]"  "$USERKEY"
    echo "***<< ABNORMAL END qtab_s006200 RC=[$rc] >>***"
    exit(1)
endif
echo "***<< END > (`date +%y%m%d`/`date +%H%M%S`) >>***"
#------------------------------------------------------#
set    MODULE     = COBOL                              # モジュール名
$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"         # 終了メッセージの出力
exit 0                                                 # 正常終了
