#!/bin/csh
#　スクリプト名  ： QTTJ40UX
#　 プロセス     ： 京都ＲＧ会員テーブル作成
#　 機  能       ： 京都ＲＧ会員テーブルのLOADを行う
#　 作成者       ： FIP
#
#　 修正履歴
# 項番   管理番号    修正内容                修正者         修正日
# 000001 0807073     非互換対応              NBC.SHIBUICHI  2009/03/29
# 000001 0808052     非互換対応              NBC.SHIBUICHI  2009/03/29

##########################################
#           環境設定                     #
##########################################
set    SHELL_NAME = $0                                      # シェル名
setenv JOB_ID       $SHELL_NAME:t                           # ジョブ名
setenv JOBNET_ID    'QTT401UX'                              # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log             # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT                # ログ出力モジュール
setenv USERKEY      'QTTJ40UX'                              # ユーザキー
set    KINOU      = '京都ＲＧ対応・データロード'

##########################################
#         固有環境設定                   #
##########################################
#ＨＵＬＦＴ受信ディレクトリ
set    HULDIR     = /s020/UFS/fromhost/qt/rcv
#ＨＵＬＦＴ受信ファイル
set    HULFILE    = $HULDIR/OFQWA8.hft
#作業ディレクトリ
set    DATDIR     = /d031/UFS/data/qt/data/host/merge
set    INFILE     = $DATDIR/OFQWA8.dat

##########################################
#         処理開始メッセージ             #
##########################################
set MODULE        = 'SHELL'                                  # モジュール
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"              # 開始メッセージの出力

##########################################
# STEP-1  HULFTファイルデータコピー      #
##########################################
STEP_1:
set    STEPKINOU  = '京都ＲＧ対応・受信データコピー'

 cp -p $HULFILE  $INFILE

set rc = $status
if ( $rc != 0 ) then
    $LOGWRITE  "$MODULE"  E  "失敗: $STEPKINOU  RC=[$rc]"  "$USERKEY"
    exit(1)
endif

##########################################
# STEP-1 主キー制約削除                  #
##########################################
STEP_1:

set    MODULE     = 'SQL*PLUS'
set    STEPKINOU  = 'QTB2 京都ＲＧ主キー制約削除'

$LOGWRITE "$MODULE" I "開始: $STEPKINOU" $USERKEY

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF > $LOGFILE
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF > $LOGFILE
ALTER TABLE QTB2_KYOTORGT          drop primary key;
QUIT SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗: $STEPKINOU RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1
endif

$LOGWRITE "$MODULE" I "終了: $STEPKINOU" $USERKEY

##########################################
# STEP-2  データロード                   #
##########################################
STEP_2:

set    MODULE     = 'SQL*LOADER'
set    STEPKINOU  = 'QTB2 京都ＲＧ会員テーブルロード'
$LOGWRITE  "$MODULE" I "開始: $STEPKINOU" $USERKEY

setenv NLS_LANG  Japanese_Japan.JA16SJIS

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlldr $DB_USERID/$DB_PASSWORD                    \
sqlldr $DB_USERID/$DB_PASSWORD@$ORACLE_SID         \
   control=$LDR_CTRL_DIR/QTB2_KYOTORGT.ctl        \
   data=$INFILE                                   \
   log=$LDR_LOG_DIR/QTB2_KYOTORGT.log             \
   direct=true                                    \
                > $LOGFILE
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
setenv NLS_LANG  Japanese_Japan.JA16EUC
if ($rc != 0) then
   set MSG = "失敗: $STEPKINOU RC=[$rc]"
    $LOGWRITE "$MODULE" E "$MSG" $USERKEY
   exit(1)                                                  #異常終了
endif

$LOGWRITE "$MODULE" I "終了: $STEPKINOU" $USERKEY

##########################################
# STEP-3 主キー制約付与                  #
##########################################
STEP_3:

set    MODULE     = 'SQL*PLUS'
set    STEPKINOU  = 'QTB2 京都ＲＧ主キー制約付与'
$LOGWRITE "$MODULE" I "開始: $STEPKINOU" $USERKEY

#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF > $LOGFILE
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF > $LOGFILE
ALTER TABLE QTB2_KYOTORGT ADD
    PRIMARY KEY(QTB2_PRMKIGYOUCD,
                QTB2_PRMSUBRANGEKEY,
                QTB2_PRMNAIBUKAIINNO)
        USING INDEX NOLOGGING
        TABLESPACE OTHERMST
            STORAGE (
                INITIAL         60K
                NEXT            10K
                MINEXTENTS        1
                MAXEXTENTS      100
                PCTINCREASE       0
                );
quit SQL.SQLCODE
EOF
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

set rc = $status
if ( $rc != 0 ) then
    set MSG = "失敗: $STEPKINOU RC=[$rc]"
    $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
    exit  1
endif

$LOGWRITE "$MODULE" I "終了: $STEPKINOU" $USERKEY

##########################################
# STEP-4 中間ファイル削除                #
##########################################
STEP_4:
rm $HULFILE


##########################################
# STEP-99  終了メッセージ出力            #
##########################################
STEP_99:
set MODULE        = 'SHELL'
$LOGWRITE "$MODULE" I "終了：$KINOU" "$USERKEY"             # 終了メッセージの出力

exit(0)
