#!/bin/csh
#　スクリプト名  ： QTTJG1UX
#　 機  能       ： キャッシング明細ＤＢ取込
#　 作成者       ： ＦＩＰ．横山
#
#　 修正履歴
# 項番   管理番号    修正内容                修正者         修正日
# 000001 0807073     非互換対応              NBC.SHIBUICHI  2009/03/29
# 000001 0808052     非互換対応              NBC.SHIBUICHI  2009/03/29

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                                 # シェル名
setenv JOB_ID       $SHELL_NAME:t                      # ジョブ名
setenv JOBNET_ID   'QTTE01UX'                          # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
setenv USERKEY      'QTTJG1UX'                         # ユーザキー
set    KINOU      = 'キャッシング明細ＤＢ取込'
set    HUL_DIR    = /d361/UFS/data/qta/fromhost
set    DAT_DIR    = /d361/UFS/data/qta/dat

#########################################
# STEP-1                                #
#########################################

set MODULE = 'SQL*LOADER'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"    # 開始メッセージの出力

   ### SQL*LOADERの実行 ###
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi start
#   sqlldr $DB_USERID/$DB_PASSWORD                    \
   sqlldr $DB_USERID/$DB_PASSWORD@$ORACLE_SID         \
      control = $LDR_CTRL_DIR/QTB1_CDMEISAIT.ctl        \
      data    = $HUL_DIR/O.F.QW96.hft               	 \
      log     = $LDR_LOG_DIR/QTB1_CDMEISAIT.log       \
             > $LOGFILE
#MOD 0807073 クレジット支援システムの再構築 20090329 shibuichi end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 shibuichi end

   set rc = $status

   if ( $rc != 0 ) then
            $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
            exit  1                                      # 異常終了
   endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"    # 終了メッセージの出力

exit 0                                           # 正常終了
