#!/bin/csh
#　 スクリプト名 ： QTYJ12UX
#　 機  能       ： 不要会員ファイル作成
#　 作成者       ： FIP

########################################
#           環境設定                   #
########################################
set    SHELL_NAME = $0                                 # シェル名
setenv JOB_ID       $SHELL_NAME:t                      # ジョブ名
setenv JOBNET_ID    QTYF01UX                           # ジョブネット名
setenv USERKEY      QTYJ12UX                           # ユーザキー
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log        # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT           # ログ出力モジュール
set    KINOU      = '不要会員ファイル作成'             # 機能
set    DATA_DIR   = $QJ_DATA_DIR/qt/data/host/merge    # 作業ＤＩＲ

#########################################
# ファイル作成                          #
#########################################
set    MODULE     = COBOL                              # モジュール名
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"         # 開始メッセージの出力

#  ファイル識別子の設定
setenv INFILE  $DATA_DIR/qtaf_kaiin5.sort              # マージファイル
setenv OTFILE1 $DATA_DIR/qtaf_kaiin5.dat               # 削除対象ファイル
setenv OTFILE2 $DATA_DIR/qtaf_kaiin5.kur               # 削除対象外ファイル

set PROGRAM = $EXE_DIR/qtab_s000421.exe
if ( -x $PROGRAM ) then
    setenv NLS_LANG Japanese_Japan.JA16SJIS            # 文字コード体系をSJISにする
    $PROGRAM > &  $LOGFILE                             # プログラム起動
    set rc = $status                                   # リターンステータス待避
    setenv NLS_LANG Japanese_Japan.JA16EUC             # 文字コード体系をEUCに戻す
else
    $LOGWRITE  "$MODULE"  E  "実行プログラム[$PROGRAM]が存在しない。" "$USERKEY"
    exit 1                                             # 異常終了
endif

if ( $rc != 0 ) then
    $LOGWRITE  "$MODULE"  E  "失敗:$KINOU  RC=[$rc]"  "$USERKEY"
    exit(1)
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"         # 終了メッセージの出力

exit 0                                                 # 正常終了
