#!/bin/csh
#　スクリプト名  ： QXDJLDUX
#　 機  能       ： 事故売上管理：入金データ日次受信ファイル作成
#　 作成者       ： FIP
#

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                              # シェル名
setenv JOB_ID       $SHELL_NAME:t                   # ジョブ名
setenv JOBNET_ID   'QXD1D2UX'                       # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log     # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT        # ログ出力モジュール
setenv USERKEY      'QXDJLDUX'                      # ユーザキー
set    KINOU      = '事故売上管理：入金データ日次受信ファイル作成'
set    QX_DATA_DIR   = /d051/UFS/data/qxn/alarmdata    #TMP FILE DIR

set MODULE = 'SHELL'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"   # 開始メッセージの出力

###############################################
# STEP-1 ローダ用ﾃﾞｰﾀ作成(入金）　　　#
###############################################
STEP_01:
set MODULE = 'qxnb_s000150'
set STEPKINOU = '入金ローダ用データ作成'
$LOGWRITE "$MODULE" I "開始:$STEPKINOU" "$USERKEY"     # 開始メッセージの出力

#ファイル作成

set PROGRAM = $EXE_DIR/qxnb_s000150.exe

if ( -x $PROGRAM ) then
    #  ファイル識別子の設定
    setenv INFILE1   $FROMHOST1_DIR/qxn/rcv/qxnf_nyuukindata.hulft
    setenv OUTFIL1   $QX_DATA_DIR/qxnj_loaddata_dat.dat
    #
    setenv NLS_LANG Japanese_Japan.JA16SJIS      # 文字コード体系をSJISにする
    $PROGRAM       >&  $LOGFILE                  # プログラム起動
    set rc = $status                             # リターンステータス待避
    setenv NLS_LANG Japanese_Japan.JA16EUC       # 文字コード体系をEUCに戻す
else
    $LOGWRITE  "$MODULE"  E  "実行プログラム[$PROGRAM]が存在しない。" "$USERKEY"
    exit 1                                       # 異常終了
endif

if ( $rc != 0 ) then                             # リターンステータス判定
    set MSG = "失敗:$STEPKINOU RC=[$rc]"
    $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
    exit  1                                      # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$STEPKINOU" "$USERKEY"   # 終了メッセージの出力



##########################################
# STEP-99      後始末                    #
##########################################
STEP_99:

set MODULE = 'SHELL'
$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   # 終了メッセージの出力

exit 0
