#!/bin/csh
#　スクリプト名  ： QXDJO6UX
#　 機  能       ： 本人悪用データ期日管理
#　 作成者       ： FIP
#

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                             # シェル名
setenv JOB_ID       $SHELL_NAME:t                  # ジョブ名
setenv JOBNET_ID   'QXDKD1UX'                      # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log    # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT       # ログ出力モジュール
setenv USERKEY      'QXDJO6UX'                     # ユーザキー 
set    KINOU      = '本人悪用テーブル期日管理'

set    QX_SAVE_DIR  = /d271/UFS/data/qxn           #本番 期日 SAVE DIR

set    TABLE_NAME   = QXN6_HONAKUDATAT             # 対象テーブル名

set MODULE = 'SHELL'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"     # 開始メッセージの出力

set year  = `date +%Y`                     # 処理年 (システム日付より)
set month = `date +%m`                     # 処理月 (システム日付より)
set day   = `date +%d`                     # 処理日 (システム日付より)

############################################
# STEP-1 本人悪用エラーテーブル　期日管理  #
############################################
STEP_1:

set MODULE = 'qxnb_s000130'
set STEPKINOU = '本人悪用テーブル　期日管理'
$LOGWRITE "$MODULE" I "開始:$STEPKINOU" $USERKEY

rm -f $QX_SAVE_DIR/kijitu/qxnf_qxn6honakudata.dat.$year$month$day.Z

setenv OT1FILE $QX_SAVE_DIR/kijitu/qxnf_qxn6honakudata.dat.$year$month$day

set PROGRAM = $EXE_DIR/qxnb_s000130.exe
if ( -x $PROGRAM ) then
    setenv NLS_LANG Japanese_Japan.JA16SJIS    # 文字コード体系をSJISにする
    $PROGRAM       >&  $LOGFILE                # プログラム起動
    set rc = $status                           # リターンステータス待避
    setenv NLS_LANG Japanese_Japan.JA16EUC     # 文字コード体系をEUCに戻す
else
    $LOGWRITE  $PROGRAM:t  E  '実行プログラム[$PROGRAM]が存在しない。'
    exit 1                                     # 異常終了
endif

if ( $rc != 0 ) then                           # リターンステータス判定
    set MSG = "失敗:$STEPKINOU RC=[$rc]"
    $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
    exit  1                                    # 異常終了
endif

compress -f $QX_SAVE_DIR/kijitu/qxnf_qxn6honakudata.dat.$year$month$day

$LOGWRITE "$MODULE" I "終了:$STEPKINOU" $USERKEY

##########################################
# STEP-99      後始末                    #
##########################################
STEP_END_PROC:

set MODULE = 'SHELL       '
$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   # 終了メッセージの出力

exit 0

