#!/bin/csh
#　スクリプト名  ： QXDJM5UX
#　 機  能       ： 事故売上管理：０件データ送信
#　 作成者       ： FIP
#

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                           # シェル名
setenv JOB_ID       $SHELL_NAME:t                # ジョブ名
setenv JOBNET_ID   'QXD1D3UX'                    # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log  # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT     # ログ出力モジュール
setenv USERKEY      'QXDJM5UX'                   # ユーザキー 
set    KINOU      = '悪用０件データ送信'         # 機能

set MODULE = 'SHELL'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"   # 開始メッセージの出力

#########################################
# STEP-1                                #
#########################################
set MODULE = 'utlsend'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"     # 開始メッセージの出力

rm -f  $FROMHOST1_DIR/qxn/rcv/qxnf_akudata.hulft
touch  $FROMHOST1_DIR/qxn/rcv/qxnf_akudata.hulft

### 送信の実行 ###
utlsend  -f OFQW55 -sync
set rc = $status

if ( $rc != 0 ) then
	set MSG = "失敗:$KINOU RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1                                      # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   # 終了メッセージの出力

exit 0

