#!/bin/csh
#　スクリプト名  ： QXDJK1UX
#　 機  能       ： 事故売上管理：リプリ売上データ日次受信ファイル配信要求
#　 作成者       ： FIP
#

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                           # シェル名
setenv JOB_ID       $SHELL_NAME:t                # ジョブ名
setenv JOBNET_ID   'QXDJK1UX'                    # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log  # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT     # ログ出力モジュール
setenv USERKEY      'QXDJK1UX'                   # ユーザキー 
set    KINOU      = 'リプリ売上データ配信要求'   # 機能

set MODULE = 'SHELL'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"   # 開始メッセージの出力

#########################################
# STEP-1                                #
#########################################
set MODULE = 'utlrecv'
$LOGWRITE "$MODULE" I "開始:リプリ売上データ配信要求" $USERKEY

### 送信要求の実行 ###
utlrecv  -f OFQW51 -sync   #リプリ売上データ
set rc = $status

if ( $rc != 0 ) then
	set MSG = "失敗:リプリ売上データ配信要求 RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1                                      # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:リプリ売上データ配信要求" $USERKEY

##########################################
# STEP-99      後始末                    #
##########################################
STEP_99:

set MODULE = 'SHELL'
$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   # 終了メッセージの出力

exit 0

