#!/bin/csh
#　スクリプト名  ： QXDJL4UX
#　 機  能       ： 事故売上管理：海外返品繰越データ連結
#　 作成者       ： FIP
#
#-------------------------------------------------------------------------
#          修  正  履  歴
# 管理No              修正内容                    担当者      修正日付
# TR0601-014          海外返品売上業務障害対応    NBC野村     06.02.28

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                              # シェル名
setenv JOB_ID       $SHELL_NAME:t                   # ジョブ名
#TR0601-014 MOD START          060228
#setenv JOBNET_ID   'QXD1D2UX'                       # ジョブネット名
setenv JOBNET_ID   'QXD1D4UX'                       # ジョブネット名
#TR0601-014 MOD END            060228
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log     # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT        # ログ出力モジュール
setenv USERKEY      'QXDJL4UX'                      # ユーザキー
set    KINOU      = '事故売上管理：海外返品繰越データ連結'
set    QX_DATA_DIR   = /d051/UFS/data/qxn/alarmdata   #TMP FILE DIR

set MODULE = 'SHELL'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"   # 開始メッセージの出力


#TR0601-014 DEL START          060228
###
####連結用ファイルの作成（ファイルが存在しないとき作る）
###touch $QX_DATA_DIR/qxn2_loaddata_dat.bak
###
##################################################
#### STEP-1 海外返品繰越データ連結　　　　　　　 #
##################################################
###STEP_01:
###set MODULE = 'command:cat'
###$LOGWRITE "$MODULE" I "開始:本日取得分データと繰越データの結合（海外返品）" $USERKEY
###
###### 本日取得分ｈｕｌｆｔデータと繰越データの結合（海外返品） ###
###cat $QX_DATA_DIR/qxn2_loaddata_dat.dat \
###    $QX_DATA_DIR/qxn2_loaddata_dat.bak \
###  > $QX_DATA_DIR/qxn2_loaddata_dat.load
###
######2000/09/01 ハルフトデータをコピー退避する
###cp /s020/UFS/fromhost/qxn/rcv/qxnf_khendata.hulft \
###    $QX_DATA_DIR/qxnf_khendata.hulft.bak
###
###set rc = $status
###
###if ( $rc != 0 ) then
###	set MSG = "失敗:本日取得分データと繰越データの結合１（海外返品）RC=[$rc]"
###	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
###	exit  1                                      # 異常終了
###endif
###
###$LOGWRITE "$MODULE" I "終了:本日取得分データと繰越データの結合（海外返品）" $USERKEY
###
##########################################################
#### STEP-2     繰越データのクリア                       #
##########################################################
###STEP_02:
###
###set MODULE = 'command:rm'
###$LOGWRITE "$MODULE" I "開始:繰越データのクリア" $USERKEY
###
###### 繰越データのクリア ###
###rm -f $QX_DATA_DIR/qxn2_loaddata_dat.bak
###set rc = $status
###
###if ( $rc != 0 ) then
###	set MSG = "失敗:繰越データのクリア RC=[$rc]"
###	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
###	exit  1                                      # 異常終了
###endif
###
###$LOGWRITE "$MODULE" I "終了:繰越データのクリア" $USERKEY
###
#TR0601-014 DEL END            060228

#TR0601-014 ADD START          060228
########################################################
## STEP-1     本日分のhulftデータをコピー退避          #
########################################################
STEP_01:

cp /s020/UFS/fromhost/qxn/rcv/qxnf_khendata.hulft \
    $QX_DATA_DIR/qxnf_khendata.hulft.bak

set rc = $status
if ( $rc != 0 ) then
	set MSG = "失敗:$KINOU RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1                                      # 異常終了
endif

#TR0601-014 ADD END            060228

##########################################
# STEP-99      後始末                    #
##########################################
STEP_99:

set MODULE = 'SHELL'
$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   # 終了メッセージの出力

exit 0
