#!/bin/csh
#　スクリプト名  ： QYDJM1UX
#　 機  能       ： 発券データテーブルＬＯＡＤ
#　 作成者       ： FIP
#
#  修正番号 修正者   修正日時   修正内容
#  000001   hayashi  2007/07/13 ﾛｰﾀﾞｰ後ｲﾝﾃﾞｯｸｽﾁｪｯｸ追加
#  000002   hayashi  2007/07/24 繰越ファイル作成修正
#  000003   ISHIDA   2009/03/29 非互換対応
#  000003   ISHIDA   2009/03/29 非互換対応

##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                              # シェル名
setenv JOB_ID       $SHELL_NAME:t                   # ジョブ名
setenv JOBNET_ID   'QYD014UX'                       # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log     # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT        # ログ出力モジュール
setenv USERKEY      'QYDJM1UX'                      # ユーザキー
set    KINOU      = '発券データテーブルＬＯＡＤ'    # 機能

set TABLE_NAME    = QYA1_HAKKENDATAT                    # 対象テーブル名

set MODULE = 'SHELL'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"      # 開始メッセージの出力

##################################
# STEP-1 データロード            #
##################################
STEP_1:

set MODULE = 'SQL*LOADER'
$LOGWRITE "$MODULE" I "開始:QYA1 データロード" $USERKEY
#MOD 0807073 クレジット支援システムの再構築 20090329 NBC.ISHIDA start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 NBC.ISHIDA start
#sqlldr $DB_USERID/$DB_PASSWORD                         \
#   control=$LDR_CTRL_DIR/qyad_hakkendatat.sql          \
#   data=$QY_DATA_DIR/hakken_daily/qyaf_hakkendata.load \
#   log=$LDR_LOG_DIR/qyad_hakkendatat_daily.log         \
#   direct=true                                         \
#               > $LOGFILE

sqlldr $DB_USERID/$DB_PASSWORD@$ORACLE_SID             \
   control=$LDR_CTRL_DIR/qyad_hakkendatat.sql          \
   data=$QY_DATA_DIR/hakken_daily/qyaf_hakkendata.load \
   log=$LDR_LOG_DIR/qyad_hakkendatat_daily.log         \
   direct=true                                         \
               > $LOGFILE
#MOD 0807073 クレジット支援システムの再構築 20090329 NBC.ISHIDA end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 NBC.ISHIDA end

set rc = $status
if ( $rc != 0 ) then
        set MSG = "失敗:QYA1 データロード RC=[$rc]"
        $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
        exit  1
endif
# 000001 hayashi add 2007/07/13 start
#----------------------------------------------------------#
#   インデックスエラーのチェック
#----------------------------------------------------------#
rm -f ${LOGFILE}2 ${LOGFILE}3
#MOD 0807073 クレジット支援システムの再構築 20090329 NBC.ISHIDA start
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 NBC.ISHIDA start
#sqlplus -S $DB_USERID/$DB_PASSWORD << EOF > ${LOGFILE}2
sqlplus -S $DB_USERID/$DB_PASSWORD@$ORACLE_SID << EOF > ${LOGFILE}2
set lin 200
select index_name,status from user_indexes
       where table_name = '$TABLE_NAME'  and
             status     = 'UNUSABLE';
quit SQL.SQLCODE
EOF

#MOD 0807073 クレジット支援システムの再構築 20090329 NBC.ISHIDA end
#MOD 0808052 ＴＣＣ支援システムの再構築     20090329 NBC.ISHIDA end

set rc = $status
if ( $rc != 0 ) then
    set MSG = "失敗:データロード(sqlplus) RC=[$rc]"
    $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
    exit  1
endif
grep "UNUSABLE" `find ${USER_LOG_DIR} -name "${JOB_ID}.log2" -print` > ${LOGFILE}3
if !(-z ${LOGFILE}3 ) then
    set MSG = "失敗:データロード(grep) RC=[$rc]"
    $LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
    exit  1
endif
# 000001 hayashi add 2007/07/13 end
$LOGWRITE "$MODULE" I "終了:QYA1 データロード" $USERKEY

##########################################
# STEP-99      後始末                    #
##########################################
STEP_99:

set MODULE = 'SHELL'
#00002 DEL hayashi 2007/07/24 START
#    rm    $FROMHOST1_DIR/qy/rcv/qyaf_hakkendata.hulft
#    touch $FROMHOST1_DIR/qy/rcv/qyaf_hakkendata.hulft
#00002 DEL hayashi 2007/07/24 END
$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   # 終了メッセージの出力

exit 0

