#!/bin/csh
#　スクリプト名  ： QYEJ22UX
#　 機  能       ： 発券繰越ファイル退避
#　 作成者       ： FIP
#
#   管理番号  修正内容                        担当者        日付
#   000001    繰越ファイル作成修正            nbc.hayashi   2007/07/24
#
##################################
#           環境設定             #
##################################
set    SHELL_NAME = $0                             # シェル名
setenv JOB_ID       $SHELL_NAME:t                  # ジョブ名
setenv JOBNET_ID   'QLER02UX'                      # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log    # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT       # ログ出力モジュール
setenv USERKEY      'QYEJ22UX'                     # ユーザキー
set    KINOU      = '発券繰越ファイル退避'

set MODULE = 'SHELL'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"      # 開始メッセージの出力

#######################################################
# STEP-1 発券データ繰越ファイル退避                   #
#######################################################
STEP_01:

set MODULE = 'command:cp'
set STEPKINOU = '発券データ繰越ファイル退避'
$LOGWRITE "$MODULE" I "開始:$STEPKINOU" $USERKEY

#000001 MOD hayashi 2007/07/24 START
#cp $QY_DATA_DIR/hakken_daily/qyaf_hakkendata.load  \
#   $QY_DATA_DIR/hakken_daily/qyaf_hakkendata.store
cp $FROMHOST1_DIR/qy/rcv/qyaf_hakkendata.hulft  \
   $QY_DATA_DIR/hakken_daily/qyaf_hakkendata.taihi
#000001 MOD hayashi 2007/07/24 END
set rc = $status

if ( $rc != 0 ) then
	set MSG = "失敗:$STEPKINOU RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1                                      # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$STEPKINOU" $USERKEY

#000001 ADD hayashi 2007/07/24 START
STEP_02:

set MODULE = 'command:cat'
set STEPKINOU = '発券データ繰越ファイルマージ'
$LOGWRITE "$MODULE" I "開始:$STEPKINOU" $USERKEY

cat $QY_DATA_DIR/hakken_daily/qyaf_hakkendata.kur   \
    $QY_DATA_DIR/hakken_daily/qyaf_hakkendata.taihi \
  > $QY_DATA_DIR/hakken_daily/qyaf_hakkendata.marge
set rc = $status

if ( $rc != 0 ) then
	set MSG = "失敗:$STEPKINOU RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1                                      # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$STEPKINOU" $USERKEY

STEP_03:

set MODULE = 'command:mv'
set STEPKINOU = '発券データ繰越ファイルリネーム'
$LOGWRITE "$MODULE" I "開始:$STEPKINOU" $USERKEY

mv $QY_DATA_DIR/hakken_daily/qyaf_hakkendata.marge \
   $QY_DATA_DIR/hakken_daily/qyaf_hakkendata.kur
set rc = $status

if ( $rc != 0 ) then
	set MSG = "失敗:$STEPKINOU RC=[$rc]"
	$LOGWRITE  "$MODULE"  E  "$MSG" $USERKEY
	exit  1                                      # 異常終了
endif

$LOGWRITE "$MODULE" I "終了:$STEPKINOU" $USERKEY

#000001 ADD hayashi 2007/07/24 END

##########################################
# STEP-99      後始末                    #
##########################################
STEP_99:

set MODULE = 'SHELL'

$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"   # 終了メッセージの出力

exit 0

