#!/bin/csh
#　スクリプト名  ： QZDJ12UX
#　 機  能       ： アクセスログレコード削除処理
#　 作成者       ： FIP
#　 新規         ： 05/08/29

####################################################
#      環境設定                                    #
####################################################
set    SHELL_NAME = $0                             # シェル名
setenv JOB_ID       $SHELL_NAME:t                  # ジョブ名
setenv JOBNET_ID    'QZD102UX'                     # ジョブネット名
set    LOGFILE    = $USER_LOG_DIR/${JOB_ID}.log    # ログファイル名
set    LOGWRITE   = $EXE_DIR/QUAJ_MSGLOG.BAT       # ログ出力モジュール
setenv USERKEY      'QZDJ12UX'                     # ユーザキー
set    KINOU      = 'アクセスログＤＢ削除処理（支援）'
####################################################
set MODULE = 'SHELL'
$LOGWRITE "$MODULE" I "開始:$KINOU" "$USERKEY"     #開始メッセージの出力
####################################################
#      STEP-1  アクセスログＤＢ削除処理            #
####################################################
STEP_1:
set MODULE = 'qzab_s000200'
set STEPKINOU = 'アクセスログＤＢ削除処理'
$LOGWRITE "$MODULE" I "開始:$STEPKINOU" "$USERKEY" # 開始メッセージの出力

set PROGRAM = $EXE_DIR/qzab_s000200.exe
if ( -x $PROGRAM ) then
    setenv NLS_LANG Japanese_Japan.JA16SJIS        # 文字コード体系をSJISにする
    $PROGRAM       >&  $LOGFILE                    # プログラム起動
    set rc = $status                               # リターンステータス待避
else
    $LOGWRITE  $PROGRAM:t  E  '実行プログラム[$PROGRAM]が存在しない。'
    exit 1                                         # 異常終了
endif

if ( $rc != 0 ) then                               # リターンステータス判定
    set MSG = "失敗:$STEPKINOU RC=[$rc]"
    $LOGWRITE      "$MODULE"  E  "$MSG" $USERKEY
    exit  1                                        # 異常終了
endif

####################################################
# STEP-99      終了処理                            #
####################################################
STEP_END_PROC:

set MODULE = 'SHELL       '
$LOGWRITE "$MODULE" I "終了:$KINOU" "$USERKEY"     #終了メッセージの出力

exit 0

