--ÇbÇrëŒâûóöó
--DROP   VIEW QCS9_TOGOMEMOV;
-- 2004/09/11 íäèoèàóùíxâÑÇÃëŒâû
-- IMZ.YAMADA   Ç∆ÇËÇ†Ç¶Ç∏ÇÃ ÉqÉìÉgï∂í«â¡Ç∆ÅAä˙ì˙ä«óùÇsÇï ÉrÉÖÅ[Ç÷
CREATE VIEW QCS9_TOGOMEMOV ( 
 QCS9_KBN
,QCS9_MAKEDATE
,QCS9_SYSTEMSKBCD
,QCS9_MEMOBNRCD
,QCS9_MEMOCD
,QCS9_NKNO
,QCS9_BLACKNO
,QCS9_UKETSUKENO
,QCS9_TANTOID
,QCS9_TANTONM
,QCS9_MEMONM
,QCS9_MEMO
,QCS9_DELDate
 ) AS 
select	/*+ INDEX(QSA7_TOGOMEMOT,XIE1QSA7_TOGOMEMOT) */
		'2'              VCS9_KBN,
		QSA7_MAKEDATE    VCS9_MAKEDATE,
		QSA7_SYSTEMSKBCD VCS9_SYSTEMSKBCD,
		QSA7_MEMOBNRCD   VCS9_MEMOBNRCD,
		QSA7_MEMOCD      VCS9_MEMOCD,
		QSA7_NKNO        VCS9_NKNO,
		QSA7_BLACKNO     VCS9_BLACKNO,
		QSA7_UKETSUKENO  VCS9_UKETSUKENO,
		QSA7_TANTOID     VCS9_TANTOID ,
		nvl(QSA7_TANTONM,QSA7_TANTOID) VCS9_TANTONM,
		QSA7_MEMONM      VCS9_MEMONM,
		QSA7_MEMO        VCS9_MEMO,
		To_Char(QSA7_DELDate,'YYYY/MM/DD')   VCS9_DELDate
		from QSA7_TOGOMEMOT
		--Where QSA7_DELDate is null
union all
select	/*+ INDEX(QCS9_TOGOMEMOT,XIE1QCS9_TOGOMEMOT) */
		'1'              VCS9_KBN,
		QCS9_MAKEDATE    VCS9_MAKEDATE,
		QCS9_SYSTEMSKBCD VCS9_SYSTEMSKBCD,
		QCS9_MEMOBNRCD   VCS9_MEMOBNRCD,
		QCS9_MEMOCD      VCS9_MEMOCD,
		QCS9_NKNO        VCS9_NKNO,
		QCS9_BLACKNO     VCS9_BLACKNO,
		QCS9_UKETSUKENO  VCS9_UKETSUKENO,
		QCS9_TANTOID     VCS9_TANTOID ,
		nvl(QCS9_TANTONM,QCS9_TANTOID) VCS9_TANTONM,
		QCS9_MEMONM      VCS9_MEMONM,
		QCS9_MEMO        VCS9_MEMO,
		To_Char(QCS9_DELDate,'YYYY/MM/DD')   VCS9_DELDate
		from QCS9_TOGOMEMOT
		--Where QCS9_DELDate is null
;
