--CREATE VIEW QXB1_KANSHIV
CREATE OR REPLACE VIEW QXB1_KANSHIV
(QXB1_PRMKIGYOUCD,QXB1_PRMSUBRANGEKEY,QXB1_PRMNAIBUKAIINNO,
	QXB1_CARDKBN,QXB1_GKNSHIKIBETSUNO,QXB1_GKNEDABAN,
	QXB1_SVTOUROKUYMD,QXB1_KANSIJYOKENNO,QXB1_HANTEIKEKKA,
	QXB1_HONSHIMEIKAN,QXB1_STSKOZA,QXB1_YSNSOUGENDO,
	QXB1_KANSIJYOKENKINGAKU,QXB1_KANSIJYOKENKAISU)
AS
SELECT
	 QXB1_PRMKIGYOUCD				--企業コード
	,QXB1_PRMSUBRANGEKEY			--サブレンジキー
	,QXB1_PRMNAIBUKAIINNO			--内部会員番号
	,QTA1_CARDKBN					--カード区分
	,QTA1_GKNSHIKIBETSUNO			--識別番号
	,QTA1_GKNEDABAN					--枝番
	,QXB1_SVTOUROKUYMD				--登録日
	,QXB1_KANSIJYOKENNO				--監視条件№
	,QXB1_HANTEIKEKKA				--判定結果
	,QTA1_HONSHIMEIKAN				--氏名
	,QTA1_STSKOZA					--口座ステータス
	,QTA1_YSNSOUGENDO				--与信情報・総限度額
	,QXB1_KANSIJYOKENKINGAKU		--監視条件金額
	,QXB1_KANSIJYOKENKAISU			--監視条件回数
FROM
	 QXB1_KANSIINFOT				--売上監視テーブル
	,QTA1_KAIINM					--会員マスタテーブル
WHERE
	QXB1_PRMKIGYOUCD = QTA1_PRMKIGYOUCD
AND
	QXB1_PRMSUBRANGEKEY = QTA1_PRMSUBRANGEKEY
AND
	QXB1_PRMNAIBUKAIINNO = QTA1_PRMNAIBUKAIINNO
/
