CREATE OR REPLACE VIEW QXS8_CICEFFECTV(
	QXS8_SHORIYMD,
	QXS8_JYUSHINTIME,
	QXS8_GAIBUKAIINNO,
	QXS8_KJNAME,
	QXS8_KINGAKU)
AS
SELECT		--HINT•¶‚È‚µ
--SELECT /*+ INDEX(QXA1_AUTHORILOGT@QS_FDS.FDS.CARD XIE4QXA1_AUTHORILOGT@QS_FDS.FDS.CARD) */	--–{”ÔŠÂ‹«
--SELECT /*+ INDEX(QXA1_AUTHORILOGT XIE4QXA1_AUTHORILOGT) */	--STŠÂ‹«
	A.QXA1_SHORIYMD,
	A.QXA1_JYUSHINTIME,
	A.QXA1_GAIBUKAIINNO,
	J.QXS1_KJNAME,
	A.QXA1_KINGAKU
FROM
	QXA1_AUTHORILOGT@QS_FDS.FDS.CARD A,		--–{”ÔŠÂ‹«
--	QXA1_AUTHORILOGT A,						--STŠÂ‹«
	QXS1_JIKOUKET J
WHERE ((A.QXA1_JYUSHINTIME BETWEEN '00:00:00' AND '10:00:00'
	AND A.QXA1_SHORIYMD = TO_CHAR(J.QXS1_PRMMAKEDATE,'YYYY/MM/DD'))
	OR  (A.QXA1_JYUSHINTIME BETWEEN '18:00:00' AND '24:00:00'
	AND A.QXA1_SHORIYMD = TO_CHAR(J.QXS1_PRMMAKEDATE - 1,'YYYY/MM/DD')))
	AND A.QXA1_ERRORCODE = 'G60'
	AND A.QXA1_GAIBUKAIINNO = J.QXS1_GAIBUKAIINNO
	AND (J.QXS1_NEGAKBN = '1'
	OR	J.QXS1_NEGAKBN = '2')
	AND J.QXS1_DELDATE IS NULL
;
SHOW ERRORS;
