--DROP   VIEW QXTD_ZENKAIV ;

CREATE VIEW QXTD_ZENKAIV (
QXTD_PRMTABANO
,QXTD_PRMKIGYOUCD
,QXTD_PRMSUBRANGEKEY
,QXTD_PRMNAIBUKAIINNO
,QXTD_PRMKANKEIKBN
,QXTD_PRMKAZOKURBN
,QXTD_HIRAISTATUS
,QXTD_CARDKBN
,QXTD_KAIINNO
,QXTD_SIMEI
,QXTD_REVSMAITSUKI
,QXTD_REVSBONUS
,QXTD_REVCMAITSUKI
,QXTD_REVCBONUS
,QXTD_KANRITEN
,QXTD_NYKAIYMD
,QXTD_CTLHONKNNAME
,QXTD_HALFORONEKBN
,QXTD_BIRTHDAY
,QXTD_JIFURIKAISU
,QXTD_JIFURINGKAISU
,QXTD_TEL1
,QXTD_TEL2
,QXTD_TEL3
,QXTD_KININMUKBN
,QXTD_KINKNNAME
,QXTD_KINTEL1
,QXTD_KINTEL2
,QXTD_KINTEL3
,QXTD_DHPOSSTATUS
,QXTD_DHDAIHYOSTATUS
,QXTD_HYOSINRANK
,QXTD_HCASHLIMIT
,QXTD_CREATEDATE
,QXTD_STRDATE
,QXTD_DELDATE
,QXTD_OPID
,QXTD_WSID
,QXTE_PRMTABANO
,QXTE_PRMKIGYOUCD
,QXTE_PRMSUBRANGEKEY
,QXTE_PRMNAIBUKAIINNO
,QXTE_PRMKANKEIKBN
,QXTE_PRMKAZOKURBN
,QXTE_HIRAISTATUS
,QXTE_JDSK001
,QXTE_JDSK002
,QXTE_JDSK003
,QXTE_JDSK004
,QXTE_JDSK005
,QXTE_JDSK006
,QXTE_JDSK007
,QXTE_JDSK008
,QXTE_JDSK009
,QXTE_JDSK010
,QXTE_JDSK011
,QXTE_JDSK012
,QXTE_JDSK013
,QXTE_JDSK014
,QXTE_JDSK015
,QXTE_JDSK016
,QXTE_JDSK017
,QXTE_JDSK018
,QXTE_JDSK019
,QXTE_JDSK020
,QXTE_JDSK021
,QXTE_JDSK022
,QXTE_JDSK023
,QXTE_JDSK024
,QXTE_JDSK025
,QXTE_JDSK026
,QXTE_JDSK027
,QXTE_JDSK028
,QXTE_JDSK029
,QXTE_JDSK030
,QXTE_JDSKEKKA
,QXTE_JDSIRAISTATUS
,QXTE_HANTEISYOKI
,QXTE_JDSYOSINRANK
,QXTE_JDSCASHLIMIT
,QXTE_JDSDATE
,QXTE_ENDHANTEI
,QXTE_ENDYOSINRANK
,QXTE_ENDCASHLIMIT
,QXTE_ENDFSTTANTOID
,QXTE_ENDFSTSHORIDATE
,QXTE_ENDTANTOID
,QXTE_ENDSHORIDATE
,QXTE_SRVHANTEI
,QXTE_SRVIRAIUMU
,QXTE_BUNSHOKANRINO
,QXTE_LETTERSYUBETU
,QXTE_KIJITUSTRDATE
,QXTE_HUPIRAIDATE
,QXTE_HUPKEKKADATE
,QXTE_HUPHANTEI
,QXTE_STRDATE
,QXTE_UPDDATE
,QXTE_DELDATE
,QXTE_OPID
,QXTE_WSID
 ) AS
Select  T1.*,T2.*
From  (Select Max(TO_NumBer(QXTD_PRMTABANO)) TABANO
    From  QXTD_GENDOKAIINM ) M
   ,QXTD_GENDOKAIINM T1
   ,QXTE_SHINSAKEKKA T2
Where    T1.QXTD_PRMTABANO       <>  M.TABANO               AND
      T1.QXTD_PRMTABANO       =  T2.QXTE_PRMTABANO       AND
      T1.QXTD_PRMKIGYOUCD     =  T2.QXTE_PRMKIGYOUCD     AND
      T1.QXTD_PRMSUBRANGEKEY  =  T2.QXTE_PRMSUBRANGEKEY  AND
      T1.QXTD_PRMNAIBUKAIINNO =  T2.QXTE_PRMNAIBUKAIINNO AND
      T1.QXTD_PRMKANKEIKBN    =  T2.QXTE_PRMKANKEIKBN    AND
      T1.QXTD_PRMKAZOKURBN    =  T2.QXTE_PRMKAZOKURBN    AND
      T1.QXTD_DELDATE         Is Null;
