DROP   VIEW QWAA_KIJITSUSHOKAIV;
CREATE VIEW QWAA_KIJITSUSHOKAIV ( 
QTA1_HONSHIMEIKAN
,QTA1_JTKTELSHIGAI
,QTA1_JTKTELKYOKU
,QTA1_JTKTELNO
,QWA3_PRMKIGYOUCD
,QWA3_PRMSUBRANGEKEY
,QWA3_PRMNAIBUKAIINNO
,QWA3_PRMUKETSUKENO
,QWA3_PRMSAKUSEIBI
,QWA3_PRMSAKUSEITIME
,QWA3_PRMRENBAN
,QWA3_KAIINNO
,QWA3_TOUZAIKBN
,QWA3_KAIINNAME
,QWA3_JSHJUSHOKBN
,QWA3_JSHYUBINNO
,QWA3_JSHJUSHO1
,QWA3_JSHJUSHO2
,QWA3_JSHJUSHO3
,QWA3_JSHJUSHO4
,QWA3_JSHATENA
,QWA3_BUNSHOKANRINO
,QWA3_BUNSHOMEI
,QWA3_HASSOUYMD
,QWA3_HENYOTEIYMD
,QWA3_HENKYAKUYMD
,QWA3_HENKYAKURIYU
,QWA3_SEIRINO
,QWA3_JOKYOKBN
,QWA3_KOUTANTOUSHACD
,QWA3_KOUTANTOUSHAMEI
,QWA3_KOUYMD
,QWA3_KOUTIME
,QWA3_TOUTANTOUSHACD
,QWA3_TOUTANTOUSHAMEI
,QWA3_TOUYMD
,QWA3_TOUTIME
,QBA1_UKETSUKENO
,QBA1_HONKJNAME
,QBA1_HONTEL1
,QBA1_HONTEL2
,QBA1_HONTEL3
,QWA1_PRMBUNSHOKANRINO
,QWA1_TOUZAIKBN
,QWA1_BUNSHOMEI
,QWA1_BUNRUICD
,QWA1_KIJITSUKANRIKBN
,QWA1_SEIRINOKBN
,QWA1_BUNSHOUMUKBN
,QWA1_SHORIKBN
-- 2002/08/31 内部会員バーコード対応 SQT.YAMADA -->
,QTA1_CARDKBN
,QTA1_GKNSHIKIBETSUNO
,QTA1_GKNEDABAN
,QWA3_BARCODE
-- 2002/08/31 <--
 ) AS 
SELECT M.QTA1_HONSHIMEIKAN,
        M.QTA1_JTKTELSHIGAI,
        M.QTA1_JTKTELKYOKU,
        M.QTA1_JTKTELNO,
        T.QWA3_PRMKIGYOUCD,
        T.QWA3_PRMSUBRANGEKEY,
        T.QWA3_PRMNAIBUKAIINNO,
        T.QWA3_PRMUKETSUKENO,
	T.QWA3_PRMSakuseiBi,
	T.QWA3_PRMSakuseiTime,
	T.QWA3_PRMRenban,
        T.QWA3_KAIINNO,
        T.QWA3_TOUZAIKBN,
        T.QWA3_KAIINNAME,
        T.QWA3_JSHJUSHOKBN,
        T.QWA3_JSHYUBINNO,
        T.QWA3_JSHJUSHO1,
        T.QWA3_JSHJUSHO2,
        T.QWA3_JSHJUSHO3,
        T.QWA3_JSHJUSHO4,
        T.QWA3_JSHATENA,
        T.QWA3_BUNSHOKANRINO,
        T.QWA3_BUNSHOMEI,
        T.QWA3_HASSOUYMD,
        T.QWA3_HENYOTEIYMD,
        T.QWA3_HENKYAKUYMD,
        T.QWA3_HENKYAKURIYU,
        T.QWA3_SEIRINO,
        T.QWA3_JOKYOKBN,
        T.QWA3_KOUTANTOUSHACD,
        T.QWA3_KOUTANTOUSHAMEI,
        T.QWA3_KOUYMD,
        T.QWA3_KOUTIME,
        T.QWA3_TOUTANTOUSHACD,
        T.QWA3_TOUTANTOUSHAMEI,
        T.QWA3_TOUYMD,
        T.QWA3_TOUTIME,
        S.QBA1_UKETSUKENO,
        S.QBA1_HONKJNAME,
        S.QBA1_HONTEL1,
        S.QBA1_HONTEL2,
        S.QBA1_HONTEL3,
	B.QWA1_PRMBunshokanriNo,
	B.QWA1_TouzaiKbn,
	B.QWA1_BunshoMei,
	B.QWA1_BunruiCd,
	B.QWA1_KijitsuKanriKbn,
	B.QWA1_SeiriNoKbn,
	B.QWA1_BunshoUmuKbn,
	B.QWA1_ShoriKbn,
-- 2002/08/31 内部会員バーコード対応 SQT.YAMADA -->
        M.QTA1_CARDKBN,
        M.QTA1_GKNSHIKIBETSUNO,
        M.QTA1_GKNEDABAN,
        T.QWA3_BARCODE
-- 2002/08/31 <--
  FROM  QTA1_KAIINM M, QWA3_KIJITSUT T, QBA1_MOSHIKOMIT S,QWA1_BunshoCTRLM B 
  WHERE T.QWA3_PRMKIGYOUCD = M.QTA1_PRMKIGYOUCD(+) 
    AND T.QWA3_PRMSUBRANGEKEY = M.QTA1_PRMSUBRANGEKEY(+)
    AND T.QWA3_PRMNAIBUKAIINNO = M.QTA1_PRMNAIBUKAIINNO(+)
    AND T.QWA3_PRMUKETSUKENO = S.QBA1_UKETSUKENO(+)
    AND T.QWA3_BunshokanriNo = B.QWA1_PRMBunshoKanriNo
;
