CREATE VIEW QYA6_HAITATSUKV ( 
QYA6_KEYCOMPUTERMEI
,QYA6_KAIINNO
,QYA6_ATENA
,QYA6_MAISU
,QYA6_YUUBINRYO
,QYA6_SEQNO
 ) AS 
SELECT
  QYA5_KEYCOMPUTERMEI,
  QYA5_KAIINNO,
  QYA5_ATENA,
  NVL(QYA5_MAISU,' '),
  NVL(QSA3_MEI,' '),
  QYA5_SeqNo
 FROM
  QYA5_HaitatsuKT, --配達記録出力テーブル
  (SELECT QSA3_PRMCODENO,
    QSA3_MEI
   FROM QSA3_CodeV
   WHERE QSA3_PRMCODEKBN = 'DS6'
  ) QSA3_CodeV  --コードＶＩＥＷ
 WHERE
  QYA5_MAISU  = QSA3_PRMCODENO(+)
 AND QYA5_KAIINNO <> '9999999999999999'
 UNION ALL SELECT
  QYA5_KEYCOMPUTERMEI,
  QYA5_KAIINNO,
  QYA5_ATENA,
  NVL(QYA5_MAISU,' '),
  ' ',
  999999
 FROM
  QYA5_HaitatsuKT  --配達記録出力テーブル
 WHERE
  QYA5_KAIINNO = '9999999999999999'
;
